### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by awkis23** [kvos/CoastSat#102]
Hello Kvos, Amanda from Japan here.
I need your help and advice. I'm a new user with kind of this coding.
I used the S2 images from Sep 1 - Oct 31, 2019, with coordinate
114.571489,  -8.387097
114.808656,  -8.388966
114.809433,  -8.419982
114.573682,  -8.420512
I don't know why the results are like this.
![Figure_3](https://user-images.githubusercontent.com/67011241/84789381-23449180-b02b-11ea-9184-71f0065d0865.png)
![Plot Perancak](https://user-images.githubusercontent.com/67011241/84789405-28a1dc00-b02b-11ea-9d19-20e3c165553c.png)
<img width="1054" alt="Screen Shot 2020-06-06 at 0 27 22" src="https://user-images.githubusercontent.com/67011241/84789541-4b33f500-b02b-11ea-95b5-9111246d540e.png">

There's the line crossed over the coastline detection result.
I was following all the instructions you give, but the results are very different.
Please help me to solve this problem.
Kind regards,

**Comment by kvos** [comment]
Your results are fine. The output is a list of points with the coordinates of the shorelines, when you convert them into a GEOJSON linestring, it just joins those points to create a line but often it doesn't do it in the right order so you get those crossing lines.

**Comment by awkis23** [comment]
Thank you kvos for your response. So, do you know how to remove those crossing line?
Thank you in advance and really appreciate for your help.

**Comment by awkis23** [comment]
Thank you kvos for your response. So, do you know how to remove those crossing line?
How if I want to compare with multi-years data, ex: 2005 and 2019 data? Is it possible to do at once and make the coastline changes like this picture?
![Figure_2](https://user-images.githubusercontent.com/67011241/85222072-b26af400-b3f3-11ea-92be-d2562bc804ba.png)

I also have a problem with this, why the coastline isn't drawn like this picture?
![2019-10-28-02-50-11_S2](https://user-images.githubusercontent.com/67011241/85226217-5f079e80-b411-11ea-86a5-27d8cab728f2.jpg)


Thank you in advance and really appreciate for your help.

**Comment by kvos** [comment]
Are you using a reference shoreline? I thinkk you are only mapping shorelines at that topleft corner of the image as your reference shoreline is only there. I recommend you break down this large polygon into small polygons that only cover the beaches of interest. Then for each polygon draw a reference shoreline where you want shoreline to be mapped (or don't use a reference shoreline if you want all waterlines).

**Comment by kvos** [comment]
hi @awkis23  the line issue has been fixed in the latest update, now it saves the shorelines as a geojson where each shoreline is a set of points so it doesn't connect the points randomly producing those weird lines. try it out!
