### ISSUE TITLE
Problem with script when attempting to re-train classifier

### ISSUE THREAD

**Issue by nickrichards96** [kvos/CoastSat#103]
Screenshot 2020-06-17 at 12 15 31](https://user-images.githubusercontent.com/64134225/84891957-a4843e80-b094-11ea-8700-6faa38ecb178.png)
)

**Comment by kvos** [comment]
it can't read your .kml file. I usually create them with Google Mymaps and it's fine. You create a new layer on Mymaps, draw a polygon with 4 vertices, then export to KML

**Comment by nickrichards96** [comment]
Hi there,

I did that and also tried in google earth pro, my friend has also tried with the same error.

Thanks

Nicholas Richards

Sent from my iPhone

On 19 Jun 2020, at 00:08, Kilian Vos <notifications@github.com<mailto:notifications@github.com>> wrote:


it can't read your .kml file. I usually create them with Google Mymaps and it's fine. You create a new layer on Mymaps, draw a polygon with 4 vertices, then export to KML

**Comment by kvos** [comment]
ok can just enter the coordinates manually as in the example?

**Comment by mcuttler** [comment]
I have found when exporting from GooleEarth Pro I sometimes have to go into the .KML with a text editor (e.g. Notepad++) and manually edit the coordinatres. When exported from GoogleEarth they all appear on a single line, however, I seem to need the coordiantes to be on individual lines, so I just go in an adjust the KML. For example

Exported from Google Earth looks like this: 
Lon1, Lat1, 0 Lon2, Lat2, 0 Lon3, Lat3, 0, Lon4, Lat4, 0

And I just adjust so looks like this: 
Lon1, Lat1, 0 
Lon2, Lat2, 0 
Lon3, Lat3, 0, 
Lon4, Lat4, 0

**Comment by nickrichards96** [comment]
Good afternoon both,

I have that found this only occurs when using mac vs windows due to the creation of .DS_Store files. Once a command is inputted in terminal window to remove the hidden files from the training_sites folder it works perfectly. Hope this helps someone else!

Thanks

Nick Richards

Sent from my iPhone

On 29 Jun 2020, at 01:01, mcuttler <notifications@github.com<mailto:notifications@github.com>> wrote:


I have found when exporting from GooleEarth Pro I sometimes have to go into the .KML with a text editor (e.g. Notepad++) and manually edit the coordinatres. When exported from GoogleEarth they all appear on a single line, however, I seem to need the coordiantes to be on individual lines, so I just go in an adjust the KML. For example

Exported from Google Earth looks like this:
Lon1, Lat1, 0 Lon2, Lat2, 0 Lon3, Lat3, 0, Lon4, Lat4, 0

And I just adjust so looks like this:
Lon1, Lat1, 0
Lon2, Lat2, 0
Lon3, Lat3, 0,
Lon4, Lat4, 0

**Comment by kvos** [comment]
thanks @mcuttler , great @nickrichards96 that you found a solution, hopefully people see this issue
