### ISSUE TITLE
Spyder: DLL load failed: The specified procedure could not be found

### ISSUE THREAD

**Issue by IraPelidae** [kvos/CoastSat#105]
Hi Killian, 

Haven't had any problems with running CoastSat on Jupyter Notebook thus far; however, when I try to run the 'Initial settings' cell in Spyder I get an error saying that 'DLL load failed: The specified procedure could not be found.' 

![image](https://user-images.githubusercontent.com/49346361/85590883-b2116980-b63c-11ea-980f-d1f334a7d98a.png)

Any chance you're able to shed a light on this? 

Best wishes,

Jack (UK)

**Comment by kvos** [comment]
Hey Jack, 

The DLL errors are tricky, that GDAL error has been appearing a lot. It's an issue with the anaconda environment and the gdal package. Only solution that we have found is to play with the environment, like update the gdal package (`conda update gdal`) or reinstall the environment. Have a look at previous issues (closed) with the keyword gdal and you should found more info about it (most users managed to solve the problem)

**Comment by IraPelidae** [comment]
Hi Killian,

Tried updating gdal and conda etc., but what I think ultimately solved this issue was launching Spyder directly from the command prompt as opposed to from Anaconda Navigator. 

Thanks for your help!
Jack

**Comment by kvos** [comment]
cool! yeah that Anaconda Navigator is a bit dodgy sometimes
