### ISSUE TITLE
coastSat is applicable for islands ?

### ISSUE THREAD

**Issue by vighneshrajendrans** [kvos/CoastSat#106]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by kvos** [comment]
yes it is! You may want to check @mcuttler branch of CoastSat which he has adapted for small islands: https://github.com/mcuttler/CoastSat/tree/CoastSat_MCuttler

**Comment by vighneshrajendrans** [comment]
> yes it is! You may want to check @mcuttler branch of CoastSat which he has adapted for small islands: https://github.com/mcuttler/CoastSat/tree/CoastSat_MCuttler

Thank for the reply in CoastSat can we  make difference in tidal correction? Can you mention which part refers it?

**Comment by vighneshrajendrans** [comment]
> > yes it is! You may want to check @mcuttler branch of CoastSat which he has adapted for small islands: https://github.com/mcuttler/CoastSat/tree/CoastSat_MCuttler
> 
> Thank for the reply in CoastSat can we make difference in tidal correction? Can you mention which part refers it?

I check the codehttps://github.com/mcuttler/CoastSat/tree/CoastSat_MCuttler .but they didnt mention how it works ? However i run the program and then  got an error like this[Errno 2] No such file or directory: 'C:\\Users\\Vicky\\.spyder\\CoastSat-master\\CoastSat-CoastSat_MCuttler\\classifiers\\NN_4classes_Landsat_Nick.pkl'

**Comment by mcuttler** [comment]
The branch is still very much in development and haven't worked out all of bugs in merging back with the main CoastSat branch - quick fix for that issue is that the CoastSat directories have changed, so now the classifiers (NN_4classes_Landsat_Nick.pkl) are located in .\classification\models. 

Also, that specific classifier is specific for the NW coast of western australia, so you will want to revert back to the default classifier for CoastSat (NN_4classes_Landsat.pkl) or a classifier trained for your study site.

**Comment by vighneshrajendrans** [comment]
> The branch is still very much in development and haven't worked out all of bugs in merging back with the main CoastSat branch - quick fix for that issue is that the CoastSat directories have changed, so now the classifiers (NN_4classes_Landsat_Nick.pkl) are located in .\classification\models.
> 
> Also, that specific classifier is specific for the NW coast of western australia, so you will want to revert back to the default classifier for CoastSat (NN_4classes_Landsat.pkl) or a classifier trained for your study site.
Thank yo for the reply .But issue is not solved yet and i think that it will  rectify after completion of the processing code

**Comment by IraPelidae** [comment]
@mcuttler was wondering if your 'small islands' branch of CoastSat has a tool to automatically compute the area of the islands in the picture? I'm studying islands in the Maldives currently, and the official database of island sizes is very outdated. Would hugely appreciate it if you have any suggestions in this regard.

**Comment by vighneshrajendrans** [comment]
> @mcuttler I was wondering if your 'small islands' branch of CoastSat has a tool to automatically compute the area of the islands in the picture? I'm studying islands in the Maldives currently, and the official database of island sizes is very outdated. Would hugely appreciate it if you have any suggestions in this regard.

The same error is show repeatedly .I want to ask something tidal corection part is not working yet.Is there any updation in it?

**Comment by mcuttler** [comment]
@IraPelidae there is a tool within the islands code to calculate island area and major axis orientation. have been meaning to test it out on the maldives but haven't had a chance, would be keen to collaborate and happy to discuss further

@vighneshrajendrans sorry, no update yet. aiming to have the islands branch sorted out by next week.

**Comment by vighneshrajendrans** [comment]
> @IraPelidae there is a tool within the islands code to calculate island area and major axis orientation. have been meaning to test it out on the maldives but haven't had a chance, would be keen to collaborate and happy to discuss further
> 
> @vighneshrajendrans sorry, no update yet. aiming to have the islands branch sorted out by next week.

Thank you for the valuable replies .Please let me know after the completion.We are also looking for that.

**Comment by IraPelidae** [comment]
> @IraPelidae there is a tool within the islands code to calculate island area and major axis orientation. have been meaning to test it out on the maldives but haven't had a chance, would be keen to collaborate and happy to discuss further
> 
> @vighneshrajendrans sorry, no update yet. aiming to have the islands branch sorted out by next week.

@mcuttler Would also be eager to collaborate! Focusing again on the Maldives now after sorting out a subsidiary task.

**Comment by mcuttler** [comment]
Hi guys, we've organised the islands work into it's own repo. check it out here: https://github.com/mcuttler/CoastSat.islands
