### ISSUE TITLE
how to update (dict) settings fields required in SDS_classify?

### ISSUE THREAD

**Issue by lparlagreco** [kvos/CoastSat#107]
I see the SDS_classify requires a nested 'settings' dictionary. 
It would be helpful to describe its structure but I haven't been able to find an example in that regard.
Following is the example: color_sand
settings['colors']['sand'] (line 198)
thanks a lot

**Comment by kvos** [comment]
there is an example as a jupyter notebook https://github.com/kvos/CoastSat/blob/master/classification/train_new_classifier.ipynb

**Comment by lparlagreco** [comment]
thanks for CoastSat!
