### ISSUE TITLE
shoreline(black line) is not marked in the figures even after giving the reference shoreline

### ISSUE THREAD

**Issue by MeghanaKavuri** [kvos/CoastSat#110]
Hi KILLIAN,
This is Meghana, I have been running this coastsat with my polygon. After plotting the reference shoreline, rest of the shorelines are not mapped with the shoreline(blackline). But other three classes sand , white water and water are correctly being mapped. Can you help me find where the mistake is? 

Thank you in advance.

![Screenshot from 2020-07-10 10-25-12](https://user-images.githubusercontent.com/67146836/87118404-ede13b80-c298-11ea-905d-e71b19b6e7c5.png)

**Comment by kvos** [comment]
hi meghana, is looking good but no shoreline. can you take a screenshot of your settings? is your reference system a projected one (cartesian coordinates)?

**Comment by MeghanaKavuri** [comment]
This is the screenshot of the settings. I am doing this for India, I also have the doubt whether i have taken the projected cartesian coordinates or not.

![Screenshot from 2020-07-10 16-14-51](https://user-images.githubusercontent.com/67146836/87146960-67911d80-c2c9-11ea-99c5-0df76ae90412.png)

**Comment by kvos** [comment]
the epsg 4326 is WGS84, that is spherical coordinates not projected!!!
change `output_epsg` to 3857 if you don't want to use a local projection

**Comment by MeghanaKavuri** [comment]
I will try to use that epsg as 3857 and then run the program and then will let  you the result. 

I also have one more doubt. Does 3857 remain same for whole India? And also should we always manually give the option to Ignore or Keep each detection? Is there any automated way, because I am doing this for the entire coastline of India for 30+ years. It will be very difficult to select the option for every polygon, because India has a coastline length of 7516.6kms.

Can you please suggest any simpler way to do it.

**Comment by kvos** [comment]
3857 is the web mercator (basically what's used in Google maps), a local projection for India will always be more accurate.
I have only made publicly available coastsat to be run at a single site as I am still working on an automated solution for the large, so i can't help with this at this stage.

**Comment by MeghanaKavuri** [comment]
Thanks you Kilian, but i have one more doubt. Should I take the reference shorelines for all the polygons in a geojson file  or, should i make each and every polygon's reference shoreline separately in a geojson file? ( Shuld i take the whole India's shoreline and then split it according to my polygon?  Or is there any method to do it?)

My thought is to download all the satellite images of every polygon at once and then run the next steps later.

**Comment by kvos** [comment]
the best way to do it is to draw the shorelines for each beach in QGIS for example and then create the minimum rotated rectangle around each shoreline automatically. Then you have your reference shorelines and polygons and you can loop through them.
![image](https://user-images.githubusercontent.com/7217258/87284149-6403cd80-c539-11ea-8666-61222b0e928f.png)

Also with the shorelines you can automatically generate 100m spaced shore-normal transects
![image](https://user-images.githubusercontent.com/7217258/87284465-bf35c000-c539-11ea-8978-095e6ae25f59.png)

What project is this for? Are you interested in making something like this? we are not making open-source the codes to do the large scale mapping but feel free to write me an email if you'd like to collaborate.

**Comment by karinguyen** [comment]
Hi Vos,

My study area is exactly similar with the photo you show here, which includes several sandy beaches (8 beaches). If I use the coastsat, I have to do 8 times, time consuming. You mentioned something about the codes to do the large scale mapping, so could you give me more information about this ? I do hope I can apply it for my case study.

Regards,
