### ISSUE TITLE
outputs of the image classification

### ISSUE THREAD

**Issue by Napogit** [kvos/CoastSat#112]
Hi everyone,
I am wondering if there any option to obtain the outputs of the image classification (where each pixel has been labeled with one of three classes: ‘sand’, ‘white-water’ and ‘water’) georeferenced? 
Thanks so much in advance!
Napo

**Comment by kvos** [comment]
so you will need to go into the code, go to SDS_shorelines.py:
- at line 821 add: `output_classif.append(im_classif)`
- at line 831 (after defining `output[satname]`) add: `output[satname]['im_classif'] = output_classif`
this should do the trick and will save the classified images in your outputs

**Comment by Napogit** [comment]
Hello Kilian,

Thank you very much for your reply. I modified the code as you suggested but I am not getting the classified images in the output files yet.  It should be in the "data" folder, right?  Within the "output.geojson" file??

Many Thanks!!
Napo

**Comment by kvos** [comment]
it's in output.pkl! it's not possible save an image in a geojson

**Comment by Napogit** [comment]
Thanks for clarifying, and sorry for the rookie mistake. 

Your software/toolkit is really cool, Thanks!

**Comment by kvos** [comment]
no worries @Napogit , it's not very clear in the documentation but the output.geojson is just for a quick visualisation,most of the files generated by coastsat are pickle files (binary format for python variables). I'll close the issue for now, cheers
