### ISSUE TITLE
Can coastsat only pull images from satellites? Or can the code be altered so the images be pulled from elsewhere?

### ISSUE THREAD

**Issue by spsarahpeterson** [kvos/CoastSat#114]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by kvos** [comment]
hi @spsarahpeterson , what kind of imagery are you referring to? UAVs? aerials? 
the current version of coastsat can download and process images from Landsat and Sentinel missions and there is a work-in-progress version for Planet labs imagery.

**Comment by spsarahpeterson** [comment]
Hi,

I am referring to aerial photos from google earth. Let me know if this is possible. Thanks

Sincerely,
Sarah Peterson

**Comment by kvos** [comment]
I'm not sure I understood what you are trying to do, could you expand a bit?

**Comment by spsarahpeterson** [comment]
Hi Kilian,

Thank you for getting back to me. I am curious if the code could be changed slightly to get images from a specific location on google earth rather than from satellite images? For instance, pulling from the history of google earth images rather than satellite images. Right now the code is pulling the images from satellites from google earth engine, but I am wondering if different images could be pulled into the program and applied into coastsat... I think with a different code to specify where to pull those images from it might work, but I’m not sure where the part of the code that takes images from the satellites specifically is. Let me know if you have any thoughts. Thank you.

Sincerely,
Sarah Peterson

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by kvos** [comment]
the part of the code that pull the images from GEE is `SDS_download.py`. I don't think you can get the google earth images from GEE. Also the code will only work for Landsat and Sentinel-2 images, if you provide different imagery with different multispectral bands you will have to make some modifications.
cheers,
Kilian

**Comment by spsarahpeterson** [comment]
Kilian,

Great, thank you!

Sincerely,
Sarah Peterson
________________________________
