### ISSUE TITLE
Testing CoastSat in the Canadian Arctic

### ISSUE THREAD

**Issue by danielbatista1** [kvos/CoastSat#115]
Hello,
I’ve obtained results using CoastSat for the delineation of the Canadian arctic coast as I mentioned in an email a few days ago. I now have results from both before and after training the algorithm using some examples of sites from this region. As I had mentioned in my email, in some areas the results are quite good, though in others they are a bit inconsistent. The training of the algorithm did improve the results a bit, though some troubles appear to persist, at least in some areas. To show you some examples I made a small pdf that I will attach to this message. The yellow lines correspond to the older pre-training results, and the orange and red points to the newer post-training results. As I ran the re-training Jupyter Notebook, I saw that I could have only used the pixels resulting from my training areas. I ended up using both mine and the original data, but perhaps it would be a good a idea to try using just mine? Again, I know that this is not the ideal environment that this software was made to be used on, but I am interested in knowing if you have any tips, as it would be extremely useful if I found that I could use this software in this type of region.

[Coastsat.pdf](https://github.com/kvos/CoastSat/files/5003129/Coastsat.pdf)

Also, just to be sure that I did it correctly (this is the first time I've had to use Python), I will also send a screenshot of what I added to the code in the SDS_shoreline.py file. I had some trouble at first because I was using Sentinel-2 images in my analyses and not Landsat ones, but then I think I got it to work right using the Sentinel-2 images too.
![python code](https://user-images.githubusercontent.com/65970845/88959983-bd3e6180-d29a-11ea-9c06-2a8bdaab61fe.png)

Thank you in advance.
Daniel L. G. Baptista

**Comment by kvos** [comment]
hi Daniel, it was cool to look at your shoreline detections in the canadian artic!
For me to understand what is going on in terms of image processing, it would be helpful if you could also include the detected shoreline that are saved by coastsat, in the jpg_files/detection folder. This should show the detected shoreline together with the RGB, classified image and MNDWI. To further improve it, it would be interesting to look at the histograms with the pixel values (not generated in CoastSat unfortunately).

Kilian

**Comment by danielbatista1** [comment]
Hi again,

Sure, I'll send some of those jpg files attached to this message. The folder contains those jpgs for the 5 sectors I created around Herschel Island and the 1 sector close to the Canada/Alaska border. I was wondering if there was any way to see these images with better resolution and maybe individually. Also, there is no way to see the histogram you mentioned?
[t6 jpgs (sand color = test2).zip](https://github.com/kvos/CoastSat/files/5023430/t6.jpgs.sand.color.test2.zip)


Thanks,
Daniel

**Comment by kvos** [comment]
hi daniel, the resolution of the images is 10m/pixel, you can't change that. You can zoom into certain sections however. I recommend you try making your polygon small and focusing on a specific are at least for this testing/validation phase. With this level of zoom, I cannot really tell what the classifier is doing around the shoreline (whitewater, shallow water, sand pixels...etc). I can see however that it's not getting a lot of sand pixels on the images. The CoastSat shoreline detection works best on a small polygons, as then the shoreline detection is specific to that section of the coast. It is hard to find one threshold that works well for such a large stretch of coastline. I usually break down my coast in small polygons and run coastsat individually, you will get much better results. 
![image](https://user-images.githubusercontent.com/7217258/89361625-15e48300-d70f-11ea-9861-9fe509474973.png)

To plot the histogram is on my to do list of enhancements but I haven't done it yet.

**Comment by danielbatista1** [comment]
Hi,

Ok, I can try to use smaller areas in the future, at least in this initial phase as you mentioned. Thank you very much for the advice.

**Comment by danielbatista1** [comment]
Hello again,

My Professors and I were wondering about an issue regarding the reference shoreline that can be traced using CoastSat. Is it possible to use/import a pre-traced or created shoreline? From what I understood, when we create the line using the software, a .geojson and a .pkl file is created in the folder containing the results of the analysis we are conducting, but it appears to me that the .pkl file is what is loaded when we are running the Jupyter Notebook. For example, by copying a reference line .pkl file created in a first analysis into the folder of other analyses (regarding the same study area) and accordingly changing the file name, I was able to get CoastSat to recognize those reference lines without having to re-trace them. However, as I said, for this I relied on the .pkl file that was produced by the software. Because of this I assume that other coastlines in other formats, including of areas that include, but extend farther than, the individual study area of each analysis, can't be used... But I was wondering if there is indeed some way to do this.

**Comment by kvos** [comment]
hi daniel, 

you can load your reference shoreline from a GIS layer as follows:

```
import gpd as geopandas
from skimage import transform

# load the shapefile or geojson
fp_ref_shorelines = 'filepath/to/ref_shoreline.geojson'
ref_shorelines = gpd.read_file(fp_ref_shorelines, driver='GeoJSON') # if shapefile change driver

# get reference shoreline coordinates and interpolate if necessary
coords = np.array(ref_shorelines['geometry'].coords)

# now check that coordinates are not too far apart, otherwise interpolate between the vertices (10m resolution)
resolution = 10
if np.any(np.sqrt(np.diff(coords[:,0])**2 + np.diff(coords[:,1])**2)>100):
    pts_world = coords
    pts_world_interp = np.expand_dims(np.array([np.nan, np.nan]),axis=0)
    for k in range(len(pts_world)-1):
        pt_dist = np.linalg.norm(pts_world[k,:]-pts_world[k+1,:])
        xvals = np.arange(0,pt_dist,resolution )
        yvals = np.zeros(len(xvals))
        pt_coords = np.zeros((len(xvals),2))
        pt_coords[:,0] = xvals
        pt_coords[:,1] = yvals
        phi = 0
        deltax = pts_world[k+1,0] - pts_world[k,0]
        deltay = pts_world[k+1,1] - pts_world[k,1]
        phi = np.pi/2 - np.math.atan2(deltax, deltay)
        tf = transform.EuclideanTransform(rotation=phi, translation=pts_world[k,:])
        pts_world_interp = np.append(pts_world_interp,tf(pt_coords), axis=0)
    pts_world_interp = np.delete(pts_world_interp,0,axis=0)
    # overwrite the coords vector
    coords = pts_world_interp
    
settings['reference_shoreline'] = coords
```

add this snippet instead of `settings['reference_shoreline'] = SDS_preprocess.get_reference_sl(metadata, settings)
` and it should be all good (make sure coordinate system is the same as the one that you defined in the settings (`output_epsg`).

**Comment by danielbatista1** [comment]
Hello,

Thank you very much!! I definitely will try it out as soon as I can. Thank
you also for the great suggestions regarding the Profile Tool plugin in
QGIS. I will also be trying that out soon. Sorry for all the trouble and
work.

Kilian Vos <notifications@github.com> escreveu no dia sexta, 14/08/2020
à(s) 06:35:
