### ISSUE TITLE
Asking about CoastSat, from Japan

### ISSUE THREAD

**Issue by karinguyen** [kvos/CoastSat#116]
Dear Mr.  Vos,

I am Nguyen, PhD student in Japan. We are doing research on shoreline changes under the influence of the Great Japan Earthquake occurred on March 11, 2011. Therefore, shoreline extraction from satellite image is the most important input data in our research.

Interestingly, we found and have read your publications, with a python code set. I am trying to run the demo data set ( example at Narrabeen-Collaroy, Australia), then we will apply your proposed protocol in the case study in Japan.

Actually, We have tried to extract the shoreline positions by manually, but the accuracy was not good enough to understand how the shoreline changed through the time.

Based on your demo data set as well as the code shown in the link attached, I have tried, but somehow it does not work. I got errors, and could not continue. Could you please help me to take a look at the code running by myself ? Something wrong from the "Digitize a reference shoreline".  

http://localhost:8888/notebooks/example_jupyter.ipynb  

I am doing exactly what you has guided here (https://github.com/kvos/CoastSat?fbclid=IwAR2ofxliY23JRMg_xSGz_-M9AMqdCbltHqzzLKEfTiAYuz24ZhUflqLt7ow). But I still could not solve the problem. I do hope I can learn something from you.

Thank you very much for your kind understanding,

Best Regards,

Note: I am using Python version 3.8.5. I was using Matlab, and now changing into Python due to your code. haha

**Comment by kvos** [comment]
hi Nguyen, can you post what there error message is?

**Comment by karinguyen** [comment]
Hi VOS,

Thank you very much for your kind reply:

Something wrong from the "Digitize a reference shoreline".

As you can see belows.

![image](https://user-images.githubusercontent.com/44887152/89361947-8f787300-d707-11ea-933a-92e1584f7925.png)



![image](https://user-images.githubusercontent.com/44887152/89362154-1594b980-d708-11ea-91b0-718a4b1a84e1.png)

**Comment by kvos** [comment]
that's a weird error, it looks like it doesn't like the line `matplotlib qt` (which is just to make plots interactive).
Can you try to run the script in Spyder? If you are used to Matlab you will like this much better, it's python's imitation of matlab. Activate your coastsat environment and then run Spyder by just typing `spyder` in the command line. Make sure you change the graphics settings as instructed in the Readme. Let me know how it goes

**Comment by karinguyen** [comment]
Hi VOS,

Thank you very much for your kind advice. I can run the code on Spyder. Your codes are really nice.

However, I got the other error as:

'FigureManagerBase' object has no attribute 'window'

I am trying to fix this. Do you have any idea ? 

![image](https://user-images.githubusercontent.com/44887152/89368989-da01eb80-d717-11ea-96ab-623edc292727.png)

**Comment by MOnrust** [comment]
This error is related to the matplotlib backend ([https://matplotlib.org/faq/usage_faq.html#what-is-a-backend](url)).

I assume that the `matplotlib qt` only works on a QT canvas and it appears that Spyder uses this backend by default, but different computers might use different backends. You can test the backend:
`print(plt.get_backend())`

@kvos maybe a good addition to specify the backend using `matplotlib.use('Qt4Agg')` or any other backend to prevent these problems in the future?

**Comment by karinguyen** [comment]
Hi Monrust,

Yes you are right, I tried as you said and fixed the problem.

@kvos Do you have any short code for tidal correction? I was reading your paper introducing about Coastsat and you mentioned that tidal correction is not implemented in the toolbox as it is site-specific.

Thanks so much guys,

**Comment by kvos** [comment]
thanks @MOnrust for the great input, will add that one-liner to the jupyter notebook

@karinguyen you can use the [CoastSat.slope](https://github.com/kvos/CoastSat.slope) package for beach slope estimation and tidal correction.

**Comment by kvos** [comment]
hey @karinguyen I just added a section on Tidal Correction in CoastSat, check it out in the [Jupyter Notebook](https://github.com/kvos/CoastSat/blob/master/example_jupyter.ipynb)!
![image](https://user-images.githubusercontent.com/7217258/89507976-95a64680-d810-11ea-88cd-008e42f342a4.png)

**Comment by karinguyen** [comment]
Dear Vos,

Wao, You are really a genius. The code is really imaging. Thank you very much for that. I am trying to apply in Japan, and will tell you the results.

We usually concern long-term shoreline change behavior, which is the rate of shoreline change. the Coastsat can be perfect if it can include the estimation of shoreline change rate. You can add a short code to estimate the change rate based on linear regression.

Best Regards,

**Comment by kvos** [comment]
if you want to contribute to the code and add a function to compute the long-term trend that would be great! (you can do a pull request)
