### ISSUE TITLE
How to change shoreline as POINTS to LINES

### ISSUE THREAD

**Issue by karinguyen** [kvos/CoastSat#118]
Hello Vos,

I have a small issue that I could not understand. Could you please help me to elucidate it?

That is I would like to create a series of LINES as your photo here 

![image](https://user-images.githubusercontent.com/44887152/89478079-e9417180-d7c9-11ea-8fcd-8f55ad5c7fc2.png)

According to the code below (SDS_shoreline.py), I should create a waterline (shoreline). 

# process the water contours into a shoreline
            shoreline = process_shoreline(contours_mwi, cloud_mask, georef, image_epsg, settings)

However, the result I got somehow just a series of POINTS (as bellow). 
![image](https://user-images.githubusercontent.com/44887152/89478181-3e7d8300-d7ca-11ea-81a0-6fc063ea1e59.png)

Could you tell me how to change the code here, in order to get the LINE as you show.

Regards, 
Nguyen

**Comment by kvos** [comment]
@karinguyen - you can change it back to lines by going into SDS_tools.py and commenting line 585 and uncommenting line 586
![image](https://user-images.githubusercontent.com/7217258/89485292-cd4ac980-d7e3-11ea-9dd6-6af82ca4513e.png)
I had changed this to points as the lines joining the points were sometimes a bit random (there was an issue about this with lines that were crossing)

**Comment by karinguyen** [comment]
Thanks Vos,

Your help is very fruitful,

Regards
