### ISSUE TITLE
Some of the conda-forge files not found. 

### ISSUE THREAD

**Issue by olivo68** [kvos/CoastSat#12]
Hello, 
I am trying to install the CoastSat package on a Macbook Pro Retina with OSX 10.13.6 following the description but it fails while running the command: 
conda install --name coastsat --file requirements_osx64.txt

some of the file listed in the requirement file seems to be missing. 
any hint? 
thanks
Marco Olivieri

CondaHTTPError: HTTP 404 NOT FOUND for url <https://conda.anaconda.org/conda-forge/osx-64/proj4-5.2.0-h470a237_1.tar.bz2>
Elapsed: 00:00.222118
CF-RAY: 4d7370aaea7ccd2e-FCO

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

CondaHTTPError: HTTP 404 NOT FOUND for url <https://conda.anaconda.org/conda-forge/osx-64/hdf5-1.10.4-nompi_h5598ddc_1003.tar.bz2>
Elapsed: 00:00.267745
CF-RAY: 4d73714a19cbcd26-FCO

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

CondaHTTPError: HTTP 404 NOT FOUND for url <https://conda.anaconda.org/conda-forge/osx-64/postgresql-10.5-ha408888_1.tar.bz2>
Elapsed: 00:00.436672
CF-RAY: 4d73729d1c01cd36-FCO

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

CondaHTTPError: HTTP 404 NOT FOUND for url <https://conda.anaconda.org/conda-forge/osx-64/libgdal-2.3.2-h42efa9e_1.tar.bz2>
Elapsed: 00:00.428753
CF-RAY: 4d737429eca7cd0a-FCO

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

CondaHTTPError: HTTP 404 NOT FOUND for url <https://conda.anaconda.org/conda-forge/osx-64/gdal-2.3.2-py36hfc77a4a_1.tar.bz2>
Elapsed: 00:00.217833
CF-RAY: 4d73748ecf86cd1e-FCO

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

**Comment by kvos** [comment]
Hi Marco,

You are right it seems like the conda-forge OSX packages have been updated and some of the ones that are in the requirements file are obsolete now and can't be find in https://conda.anaconda.org/conda-forge/osx-64/. 

I will update the requirements file as soon as I get a Mac in my hands (not a Mac user). Hopefully in the next couple of days. Maybe @chrisleaman has CoastSat running on Mac?

In the meanwhile, you can remove the URLs of the 5 missing packages (proj4, hdf5, postgresql, libgdal and gdal) from the requirements .txt file and run that command again (conda install --name coastsat --file requirements_osx64.txt). Then you can install the missing packages separately by running: conda install name_of_the_package.

**Comment by chrisleaman** [comment]
@kvos, @olivo68 - I can have a look at this and test on my mac in the next day. My feeling is we should have a single environment.yml with the dependencies pinned to a specific version, but I think @kvos had some trouble making this work over multiple platforms. Will get back to you soon.

**Comment by olivo68** [comment]
I followed @kvos suggestion and installed the packages manually. However  gdal finds some conflict. I checked the web and It is not clear how to solve them. I will try. Thanks for your support. 
Marco



(coastsat) CricetoVolante:requirements olivo$ conda install gdal
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - conda-forge/osx-64::expat==2.2.5=hfc679d8_2
  - conda-forge/osx-64::kealib==1.4.10=heffcb4b_1
  - defaults/osx-64::sip==4.19.8=py36h0a44026_0

**Comment by chrisleaman** [comment]
Hi Marco, 

Can you copy paste this code into a new file called `environment.yml`:

```
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - numpy=1.16.3
  - matplotlib=3.0.3
  - earthengine-api=0.1.173
  - gdal=2.3.3
  - pandas=0.24.2
  - geopandas=0.4.1
  - pytz=2019.1
  - scikit-image=0.15.0
  - geos=3.7.1
  - scikit-learn=0.20.3
  - shapely=1.6.4
  - simplekml=1.3.0
  - scipy=1.2.1
  - spyder=3.3.4
  - notebook=5.7.8
```

Then, try create the environment by running the following command:

```
conda env create -f environment.yml -n coastsat
```

You should be able to then activate the environment by using:

```
conda activate coastsat
```

This worked for me, testing on Windows and Mac. Can you let us know if this also works for you and we will update the repo with this change.

**Comment by olivo68** [comment]
@kvos the test was successful, installation did not return any error message and I could successfully run the example file  example_jupyter.ipynb. 
 For completeness this installation was done under OSX 10.13.6 and using conda version 4.5.12. 

I am now ready to test the code on my own project. Thank you very much for the rapid and exhaustive support. 
Marco

**Comment by kvos** [comment]
thanks to @chrisleaman  who solved this issue!

**Comment by kvos** [comment]
I have merged these changes into the master, issue resolved.
