### ISSUE TITLE
Problem with cloud cover condition setting

### ISSUE THREAD

**Issue by karinguyen** [kvos/CoastSat#120]
Hello Vos,

I found there is a problem about setting threshold of maximum cloud cover.  

I was setting the threshold of 0.0. The reason why I was setting this threshold because I want to reduce the number of images downloaded (from about 2000 images to 100 images in period 2000-2020). However, the image obtained after downloading is still have cloud cover and about 2000 images. 

It looks like the settings do not have any effect?

# settings for the shoreline extraction
settings = { 
    # general parameters:
    'cloud_thresh': 0.0,        # threshold on maximum cloud cover

And the result still has cloud cover
![image](https://user-images.githubusercontent.com/44887152/89604985-67277a80-d8a7-11ea-9316-44825aad4699.png)

**Comment by kvos** [comment]
welcome to the world of remote sensing! 
the Sentinel-2 cloud mask that comes with the images from Google Earth Engine is actually not very reliable. There is a more advanced one here https://github.com/sentinel-hub/sentinel2-cloud-detector but I have not implemented it into CoastSat.
Also if you have 2000 images you probably have a number of duplicates.

Finally a suggestion here is to break down each beach into a smaller polygon, it will save you a lot of time and memory and you have to download much smaller images (and the shoreline detection will be more accurate). Here's an example:
![image](https://user-images.githubusercontent.com/7217258/89610406-c09aa400-d8bd-11ea-9660-11822d0bf3ee.png)

**Comment by karinguyen** [comment]
Hi Vos,

Thanks for the advise. I am doing like this.

Best Regards,

**Comment by karinguyen** [comment]
Hi Vos,

I am following your instructions, dividing the large area into several small beach. However, could you see the result below? It looks like something wrong with the shoreline detection? The beach is only 700 m long.


![image](https://user-images.githubusercontent.com/44887152/89862225-74fc3900-dbe2-11ea-95cb-155b576f81fd.png)

**Comment by kvos** [comment]
yes it's not picking any sand, try using the `bright` option for the `sand_color`

**Comment by karinguyen** [comment]
Hi Vos,

I changed to use "bright" option and the result as below. The shoreline is drawn landward slightly ?

I and my supervisor are thinking about the accuracy of coastsat, which is using Landsat only. As you mentioned in your papers, the accuracy reached sub-pixel level, ranging from 7.3 to 12.7 m (at four locations). But how about the accuracy for the Landsat only? The photo taken below for Landsat 5, and by using visually check, I think the accuracy will not be high as your paper showed.

Do you think so?

![image](https://user-images.githubusercontent.com/44887152/89874562-f958b700-dbf6-11ea-93a1-9dfa20e92f3f.png)

**Comment by kvos** [comment]
A single shoreline on an individual image may have an offset but we found that over the 30+ years time-series, after tidal correction, the accuracy of the time-series of cross-shore change along transects was ~10-15m. You can use Sentinel-2 as well is you want.
I would make that polygon slightly bigger, minimum ~5km2 so you can capture more pixels for each class. Also keep in mind that the classifier that you are using has never seen any data from Japan, so it will inherently not be as good as for the sites where it was trained. You can re-train the classifier as demonstrated here: https://github.com/kvos/CoastSat/blob/master/doc/train_new_classifier.md with an example here https://github.com/kvos/CoastSat/blob/master/classification/train_new_classifier.ipynb
