### ISSUE TITLE
'Remove bad georef' not working?

### ISSUE THREAD

**Issue by dixa12** [kvos/CoastSat#121]
Hi @kvos ,

I am applying the updated version with the two lines that remove duplicates and bad georeferenced images

output = SDS_tools.remove_duplicates(output) # removes duplicates (images taken on the same date by the same satellite)
output = SDS_tools.remove_inaccurate_georef(output, 10) # remove inaccurate georeferencing (set threshold to 10 m)

When I run the script I get a message with number of bad georef but they are not removed from the final result.
e..g
3 duplicates
1 bad georef
Am I doing something wrong or is it a bug in the code?

In addition, I want to ask if you think that a similar flag shold be applied to S2 images where geoaccuracy is just two values?

Best Regards,
Dimitris

**Comment by kvos** [comment]
this is the function (in SDS_tools.py): 
![image](https://user-images.githubusercontent.com/7217258/89700254-470fbe00-d970-11ea-9185-a21c272865e4.png)
so it's removing Landsat images based on the RMSE which comes in the metadata and for S2 based on the pass/fail flag for geometric quality control.
