### ISSUE TITLE
Error while merging S2 images

### ISSUE THREAD

**Issue by Noza1212** [kvos/CoastSat#124]
Hello Mr. Vos

I'm having trouble downloading the images. I want to extract shorelines from the coast  of Ecuador, a little country from South America. The thing is, every image I download is black or is corrupted... 

I'm kind of new in coding  so I don't understand why I'm getting the error shown in the image
By the way, my coordinates are:
[[[-80.806271, -1.716059],
            [-80.787973, -1.710072],
            [-80.759501, -1.835564],
            [-80.742579, -1.829916], 
            [-80.806271, -1.716059]]] 
The dates are: ['2011-01-01', '2020-12-01']

 ![Issue](https://user-images.githubusercontent.com/69748262/90329960-cdc72b00-df6e-11ea-9667-70f214b3eee4.jpg)

Congratulations for your work, I really like it. Thank you for taking the time to attend this message.
Regards.
Andrés Espinoza

**Comment by kvos** [comment]
hi @Noza1212 , I will check whats going on at those coordinates and let you know. Also the Landsat images are black?

**Comment by Noza1212** [comment]
Yes. This is an image from the subfolder 'pan' inside the folder 'L8'
![image](https://user-images.githubusercontent.com/69748262/90345729-d0fefd00-dfe8-11ea-8bc7-e38b56f55436.png)

**Comment by kvos** [comment]
are the coordinates of your polygon in the right sequence? clockwise from one of the vertices. First and last pair of coordinates should be the same

**Comment by Noza1212** [comment]
I didn`t consider the sequence. That fixed the problem in L7 and L8 images, although in L7 images, the images came out with black parts. Take a look:
L7 image
![image](https://user-images.githubusercontent.com/69748262/90348444-9d799e00-dffb-11ea-83d7-15721930bdf5.png)
L8 image
![image](https://user-images.githubusercontent.com/69748262/90348462-aec2aa80-dffb-11ea-87e8-356829aede93.png)

Nevertheless, in the case of S2, I keep getting the same error: 'there was an error while merging overlapping S2 images' and the images are totally black.

**Comment by kvos** [comment]
that's normal for L7 images (hardware issue onboard satellite, you have this on all images since 2002, but we can still use them).
Can you send me the updated coordinates, I will check what's happening with S2

**Comment by kvos** [comment]
I just made a update on the function that merges overlapping S2 images based on this issue #123 , maybe it fixes also your problem, try it out with the latest version #126

**Comment by Noza1212** [comment]
These are the updated coordinates: 
polygon = [[[-80.806271, -1.716059],
            [-80.787973, -1.710072],
            [-80.742579, -1.829916],
            [-80.759501, -1.835564], 
            [-80.806271, -1.716059]]]   
I tried with the updated function SDS_download, but I'm still getting the same error

**Comment by kvos** [comment]
@Noza1212 I tested your polygon and it works fine on my end
![image](https://user-images.githubusercontent.com/7217258/90503200-612c7600-e192-11ea-9c9c-50d855c57f5e.png)
![image](https://user-images.githubusercontent.com/7217258/90503231-6c7fa180-e192-11ea-8fdd-ce68909022a3.png)

if you want to visualise the .tif files just drag and drop in QGIS or ArcGIS
![image](https://user-images.githubusercontent.com/7217258/90503413-b799b480-e192-11ea-965c-e89ca640e6a3.png)
