### ISSUE TITLE
A histogram of MNDWI values 

### ISSUE THREAD

**Issue by karinguyen** [kvos/CoastSat#127]
Hi Vos,

Could you tell me where can I extract the histogram of MNDWI values as in your paper ?

I could not see which part in your code, so I am curious this ?

![image](https://user-images.githubusercontent.com/44887152/90456289-8938bc80-e133-11ea-8c64-d32740f1add9.png)

Best Regards,

**Comment by kvos** [comment]
it's not in there! I can add it when I get time, I have it on the scripts for the paper

**Comment by kvos** [comment]
hi @karinguyen  and other that were interested in the histogram of MNDWI values. I have just implemented this in the `development` branch, you can set the `adjust_detection` parameter to True and then if will make these plots with the histogram. Also for issue #136 from @Mobarz388.
![image](https://user-images.githubusercontent.com/7217258/95169461-a23e1f80-07fe-11eb-8d28-114124df7ab9.png)

**Comment by karinguyen** [comment]
Hi Vos,

Thank you very much for your kind support. I am following your presentation on International Conference on Coastal Engineering. 

All the best.

**Comment by kvos** [comment]
cool! will close this issue for the time being, feel free to reopen if any issue
