### ISSUE TITLE
Bug: 'gdf_all' referenced before assignment 

### ISSUE THREAD

**Issue by IraPelidae** [kvos/CoastSat#128]
Hi Killian,

Reinstalled CoastSat recently and am now getting the follow error when I run Section 3 (Batch Shoreline Detection) of the example.py script in Sypder:

![image](https://user-images.githubusercontent.com/49346361/90884687-1c7a2800-e3a8-11ea-9f2e-c2a04ae5d9e1.png)

Any chance you could please shed a light on this?

Best wishes,
Jack

**Comment by kvos** [comment]
it's fine, it did everything it just could not save the shorelines as a geojson, but you have the pickle file there with the outputs

**Comment by kvos** [comment]
I think your error could be related to #131 , try the development branch https://github.com/kvos/CoastSat/tree/development , I think it should fix your issue as well

**Comment by kvos** [comment]
did the update fix this issue?
