### ISSUE TITLE
can't compare offset-naive and offset-aware datetimes typeerror

### ISSUE THREAD

**Issue by vighneshrajendrans** [kvos/CoastSat#129]
hi mitchel
Iam updated  new coastsat environment for tidal correction 
After downloading the images and  got this error "can't compare offset-naive and offset-aware datetimes ".I change the date and time format in tidal data also but the error  exists.Please reply as soon as possible

**Comment by kvos** [comment]
1) you need to provide more details otherwise no one can help you (which file are you using, in what format does the dates come..etc)
2) python datetime objects can be offset-naive (don't have a timezone associated with the date) or offset-aware (have a timezone associate with the dates). You can only do operations with datetime objects that are of the same type otherwise you have that error.
3) no need to write "please reply as soon as possible" as this is a community based open-source development

**Comment by vighneshrajendrans** [comment]
> 1. you need to provide more details otherwise no one can help you (which file are you using, in what format does the dates come..etc)
> 2. python datetime objects can be offset-naive (don't have a timezone associated with the date) or offset-aware (have a timezone associate with the dates). You can only do operations with datetime objects that are of the same type otherwise you have that error.
> 3. no need to write "please reply as soon as possible" as this is a community based open-source development

We are working on Coastsat environment  past 6 months.And  earlier  i asked you for tidal correction part. Thats why iam hurry with the  comment.I changed the time format in tidal data then again i got this error again.And  now i explained the issue actually by downloading images displays warning like warning 1: Unable to export GeoTIFF file with different datatypes per different bands. All bands should have the same types in TIFF.".We focussed on lakshadweep islands ,lat and long mentioned below 
polygon = [[[73.110476, 8.300646],
            [73.077480, 8.324404],
            [73.011090, 8.278046],
            [73.043206, 8.244040],
            [73.110476, 8.300646]]]
We have our tidal data with this  below format

2016-12-01 0:00 | 0.04667
-- | --
2016-12-01 0:15 | 0.023035
2016-12-01 0:30 | 0.002143
2016-12-01 0:45 | -0.01519
2016-12-01 1:00 | -0.02877
2016-12-01 1:15 | -0.03846
2016-12-01 1:30 | -0.04422
2016-12-01 1:45 | -0.04607
 I enquire and understood that Selection step of tidal data has this issue
can't compare offset-naive and offset-aware datetimes 
I think that the problem is clear right now

**Comment by kvos** [comment]
ok if you look on that example tide file for Narrabeen you can see what the format has to be
![image](https://user-images.githubusercontent.com/7217258/91371148-8fc1e500-e853-11ea-9d41-2b8b68f021c7.png)

if you want to make offset-aware datetimes from offset naive it's very easy, just use the localize function, the code below should do :
```
import pytz
from datetime import datetime

dates_aware = [pytz.utc.localize(_) for _ in dates_naive]
```

**Comment by vighneshrajendrans** [comment]
USing the above code  got the error like this "dates_naive' is not defined"

**Comment by vighneshrajendrans** [comment]
>use  the above code and  got the error like this "dates_naive' is not defined"

**Comment by kvos** [comment]
you need to provide those dates_naive from your file with the tides, that line is just to convert to aware dates once you have the naive dates. I recommend taking an online course on python programming before attempting to use the toolbox

**Comment by vighneshrajendrans** [comment]
> you need to provide those dates_naive from your file with the tides, that line is just to convert to aware dates once you have the naive dates. I recommend taking an online course on python programming before attempting to use the toolbox

I already had  the course .I had only doubt that dates only accept in utc time with this format

2016-12-01  12:15:00 :00.000003+00:00
--

**Comment by vighneshrajendrans** [comment]
> you need to provide those dates_naive from your file with the tides, that line is just to convert to aware dates once you have the naive dates. I recommend taking an online course on python programming before attempting to use the toolbox

actually we already working in python .I have only one question Is the tide data definitely need utc time  code

**Comment by vighneshrajendrans** [comment]
Hi mitchel We are already working in python programming for past 1year.Now the actual problem is 
we converted into utc code and got the error str' object has no attribute 'to_pydatetime'.

**Comment by kvos** [comment]
please provide a clear description of the issue, otherwise it's hard to assist you

**Comment by vighneshrajendrans** [comment]
> please provide a clear description of the issue, otherwise it's hard to assist you

Initially date in our tide data in the form of 

2016-12-01 00:00
later we convert into the UTC 

2016-12-01  12:15:00 :00.000003+00:00
--
then   we got the error given below  .
--str' object has no attribute 'to_pydatetime'.I
we already imported datetime and time in the program also.Then how we got the error
