### ISSUE TITLE
Cannot write empty DataFrame to file

### ISSUE THREAD

**Issue by MGardevoir** [kvos/CoastSat#130]
hi Kilian,

I get the error "Unable to export GeoTIFF file with different datatypes per different bands. All bands should have the same types in TIFF." when download the images, and it cause the "Value Error: Cannot write empty DataFrame to file."
Is the error caused by incorrect metadata or anything else? Any suggestions for solving this problem?

Best wishes,
Tommy

**Comment by kvos** [comment]
hi Tommy, I have no idea what this could be, can you provide more information:
- which inputs you are using ? narrabeen example?
- which call produces this error?
unless I can reproduce the error I can't help
Cheers,
Kilian

**Comment by MGardevoir** [comment]
Hi,

I modify the polygon, dates and sat_list to data shown in the first image with espg = 32651.  All the data I get these data are from USGS website.
![222](https://user-images.githubusercontent.com/46940265/91522067-4d39f000-e8c7-11ea-8346-e3476fac8865.png)
Everything else are the same with the sample.
The error occur when I call SDS_shoreline.extract_shorelines.
![111](https://user-images.githubusercontent.com/46940265/91522075-51fea400-e8c7-11ea-9042-ec925a072635.png)
I hope these information are enough. Thanks for help.

Best wishes,
Tommy

**Comment by kvos** [comment]
I can't access your polygon coordinates, it looks like it's an image, can you post them as characters so I can copy-paste them and test it, thanks

**Comment by kvos** [comment]
I think your error could be related to #131 , try the development branch https://github.com/kvos/CoastSat/tree/development , I think it should fix your issue as well

**Comment by kvos** [comment]
did the update fix the issue?
