### ISSUE TITLE
Contours and EPSG

### ISSUE THREAD

**Issue by OctoData** [kvos/CoastSat#134]
done done done :)

**Comment by kvos** [comment]
EPSG is just a number that is attributed to a coordinate system. For example 4326 is WGS84 which are spherical coordinates. In coastsat we only work with projected coordinates (project the sphere onto a cartesian grid) and both Landsat and Sentinel-2 use UTM (Universal Transverse Mercator) projections.

Can you provide some examples of images? I'm also not sure which code you are using so it's hard to help

I've just seen this new paper in MDPI Remote Sensing, which uses Worldview2 imagery, maybe you can contact the authors to access their code https://search.proquest.com/docview/2436228781/fulltextPDF/D617235A1A794ED8PQ/1?accountid=12763

all the best,
Kilian

**Comment by OctoData** [comment]
@kvos sure, I will park some of the fork I have been working on here. Also, I am limited by the license to : `collection date/time, vehicle, and band combination` display. For code, are you referencing the EPSG or something else? I obtain EPSG from gdal (similar to output above).

Image 1 [ NIR ] (Coastal-NIR2)/(Coastal+NIR2)
----
![NIR](https://user-images.githubusercontent.com/63720259/92117614-6826cb80-edc3-11ea-83fe-45bf2cb96e6f.png)

Image 2 [RGB] (Band 4, 2, 1)
![RGB](https://user-images.githubusercontent.com/63720259/92118141-10d52b00-edc4-11ea-9317-791ed9ded2a6.png)


Image 3 [NIR R G] (7,4,2)
![NIR_R_G](https://user-images.githubusercontent.com/63720259/92118528-9b1d8f00-edc4-11ea-8dc8-7e5493cfd018.png)

------

**Scripting**

```python
import itertools
import os
import numpy as np
from osgeo import gdal, osr
import matplotlib.pyplot as plt
import json
from sklearn import preprocessing
from sklearn.cluster import KMeans
import cv2 as cv
import pickle 


data = gdal.Open(myImageFile, gdal.GA_ReadOnly)
bands = [data.GetRasterBand(k + 1).ReadAsArray() for k in range(data.RasterCount)]
im_ms = np.stack(bands, 2)

im_RGB = im_ms[:,:,[4,2,1]]

N_OPTICS_BANDS = data.RasterCount

reshapedData = im_ms.reshape(im_ms.shape[0] * im_ms.shape[1], im_ms.shape[2])
print("Fitting model...")
model = KMeans(2, max_iter=30)
model.fit(reshapedData)
print("Done")
pickle.dump(model, open("kmeansModel.pkl", "wb"))
plt.imshow(model.labels_.reshape(bands[0].shape),cmap="GnBu_r")
plt.title("Segmented acquisition")
plt.show()
```

![Segmented acquisition](https://user-images.githubusercontent.com/63720259/92119858-58f54d00-edc6-11ea-89fe-f7c975a3b3da.png)


 - Does the odd output (color of RGB) happen as a result of the uint being 16? It's not much better at uint8 btw.

**Comment by OctoData** [comment]
@kvos I think I was able to get a good solution on Part I (EPSG), please see below:

```python

from osgeo import gdal, osr
import utm

def WGS_to_UTM(raster):
  rasterInfo = gdal.Info(raster,format='json')
  raster_lat = rasterInfo['gcps']['gcpList'][0]['y'] 
  raster_long = rasterInfo['gcps']['gcpList'][0]['x']
  WV_UTM = utm.from_latlon(raster_lat,raster_long)
  WV_UTM=WV_UTM[2] ##56
  if raster_lat < 0:    ## define based on hemisphere
    hemisphere = 326 
  else: 
    hemisphere = 327
  UTM = int(str(hemisphere)+str(WV_UTM)) ##32656
```

Thoughts?
