### ISSUE TITLE
How much shoreline changes

### ISSUE THREAD

**Issue by Mobarz388** [kvos/CoastSat#135]
Dear Kilian Vos,

Can the CoastSat tool determine how much shoreline changes during a year or a month?

How can I find this information from the CoastSat toolkit?

Please let me know!

Regards,
Mojtaba

**Comment by kvos** [comment]
hi @Mobarz388 , you can find this information here https://doi.org/10.1016/j.coastaleng.2019.04.004, horizontal accuracy of the detected shorelines is 10-15m.
