### ISSUE TITLE
The date range

### ISSUE THREAD

**Issue by Mobarz388** [kvos/CoastSat#137]
Dear Kilian Vos,

Are these date ranges correct for analyzing Baltic Sea shoreline changes by CoastSat from 2017 to 2020?

dates = ['2017-06-01', '2018-06-01']

dates = ['2018-06-01', '2019-07-01']

dates = ['2019-07-01', '2020-09-01']

I want to analyze shoreline changes for each year separately by CoastSat. Would it be possible?

Please let me know. Thanks!

Regards,
Mojtaba

**Comment by kvos** [comment]
hi mojtaba, yes it's possible, I would recommend to extract the shorelines for all imagery available and then look at specific periods once you have the complete time-series of shoreline change.
