### ISSUE TITLE
Sub-module requires modules which aren't available on windows?

### ISSUE THREAD

**Issue by BsFrederiksen** [kvos/CoastSat#138]
Hi there, 
interesting stuff you guys are doing 👍 

I'm trying to run the example script provided, but i'm quite some issues. 
I'm using IDLE, not Anaconda, but seemingly have all the module required in the environment-package.

The SDS_download module import ee (Google's Earth Engine), which in tern import "fctnl" (made stupid workaround for now) and later "termios", both of which raises errors.

fcntl: [https://stackoverflow.com/questions/38936259/importerror-no-module-named-fcntl-under-windows](url)
termios: [https://stackoverflow.com/questions/52062977/unable-to-import-termios-package](url)

Googling the issues it appears neither is available on windows, but only Unix? 

Can it be, that CoastSat can only be run using Unix?

**Comment by BsFrederiksen** [comment]
Internal errors, sorry for the trouble - I'll give it another go before posting again :)

**Comment by kvos** [comment]
hey @BsFrederiksen , I recommend sticking to Anaconda (I've tested ubuntu, windows and mac and it works with anaconda). WIth pip it doesn't work because of the gdal library.

**Comment by BsFrederiksen** [comment]
Ok, thanks, i'll keep that in mind.
I got all the modules to load without any errors, after i reinstalled scikit-learn to the version specified. 
Waiting for google to grant acces to their api.
