### ISSUE TITLE
Error upgrading to Coastsat v1.0.5

### ISSUE THREAD

**Issue by dtkahl** [kvos/CoastSat#139]
Hello,
Thank you for your work! I have been messing around with Coastsat and have been successful for the past few months, when I received an error to update GEE today. I was running an older Coastsat version, so I downloaded and installed v1.0.5 and updated the environment and upgraded ee. I should preface the following that your project is my first experience with coding.

I am getting 1 error and one maybe error not related/maybe minor. 
(side problem) When I run the first cell I get the notification/error below about matplotlib in the Coastsat environment folder. When I check the version, I have 3.3.1 while the environment specifies 3.0.3. Is there a way to install the older version just for when I use coastsat, or do I just conda install the older version and the environment will use the correct version?

![error1](https://user-images.githubusercontent.com/67396034/93936598-40989400-fcdb-11ea-8b8b-69378da22360.JPG)

The main problem is when downloading satellite images, the code freezes. I experienced this earlier this summer and saw in previous issues that ee version 1.226 caused this problem, so I downgraded my ee version. This worked and all was well. I also saw it was resolved for Coastsat v1.0.4. Now as I upgrade versions, I have been unable to get the code to run. When in the coastsat environment I am using ee v0.1.226 which matches the environment file.

Please advise if you need additional information from me, not sure what is relevant to help with the issue. Also thank you for your time devoted to the project.

**Comment by kvos** [comment]
hi @dtkahl , thanks for reporting this. I would need to see what the first error relating to the GEE update was? were you told to update the GEE package as it's not working any more? I am not too worried about the matplotlib warnings but would like to know more about how your code freezes when downloading images? If you can provide your inputs (polygon, dates, satellites) as well as your coastsat environment (run conda list in the anaconda prompt) I can have a look at what could be going wrong

**Comment by dtkahl** [comment]
Hello and thank you for your quick reply. I ran some of my earlier Coastsat files as well as the v1.0.5 practice file, and I was able run the code just fine, even when I used older Jupiter notebook versions of the Coastsat code. I realized my polygon was over 100km^2, so when I reduced it, the code ran fine. Sorry for bothering you, it came down to user error!

I have a few questions if you may-- Can I run older versions of jupyter notebook with the new environment without a problem? I am asking because I prefer the points .goejson output and wanted to check if anything changed in the new version.
Also, how can I get multi-points as the .geojson output rather than lines from the new code? I find points are easier to clean up in GIS before extracting useful data, such as in older versions of the jupyter notebook code.

Otherwise, this issue can be closed and deleted as it does not contribute to your program. Again, my apologizes and thank you for your time.

**Comment by kvos** [comment]
the only thing that changed in the new environment is the version of the earthengine-api. However, I have updated the code so that it works both with the old and new environment (it checks which version of the earthengine-api you have installed and processes the images accordingly). 

In the new version of coastsat (download the latest master branch), you can choose whether you'd like to save the shorelines as lines or points:
![image](https://user-images.githubusercontent.com/7217258/94085580-dce1a880-fe4b-11ea-93d2-d8b09d9d1ba0.png)
