### ISSUE TITLE
Need some clarifications regarding the generated output after executing Coastsat

### ISSUE THREAD

**Issue by MeghanaKavuri** [kvos/CoastSat#140]
Hi Vos,
This is Meghana, I have been working on your CoastSat and have learnt many new things, Thanks for that, but now i have some doubts which I need them to be clarified for the further enhancement of my work. These are the following doubts which are listed one by one. 

1.) After the detection of the shoreline is done, for how many meters is a point getting detected in that process? I mean that for a particular date, we get a shoreline detected and that shoreline is detected and marked down as in the form of continuous points, I wanted to know whether points are uniformly marked. If so, then for how many meters each point is detected. 

2.) What are the "nan" values in the transect.geojson file? What do they mean?

3.) Does Geoaccuracy have any range according to your program? What are its units? How can it be enhanced?

4.) While each shoreline detected is saved in output.geojson, but is it right to compare them when their geoaccuracy varies dynamically? Is there any way to get the perfect time series?

5.) There are some missing points in some images when the shoreline detection algorithm fails to detect in some of the satellite images. Is it due to the clarity of the image or is it due to the geoaccuracy?

6.) When we get the graphs for each transect, Does it mean how the beach wave is dynamically changing? And also what are those values in the output.csv file? 

7.) I have used jupyter notebook, but when compare to executing the program using python, jupyter notebook is very very very slow. I don't know why? 

8.) Is it necessary to draw the transects? What is the advantage of drawing the transects? And what is the best way to draw the transects if I am taking ROI > 100kms. (Currently I am doing this time series analysis for a whole country.)

Thank you in advance. I am purely from computer science background, I don't know much about the terms and terminology of this stream. But learning them bit by bit. I have been googling them, but couldn't understand completely. So I thought it would be better to ask you as it is your own project and you will be knowing about it exactly.

**Comment by kvos** [comment]
the answers to most of these questions are in the documentation...NaNs are returned when there is not intersection between the transects and the 2D shorelines. Units for geoaccuracy is metres, except for Sentinel-2 where it's just a pass/fail flag (1 or -1)
