### ISSUE TITLE
Problem with script when training a new classifier

### ISSUE THREAD

**Issue by maithiyenlinh** [kvos/CoastSat#141]
Hi Vos, 
I tried to re-train the classer for my study are (in Vietnam). When I run the command for dividing the dataset into train and test and have some error like picture below. 
![Screenshot (110)](https://user-images.githubusercontent.com/71930085/94340816-ce9fb200-002e-11eb-9228-69f7df461381.png)

**Comment by kvos** [comment]
the error is quite explicit, you can't have any NaN or infinity values in your training data, remove those and it should be ok

**Comment by maithiyenlinh** [comment]
Thanks you for your answer. But I want to know the NaN or infinity values I need remove, they are the image I skip when classifying or they are the pixel I've not yet labeled for them?

**Comment by kvos** [comment]
just remove the rows in your X matrix and y vector where there are nans or infinity values (not sure how these may have ended there)

**Comment by maithiyenlinh** [comment]
I understand. Thank you for your answer
