### ISSUE TITLE
Timeout error

### ISSUE THREAD

**Issue by BlueGis** [kvos/CoastSat#142]
Hello kvos,
I recently encountered a problem that I didn't have before.
![1](https://user-images.githubusercontent.com/66717941/94367227-e8fd8c80-010f-11eb-8f34-fbd49a30befb.PNG)

Is this my network problem?

By the way, I'm studying your coastsat.slope, it's really amazing. But i don't know how to  set up the FES2014 global tide model.
Could you please tell me the solution?

Regards,
Qunqi

**Comment by kvos** [comment]
I can't see the full error

**Comment by BlueGis** [comment]
> I can't see the full error

OK, 
---------------------------------------------------------------------------
EEException                               Traceback (most recent call last)
D:\coast\coastsat\SDS_download.py in check_images_available(inputs)
    315     try:
--> 316         ee.ImageCollection('LANDSAT/LT05/C01/T1_TOA')
    317     except:

D:\anaconda\envs\coastsat\lib\site-packages\ee\computedobject.py in __call__(cls, *args, **kwargs)
     31     else:
---> 32       return type.__call__(cls, *args, **kwargs)
     33 

D:\anaconda\envs\coastsat\lib\site-packages\ee\imagecollection.py in __init__(self, args)
     37     """
---> 38     self.initialize()
     39 

D:\anaconda\envs\coastsat\lib\site-packages\ee\imagecollection.py in initialize(cls)
     71     if not cls._initialized:
---> 72       super(ImageCollection, cls).initialize()
     73       apifunction.ApiFunction.importApi(

D:\anaconda\envs\coastsat\lib\site-packages\ee\collection.py in initialize(cls)
     31     if not cls._initialized:
---> 32       apifunction.ApiFunction.importApi(cls, 'Collection', 'Collection')
     33       apifunction.ApiFunction.importApi(

D:\anaconda\envs\coastsat\lib\site-packages\ee\apifunction.py in importApi(cls, target, prefix, type_name, opt_prepend)
    182     """
--> 183     cls.initialize()
    184     prepend = opt_prepend or ''

D:\anaconda\envs\coastsat\lib\site-packages\ee\apifunction.py in initialize(cls)
    153     if not cls._api:
--> 154       signatures = data.getAlgorithms()
    155       api = {}

D:\anaconda\envs\coastsat\lib\site-packages\ee\data.py in getAlgorithms()
   1046     try:
-> 1047       call = _get_cloud_api_resource().projects().algorithms().list(
   1048           parent=_get_projects_path(), prettyPrint=False)

D:\anaconda\envs\coastsat\lib\site-packages\ee\data.py in _get_cloud_api_resource()
    302     raise ee_exception.EEException(
--> 303         'Earth Engine client library not initialized. Run `ee.Initialize()`')
    304   return _cloud_api_resource

EEException: Earth Engine client library not initialized. Run `ee.Initialize()`

During handling of the above exception, another exception occurred:

timeout                                   Traceback (most recent call last)
<ipython-input-9-3c3a3e3dfe68> in <module>
----> 1 SDS_download.check_images_available(inputs);

D:\coast\coastsat\SDS_download.py in check_images_available(inputs)
    316         ee.ImageCollection('LANDSAT/LT05/C01/T1_TOA')
    317     except:
--> 318         ee.Initialize()
    319 
    320     print('Images available between %s and %s:'%(inputs['dates'][0],inputs['dates'][1]), end='\n')

D:\anaconda\envs\coastsat\lib\site-packages\ee\__init__.py in Initialize(credentials, opt_url, use_cloud_api, cloud_api_key, http_transport, project)
    121       cloud_api_key=cloud_api_key,
    122       project=project,
--> 123       http_transport=http_transport)
    124   # Initialize the dynamically loaded functions on the objects that want them.
    125   ApiFunction.initialize()

D:\anaconda\envs\coastsat\lib\site-packages\ee\data.py in initialize(credentials, api_base_url, tile_base_url, use_cloud_api, cloud_api_base_url, cloud_api_key, project, http_transport)
    208   _http_transport = http_transport
    209 
--> 210   _install_cloud_api_resource()
    211 
    212   if project is not None:

D:\anaconda\envs\coastsat\lib\site-packages\ee\data.py in _install_cloud_api_resource()
    285       headers_supplier=_make_request_headers,
    286       response_inspector=_handle_profiling_response,
--> 287       http_transport=_http_transport)
    288 
    289   _cloud_api_resource_raw = _cloud_api_utils.build_cloud_resource(

D:\anaconda\envs\coastsat\lib\site-packages\ee\_cloud_api_utils.py in build_cloud_resource(api_base_url, api_key, credentials, timeout, headers_supplier, response_inspector, http_transport, raw)
    147       http=http_transport,
    148       requestBuilder=request_builder,
--> 149       model=alt_model)
    150   return resource
    151 

D:\anaconda\envs\coastsat\lib\site-packages\googleapiclient\_helpers.py in positional_wrapper(*args, **kwargs)
    132                 elif positional_parameters_enforcement == POSITIONAL_WARNING:
    133                     logger.warning(message)
--> 134             return wrapped(*args, **kwargs)
    135 
    136         return positional_wrapper

D:\anaconda\envs\coastsat\lib\site-packages\googleapiclient\discovery.py in build(serviceName, version, http, discoveryServiceUrl, developerKey, model, requestBuilder, credentials, cache_discovery, cache, client_options, adc_cert_path, adc_key_path, num_retries)
    272                 cache,
    273                 developerKey,
--> 274                 num_retries=num_retries,
    275             )
    276             return build_from_document(

D:\anaconda\envs\coastsat\lib\site-packages\googleapiclient\discovery.py in _retrieve_discovery_doc(url, http, cache_discovery, cache, developerKey, num_retries)
    363     # Note that it will already raise an error if we don't get a 2xx response
    364     req = HttpRequest(http, HttpRequest.null_postproc, actual_url)
--> 365     resp, content = req.execute(num_retries=num_retries)
    366 
    367     try:

D:\anaconda\envs\coastsat\lib\site-packages\googleapiclient\_helpers.py in positional_wrapper(*args, **kwargs)
    132                 elif positional_parameters_enforcement == POSITIONAL_WARNING:
    133                     logger.warning(message)
--> 134             return wrapped(*args, **kwargs)
    135 
    136         return positional_wrapper

D:\anaconda\envs\coastsat\lib\site-packages\googleapiclient\http.py in execute(self, http, num_retries)
    899             method=str(self.method),
    900             body=self.body,
--> 901             headers=self.headers,
    902         )
    903 

D:\anaconda\envs\coastsat\lib\site-packages\googleapiclient\http.py in _retry_request(http, num_retries, req_type, sleep, rand, uri, method, *args, **kwargs)
    202         if exception:
    203             if retry_num == num_retries:
--> 204                 raise exception
    205             else:
    206                 continue

D:\anaconda\envs\coastsat\lib\site-packages\googleapiclient\http.py in _retry_request(http, num_retries, req_type, sleep, rand, uri, method, *args, **kwargs)
    175         try:
    176             exception = None
--> 177             resp, content = http.request(uri, method, *args, **kwargs)
    178         # Retry on SSL errors and socket timeout errors.
    179         except _ssl_SSLError as ssl_error:

D:\anaconda\envs\coastsat\lib\site-packages\google_auth_httplib2.py in request(self, uri, method, body, headers, **kwargs)
    185 
    186         self.credentials.before_request(
--> 187             self._request, method, uri, request_headers)
    188 
    189         # Check if the body is a file-like stream, and if so, save the body

D:\anaconda\envs\coastsat\lib\site-packages\google\auth\credentials.py in before_request(self, request, method, url, headers)
    122         # the http request.)
    123         if not self.valid:
--> 124             self.refresh(request)
    125         self.apply(headers)
    126 

D:\anaconda\envs\coastsat\lib\site-packages\google\oauth2\credentials.py in refresh(self, request)
    208             self._client_id,
    209             self._client_secret,
--> 210             self._scopes,
    211         )
    212 

D:\anaconda\envs\coastsat\lib\site-packages\google\oauth2\_client.py in refresh_grant(request, token_uri, refresh_token, client_id, client_secret, scopes)
    246         body["scope"] = " ".join(scopes)
    247 
--> 248     response_data = _token_endpoint_request(request, token_uri, body)
    249 
    250     try:

D:\anaconda\envs\coastsat\lib\site-packages\google\oauth2\_client.py in _token_endpoint_request(request, token_uri, body)
    103     # occurs.
    104     while True:
--> 105         response = request(method="POST", url=token_uri, headers=headers, body=body)
    106         response_body = (
    107             response.data.decode("utf-8")

D:\anaconda\envs\coastsat\lib\site-packages\google_auth_httplib2.py in __call__(self, url, method, body, headers, timeout, **kwargs)
    114             _LOGGER.debug('Making request: %s %s', method, url)
    115             response, data = self.http.request(
--> 116                 url, method=method, body=body, headers=headers, **kwargs)
    117             return _Response(response, data)
    118         except httplib2.HttpLib2Error as exc:

D:\anaconda\envs\coastsat\lib\site-packages\httplib2\__init__.py in request(self, uri, method, body, headers, redirections, connection_type)
   1992                         headers,
   1993                         redirections,
-> 1994                         cachekey,
   1995                     )
   1996         except Exception as e:

D:\anaconda\envs\coastsat\lib\site-packages\httplib2\__init__.py in _request(self, conn, host, absolute_uri, request_uri, method, body, headers, redirections, cachekey)
   1649 
   1650         (response, content) = self._conn_request(
-> 1651             conn, request_uri, method, body, headers
   1652         )
   1653 

D:\anaconda\envs\coastsat\lib\site-packages\httplib2shim\__init__.py in _conn_request(self, conn, request_uri, method, body, headers)
    152 
    153         except Exception as e:
--> 154             raise _map_exception(e)
    155 
    156         return response, content

timeout: timed out
---------------------------------------------------------------------------
This is the error.

**Comment by kvos** [comment]
I don't know what the timeout error is, maybe network, maybe GEE access...
to install fes2014 you can follow the instructions here https://github.com/kvos/CoastSat.slope/blob/master/doc/FES2014_installation.md

**Comment by BlueGis** [comment]
> I don't know what the timeout error is, maybe network, maybe GEE access...
> to install fes2014 you can follow the instructions here https://github.com/kvos/CoastSat.slope/blob/master/doc/FES2014_installation.md

OK, I will try agian. Thank you!
