### ISSUE TITLE
About TypeError

### ISSUE THREAD

**Issue by BlueGis** [kvos/CoastSat#146]
Dear kvos,
I'm sorry to trouble you again.
When I click points along the shoreline and finish digitizing, a strange problem appears.
![捕获](https://user-images.githubusercontent.com/66717941/95408375-e0982380-0951-11eb-89cc-d1423e19757f.PNG)\

Thank you very much!

**Comment by kvos** [comment]
hey @BlueGis, I think this is an issue with the gdal package, it has been reported before...the only way to solve it from memory was to re-install the gdal package in the coastsat environment https://anaconda.org/conda-forge/gdal

**Comment by BlueGis** [comment]
> hey @BlueGis, I think this is an issue with the gdal package, it has been reported before...the only way to solve it from memory was to re-install the gdal package in the coastsat environment https://anaconda.org/conda-forge/gdal

I tried to install this package, but the problem was not resolved.

**Comment by kvos** [comment]
did you try to copy-paste the error in google or stackoverflow to see what they say? I think is an issue with the environment

**Comment by rodogomezs1** [comment]
install at the beginning on windows, reinstall gdal and it doesn't work for me. So switch to ubuntu 20.04 and it works without problems
