### ISSUE TITLE
ModuleNotFoundError: No module named 'ee

### ISSUE THREAD

**Issue by risanixm** [kvos/CoastSat#149]
<img width="849" alt="Screen Shot 2020-10-21 at 14 44 50" src="https://user-images.githubusercontent.com/64487566/96689146-389c4480-13ac-11eb-9703-c70010992eb9.png">
Hi Killian @kvos !
I have a problem, I think from the beginning of the installation I am sure there is nothing wrong but when I run it an error appears "ModuleNotFoundError: No module named 'ee"
I have previously used CoastSat from the previous version but it has never had a problem, now I want to try the latest version but it has problems. Can you please help me to solve this problem? Thanks.

**Comment by kvos** [comment]
try to install the ee module again as it means that it's not in the environment (`conda install earthengine-api`). If this doesn't work, I fear you will have to clean up your environment and re-install it, something must have gone wrong and you don't have the ee module anymore.

**Comment by risanixm** [comment]
I have tried installing the ee module again (conda install earthengine-api) but it still doesn't work. I also deleted the environment and reinstalled it but still can't. What should I do? or maybe i have to reinstall anaconda? thanks.

**Comment by kvos** [comment]
you can see which packages you have in your environment with `conda list`. If earthengine-api is not in there, then it will show that error. Maybe removing anaconda and reinstalling it is a good idea as when an environment is corrupted is usually hard to fix it

**Comment by risanixm** [comment]
Hi @kvos 
I really don't know what's wrong anymore. I have tried everything but it still doesn't work. Anyway Thanks for your advice

**Comment by HSdouma** [comment]
I had similar problem but solved by installing the last version ee as suggested by kvost. It works fine for me. I am pretty sure your issue is related to the earthengine version

**Comment by risanixm** [comment]
I have tried many ways including installing the latest version of ee as suggested but it still doesn't work

**Comment by HSdouma** [comment]
Are you using spyder?

**Comment by risanixm** [comment]
I'm using jupyter notebook

**Comment by Cosmo-liu** [comment]
I think before you start following all the instruction of creating the environment, you need to make sure your directory is point to where you downloaded CoastSat-master on your computer by using cd command, I had some issue in the beginning when I cd after I created the environment
