### ISSUE TITLE
output.geojson is not generated after the completion of the whole process 

### ISSUE THREAD

**Issue by MeghanaKavuri** [kvos/CoastSat#150]
Hello Kilian,
after running the program , the output.geojson is not getting generated from the day I updated the new release of the code.

I am getting the foloowing error, 

Transect locations saved in /home/meghana/Desktop/CoastSat/GUJARAT/abdasa2
Time-series of the shoreline change along the transects saved as:
/home/meghana/Desktop/CoastSat/GUJARAT/abdasa2/transect_time_series.csv
Traceback (most recent call last):
  File "example.py", line 205, in <module>
    tides_sat = SDS_tools.get_closest_datapoint(dates_sat, dates_ts, tides_ts)
  File "/home/meghana/Desktop/CoastSat/coastsat/SDS_tools.py", line 524, in get_closest_datapoint
    raise Exception('Time-series do not cover the range of your input dates')
Exception: Time-series do not cover the range of your input dates

Can you please tell me where it's going wrong. Thank you.

**Comment by kvos** [comment]
it raised an exception because your tide file does not match with the dates at which you are mapping shorelines
