### ISSUE TITLE
SDS_preprocess: "IndexError: Too many indices for array"

### ISSUE THREAD

**Issue by BsFrederiksen** [kvos/CoastSat#151]
Hi, gettting the following errors, I have too many indices for array. 

I have just installed and wanted to run the example notebook.

![image](https://user-images.githubusercontent.com/71383320/98105015-97c38400-1e97-11eb-83bc-9da15eb4c1b4.png)

Any ideas what it could be? I shouldn't have touched anything.

**Comment by kvos** [comment]
hi @BsFrederiksen,

that cell is to digitise a reference shoreline on a cloud free image, which helps to automatically map the shorelines in the next steps. Did you draw some points as showed in the readme animation?

**Comment by kvos** [comment]
is this issue solved @BsFrederiksen ?

**Comment by BsFrederiksen** [comment]
> is this issue solved @BsFrederiksen ?

Sorry for the late reply. I have not been able to replicate my problem recently, but i have also not had time to look further. So i think that yes, it is not a problem i struggling with any more.

**Comment by kvos** [comment]
ok will close the issue then, feel free to reopen if you run into other problems
