### ISSUE TITLE
Working with sat images not listed in coastSat

### ISSUE THREAD

**Issue by HSdouma** [kvos/CoastSat#153]
Hi Kvos
Afmgain many thanks for the program. Quite nice. 
My question is what if we have additional others sat images not from landsat or sentinel, say for instance worldview. What is the best way to include them for the shoreline detection?
Can this be done by adding them as jpeg and add their Metadata to the pkl file? Or do you have better suggestion?
Many thanks

**Comment by kvos** [comment]
hi @HSdouma, the codes would need to be adapted for worldview imagery as there isn't a SWIR1 band, only RGB and NIR.
@ydoherty has written code to extract the shoreline from worldview imagery with the coastsat algorithm, slightly modified. 
if you give us your email address we can send you a copy

**Comment by HSdouma** [comment]
Oh this is great Please can you send me a copy of the adopted code for worldview? Many thanks 

Envoyé depuis Yahoo Mail pour Android 
 
  Le mar., nov. 10, 2020 à 1:57, Kilian Vos<notifications@github.com> a écrit :   


hi @HSdouma, the codes would need to be adapted for worldview imagery as there isn't a SWIR1 band, only RGB and NIR.
@ydoherty has written code to extract the shoreline from worldview imagery with the coastsat algorithm, slightly modified.
if you give us your email address we can send you a copy

**Comment by HSdouma** [comment]
You can send it to laykehl@gmail.com

**Comment by HSdouma** [comment]
Hi Kvos
You can send me a copy of the code for worldview images, please to laykehl@gmail.com
Many thanks

**Comment by ydoherty** [comment]
Hi @HSdouma, I've sent the code to your email address. Be aware that the resolution of the worldview imagery means there are ~10,000 times more pixels for the same area and the code can be very slow (5-10min for a single image). The code I sent is seperate to coastsat and only extracts a single shoreline from a single image when you provide the filepath. Let me know if you have any troubles!
