### ISSUE TITLE
Problem with figure arrows

### ISSUE THREAD

**Issue by FREDERICBONOU** [kvos/CoastSat#155]
Dear friend,
Many thanks for providing coastsat to scintific community.
I have a problem with my figures,   when I make the plot, the (skip or keep ) button does not work. Everything is stop, no possibility to continue with the script
Best regards

**Comment by kvos** [comment]
are you using jupyter notebook or spyder? does it pop up any error message?

**Comment by FREDERICBONOU** [comment]
I am using both  spyder and jupyter notebook.  I got the same problem  with them

**Comment by FREDERICBONOU** [comment]
Is it possible to run coastsat on windows?

**Comment by kvos** [comment]
yes it's fine, I mostly run it on windows. You need to post what the error is so we can help you.

**Comment by FREDERICBONOU** [comment]
If so, what terminal are you using in windows to activate coastsat env ?

**Comment by kvos** [comment]
Anaconda Prompt as described in the README

**Comment by FREDERICBONOU** [comment]
ok thanks
