### ISSUE TITLE
Tidal correction problems with dates

### ISSUE THREAD

**Issue by pgurruchaga** [kvos/CoastSat#156]
Hi, I've been working with tidal correction by using fes2014 tide series. My .csv file with dates and tide format is identical to the one in the example. When I run the section of "get tide levels corresponding to the time of image acquisition" it gives me an error at the following line:
**tides_sat = SDS_tools.get_closest_datapoint(dates_sat, dates_ts, tides_ts)**
The error is: "Time-series do not cover the range of your input dates"
I've checked the input dates and everything is right, ['2013-01-01', '2020-10-31'] for mission L8. The .csv file with tide data covers the range 2013-2019, so I don't see the problem. Do you have any idea what the problem could be?

Thanks, Paula

**Comment by Julai091** [comment]
Hi Paula, 
Did you solve it?
I'm having this error as well. 
What am i doing wrong?
Thank you.
Julia

**Comment by pgurruchaga** [comment]
Hi! In my case I was using CoastSat.Slope to obtain the tide data from fes and when you set the data range [yyyyy,yyyy] if the last date in CoastSat was 2019-08-15 for instance, you have to set 2020 in CoastSat.Slope. I think that was it.
Later I realized since I was obtaining tide data for the exact moment the images were taken, I didn't even need that line to work because SDS_tools.get_closest_datapoint searches for this coincidences in case you have tide data every x minutes for example.

**Comment by Julai091** [comment]
Thank you! 

I did what you suggested, in my case the first date was wrong.  But now i get 'ValueError: min() arg is an empty sequence'.
I saw your comments with this error, and you said that that you didnt need to use  SDS_tools.get_closest_datapoint , right?! and skip that part of the code, right?
But can you create the tidally-correted  transects or just create csv. ?

Thank you so much.

Juli

**Comment by kvos** [comment]
just reopened this issue as it was closed. Could you please describe the issue Julia and I can try to help out. cheers, kilian

**Comment by Julai091** [comment]
Hi Kilian, So sorry.
I'm getting 'ValueError: min() arg is an empty sequence'. I saw Paula's comment that as we are getting FES2014 data, we dont need to run this part of the code # **get tide levels corresponding to the time of image acquisition, 
                                                        dates_sat = output['dates']
                                                        tides_sat = SDS_tools.get_closest_datapoint(dates_sat, dates_ts, tides_ts)**

But if i don't run this part of the code, it gives me **NameError: name 'tides_sat' is not defined**
What to do?
My dates are ok...i guess

Thank you Kilian.

**Comment by pgurruchaga** [comment]
you have to define "tides_sat = tides_ts" since that's the name it has above when you lod the data (tides_ts = np.array(tide_data['tide'])) or renaming there when loading. If you just skipped that line tides_sat is undefined effectively.

**Comment by Julai091** [comment]
Thanks heaps! :)

**Comment by Julai091** [comment]
Hi,

During the tidal correction for each transect did you get this error?

ValueError    Traceback (most recent call last)
<ipython-input-112-a52d06a5c5d1> in <module>
      6 for key in cross_distance.keys():
      7     correction = (tides_ts-reference_elevation)/beach_slope
----> 8     cross_distance_tidally_corrected[key] = cross_distance[key] + correction
      9 

ValueError: operands could not be broadcast together with shapes (11,) (8,) 

I dont know why cross_distance is adding nan to the string. I tried to filter nan, but it has no attribute to keys. Any ideas?

Thank you

**Comment by pgurruchaga** [comment]
Cross_distance contains the distance of the shoreline for each date for each transect, in your case for 11 images. Then the correction with tide data has only 8 elements, I guess in the process of obtaining tide data from FES you ignored some dates (for example the code from coastsat.slope deletes S2 and merges some dates). Perhaps that's not it cause I don't know which code are you using to obtain the tide series from fes, I hope this helps.

**Comment by Julai091** [comment]
Hi...i removed nans, but cross_distance is adding one more value to each transect.  Trying to figure it out. I'll see. Thank you!

**Comment by tomatehui** [comment]
Hi 
I'm trying to make tidal corrections and have no tidal data, therefore I did set up the FES 2014 and working on the coastal slope jupyter notebook. 
I want to use this information in the coastsat notebook,  but haven't be able to run it properly.  
Could you tell me how to use it? 
Do you convert  dates_sat, tide_sat to CSV files?  
Furthermore, how can you integrate the Sentinel 2 dates into the Landsat dates ?

Thanks in advance.

**Comment by tomatehui** [comment]
I'll look into it and I'll let you know how it goes.

Thanks for the help

**Comment by pgurruchaga** [comment]
Hi. In my case I used CoastSat.Slope at first, but then I copied the part of the code where it gets tide data from FES and introduced it into CoastSat, skipping the part where it ignores S2 because I need tide data for those images. Once I obtain the data I save it as .csv like this:
`#save FES model tide data at time of image acquisition
import pandas as pd
name_dict = {
            'dates': dates_sat,
            'tide': tide_sat
          }
df = pd.DataFrame(name_dict)
df.to_csv(os.path.join(inputs['filepath'], inputs['sitename'], sitename + '_tides'), index=False)`

and then load it to make the correction:
`#4. Tidal correction
# load the measured tide data
filepath = os.path.join(inputs['filepath'], inputs['sitename'], sitename + '_MMtides.csv')
tide_data = pd.read_csv(filepath, parse_dates=['dates'])
dates_ts = [_.to_pydatetime() for _ in tide_data['dates']]
tides_ts = np.array(tide_data['tide'])`

I guess it's unnecesary to save it and then load it as .csv but for me it's useful to have the information as a file.
I hope this helps!

**Comment by tomatehui** [comment]
Thanks  Paula,

I also think its a good idea to have them.  I tried to save the tide data with your lines and I got this error.


---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_15880/2235315630.py in <module>
     32           }
     33 df = pd.DataFrame(name_dict)
---> 34 df.to_csv(os.path.join(inputs['filepath'], **inputs[**'sitename'], sitename + '_tides'), index=False)

NameError: name 'inputs' is not defined
-------------------------------------------------------

Nor sure what's happening.

Thanks in advance.

**Comment by tomatehui** [comment]
Hello again,

I finally managed to follow Paula's advice and got the tide info onto the CoastSat.  
Thanks again for your help.

**Comment by kvos** [comment]
happy days! thanks @pgurruchaga !
one day it will be good to also integrate the tide model into main coastsat

**Comment by tomatehui** [comment]
I also meant thanks to  @pgurruchaga !

just she knows

**Comment by TiagoRodrigues-star** [comment]
Hello, I've been trying to use the tidal correction section of the code in CoastSat, unfortunately, I haven't been very successful. I'm trying to do an evaluation of the shoreline from 1984 to 2021, and I've used my very own modeled tide table from 1984-01-01 to 2021-01-01 (with the exact same format that is used in the example), but I end up always getting:

TypeError                                 Traceback (most recent call last)
<ipython-input-14-5c8520f17bb7> in <module>
      7 # get tide levels corresponding to the time of image acquisition
      8 dates_sat = output['dates']
----> 9 tides_sat = SDS_tools.get_closest_datapoint(dates_sat, dates_ts, tides_ts)
     10 
     11 # plot the subsampled tide data

~\Desktop\Mestrado\Mestrado (2ºSemestre)\Tese\CoastSat-master\CoastSat-master\coastsat\SDS_tools.py in get_closest_datapoint(dates, dates_ts, values_ts)
    521 
    522     # check if the time-series cover the dates
--> 523     if dates[0] < dates_ts[0] or dates[-1] > dates_ts[-1]:
    524         raise Exception('Time-series do not cover the range of your input dates')
    525 

TypeError: can't compare offset-naive and offset-aware datetimes

Does anyone know how to bypass this issue?

Btw, congratulations on this fine piece of coding it does wonders

**Comment by kvos** [comment]
yes this is a very easy one to fix, basically Python has two formats for dates, offset-naive (does not specify the timezone) and offset-aware (has a timezone). The coastsat shorelines are offset-aware and are in UTC time. If your tide table is not in offset-aware format you won't be able to compare them and it throws that error.

You can convert your dates from offset-naive to offset-aware with the localize() function. Example, if `dates` is a list with your offset-naive dates, convert to offset-aware like this:
`dates = [pytz.utc.localize(_) for _ in dates]`
you need to import pytz and crucially make sure that you tide table dates are in UTC (otherwise you won't be applying the right correction).

kilian

**Comment by seamuslo** [comment]
Hello @kvos , I am working with my own CSV of tidal data (attached) to apply the tidal correction. I originally encountered the same error as TiagoRodrigues-star, but as per your previous comment, I implemented the following changes regarding importing pytz and converting to offset aware (see below)
![image](https://user-images.githubusercontent.com/46720568/140542977-308a878d-ba96-4c42-8f8a-1072b91b5a81.png)

However, I now get the following error when I attempt to run that section of the code:
`---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_23864/2448828397.py in <module>
     14 fig, ax = plt.subplots(1,1,figsize=(15,4), tight_layout=True)
     15 ax.grid(which='major', linestyle=':', color='0.5')
---> 16 ax.plot(tide_data['dates'], tide_data['tide'], '-', color='0.6', label='all time-series')
     17 ax.plot(dates_sat, tides_sat, '-o', color='k', ms=6, mfc='w',lw=1, label='image acquisition')
     18 ax.set(ylabel='tide level [m]',xlim=[dates_sat[0],dates_sat[-1]], title='Water levels at the time of image acquisition');

~\anaconda3\envs\coastsat\lib\site-packages\matplotlib\axes\_axes.py in plot(self, scalex, scaley, data, *args, **kwargs)
   1605         lines = [*self._get_lines(*args, data=data, **kwargs)]
   1606         for line in lines:
-> 1607             self.add_line(line)
   1608         self._request_autoscale_view(scalex=scalex, scaley=scaley)
   1609         return lines

~\anaconda3\envs\coastsat\lib\site-packages\matplotlib\axes\_base.py in add_line(self, line)
   2099             line.set_clip_path(self.patch)
   2100 
-> 2101         self._update_line_limits(line)
   2102         if not line.get_label():
   2103             line.set_label('_line%d' % len(self.lines))

~\anaconda3\envs\coastsat\lib\site-packages\matplotlib\axes\_base.py in _update_line_limits(self, line)
   2121         Figures out the data limit of the given line, updating self.dataLim.
   2122         """
-> 2123         path = line.get_path()
   2124         if path.vertices.size == 0:
   2125             return

~\anaconda3\envs\coastsat\lib\site-packages\matplotlib\lines.py in get_path(self)
   1020         """
   1021         if self._invalidy or self._invalidx:
-> 1022             self.recache()
   1023         return self._path
   1024 

~\anaconda3\envs\coastsat\lib\site-packages\matplotlib\lines.py in recache(self, always)
    666         if always or self._invalidy:
    667             yconv = self.convert_yunits(self._yorig)
--> 668             y = _to_unmasked_float_array(yconv).ravel()
    669         else:
    670             y = self._y

~\anaconda3\envs\coastsat\lib\site-packages\matplotlib\cbook\__init__.py in _to_unmasked_float_array(x)
   1331         return np.ma.asarray(x, float).filled(np.nan)
   1332     else:
-> 1333         return np.asarray(x, float)
   1334 

   1335 

~\anaconda3\envs\coastsat\lib\site-packages\numpy\core\_asarray.py in asarray(a, dtype, order, like)
    100         return _asarray_with_like(a, dtype=dtype, order=order, like=like)
    101 
--> 102     return array(a, dtype, copy=False, order=order)
    103 
    104 

ValueError: could not convert string to float: '#DIV/0!'`

Do you have any insights as to why this error is occurring? I've attached my tidal data CSV so you can see my formatting

[Pekalongan_Tides.csv](https://github.com/kvos/CoastSat/files/7487421/Pekalongan_Tides.csv)

**Comment by seamuslo** [comment]
Also, as a follow on question, I would like to use the slope estimation functionality, however, when I look at the example code for slope, I am unsure how to convert the CSV tidal data from my previous comment into the .pkl file referenced below:
![image](https://user-images.githubusercontent.com/46720568/140543735-8504cfd9-2615-413a-9b0e-c9cc241df681.png)

Is there code within this package to convert the CSV of tidal data to the .pkl format required for the slope estimation?
