### ISSUE TITLE
EEE error

### ISSUE THREAD

**Issue by KatKonst** [kvos/CoastSat#158]
Hi Kilian, 

I keep getting this message today:
![image](https://user-images.githubusercontent.com/51007567/100100492-cf02d080-2e58-11eb-975e-dadf0b37b3d7.png)

I've tried scripts that used to work;  run the GEE authentication again; downloaded the latest version of your code;  tried on a different computer. I kept getting the same message. Any ideas what might be going on?

Cheers,
Kat

**Comment by kvos** [comment]
not sure what could be wrong there. can you activate your environment and then type 'conda list' and copy-paste that list here? it may give some clues on what the issue could be.

**Comment by KatKonst** [comment]
Thanks for getting back to me Kilian,

This is the list I get on my main computere:

# packages in environment at C:\Users\Kat\Anaconda3\envs\coastsat:
#
# Name                    Version                   Build  Channel
alabaster                 0.7.12                   py37_0
argh                      0.26.2                   py37_0
asn1crypto                1.3.0                    py37_0
astroid                   2.3.3                    py37_0
astropy                   3.2.1            py37he774522_0
atomicwrites              1.3.0                    py37_1
attrs                     19.3.0                     py_0
autopep8                  1.4.4                      py_0
babel                     2.8.0                      py_0
backcall                  0.1.0                    py37_0
bcrypt                    3.1.7            py37he774522_0
blas                      1.0                         mkl
bleach                    3.1.0                    py37_0
bzip2                     1.0.8                he774522_0
ca-certificates           2020.1.1                      0
cachetools                3.1.1                      py_0
certifi                   2019.11.28               py37_0
cffi                      1.14.0           py37h7a1dbc1_0
chardet                   3.0.4                 py37_1003
click                     7.0                      py37_0
click-plugins             1.1.1                      py_0
cligj                     0.5.0                    py37_0
cloudpickle               1.3.0                      py_0
colorama                  0.4.3                      py_0
cryptography              2.8              py37h7a1dbc1_0
curl                      7.67.0               h2a8f88b_0
cycler                    0.10.0                   py37_0
cytoolz                   0.10.1           py37he774522_0
dask-core                 2.11.0                     py_0
decorator                 4.4.1                      py_0
defusedxml                0.6.0                      py_0
deprecated                1.2.6                      py_0
descartes                 1.1.0                      py_3
diff-match-patch          20181111                   py_0
docutils                  0.16                     py37_0
earthengine-api           0.1.173                    py_0    conda-forge
entrypoints               0.3                      py37_0
expat                     2.2.5                he025d50_0
fiona                     1.8.4            py37h22081e2_0
flake8                    3.7.9                    py37_0
freetype                  2.9.1                ha9979f8_1
freexl                    1.0.5                hfa6e2cd_0
future                    0.18.2                   py37_0
gdal                      2.3.3            py37hdf43c64_0
geopandas                 0.4.1                      py_0
geos                      3.7.1                h33f27b4_0
google-api-python-client  1.7.11                     py_0    conda-forge
google-auth               1.11.2                     py_0
google-auth-httplib2      0.0.3                      py_3    conda-forge
hdf4                      4.2.13               h712560f_2
hdf5                      1.10.4               h7ebc959_0
httplib2                  0.17.0                   py37_0    conda-forge
hypothesis                5.5.4                      py_0
icc_rt                    2019.0.0             h0cc432a_1
icu                       58.2                 ha66f8fd_1
idna                      2.8                      py37_0
imageio                   2.6.1                    py37_0
imagesize                 1.2.0                      py_0
importlib_metadata        1.5.0                    py37_0
intel-openmp              2020.0                      166
intervaltree              3.0.2                      py_0
ipykernel                 5.1.4            py37h39e3cac_0
ipython                   7.12.0           py37h5ca1d4c_0
ipython_genutils          0.2.0                    py37_0
isort                     4.3.21                   py37_0
jedi                      0.14.1                   py37_0
jinja2                    2.11.1                     py_0
jpeg                      9b                   hb83a4c4_2
jsonschema                3.2.0                    py37_0
jupyter_client            5.3.4                    py37_0
jupyter_core              4.6.1                    py37_0
kealib                    1.4.7                h07cbb95_6
keyring                   21.1.0                   py37_0
kiwisolver                1.1.0            py37ha925a31_0
krb5                      1.16.4               hc04afaa_0
lazy-object-proxy         1.4.3            py37he774522_0
libboost                  1.67.0               hd9e427e_4
libcurl                   7.67.0               h2a8f88b_0
libgdal                   2.3.3                h10f50ba_0
libiconv                  1.15                 h1df5818_7
libkml                    1.3.0                he5f2a48_4
libnetcdf                 4.6.1                h411e497_2
libpng                    1.6.37               h2a8f88b_0
libpq                     11.2                 h3235a2c_0
libsodium                 1.0.16               h9d3ae62_0
libspatialindex           1.9.3                h33f27b4_0
libspatialite             4.3.0a              hc36aec2_19
libssh2                   1.8.2                h7a1dbc1_0
libtiff                   4.1.0                h56a325e_0
libxml2                   2.9.9                h464c3ec_0
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gmp                 6.1.0                         2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
mapclassify               2.2.0                      py_0
markupsafe                1.1.1            py37he774522_0
matplotlib                3.0.3            py37hc8f65d3_0
mccabe                    0.6.1                    py37_1
mistune                   0.8.4            py37he774522_0
mkl                       2020.0                      166
mkl-service               2.3.0            py37hb782905_0
mkl_fft                   1.0.15           py37h14836fe_0
mkl_random                1.1.0            py37h675688f_0
more-itertools            8.2.0                      py_0
msys2-conda-epoch         20160418                      1
munch                     2.5.0                      py_0
nbconvert                 5.6.1                    py37_0
nbformat                  5.0.4                      py_0
networkx                  2.4                        py_0
notebook                  6.0.3                    py37_0
numpy                     1.16.3           py37h19fb1c0_0
numpy-base                1.16.3           py37hc3f5095_0
numpydoc                  0.9.2                      py_0
oauth2client              4.1.3                      py_0    conda-forge
olefile                   0.46                     py37_0
openssl                   1.1.1d               he774522_4
packaging                 20.1                       py_0
pandas                    0.24.2           py37ha925a31_0
pandoc                    2.2.3.2                       0
pandocfilters             1.4.2                    py37_1
paramiko                  2.7.1                      py_0
parso                     0.5.2                      py_0
pathtools                 0.1.2                      py_1
pcre                      8.43                 ha925a31_0
pexpect                   4.8.0                    py37_0
pickleshare               0.7.5                    py37_0
pillow                    6.2.1            py37hdc69c19_0
pip                       20.0.2                   py37_1
pluggy                    0.13.1                   py37_0
proj4                     5.2.0                ha925a31_1
prometheus_client         0.7.1                      py_0
prompt_toolkit            3.0.3                      py_0
psutil                    5.6.7            py37he774522_0
psycopg2                  2.8.4            py37h7a1dbc1_0
py                        1.8.1                      py_0
pyasn1                    0.4.8                      py_0
pyasn1-modules            0.2.7                      py_0
pycodestyle               2.5.0                    py37_0
pycparser                 2.19                     py37_0
pydocstyle                4.0.1                      py_0
pyflakes                  2.1.1                    py37_0
pygments                  2.5.2                      py_0
pylint                    2.4.4                    py37_0
pynacl                    1.3.0            py37h62dcd97_0
pyopenssl                 19.1.0                   py37_0
pyparsing                 2.4.6                      py_0
pyproj                    1.9.6            py37h6782396_0
pyqt                      5.9.2            py37h6538335_2
pyrsistent                0.15.7           py37he774522_0
pysocks                   1.7.1                    py37_0
pytest                    5.3.5                    py37_0
pytest-arraydiff          0.3              py37h39e3cac_0
pytest-astropy            0.8.0                      py_0
pytest-astropy-header     0.1.2                      py_0
pytest-doctestplus        0.5.0                      py_0
pytest-openfiles          0.4.0                      py_0
pytest-remotedata         0.3.2                    py37_0
python                    3.7.6                h60c2a47_2
python-dateutil           2.8.1                      py_0
python-jsonrpc-server     0.3.4                      py_0
python-language-server    0.31.7                   py37_0
pytz                      2019.1                     py_0
pywavelets                1.1.1            py37he774522_0
pywin32                   227              py37he774522_1
pywin32-ctypes            0.2.0                 py37_1000
pywinpty                  0.5.7                    py37_0
pyyaml                    5.3              py37he774522_0
pyzmq                     18.1.1           py37ha925a31_0
qdarkstyle                2.8                        py_0
qt                        5.9.7            vc14h73c81de_0
qtawesome                 0.6.1                      py_0
qtconsole                 4.6.0                      py_1
qtpy                      1.9.0                      py_0
requests                  2.22.0                   py37_1
rope                      0.16.0                     py_0
rsa                       4.0                        py_0
rtree                     0.9.3            py37h21ff451_0
scikit-image              0.15.0           py37ha925a31_0
scikit-learn              0.20.3           py37h343c172_0
scipy                     1.2.1            py37h29ff71c_0
send2trash                1.5.0                    py37_0
setuptools                45.2.0                   py37_0
shapely                   1.6.4            py37h222a598_0
simplejson                3.17.0           py37he774522_0
sip                       4.19.8           py37h6538335_0
six                       1.14.0                   py37_0
snowballstemmer           2.0.0                      py_0
sortedcontainers          2.1.0                    py37_0
sphinx                    2.4.0                      py_0
sphinxcontrib-applehelp   1.0.1                      py_0
sphinxcontrib-devhelp     1.0.1                      py_0
sphinxcontrib-htmlhelp    1.0.2                      py_0
sphinxcontrib-jsmath      1.0.1                      py_0
sphinxcontrib-qthelp      1.0.2                      py_0
sphinxcontrib-serializinghtml 1.1.3                      py_0
spyder                    4.0.1                    py37_0
spyder-kernels            1.8.1                    py37_0
sqlalchemy                1.3.13           py37he774522_0
sqlite                    3.31.1               he774522_0
terminado                 0.8.3                    py37_0
testpath                  0.4.4                      py_0
tk                        8.6.8                hfa6e2cd_0
toolz                     0.10.0                     py_0
tornado                   6.0.3            py37he774522_3
traitlets                 4.3.3                    py37_0
ujson                     1.35             py37hfa6e2cd_0
uritemplate               3.0.1                      py_0    conda-forge
urllib3                   1.25.8                   py37_0
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.16.27012          hf0eaf9b_1
watchdog                  0.10.2                   py37_0
wcwidth                   0.1.8                      py_0
webencodings              0.5.1                    py37_1
wheel                     0.34.2                   py37_0
win_inet_pton             1.1.0                    py37_0
wincertstore              0.2                      py37_0
winpty                    0.4.3                         4
wrapt                     1.11.2           py37he774522_0
xerces-c                  3.2.2                ha925a31_0
xz                        5.2.4                h2fa13f4_4
yaml                      0.1.7                hc54c509_2
yapf                      0.28.0                     py_0
zeromq                    4.3.1                h33f27b4_3
zipp                      2.2.0                      py_0
zlib                      1.2.11               h62dcd97_3
zstd                      1.3.7                h508b16e_0

And this is the list from my second computer (both return the same error...)

(coastsat) C:\Users\akonstantinou>conda list
# packages in environment at C:\Users\akonstantinou\.conda\envs\coastsat:
#
# Name                    Version                   Build  Channel
alabaster                 0.7.12                   py37_0
argh                      0.26.2                   py37_0
asn1crypto                1.3.0                    py37_0
astroid                   2.3.3                    py37_0
astropy                   3.2.1            py37he774522_0
atomicwrites              1.3.0                    py37_1
attrs                     19.3.0                     py_0
autopep8                  1.4.4                      py_0
babel                     2.8.0                      py_0
backcall                  0.1.0                    py37_0
bcrypt                    3.1.7            py37he774522_0
blas                      1.0                         mkl
bleach                    3.1.0                    py37_0
bzip2                     1.0.8                he774522_0
ca-certificates           2020.1.1                      0
cachetools                3.1.1                      py_0
certifi                   2019.11.28               py37_0
cffi                      1.14.0           py37h7a1dbc1_0
chardet                   3.0.4                 py37_1003
click                     7.0                      py37_0
click-plugins             1.1.1                      py_0
cligj                     0.5.0                    py37_0
cloudpickle               1.3.0                      py_0
colorama                  0.4.3                      py_0
cryptography              2.8              py37h7a1dbc1_0
curl                      7.67.0               h2a8f88b_0
cycler                    0.10.0                   py37_0
cytoolz                   0.10.1           py37he774522_0
dask-core                 2.11.0                     py_0
decorator                 4.4.1                      py_0
defusedxml                0.6.0                      py_0
deprecated                1.2.6                      py_0
descartes                 1.1.0                      py_3
diff-match-patch          20181111                   py_0
docutils                  0.16                     py37_0
earthengine-api           0.1.173                    py_0    conda-forge
entrypoints               0.3                      py37_0
expat                     2.2.5                he025d50_0
fiona                     1.8.4            py37h22081e2_0
flake8                    3.7.9                    py37_0
freetype                  2.9.1                ha9979f8_1
freexl                    1.0.5                hfa6e2cd_0
future                    0.18.2                   py37_0
gdal                      2.3.3            py37hdf43c64_0
geopandas                 0.4.1                      py_0
geos                      3.7.1                h33f27b4_0
google-api-python-client  1.7.11                     py_0    conda-forge
google-auth               1.11.2                     py_0
google-auth-httplib2      0.0.3                      py_3    conda-forge
hdf4                      4.2.13               h712560f_2
hdf5                      1.10.4               h7ebc959_0
httplib2                  0.17.0                   py37_0    conda-forge
hypothesis                5.5.4                      py_0
icc_rt                    2019.0.0             h0cc432a_1
icu                       58.2                 ha66f8fd_1
idna                      2.8                      py37_0
imageio                   2.6.1                    py37_0
imagesize                 1.2.0                      py_0
importlib_metadata        1.5.0                    py37_0
intel-openmp              2020.0                      166
intervaltree              3.0.2                      py_0
ipykernel                 5.1.4            py37h39e3cac_0
ipython                   7.12.0           py37h5ca1d4c_0
ipython_genutils          0.2.0                    py37_0
isort                     4.3.21                   py37_0
jedi                      0.14.1                   py37_0
jinja2                    2.11.1                     py_0
jpeg                      9b                   hb83a4c4_2
jsonschema                3.2.0                    py37_0
jupyter_client            5.3.4                    py37_0
jupyter_core              4.6.1                    py37_0
kealib                    1.4.7                h07cbb95_6
keyring                   21.1.0                   py37_0
kiwisolver                1.1.0            py37ha925a31_0
krb5                      1.16.4               hc04afaa_0
lazy-object-proxy         1.4.3            py37he774522_0
libboost                  1.67.0               hd9e427e_4
libcurl                   7.67.0               h2a8f88b_0
libgdal                   2.3.3                h10f50ba_0
libiconv                  1.15                 h1df5818_7
libkml                    1.3.0                he5f2a48_4
libnetcdf                 4.6.1                h411e497_2
libpng                    1.6.37               h2a8f88b_0
libpq                     11.2                 h3235a2c_0
libsodium                 1.0.16               h9d3ae62_0
libspatialindex           1.9.3                h33f27b4_0
libspatialite             4.3.0a              hc36aec2_19
libssh2                   1.8.2                h7a1dbc1_0
libtiff                   4.1.0                h56a325e_0
libxml2                   2.9.9                h464c3ec_0
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gmp                 6.1.0                         2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
mapclassify               2.2.0                      py_0
markupsafe                1.1.1            py37he774522_0
matplotlib                3.0.3            py37hc8f65d3_0
mccabe                    0.6.1                    py37_1
mistune                   0.8.4            py37he774522_0
mkl                       2020.0                      166
mkl-service               2.3.0            py37hb782905_0
mkl_fft                   1.0.15           py37h14836fe_0
mkl_random                1.1.0            py37h675688f_0
more-itertools            8.2.0                      py_0
msys2-conda-epoch         20160418                      1
munch                     2.5.0                      py_0
nbconvert                 5.6.1                    py37_0
nbformat                  5.0.4                      py_0
networkx                  2.4                        py_0
notebook                  6.0.3                    py37_0
numpy                     1.16.3           py37h19fb1c0_0
numpy-base                1.16.3           py37hc3f5095_0
numpydoc                  0.9.2                      py_0
oauth2client              4.1.3                      py_0    conda-forge
olefile                   0.46                     py37_0
openssl                   1.1.1d               he774522_4
packaging                 20.1                       py_0
pandas                    0.24.2           py37ha925a31_0
pandoc                    2.2.3.2                       0
pandocfilters             1.4.2                    py37_1
paramiko                  2.7.1                      py_0
parso                     0.5.2                      py_0
pathtools                 0.1.2                      py_1
pcre                      8.43                 ha925a31_0
pexpect                   4.8.0                    py37_0
pickleshare               0.7.5                    py37_0
pillow                    6.2.1            py37hdc69c19_0
pip                       20.0.2                   py37_1
pluggy                    0.13.1                   py37_0
proj4                     5.2.0                ha925a31_1
prometheus_client         0.7.1                      py_0
prompt_toolkit            3.0.3                      py_0
psutil                    5.6.7            py37he774522_0
psycopg2                  2.8.4            py37h7a1dbc1_0
py                        1.8.1                      py_0
pyasn1                    0.4.8                      py_0
pyasn1-modules            0.2.7                      py_0
pycodestyle               2.5.0                    py37_0
pycparser                 2.19                     py37_0
pydocstyle                4.0.1                      py_0
pyflakes                  2.1.1                    py37_0
pygments                  2.5.2                      py_0
pylint                    2.4.4                    py37_0
pynacl                    1.3.0            py37h62dcd97_0
pyopenssl                 19.1.0                   py37_0
pyparsing                 2.4.6                      py_0
pyproj                    1.9.6            py37h6782396_0
pyqt                      5.9.2            py37h6538335_2
pyrsistent                0.15.7           py37he774522_0
pysocks                   1.7.1                    py37_0
pytest                    5.3.5                    py37_0
pytest-arraydiff          0.3              py37h39e3cac_0
pytest-astropy            0.8.0                      py_0
pytest-astropy-header     0.1.2                      py_0
pytest-doctestplus        0.5.0                      py_0
pytest-openfiles          0.4.0                      py_0
pytest-remotedata         0.3.2                    py37_0
python                    3.7.6                h60c2a47_2
python-dateutil           2.8.1                      py_0
python-jsonrpc-server     0.3.4                      py_0
python-language-server    0.31.7                   py37_0
pytz                      2019.1                     py_0
pywavelets                1.1.1            py37he774522_0
pywin32                   227              py37he774522_1
pywin32-ctypes            0.2.0                 py37_1000
pywinpty                  0.5.7                    py37_0
pyyaml                    5.3              py37he774522_0
pyzmq                     18.1.1           py37ha925a31_0
qdarkstyle                2.8                        py_0
qt                        5.9.7            vc14h73c81de_0
qtawesome                 0.6.1                      py_0
qtconsole                 4.6.0                      py_1
qtpy                      1.9.0                      py_0
requests                  2.22.0                   py37_1
rope                      0.16.0                     py_0
rsa                       4.0                        py_0
rtree                     0.9.3            py37h21ff451_0
scikit-image              0.15.0           py37ha925a31_0
scikit-learn              0.20.3           py37h343c172_0
scipy                     1.2.1            py37h29ff71c_0
send2trash                1.5.0                    py37_0
setuptools                45.2.0                   py37_0
shapely                   1.6.4            py37h222a598_0
simplejson                3.17.0           py37he774522_0
sip                       4.19.8           py37h6538335_0
six                       1.14.0                   py37_0
snowballstemmer           2.0.0                      py_0
sortedcontainers          2.1.0                    py37_0
sphinx                    2.4.0                      py_0
sphinxcontrib-applehelp   1.0.1                      py_0
sphinxcontrib-devhelp     1.0.1                      py_0
sphinxcontrib-htmlhelp    1.0.2                      py_0
sphinxcontrib-jsmath      1.0.1                      py_0
sphinxcontrib-qthelp      1.0.2                      py_0
sphinxcontrib-serializinghtml 1.1.3                      py_0
spyder                    4.0.1                    py37_0
spyder-kernels            1.8.1                    py37_0
sqlalchemy                1.3.13           py37he774522_0
sqlite                    3.31.1               he774522_0
terminado                 0.8.3                    py37_0
testpath                  0.4.4                      py_0
tk                        8.6.8                hfa6e2cd_0
toolz                     0.10.0                     py_0
tornado                   6.0.3            py37he774522_3
traitlets                 4.3.3                    py37_0
ujson                     1.35             py37hfa6e2cd_0
uritemplate               3.0.1                      py_0    conda-forge
urllib3                   1.25.8                   py37_0
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.16.27012          hf0eaf9b_1
watchdog                  0.10.2                   py37_0
wcwidth                   0.1.8                      py_0
webencodings              0.5.1                    py37_1
wheel                     0.34.2                   py37_0
win_inet_pton             1.1.0                    py37_0
wincertstore              0.2                      py37_0
winpty                    0.4.3                         4
wrapt                     1.11.2           py37he774522_0
xerces-c                  3.2.2                ha925a31_0
xz                        5.2.4                h2fa13f4_4
yaml                      0.1.7                hc54c509_2
yapf                      0.28.0                     py_0
zeromq                    4.3.1                h33f27b4_3
zipp                      2.2.0                      py_0
zlib                      1.2.11               h62dcd97_3
zstd                      1.3.7                h508b16e_0

I hope this gives you an idea?

Cheers,
Kat

**Comment by kvos** [comment]
yep this one is the issue : earthengine-api 0.1.173 py_0 conda-forge
The EarthEngine developers do not maintain this version of the api any more, that's why it's not letting you initialise.
You have two options, one is to update the earthengine-api package alone but sometimes it doesn't work. The best option in my opinion is to create a new environment with the updated packages (in the latest environment.yml file). Before creating the new environment, type 'conda clean --all' in the anaconda prompt (ran as administrator) to clean up all the cached packages. Let me know if it fixes it, kilian

**Comment by KatKonst** [comment]
Aha! Thank you, Kilian. I'll try it out tomorrow and get back to you (it's almost 2230 at my corner of the world). Fingers crossed, it will sort things out. -Kat

**Comment by KatKonst** [comment]
Hello, again Kilian,
So, the fix you suggested worked as far as the GEE api is concerned, but it also updated matplotlib (to 3.3.3) and CoastSat did not like that. I reverted back to v3.0.3 and this now connecting with GEE and seems to work up to a point. I have still not managed to resolve the following:
1.	For some areas (eg: polygon = [[[1.0448145632994166,52.959800399543404], [1.0734820132505885,52.96864058539745], [1.0448145632994166,52.96864058539745],  [1.0448145632994166,52.959800399543404], [1.0448145632994166,52.959800399543404]]] ), only S2 images are saved in the processes jpg folder. Could that have anything to do with overlapping images?
2.	At areas processes images from all satellites are saved (e.g.: polygon = [[[-5.1741082648855,50.33762430074528],   [-5.137716052971437,50.33762430074528], [-5.137716052971437,50.38186794391341],  [-5.1741082648855,50.38186794391341],  [-5.1741082648855,50.33762430074528]]]), I get the following message when I run it with or without a reference shoreline:

![image](https://user-images.githubusercontent.com/51007567/100631838-0e7f6000-3324-11eb-9e13-54b55ecca6b2.png)

I would greatly appreciate your help in resolving this…
Cheers,
Kat

**Comment by kvos** [comment]
hi kat, good news. I would not worry too much about the matplotlib warnings, they shouldn't cause any issues. 
Regarding your error, the new version of coastsat has a setting called 'adjust_detection' where you can adjust the threshold used to map the shoreline, do you have that setting in your settings dictionary? if not you should add it and set it to False if you don't want to use it.

**Comment by KatKonst** [comment]
Thanks Kilian! Sounds promising... Also sounds like I should keep a bit more up to date with coastsat developments!
