### ISSUE TITLE
Installation/Initialization errors on MacOS

### ISSUE THREAD

**Issue by conlin-matt** [kvos/CoastSat#16]
Hey Killian,

I've just begun the process of using CoastSat for my local east coast Florida site. For reference, I'm doing this on MacOS 10.14. In following your nicely laid out installation/initialization steps in the readme, I ran into trouble when your line to create a new environment (i.e. "conda env create -f environment.yml -n coastsat") threw me an error. To fix this, and to make it through the step of linking my GEE credentials to the Python API, I had to do the following:
1) Create the new environment within the folder containing CoastSat using conda create --name coastsat
2) Install python and pip within the new environment using conda install pip
3) Install the GEE python library using pip install earthengine-api
4) Do earthengine-authenticate and follow the steps in the readme to authenticate

I'm not sure if this is a general MacOS issue, or one specific to my system, but I figured I post in case anyone else runs into the same issue.

-Matt Conlin

**Comment by kvos** [comment]
thanks @conlin-matt ! this is very useful for other MacOS users.
what was the error when you ran "conda env create -f environment.yml -n coastsat"?

**Comment by conlin-matt** [comment]
Sorry, should have posted that before. The error is as follows:
"SpecNotFound: Invalid name, try the format: user/package"

I tried changing the name to the full path whereI am trying to create the environment, but that didn't work either with error "<path> was not found on anaconda.org"

**Comment by Julai091** [comment]
Hi guys,

I'm facing some problem using Windows .
:(
Juliana

Em sáb, 8 de jun de 2019 9:48 PM, Matthew Conlin <notifications@github.com>
escreveu:

**Comment by Julai091** [comment]
Same


Em dom, 9 de jun de 2019 12:42 AM, Juliana Guerreiro <julai091@gmail.com>
escreveu:

**Comment by kvos** [comment]
ok so there seems to be an issue with the installation.
@conlin-matt did you manage to get coastsat running on your Mac with your fix?
@Julai091 what is the problem on Windows? could you please add a screenshot of the error?

If the environment.yml file does not work for you, another option is to install the individual packages separately:
1. conda create --name coastsat
2. conda activate coastsat
3. conda install <name_of_the_package>

You will need to install the following packages to run coastsat: 
- *earthengine-api, gdal, geopandas, pytz, scikit-image, scikit-learn, shapely*
- as well as these basic python packages *numpy, scipy, spyder, notebook*.

Once they have all been installed you have to run the command *earthengine authenticate* and link to your gmail account.

I hope this helps, let me know if there are still issues with the installation.

**Comment by conlin-matt** [comment]
@kvos yes, after using my 4 steps above I individually downloaded all the required packages with conda or pip and coastsat seems to be running. Thanks for providing that package dependency list- very helpful!

**Comment by Julai091** [comment]
Thank you Kilian, it worked for me as well. I also used conda and pip and
coastsat seems to be running too. Thank you!!

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Livre
de vírus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>.
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Em dom, 9 de jun de 2019 às 13:47, Matthew Conlin <notifications@github.com>
escreveu:

**Comment by kvos** [comment]
great! thanks @conlin-matt for providing a fix for Mac, I will leave this issue open for a little longer to see if other users have similar issues before closing it and updating the documentation.

**Comment by hamidj2019** [comment]
Hi everybody, 

I am using a windows system, I spent a couple of hours to set up the system on the computer but in the step 1.1 I come across some Error Messages. I installed Anaconda on my PC. Then I created a new environment named coastsat with all the required packages:
conda env create -f environment.yml -n coastsat
Then I wanted to activate the new environment as below according to the website

conda activate coastsat
At this stage the following message has appeared. 

Invoke-Expression : Cannot bind argument to parameter 'Command' because it is an empty string.

At C:\Users\TANIN\Anaconda3\shell\condabin\Conda.psm1:70 char:36

+         Invoke-Expression -Command $activateCommand;

+                                    ~~~~~~~~~~~~~~~~

    + CategoryInfo      : InvalidData: (:) [Invoke-Expression], ParameterBindingValidationException

    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Microsoft.PowerShell.Commands.Invo

   keExpressionCommand

---------------------------------------------------------------------------------------------------------------
I would highly appreciate if you can kindly advise how I can fix this issue.

**Comment by hamidj2019** [comment]
Hi,

I tried to follow Kilian advise that is "to install the individual packages separately", BUT in the step two (conda activate coastsat) I got the following error message. I am using WINDOWS.

---------------------------Error Message ---------------------------------------------
(base) PS C:\Users\TANIN\Anaconda3> conda activate coastsat

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\Users\TANIN\Anaconda3\lib\site-packages\conda\cli\main.py", line 138, in main
        return activator_main()
      File "C:\Users\TANIN\Anaconda3\lib\site-packages\conda\activate.py", line 940, in main
        print(activator.execute(), end='')
      File "C:\Users\TANIN\Anaconda3\lib\site-packages\conda\activate.py", line 173, in execute
        return getattr(self, self.command)()
      File "C:\Users\TANIN\Anaconda3\lib\site-packages\conda\activate.py", line 150, in activate
        builder_result = self.build_activate(self.env_name_or_prefix)
      File "C:\Users\TANIN\Anaconda3\lib\site-packages\conda\activate.py", line 275, in build_activate
        return self._build_activate_stack(env_name_or_prefix, False)
      File "C:\Users\TANIN\Anaconda3\lib\site-packages\conda\activate.py", line 332, in _build_activate_stack
        self._replace_prefix_in_path(old_conda_prefix, prefix))
      File "C:\Users\TANIN\Anaconda3\lib\site-packages\conda\activate.py", line 550, in _replace_prefix_in_path
        assert last_idx is not None
    AssertionError

`$ C:\Users\TANIN\Anaconda3\Scripts\conda-script.py shell.powershell activate coastsat`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=C:\Users\TANIN\Anaconda3\Scripts\conda.exe
             CONDA_PREFIX=C:\Users\TANIN\Anaconda3
    CONDA_PROMPT_MODIFIER=(base)
               CONDA_ROOT=C:\Users\TANIN\Anaconda3
              CONDA_SHLVL=1
                 HOMEPATH=\Users\TANIN
                     PATH=C:\Users\TANIN\Anaconda3;C:\Users\TANIN\Anaconda3\Library\mingw-w64\bi
                          n;C:\Users\TANIN\Anaconda3\Library\usr\bin;C:\Users\TANIN\Anaconda3\Li
                          brary\bin;C:\Users\TANIN\Anaconda3\Scripts;C:\Users\TANIN\Anaconda3\bi
                          n;C:\Users\TANIN\Anaconda3\condabin;C:\Program
                          Files\firemodels\SMV6;C:\Program Files\firemodels\FDS6\bin;C:\Program
                          Files (x86)\Common Files\Oracle\Java\javapath;C:\ProgramData\Oracle\Ja
                          va\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:
                          \WINDOWS\System32\WindowsPowerShell\v1.0\;D:\Bremen Turbulence
                          course\bin;D:\MATLAB\bin;D:\matlab
                          software\bin;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\MiKTeX 2.9\
                          miktex\bin\x64\;C:\Users\TANIN\AppData\Local\Microsoft\WindowsApps;
             PSMODULEPATH=C:\Users\TANIN\Documents\WindowsPowerShell\Modules;C:\Program Files\Wi
                          ndowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Mod
                          ules
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
    VBOX_MSI_INSTALL_PATH=C:\Program Files\Oracle\VirtualBox\

     active environment : base
    active env location : C:\Users\TANIN\Anaconda3
            shell level : 1
       user config file : C:\Users\TANIN\.condarc
 populated config files :
          conda version : 4.6.11
    conda-build version : 3.17.8
         python version : 3.7.3.final.0
       base environment : C:\Users\TANIN\Anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\TANIN\Anaconda3\pkgs
                          C:\Users\TANIN\.conda\pkgs
                          C:\Users\TANIN\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\TANIN\Anaconda3\envs
                          C:\Users\TANIN\.conda\envs
                          C:\Users\TANIN\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.6.11 requests/2.21.0 CPython/3.7.3 Windows/10 Windows/10.0.17134
          administrator : False
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.

I would highly appreciate if you can kindly advise how I can fix this issue.

**Comment by kvos** [comment]
ok @hamidj2019 , I don't know what invoke-expression means and why is it raising an error when you call conda activate which is a very basic conda command. Let's try to debug it from the start:

1. Are you opening the Anaconda Prompt as shown in the screenshot below (not the Anaconda PowerShell Prompt) ? 
![Capture](https://user-images.githubusercontent.com/7217258/59542615-2dc8d880-8f4a-11e9-83af-fc8d4737448a.JPG)

2. Can you type on the Anaconda Prompt:
`conda list conda$` 
and provide us with a screenshot of what is printed in the console (it should be something like below).
![Capture](https://user-images.githubusercontent.com/7217258/59542855-61f0c900-8f4b-11e9-87b7-ff4377f3d654.JPG)

3. Can you try to create a dummy environment and activate it?
Type on the Anaconda Prompt:
`conda create --name dummy`
Then:
`conda activate dummy`
If it doesn't work, run the Anaconda Prompt as Administrator and try again.

Let me know how it goes.

**Comment by hamidj2019** [comment]
Hi Kilian,
You posted some message here to me but that has been deleted. Are you deleting the messages and communications after some time period?
Could you please advise so that I can know about it so I do not miss them.
Best regards
Hamid

**Comment by hamidj2019** [comment]
Hello Kilian,

Are you monitoring this email?

**Comment by hamidj2019** [comment]
> ok so there seems to be an issue with the installation.
> @conlin-matt did you manage to get coastsat running on your Mac with your fix?
> @Julai091 what is the problem on Windows? could you please add a screenshot of the error?
> 
> If the environment.yml file does not work for you, another option is to install the individual packages separately:
> 
> 1. conda create --name coastsat
> 2. conda activate coastsat
> 3. conda install <name_of_the_package>
> 
> You will need to install the following packages to run coastsat:
> 
> * _earthengine-api, gdal, geopandas, pytz, scikit-image, scikit-learn, shapely_
> * as well as these basic python packages _numpy, scipy, spyder, notebook_.
> 
> Once they have all been installed you have to run the command _earthengine authenticate_ and link to your gmail account.
> 
> I hope this helps, let me know if there are still issues with the installation.

-------------------------------------------------------------------
After that I tried to follow the following 3 steps: 

conda create --name coastsat
conda activate coastsat
conda install <name_of_the_package>
BUT in step 3, I get an ERROR message. please see below:

(coastsat) C:\Users\TANIN>conda install earthengine-api
Collecting package metadata: done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - earthengine-api

Current channels:

  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/win-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
