### ISSUE TITLE
Odd black stripes across images

### ISSUE THREAD

**Issue by arttrembanis** [kvos/CoastSat#164]
Has anyone come across this?
I've just finished loading a sequence of Landsat images covering the period 1999-2020 and there are a bunch of images with large black stripes running across them.
![Screen Shot 2020-12-21 at 1 52 36 PM](https://user-images.githubusercontent.com/60475018/102823127-4bc99180-43a8-11eb-8ec1-aae18a5e0367.png)
![Screen Shot 2020-12-21 at 1 53 12 PM](https://user-images.githubusercontent.com/60475018/102823128-4c622800-43a8-11eb-97e1-2052bf47a372.png)

**Comment by kvos** [comment]
hey Art, here is what is causing this https://www.usgs.gov/faqs/what-landsat-7-etm-slc-data?qt-news_science_products=0#qt-news_science_products
You can still use L7 images, you will have to make the minimum shoreline length parameter smaller so it can map the shoreline between the bands (which continuously move)
