### ISSUE TITLE
Errors encountered

### ISSUE THREAD

**Issue by arheem** [kvos/CoastSat#167]
what is wrong?
![screenshot-localhost-8888-notebooks-OneDrive-Desktop-Anaconda-CoastSat-master-Abuesi-ipynb-1609768804789](https://user-images.githubusercontent.com/69360729/103543322-3bc8ac00-4e96-11eb-8e8c-1a78e3cf5ce0.png)

**Comment by kvos** [comment]
that's just a warning from matplotlib you can ignore it
