### ISSUE TITLE
Downloading of available satellite images

### ISSUE THREAD

**Issue by arheem** [kvos/CoastSat#168]
Vos, Coastsat only gives me 2 images from L5 only but I require more images for the analysis. Even the two images cannot be downloaded. Help needed ASAP!!
![screenshot-localhost-8888-notebooks-OneDrive-Desktop-Anaconda-CoastSat-master-Abuesi-ipynb-1609769121495](https://user-images.githubusercontent.com/69360729/103543646-cb6e5a80-4e96-11eb-88ae-3e54b418bcd5.png)
![screenshot-localhost-8888-notebooks-OneDrive-Desktop-Anaconda-CoastSat-master-Abuesi-ipynb-1609769049374](https://user-images.githubusercontent.com/69360729/103543650-cc9f8780-4e96-11eb-80ec-2e2b545ab565.png)

**Comment by kvos** [comment]
unfortunately this means that there are no Landsat images for that region of interest. Landsat coverage is not homogeneous around the globe. However, I'm surprised that there are no images at all. can you send your polygon as text instead of screenshot , I will test it
