### ISSUE TITLE
configure problem

### ISSUE THREAD

**Issue by eaven123** [kvos/CoastSat#169]
Does the configuration not support Windows system?I have the following configuration error under Windows：ModuleNotFoundError: No module named 'termios'，Could you tell me the solution of solve the bug? thank you!

![image](https://user-images.githubusercontent.com/58174523/103723615-6e48e500-500d-11eb-8a8e-eb1fbfd06d5d.png)

**Comment by kvos** [comment]
not sure what module termios or blessings are. maybe try to delete and reinstall your environment (also run conda clean --all)
