### ISSUE TITLE
On which side is the water and land?

### ISSUE THREAD

**Issue by Bene2907** [kvos/CoastSat#170]
Hey there,
I got the CoastSat module working and its really great. I just have the problem of never knowing on which side of the points/lines the land is and on which one water/sea is after I saved it as a Geojson file. I would like to find out in which direction the coastline is pointing (East, South...). To do that I obviously have to know on which side the water is. Is there any way to automate that?
Is there anyone who could help me with that? I really appreciate it.

Thanks in advance!

**Comment by kvos** [comment]
you could use the classifier to see where land and water pixels are, although you could have some water bodies behind the shore as well. would be a cool feature to implement
