### ISSUE TITLE
Warning while downloading images

### ISSUE THREAD

**Issue by rdgomt** [kvos/CoastSat#171]
Hi!

I'm facing this warning for every image:

**`Warning 1: Unable to export GeoTIFF file with different datatypes per different bands. All bands should have the same types in TIFF.`**

**Comment by kvos** [comment]
thanks for reporting this, I've also seen this before, I don't know what is causing it but will investigate. It doesn't seem to affect the downloads at all, so feel free to keep working with those downloaded images. cheers, kilian
