### ISSUE TITLE
no shoreline mapped

### ISSUE THREAD

**Issue by bruna-ambrosio** [kvos/CoastSat#173]
Hi Kilian @kvos ,

how are you? Sorry for taking your time again, but I am having some problems using the new version of CoastSat.

In my study area only Landsat Tier 2 images are available. The CoastSat is able to download and preprocess these images, however during the shoreline detection, the pixels are classified correctly but no coastline is drawn (in any of the images). 

![no_shoreline](https://user-images.githubusercontent.com/60444738/104868354-e1156280-5921-11eb-8664-af226a640708.png)

Then in the step of saving the mapped shorelines as a geojson layer I have this error:

![geojson_error](https://user-images.githubusercontent.com/60444738/104868213-82e87f80-5921-11eb-9136-99affd204eb2.png)

I think this is because no shoreline has actually been mapped, despite the pixel classification. Do you know what may be happening? I was able to extract shorelines for this area using the first version of CoastSat, when I tested it before the GEE update.

I've had some problems before, but I don't know if they can be the cause:
1. when I import the libraries, this warning / error occurs:
![import_error](https://user-images.githubusercontent.com/60444738/104868774-225a4200-5923-11eb-9fca-8c3d1050171e.png)
2. I am not allowed to digitise a reference coastline because there are no cloud free images (despite having images with few clouds - <20%)
![refshoreline_error](https://user-images.githubusercontent.com/60444738/104868849-4158d400-5923-11eb-9ecc-6e323928187a.png)

Could you help me please? Thanks again!

Bruna

**Comment by kvos** [comment]
- you can increase the cloud cover threshold to get images for digitising the reference shoreline
- don't worry about the matplotlib warning
- I need to see your settings to understand why it's not mapping the shoreline, it could be an issue with the coordinate system (has to be projected coordinates, eastings/northings). It could also be that the min_shoreline_length is too large. Feel free to post your settings here

**Comment by bruna-ambrosio** [comment]
Hi Kilian @kvos,

You are absolutely correct. I just changed the epsg to a projected coordinate system and it worked... the shorelines have being mapped normally. I will increase the cloud cover (and the period of image collection) to try to be able to digitise some reference shoreline. 

Thank you so much for all the tips and help.

**Comment by bruna-ambrosio** [comment]
Hi Kilian @kvos ,

Just one more question...is it possible to insert a previously digitised reference shoreline instead of digitising it during CoastSat run?

Thanks.

**Comment by kvos** [comment]
yes you can, it saves your reference shoreline in a .geojson file called SITENAME_reference_shoreline.geojson. It will always look if a file like this exists before asking you to digitise a shoreline.

**Comment by bruna-ambrosio** [comment]
Excellent, @kvos . This is very efficient.

Thank you so much for all your help.
