### ISSUE TITLE
404 return from example

### ISSUE THREAD

**Issue by stz1945** [kvos/CoastSat#174]
Hello! Having problem with running example code.

`~/opt/anaconda3/envs/coastsat/lib/python3.7/site-packages/ee/data.py in send_(path, params, opt_method, opt_raw)
   1195     raise ee_exception.EEException(
-> 1196         'Server returned HTTP code: %d' % response.status)
   1197 
EEException: Server returned HTTP code: 404
During handling of the above exception, another exception occurred:
EEException                               Traceback (most recent call last)`

`~/opt/anaconda3/envs/coastsat/lib/python3.7/site-packages/ee/data.py in send_(path, params, opt_method, opt_raw)
   1194     # error above rather than this generic one.
   1195     raise ee_exception.EEException(
-> 1196         'Server returned HTTP code: %d' % response.status)
   1197 
   1198   # Now known not to be an error response...

EEException: Server returned HTTP code: 404`

**Comment by kvos** [comment]
could be an internet connection issue, 404 means it cannot find that page
