### ISSUE TITLE
Transect issue

### ISSUE THREAD

**Issue by Feed99** [kvos/CoastSat#175]
Hello, 

I am an undergrad working from Oregon and attempting to use coastsat for a stretch of beach here. I use the epsg code 2291 to allow me to use lat and long coordinates for my 29 transects. This appears to work until I go to get an image of the transects plotted. This shows me one dot with the title of one of the transects and that is it. Do you have any idea as to what this issue is stemming from or how I can fix this? Moving around on the plot and messing with the scaling has not provided any further insight. 
Thank you! I think coastsat is very cool and I would love to get a transect time series.

**Comment by kvos** [comment]
hey @Feed99 , you need to use projected coordinates as the spatial library used in coastsat (shapely) does not work with spherical coordinates (lat/lon). If you don't know what is the best projection for your area you may want to use the default 3857 which is Google Maps basically

**Comment by Feed99** [comment]
Gotcha, thanks @kvos  !
