### ISSUE TITLE
Cross-shore change calculations

### ISSUE THREAD

**Issue by jezzajay** [kvos/CoastSat#179]
Hi Kilian

Firstly, thank you so much for this amazing software! It is so great to see new developments in the field of shoreline change analysis and has really helped advance my masters project, also it’s gotten me inspired to learn way more about GEE.

My question is related to the previous one about transect analysis. I wish to create cross-shore change graphs like step 2.3 and the CoastSat website where there are positive and negative distances from a baseline point.
![transects](https://user-images.githubusercontent.com/69304603/107487241-a607f700-6b8e-11eb-8017-decf84ee91ec.png)

From the excel spreadsheet that is downloaded after completing step 2.3, there are only positive distances, which I assume are the distances from the landward end of the transect to the point of interaction with the shoreline?
I have different shoreline datasets already downloaded from CoastSat and then merged and processed in QGIS so I’m not sure if I can re-upload them to perform step 2.3. So I drew my own transects in QGIS and used the intersection tool, created ‘hub’ points at the end of each transect and used the ‘hub distance’ tool. 

How is the cross-shoreline base distance ‘zero’ created? Is it the average or median distance or the final shoreline’s distance? 

Many thanks, 
Jezzajay

**Comment by kvos** [comment]
hi @jezzajay , the cross-shore distance plotted there is demeaned. please check out #178 as @wvreys was asking the same thing regarding putting the shorelines back into the workflow after editing with gis.

**Comment by jezzajay** [comment]
Thank you very much @kvos . I think I shall stick to creating my own cross-shore graphs with other plotting software, but thanks for showing how to enter it back into the workflow. 
All the best with CoastSat and future research :)
