### ISSUE TITLE
Error while setting up in windows system

### ISSUE THREAD

**Issue by hamidj2019** [kvos/CoastSat#18]
Hi everybody, 

I am using a windows system, I spent a couple of hours to set up the system on the computer but in the step 1.1 I come across some Error Messages. I installed Anaconda on my PC. Then I created a new environment named coastsat with all the required packages:
conda env create -f environment.yml -n coastsat
Then I wanted to activate the new environment as below according to the website

conda activate coastsat
At this stage the following message has appeared. 

Invoke-Expression : Cannot bind argument to parameter 'Command' because it is an empty string.

At C:\Users\TANIN\Anaconda3\shell\condabin\Conda.psm1:70 char:36

+         Invoke-Expression -Command $activateCommand;

+                                    ~~~~~~~~~~~~~~~~

    + CategoryInfo      : InvalidData: (:) [Invoke-Expression], ParameterBindingValidationException

    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Microsoft.PowerShell.Commands.Invo

   keExpressionCommand

---------------------------------------------------------------------------------------------------------------
I would highly appreciate if you can kindly advise how I can fix this issue.

**Comment by kvos** [comment]
ok @hamidj2019 , I don't know what invoke-expression means and why is it raising an error when you call conda activate which is a very basic conda command. Let's try to debug it from the start:

1. Are you opening the Anaconda Prompt as shown in the screenshot below (not the Anaconda PowerShell Prompt) ? 
![Capture](https://user-images.githubusercontent.com/7217258/59542615-2dc8d880-8f4a-11e9-83af-fc8d4737448a.JPG)

2. Can you type on the Anaconda Prompt:
`conda list conda$` 
and provide us with a screenshot of what is printed in the console (it should be something like below).
![Capture](https://user-images.githubusercontent.com/7217258/59542855-61f0c900-8f4b-11e9-87b7-ff4377f3d654.JPG)

3. Can you try to create a dummy environment and activate it?
Type on the Anaconda Prompt:
`conda create --name dummy`
Then:
`conda activate dummy`
If it doesn't work, run the Anaconda Prompt as Administrator and try again.

Let me know how it goes.

**Comment by kvos** [comment]
ok now that you are able to create an Anaconda environment, you have to create the coastsat environment which contains the required packages to install the toolbox.

1. Open Anaconda Prompt and use the `cd` command to go to the folder where you downloaded the toolbox
2. Run `conda env create -f environment.yml -n coastsat`
3. `conda activate coastsat`
Then follow the instructions in the README section 1.2.

**Comment by hamidj2019** [comment]
Hi,
Thanks for your input. 
When I use "cd" in "Anaconda Prompt" I get the following message
"The system cannot find the path specified."
Shouldn't I use Anaconda Powershel prompt?

**Comment by kvos** [comment]
nono don't use the Powershell prompt, just normal Anaconda prompt. 
You can find on this [link](https://stackoverflow.com/questions/48304305/anaconda-python-change-anaconda-prompt-user-path) how to use the `cd` command. you can use `dir` to print the current directory and see where you are when navigating.

**Comment by hamidj2019** [comment]
Thanks. Using the dir command I can see that it shows "Anaconda" as one of the outputs in the list. So it exists there. Still when I use CD (Change Directory) and name of "Anaconda" after that, then the same message appears. Any input?

**Comment by hamidj2019** [comment]
I have just now continued a bit more trying to type the following 
conda env create -f environment.yml -n coastsat
As a result the following message pops up:

(base) C:\Users\TANIN\Anaconda3>conda env create -f environment.yml -n coastsat
SpecNotFound: Invalid name, try the format: user/package
Should I use a special Syntax here?

**Comment by hamidj2019** [comment]
Hi again,

I have just now continued a bit more trying to type the following
conda env create -f environment.yml -n coastsat
As a result the following message pops up:

(base) C:\Users\TANIN\Anaconda3>conda env create -f environment.yml -n
coastsat
SpecNotFound: Invalid name, try the format: user/package
Should I use a special Syntax here?


*I also included this message in the portal.*

**Comment by hamidj2019** [comment]
By the way, don't you think it is better if i follow one the other possibility as advised by you in one of the discussions before as follows:
---------------------------------------------------------------------------------------------
If the environment.yml file does not work for you, another option is to install the individual packages separately:

conda create --name coastsat
conda activate coastsat
conda install <name_of_the_package>
You will need to install the following packages to run coastsat:

earthengine-api, gdal, geopandas, pytz, scikit-image, scikit-learn, shapely
as well as these basic python packages numpy, scipy, spyder, notebook.

**Comment by kvos** [comment]
you are not in the correct folder...you have to navigate to the folder where you have downloaded the toolbox and where **environment.yml** is located

**Comment by hamidj2019** [comment]
Hi, Isnot it true that the folder name should be "Anaconda3"?

**Comment by kvos** [comment]
have you downloaded the CoastSat toolbox from Github?

**Comment by hamidj2019** [comment]
I just started following the instructions in the README.md file.
Is there anything that needed to be done before that like Installing CoastSAT toolbox? I think that has not been indicated in the README.md file. Could you please send the link of the CoastSAT toolbox?

**Comment by kvos** [comment]
the CoastSat-master contains the toolbox. You should navigate the anaconda prompt to the location where you have downloaded CoastSat-master (it doesn't matter where it is).

**Comment by hamidj2019** [comment]
Yes, I did downlaod the "CoastSat-master" folder which contains environment.yml
Then I can use CD to go into folder of "coastsat". It shows the following:
CoastSat-master\coastsat>
I can then "Run" conda env create -f environment.yml -n coastsat
Are we on the right track here?

**Comment by hamidj2019** [comment]
After typing `conda env create -f environment.yml -n coastsat` in the folder same as CoastSat-master
I posted another issue in another category called "Issue 4".

**Comment by hamidj2019** [comment]
Hi Kilian

Any comment on the following issue:
CondaValueError: prefix already exists: C:\Users........\Anaconda3\envs\coastsat

**Comment by kvos** [comment]
you have to be in the folder that contains environment.yml (CoastSat-master) in order to run `conda env create -f environment.yml -n coastsat`.

the error above means that you already have an environment called coastsat, you should remove that one and before running the command.

The Python and Anaconda workflow used in CoastSat seems to be relatively new to you so I strongly recommend that you seek some help from someone in the computer science department of your university before proceeding and posting more issues. Without a basic understanding of Python you will NOT be able to run the toolbox and map shorelines on the satellite images.

**Comment by hamidj2019** [comment]
Hi again,

I can confirm you that I "WAS" and "HAVE BEEN" in the folder that contains environment.yml (CoastSat-master) in order to run conda env create -f environment.yml -n coastsat.
BUT the ERROR message still appear. That is why I had to write to you again. This error has anything to do with with knowledge of Python at this stage. 

Again after typing "conda env create -f environment.yml -n coastsat" in the folder same as CoastSat-master the following ERROR appears:
CondaValueError: prefix already exists: C:\Users........\Anaconda3\envs\coastsat

Is not this related to the debugging procedure that you advised before? or something else?

**Comment by kvos** [comment]
no this error is popping up because you are trying to create an environment called coastsat while you already have an environment with the same name.

1. Run `conda env remove --name coastsat`
2. Run `conda env create -f environment.yml -n coastsat`

Make sure you are in the correct directory otherwise it will not find environment.yml. When you type `dir` environment.yml should appear in the list of elements that are in the current directory.

**Comment by kvos** [comment]
I’m closing this issue because it has been inactive for more than a month

**Comment by kiwi0fruit** [comment]
It's still not fixed?  The bug is still there:

```
(base) C:\Users\User>conda remove -n test --all

(base) C:\Users\User>conda env remove -n test

(base) C:\Users\User>conda create -n test "python=3.7"
WARNING: A directory already exists at the target location 'D:\Programs\Python\M
iniconda3__\envs\test'
but it is not a conda environment.
Continue creating environment (y/[n])? y

CondaValueError: prefix already exists: D:\Programs\Python\Miniconda3__\envs\tes
t

(base) C:\Users\User>
```

**Comment by kiwi0fruit** [comment]
It's still not fixed?  The bug is still there:

```
(base) C:\Users\User>conda remove -n test --all

(base) C:\Users\User>conda env remove -n test

(base) C:\Users\User>conda create -n test "python=3.7"
WARNING: A directory already exists at the target location 'C:\Python\Miniconda3\envs\test'
but it is not a conda environment.
Continue creating environment (y/[n])? y

CondaValueError: prefix already exists: C:\Python\Miniconda3\envs\test

(base) C:\Users\User>
```
