### ISSUE TITLE
Using irregular tide series

### ISSUE THREAD

**Issue by pgurruchaga** [kvos/CoastSat#180]
Hi Kilian,
I've been working with an in situ measured sea level series, and it has al lot of missing data. Like 20 days without information for example. 
The thing is, the **_get.closest.datapoint_** tool searches for the min tide date of the ones following the image date. In my case this is a problem because it can associate an imagen with a tide data that took place 20 days later.
In order to solve it, I would like to put some restriction such as "if you cant't find tide data on the same day discard the image" but I really don't know how to do it. Even if I managed to apply a restriction in the tool definition I wouldn't know how to delete de data of that image from the transect series.

Can you think of any idea that would help me?
Thanks a lot

**Comment by kvos** [comment]
My suggestion would be to gap-fill your in-situ water levels with modelled tides (from FES2014 or by running Xtide or similar on your time-series). Another option could be to find the gaps in your tide time-series and then remove the associated images from the shoreline data. You can google 'how to drop data from a list in python'.

**Comment by pgurruchaga** [comment]
I managed to remove those images, thank you!!!
