### ISSUE TITLE
tide files csv format

### ISSUE THREAD

**Issue by tomatehui** [kvos/CoastSat#181]
Hello again Kilian,

I am trying to obtain a tide correction using a CSV file with a local model. However, I get this error  : str' object has no attribute 'to_pydatetime' this message

I have changed the seconds and milliseconds format and tried  to use the same format as your example from Narrabeen but I haven't been able to make it work (see image below)

Does it need a specific format ?

Best regards

Tona

![Captura de pantalla (40)](https://user-images.githubusercontent.com/76249625/107944921-26fc2f80-6f8f-11eb-8233-33191e3f64c5.png)

########### Attribute error#####

AttributeError                            Traceback (most recent call last)
<ipython-input-47-c44766f43754> in <module>
      2 filepath = os.path.join(os.getcwd(),'examples','ETRETAT_TIDES_PRUEBA3.csv')
      3 tide_data = pd.read_csv(filepath, parse_dates=['dates'])
----> 4 dates_ts = [_.to_pydatetime() for _ in tide_data['dates']]
      5 tides_ts = np.array(tide_data['tide'])
      6 

<ipython-input-47-c44766f43754> in <listcomp>(.0)
      2 filepath = os.path.join(os.getcwd(),'examples','ETRETAT_TIDES_PRUEBA3.csv')
      3 tide_data = pd.read_csv(filepath, parse_dates=['dates'])
----> 4 dates_ts = [_.to_pydatetime() for _ in tide_data['dates']]
      5 tides_ts = np.array(tide_data['tide'])
      6 

AttributeError: 'str' object has no attribute 'to_pydatetime'

**Comment by kvos** [comment]
basically you want to convert `tide_data['dates']` into a datetime object. When adding the parse_dates argument to read_csv it should automatically read the dates as pd.TimeStamp which then are converted to datetime with ._to_pydatetime(). In your case is not reading the dates correctly (I don't know why cause the format looks good), so `tide_data['dates']` contains strings. You can google 'how to convert string to datetime python' and you should find a quick solution. Also make sure to add a timezone with `pytz.utc.localize(datetime)` to your datetimes.

**Comment by tomatehui** [comment]
Thanks Kilian, I really appreciate you taking the time to answer everyone. 
 I did convert to daytime python and will add the time zone. I still can't figure out why pydatetime won't accept the CSV format, enough spending time with that.
