### ISSUE TITLE
Import coastsat error

### ISSUE THREAD

**Issue by CurmudgeonPhD** [kvos/CoastSat#185]
The import lines through datetime are running fine when put into a separate cell. When I'm executing the line "from coastsat import SDS_download..." I received the following error.  
![conda_issue](https://user-images.githubusercontent.com/37665052/108286652-7beaa200-7157-11eb-855d-33cc2425032a.JPG)

TypeError: an integer is required (got type bytes)

**Comment by kvos** [comment]
I think this issue is related to #188 , could you try that solution as well

**Comment by CurmudgeonPhD** [comment]
Thank you!  The suggestion worked. For anyone else finding this issue. I ran the following through conda and it worked fine

pip install scikit_learn==0.22.2

**Comment by kvos** [comment]
thanks @CurmudgeonPhD ! I will check that everything works ok with that version and may update the version number directly into the environment.yml file
