### ISSUE TITLE
No module named 'sklearn.neural_network.multilayer_perceptron'

### ISSUE THREAD

**Issue by KDUPrasadh** [kvos/CoastSat#187]
I got the error, what can I do for that?

**Comment by KDUPrasadh** [comment]
M
apping shorelines:
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-14-78c4e5dc2bfe> in <module>
      1 get_ipython().run_line_magic('matplotlib', 'qt')
----> 2 output = SDS_shoreline.extract_shorelines(metadata, settings)

~\anaconda3\envs\Coastsat\CoastSat-master\coastsat\SDS_shoreline.py in extract_shorelines(metadata, settings)
    123         elif satname == 'S2':
    124             pixel_size = 10
--> 125             clf = joblib.load(os.path.join(filepath_models, 'NN_4classes_S2.pkl'))
    126 
    127         # convert settings['min_beach_area'] and settings['buffer_size'] from metres to pixels

~\anaconda3\envs\Coastsat\lib\site-packages\joblib\numpy_pickle.py in load(filename, mmap_mode)
    583                     return load_compatibility(fobj)
    584 
--> 585                 obj = _unpickle(fobj, filename, mmap_mode)
    586     return obj

~\anaconda3\envs\Coastsat\lib\site-packages\joblib\numpy_pickle.py in _unpickle(fobj, filename, mmap_mode)
    502     obj = None
    503     try:
--> 504         obj = unpickler.load()
    505         if unpickler.compat_mode:
    506             warnings.warn("The file '%s' has been generated with a "

~\anaconda3\envs\Coastsat\lib\pickle.py in load(self)
   1208                     raise EOFError
   1209                 assert isinstance(key, bytes_types)
-> 1210                 dispatch[key[0]](self)
   1211         except _Stop as stopinst:
   1212             return stopinst.value

~\anaconda3\envs\Coastsat\lib\pickle.py in load_global(self)
   1524         module = self.readline()[:-1].decode("utf-8")
   1525         name = self.readline()[:-1].decode("utf-8")
-> 1526         klass = self.find_class(module, name)
   1527         self.append(klass)
   1528     dispatch[GLOBAL[0]] = load_global

~\anaconda3\envs\Coastsat\lib\pickle.py in find_class(self, module, name)
   1575             elif module in _compat_pickle.IMPORT_MAPPING:
   1576                 module = _compat_pickle.IMPORT_MAPPING[module]
-> 1577         __import__(module, level=0)
   1578         if self.proto >= 4:
   1579             return _getattribute(sys.modules[module], name)[0]

ModuleNotFoundError: No module named 'sklearn.neural_network.multilayer_perceptron'

**Comment by KDUPrasadh** [comment]
apping shorelines:
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-14-78c4e5dc2bfe> in <module>
      1 get_ipython().run_line_magic('matplotlib', 'qt')
----> 2 output = SDS_shoreline.extract_shorelines(metadata, settings)

~\anaconda3\envs\Coastsat\CoastSat-master\coastsat\SDS_shoreline.py in extract_shorelines(metadata, settings)
    123         elif satname == 'S2':
    124             pixel_size = 10
--> 125             clf = joblib.load(os.path.join(filepath_models, 'NN_4classes_S2.pkl'))
    126 
    127         # convert settings['min_beach_area'] and settings['buffer_size'] from metres to pixels

~\anaconda3\envs\Coastsat\lib\site-packages\joblib\numpy_pickle.py in load(filename, mmap_mode)
    583                     return load_compatibility(fobj)
    584 
--> 585                 obj = _unpickle(fobj, filename, mmap_mode)
    586     return obj

~\anaconda3\envs\Coastsat\lib\site-packages\joblib\numpy_pickle.py in _unpickle(fobj, filename, mmap_mode)
    502     obj = None
    503     try:
--> 504         obj = unpickler.load()
    505         if unpickler.compat_mode:
    506             warnings.warn("The file '%s' has been generated with a "

~\anaconda3\envs\Coastsat\lib\pickle.py in load(self)
   1208                     raise EOFError
   1209                 assert isinstance(key, bytes_types)
-> 1210                 dispatch[key[0]](self)
   1211         except _Stop as stopinst:
   1212             return stopinst.value

~\anaconda3\envs\Coastsat\lib\pickle.py in load_global(self)
   1524         module = self.readline()[:-1].decode("utf-8")
   1525         name = self.readline()[:-1].decode("utf-8")
-> 1526         klass = self.find_class(module, name)
   1527         self.append(klass)
   1528     dispatch[GLOBAL[0]] = load_global

~\anaconda3\envs\Coastsat\lib\pickle.py in find_class(self, module, name)
   1575             elif module in _compat_pickle.IMPORT_MAPPING:
   1576                 module = _compat_pickle.IMPORT_MAPPING[module]
-> 1577         __import__(module, level=0)
   1578         if self.proto >= 4:
   1579             return _getattribute(sys.modules[module], name)[0]

ModuleNotFoundError: No module named 'sklearn.neural_network.multilayer_perceptron'

**Comment by kvos** [comment]
if you could please try the latest development branch, this issue should be fixed on that version, let me know how it goes, thanks
