### ISSUE TITLE
EPSG  GDAL_DATA environment variable

### ISSUE THREAD

**Issue by tomatehui** [kvos/CoastSat#189]
Hello again Kilian,

I have tried to run coastsat on spyder. Everything works fine until  I get to : # extract shorelines from all images (also saves output.pkl and shorelines.kml).

I get this errors:
ERROR 4: Unable to open EPSG support file gcs.csv.  Try setting the GDAL_DATA environment variable to point to the directory containing EPSG csv files.
ERROR 4: Unable to open EPSG support file gcs.csv.  Try setting the GDAL_DATA environment variable to point to the directory containing EPSG csv files.
ERROR 6: No translation for an empty SRS to PROJ.4 format is known.

I have seen previous issues and tried updating GDAL  and followed the update, clean etc.

I have tried the environment preferences in spyder  and is set to C:\Users\Tona\anaconda3\envs\coastsat\python.exe

 somehow still isn't working. 

Thanks in advance for all the help.

**Comment by kvos** [comment]
gdal always caused some weird issues, try to google that error to see what's wrong. Maybe the epsg code that you chose is not supported, try with 3857 to see if the error persists...

**Comment by tomatehui** [comment]
tried changing 3857 and the error persists, This is going to be a tricky one, will continue trying to find out what it is.

Thanks for the help.
