### ISSUE TITLE
No module named 'gdal'

### ISSUE THREAD

**Issue by 21overdose** [kvos/CoastSat#191]
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-99dd06762137> in <module>
      9 import pandas as pd
     10 from datetime import datetime
---> 11 from coastsat import SDS_download, SDS_preprocess, SDS_shoreline, SDS_tools, SDS_transects

~\CoastSat-master\coastsat\SDS_download.py in <module>
     20 import copy
     21 import shutil
---> 22 import gdal
     23 
     24 # additional modules

ModuleNotFoundError: No module named 'gdal'

and ı have no module named 'coastsat'  what should I do ?

**Comment by kvos** [comment]
make sure that you have gdal installed, you need gdal 2.3.3, you can check which packages you have installed with conda list

**Comment by 21overdose** [comment]
I loaded all the necessary modules ı have gdal 2.3.3 but I could not start it.I tried to install a gee environment and run the code, but I got an error like this

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-9fd48f2b36d8> in <module>
     18 import pandas as pd
     19 from datetime import datetime
---> 20 from coastsat import SDS_download, SDS_preprocess, SDS_shoreline, SDS_tools, SDS_transects

ModuleNotFoundError: No module named 'coastsat'

**Comment by kvos** [comment]
are you in the right working directory?
