### ISSUE TITLE
[Help needed] Update neural network models

### ISSUE THREAD

**Issue by kvos** [kvos/CoastSat#193]
Several issues have been raised with the scikit-learn package (see issues #187 #188) and the current problem is that CoastSat is using the old version of scikit-learn (0.20.3) where joblib can be loaded through sklearn and used to save/load the neural network models used to classify the images (from sklearn.externals import joblib). Now, this is deprecated and sklearn does not include joblib any more in externals but the joblib package itselft is required.

The 4 models (.pkl files) located in /classification/models were created with the old version of joblib and currently cannot be loaded with the new version. Can someone help to convert those 4 files so that they can be loaded by joblib? I have made the necessary changes to the environment file and imports in the `development branch`, the only step remaining is to be able to load the neural networks. I have tried to load the models with the old joblib and save them with the new joblib but it did not work.

@simmonsja do you have any experience with this? I guess the neural network itself is just a numpy array with weights and biases so it should not be too hard...

@cosstas @chrisleaman @SBFRF  @Noza1212 @KatKonst

**Comment by chrisleaman** [comment]
@kvos - I tried the approach [here](https://stackoverflow.com/a/61895560) to generate the new model files. You can download the new files [here](https://www.dropbox.com/sh/dgq6bkfbxsc22ua/AACBXwKERDBilQN9S3V9JqFYa?dl=0).

Code used to generate the new model files:

``` python
from sklearn.externals import joblib as extjoblib
import joblib
from pathlib import Path

def main():

    # Iterate through all pickle files in directory
    for pkl in Path.cwd().glob('*.pkl'):

        # Load file in sklearn with old joblib
        clf = extjoblib.load(pkl)

        # Dump using joblib
        new_filename = str(pkl).replace('.pkl','_new.pkl')
        joblib.dump(clf, new_filename)

if __name__ == '__main__':
    main()
```

I then tried importing the new pickle files using the latest version sklearn (0.24.1), but got the following warnings:

<details>
<summary>Details</summary>

```
C:\Users\Chris\Anaconda3\envs\coastsattemplatest\lib\site-packages\sklearn\base.py:315: UserWarning: Trying to unpickle estimator LabelBinarizer from version 0.22.2.post1 when using version 0.24.1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
C:\Users\Chris\Anaconda3\envs\coastsattemplatest\lib\site-packages\sklearn\base.py:315: UserWarning: Trying to unpickle estimator MLPClassifier from version 0.22.2.post1 when using version 0.24.1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
Traceback (most recent call last):
  File "C:\Program Files (x86)\JetBrains\PyCharm 2020.1.4\plugins\python\helpers\pydev\_pydevd_bundle\pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<input>", line 1, in <module>
  File "C:\Users\Chris\Anaconda3\envs\coastsattemplatest\lib\site-packages\sklearn\base.py", line 260, in __repr__
    repr_ = pp.pformat(self)
  File "C:\Users\Chris\Anaconda3\envs\coastsattemplatest\lib\pprint.py", line 144, in pformat
    self._format(object, sio, 0, 0, {}, 0)
  File "C:\Users\Chris\Anaconda3\envs\coastsattemplatest\lib\pprint.py", line 161, in _format
    rep = self._repr(object, context, level)
  File "C:\Users\Chris\Anaconda3\envs\coastsattemplatest\lib\pprint.py", line 393, in _repr
    self._depth, level)
  File "C:\Users\Chris\Anaconda3\envs\coastsattemplatest\lib\site-packages\sklearn\utils\_pprint.py", line 181, in format
    changed_only=self._changed_only)
  File "C:\Users\Chris\Anaconda3\envs\coastsattemplatest\lib\site-packages\sklearn\utils\_pprint.py", line 425, in _safe_repr
    params = _changed_params(object)
  File "C:\Users\Chris\Anaconda3\envs\coastsattemplatest\lib\site-packages\sklearn\utils\_pprint.py", line 91, in _changed_params
    params = estimator.get_params(deep=False)
  File "C:\Users\Chris\Anaconda3\envs\coastsattemplatest\lib\site-packages\sklearn\base.py", line 195, in get_params
    value = getattr(self, key)
AttributeError: 'MLPClassifier' object has no attribute 'max_fun'
```

</details>

It looks like the version used to create the classifiers (0.22.2.post1) isn't combatible with the latest version (0.24.1). I think there are therefore two options to address this:

1. Retrain and recreate the pickle files with the latest version of scikit-learn.
2. Tell people not to upgrade their version of scikit-learn. For example, I suspect [this issue](https://github.com/kvos/CoastSat/issues/188#issuecomment-796716771) is due to the user using a later version of scikit-learn.

**Comment by kvos** [comment]
great thanks @chrisleaman for converting the files! I tested them and it ran smoothly! I had `scikit-learn 0.24.1` installed (no warning for me). 
I'm keen to push the new pickle files to the repository, but another issue is that if they replace the old ones, users that already have Coastsat running may have to update scikit-learn and this may create all sort of additional problems. So for the moment, better to keep the old files as well and load the old or new version of the models based on which version of scikit-learn the users have installed. It seems like we are close to a solution here, thanks again Chris!

**Comment by KatKonst** [comment]
Also see the last comment [here ](https://github.com/cisco/mindmeld/pull/157). Basically the same conclusion...
