### ISSUE TITLE
NARRA example runs well on macOS Mojave (10.14), but fails on macOS Big Sur (11.1)

### ISSUE THREAD

**Issue by geopete1** [kvos/CoastSat#197]
Hello - Your repository is outstanding.  Thank you for creating a very valuable tool.

I am able to run the Narrabeen beach example_jupyter.ipynb without issue on my old desktop running macOS Mojave (10.14).  However, when I attempt the exact same procedure on my newer MacbookPro, running macOS BigSur (11.1), I get an error on line 13 of the 'Initial Settings' cell:  

from coastsat import SDS_download, SDS_preprocess, SDS_shoreline, SDS_tools, SDS_transects

The error is shown in the attached series of 3 overlapping screengrabs.  It appears to have trouble finding lib c?

Any help you can offer would be most appreciated.

Thank you,
Pete Adams

<img width="1119" alt="Screen Shot 2021-03-17 at 11 23 28 AM" src="https://user-images.githubusercontent.com/15240902/111492973-89be2380-8713-11eb-9135-6af7e6595cf9.png">
<img width="1128" alt="Screen Shot 2021-03-17 at 11 23 44 AM" src="https://user-images.githubusercontent.com/15240902/111492976-8aef5080-8713-11eb-8b4f-f3c45f565be7.png">
<img width="1122" alt="Screen Shot 2021-03-17 at 11 23 59 AM" src="https://user-images.githubusercontent.com/15240902/111492977-8aef5080-8713-11eb-954c-43bed3f115ee.png">

**Comment by kvos** [comment]
hi pete, it's an OSError triggered when loading the geopandas library, I would not know how to fix it, have you tried to type the error on google and add geopandas? there must be a solution somewhere on stackoverflow

**Comment by geopete1** [comment]
Thank you Kilian.  I hunted around a little bit and found this solution that worked for me:
[https://stackoverflow.com/questions/64821850/error-when-importing-geopandas-oserror-could-not-find-lib-c-or-load-any-of-its]()

Reinstalling shapely did the trick:

pip install --upgrade --force-reinstall shapely

I think you can close this issue.

Thanks!
