### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by hamidj2019** [kvos/CoastSat#20]
The following is the error message:
---------------------------------------------------------------------------------------
(base) PS C:\Users\TANIN\Anaconda3> conda activate coastsat

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\Users\TANIN\Anaconda3\lib\site-packages\conda\cli\main.py", line 138, in main
        return activator_main()
      File "C:\Users\TANIN\Anaconda3\lib\site-packages\conda\activate.py", line 940, in main
        print(activator.execute(), end='')
      File "C:\Users\TANIN\Anaconda3\lib\site-packages\conda\activate.py", line 173, in execute
        return getattr(self, self.command)()
      File "C:\Users\TANIN\Anaconda3\lib\site-packages\conda\activate.py", line 150, in activate
        builder_result = self.build_activate(self.env_name_or_prefix)
      File "C:\Users\TANIN\Anaconda3\lib\site-packages\conda\activate.py", line 275, in build_activate
        return self._build_activate_stack(env_name_or_prefix, False)
      File "C:\Users\TANIN\Anaconda3\lib\site-packages\conda\activate.py", line 332, in _build_activate_stack
        self._replace_prefix_in_path(old_conda_prefix, prefix))
      File "C:\Users\TANIN\Anaconda3\lib\site-packages\conda\activate.py", line 550, in _replace_prefix_in_path
        assert last_idx is not None
    AssertionError

`$ C:\Users\TANIN\Anaconda3\Scripts\conda-script.py shell.powershell activate coastsat`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=C:\Users\TANIN\Anaconda3\Scripts\conda.exe
             CONDA_PREFIX=C:\Users\TANIN\Anaconda3
    CONDA_PROMPT_MODIFIER=(base)
               CONDA_ROOT=C:\Users\TANIN\Anaconda3
              CONDA_SHLVL=1
                 HOMEPATH=\Users\TANIN
                     PATH=C:\Users\TANIN\Anaconda3;C:\Users\TANIN\Anaconda3\Library\mingw-w64\bi
                          n;C:\Users\TANIN\Anaconda3\Library\usr\bin;C:\Users\TANIN\Anaconda3\Li
                          brary\bin;C:\Users\TANIN\Anaconda3\Scripts;C:\Users\TANIN\Anaconda3\bi
                          n;C:\Users\TANIN\Anaconda3\condabin;C:\Program
                          Files\firemodels\SMV6;C:\Program Files\firemodels\FDS6\bin;C:\Program
                          Files (x86)\Common Files\Oracle\Java\javapath;C:\ProgramData\Oracle\Ja
                          va\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:
                          \WINDOWS\System32\WindowsPowerShell\v1.0\;D:\Bremen Turbulence
                          course\bin;D:\MATLAB\bin;D:\matlab
                          software\bin;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\MiKTeX 2.9\
                          miktex\bin\x64\;C:\Users\TANIN\AppData\Local\Microsoft\WindowsApps;
             PSMODULEPATH=C:\Users\TANIN\Documents\WindowsPowerShell\Modules;C:\Program Files\Wi
                          ndowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Mod
                          ules
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
    VBOX_MSI_INSTALL_PATH=C:\Program Files\Oracle\VirtualBox\

     active environment : base
    active env location : C:\Users\TANIN\Anaconda3
            shell level : 1
       user config file : C:\Users\TANIN\.condarc
 populated config files :
          conda version : 4.6.11
    conda-build version : 3.17.8
         python version : 3.7.3.final.0
       base environment : C:\Users\TANIN\Anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\TANIN\Anaconda3\pkgs
                          C:\Users\TANIN\.conda\pkgs
                          C:\Users\TANIN\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\TANIN\Anaconda3\envs
                          C:\Users\TANIN\.conda\envs
                          C:\Users\TANIN\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.6.11 requests/2.21.0 CPython/3.7.3 Windows/10 Windows/10.0.17134
          administrator : False
             netrc file : None
           offline mode : False

An unexpected error has occurred. Conda has prepared the above report.

**Comment by hamidj2019** [comment]
Hello 

This is the screen shot that you have requested after typing "conda list conda$"
--------------------------------------------------------------------------
(base) C:\Users\TANIN>conda list conda$
WARNING: The conda.compat module is deprecated and will be removed in a future release.
# packages in environment at C:\Users\TANIN\Anaconda3:
#
# Name                    Version                   Build  Channel
anaconda                  2019.03                  py37_0
conda                        4.6.11                   py37_0
--------------------------------------------------------------------------------------
Would you please advise?
Best regards

**Comment by kvos** [comment]
duplicate of #18
