### ISSUE TITLE
tidally-corrected time-series

### ISSUE THREAD

**Issue by Julai091** [kvos/CoastSat#200]
Hi Kilian,

Thank you for time spending helping us. 

I have a doubt.

When we create tidally-corrected time-series csv file it doesnt come with negative values.

   | dates | Transect 1 | Transect 2 | Transect 3 | Transect 4
0 | 1988-06-29 12:47:34+00:00 | 352.486983 | 370.857317 | 271.040091 | 199.373359
1 | 1988-07-31 12:47:39+00:00 | 155.980076 | 366.227281 | 262.840154 | 161.977865
2 | 1988-09-01 12:47:42+00:00 | 328.481433 | 355.258715 | 248.393709 | 152.521950
3 | 1989-09-20 12:42:40+00:00 | 329.396153 | 343.981941 | 292.927561 | 204.439903
4 | 1990-08-06 12:36:54+00:00 | 308.199592 | 309.307864 | 237.792690 | 172.260938
5 | 1999-10-02 12:53:28+00:00 | 240.703842 | 250.910203 | 231.487397 | 209.363475
6 | 2000-07-16 12:53:56+00:00 | 240.318651 | 213.285518 | 199.309439 | 211.673018
7 | 2001-09-21 12:56:58+00:00 | 222.977876 | 243.285579 | 205.612525 | 210.929082
8 | 2001-10-07 12:56:48+00:00 | 237.524070 | 255.716465 | 214.675019 | 227.250010
9 | 2005-06-28 13:04:31+00:00 | 182.846506 | 204.893389 | 168.171397 | 208.269792
10 | 2005-07-30 13:04:50+00:00 | 181.842533 | 202.881744 | 176.807860 | 229.294521
11 | 2006-07-17 13:09:58+00:00 | 171.825828 | 178.448054 | 157.549078 | 200.918402
12 | 2008-06-20 13:04:26+00:00 | 167.106893 | 183.648889 | 149.966464 | 203.787304
13 | 2008-08-07 13:03:04+00:00 | 159.759287 | 178.302877 | 146.623738 | 204.177286
14 | 2008-11-11 13:00:05+00:00 | 131.326868 | 156.226854 | 131.196440 | 190.948098
15 | 2009-08-10 13:06:09+00:00 | 146.246388 | 168.134678 | 149.626923 | 206.004191
16 | 2009-11-30 13:07:23+00:00 | 114.910009 | 134.877538 | 114.294862 | 181.811788
17 | 2010-06-26 13:07:29+00:00 | 126.021998 | 157.656062 | 127.016906 | 193.233710
18 | 2010-08-13 13:07:14+00:00 | 131.408178 | 166.679367 | 151.470450 | 203.240855
19 | 2013-06-18 13:18:51+00:00 | 111.414721 | 160.322273 | 128.617863 | 192.973989
20 | 2013-08-05 13:18:55+00:00 | 125.710321 | 141.046363 | 111.969555 | 175.265260
21 | 2013-09-22 13:18:49+00:00 | 125.193424 | 159.579957 | 131.309075 | 192.136576
22 | 2013-10-24 13:18:41+00:00 | 123.023145 | 148.571105 | 121.790722 | 182.149945
23 | 2015-04-21 13:16:16+00:00 | 77.374984 | 119.664292 | 116.633977 | 176.809333
24 | 2015-06-08 13:16:08+00:00 | 78.011808 | 114.818207 | 112.094633 | 157.556099
25 | 2015-10-30 13:17:01+00:00 | 72.846095 | 109.263518 | 116.363929 | 174.866303
26 | 2015-12-17 13:17:03+00:00 | 92.468811 | 117.306335 | 120.539003 | 182.234830
27 | 2016-01-02 13:17:00+00:00 | 115.410111 | 133.348253 | 114.584976 | 175.818781
28 | 2016-01-18 13:17:00+00:00 | 106.933038 | 116.788433 | 116.628667 | 172.414436
29 | 2017-02-05 13:16:55+00:00 | 93.735465 | 99.757966 | 92.223235 | 150.845663
30 | 2017-07-15 13:16:44+00:00 | 111.848394 | 136.332472 | 124.902941 | 175.055936
31 | 2017-07-31 13:16:52+00:00 | 119.459962 | 139.344955 | 121.015066 | 168.832252
32 | 2017-12-22 13:17:06+00:00 | 77.840498 | 104.451490 | 95.860960 | 153.456430
33 | 2018-05-31 13:15:42+00:00 | 61.652440 | 88.921007 | 85.768418 | 168.627892
34 | 2018-07-18 13:16:06+00:00 | 65.134861 | 100.765651 | 89.211916 | 154.126570
35 | 2018-09-20 13:16:33+00:00 | 89.139166 | 114.464597 | 91.656069 | 162.976616

But when we plot time-series of shoreline change it comes.

![time-series of shoreline change](https://user-images.githubusercontent.com/49702201/112145424-160b9300-8bb9-11eb-8366-399aabc711a8.png)

:(

What i am doing wrong?

# load the measured tide data
filepath = os.path.join(os.getcwd(),'examples','ajututeua.csv')
tide_data = pd.read_csv(filepath, parse_dates=['dates'])
dates_ts = [_.to_pydatetime() for _ in tide_data['dates']]
tides_ts = np.array(tide_data['tide'])

# get tide levels corresponding to the time of image acquisition
dates_sat = output['dates']
tides_sat = tides_ts

# plot the subsampled tide data
fig, ax = plt.subplots(1,1,figsize=(15,4), tight_layout=True)
ax.grid(which='major', linestyle=':', color='0.5')
ax.plot(tide_data['dates'], tide_data['tide'], '-o', color='b', label='all time-series')
ax.plot(dates_sat, tides_sat, '-o', color='r', ms=6, mfc='w',lw=1, label='image acquisition')
ax.set(ylabel='tide level [m]',xlim=[dates_sat[0],dates_sat[-1]], title='Water levels at the time of image acquisition');
ax.legend();

# tidal correction along each transect
reference_elevation = 0 # elevation at which you would like the shoreline time-series to be
beach_slope = 0.2
cross_distance_tidally_corrected = {}
for key in cross_distance.keys():
    correction = (tides_sat-reference_elevation)/beach_slope
    cross_distance_tidally_corrected[key] = cross_distance[key] + correction
    
# store the tidally-corrected time-series in a .csv file
out_dict = dict([])
out_dict['dates'] = dates_sat
for key in cross_distance_tidally_corrected.keys():
    out_dict['Transect '+ key] = cross_distance_tidally_corrected[key]
df = pd.DataFrame(out_dict)
fn = os.path.join(settings['inputs']['filepath'],settings['inputs']['sitename'],
                  'transect_time_series_tidally_corrected.csv')
df.to_csv(fn, sep=',')
print('Tidally-corrected time-series of the shoreline change along the transects saved as:\n%s'%fn)

**Comment by kvos** [comment]
when plotting the time-series it's subtracting the mean, you can modify the plot to make it as you like

**Comment by Julai091** [comment]
That's what I thought. :)

Thank you. 

So it is the distance from the baseline [0] in meters?!

If we correlate it to other physical parameters,  it doent matter if it has negative or positive values (erosion/accretion)? 

Or do you think that i should subtract the mean for the correlation?

Thank you much Kilian!!

**Comment by kvos** [comment]
it does not matter if you subtract the mean or not when calculating correlations. Subtracting the mean is more for visual interpretation, to see when the beach was more eroded / accreted that its long-term average

**Comment by Julai091** [comment]
Thank you so much Kilian!! 

I am really thankful for the work you've done!!!

Julia
