### ISSUE TITLE
'quality_check' error in SDS_download

### ISSUE THREAD

**Issue by NO645** [kvos/CoastSat#204]
I started getting an error at the data download step which I have not seen before. The following inputs variable and line are below:
```
inputs
{'polygon': [[[-117.29306249596688, 33.011034574794074],
   [-117.26564237984745, 33.01144794337879],
   [-117.26550459031921, 32.98085866810988],
   [-117.29241947816843, 32.980583089053404],
   [-117.29306249596688, 33.011034574794074]]],
 'dates': ['2010-01-01', '2021-01-01'],
 'sat_list': ['L5', 'L8', 'S2'],
 'sitename': 'DRYADcardiff',
 'filepath': 'C:\\Users\\RDCHLNRO\\Desktop\\waves2021\\data'}


metadata = SDS_download.retrieve_images(inputs)
```
The resulting error, part way through the download was:

```
  File "C:\Users\RDCHLNRO\AppData\Local\Continuum\anaconda3\envs\coastsat3152021\lib\site-packages\coastsat\SDS_download.py", line 136, in retrieve_images
    if im_meta['properties'][key] == 'PASSED': acc_georef = 1

KeyError: 'quality_check'
```

Thank you for any suggestions you might have.

**Comment by kvos** [comment]
hi @NO645 , that's an issue with S2 images, it's happening at lines 133-137 in SDS_download.py
![image](https://user-images.githubusercontent.com/7217258/113793843-94a52a80-978c-11eb-853f-21e5a440f740.png)
it must be that in your case the flag name is none of the three listed there in the flag_names variable, can you have a look to see which flagname that image has? they often change it without too much notice in S2.

**Comment by NO645** [comment]
Below are the keys, perhaps it's GENERAL_QUALITY_FLAG?

`
dict_keys(['DATATAKE_IDENTIFIER', 'SPACECRAFT_NAME', 'FORMAT_CORRECTNESS_FLAG', 'MEAN_INCIDENCE_AZIMUTH_ANGLE_B8A', 'MEAN_SOLAR_AZIMUTH_ANGLE', 'system:footprint', 'SOLAR_IRRADIANCE_B12', 'SOLAR_IRRADIANCE_B10', 'SOLAR_IRRADIANCE_B11', 'GENERATION_TIME', 'SOLAR_IRRADIANCE_B8A', 'SENSOR_QUALITY_FLAG', 'CLOUD_COVERAGE_ASSESSMENT', 'system:time_end', 'system:time_start', 'DATASTRIP_ID', 'PROCESSING_BASELINE', 'SENSING_ORBIT_NUMBER', 'SENSING_ORBIT_DIRECTION', 'GRANULE_ID', 'REFLECTANCE_CONVERSION_CORRECTION', 'MEAN_INCIDENCE_AZIMUTH_ANGLE_B8', 'DATATAKE_TYPE', 'MEAN_INCIDENCE_AZIMUTH_ANGLE_B9', 'MEAN_INCIDENCE_AZIMUTH_ANGLE_B6', 'MEAN_INCIDENCE_AZIMUTH_ANGLE_B7', 'RADIOMETRIC_QUALITY_FLAG', 'MEAN_INCIDENCE_AZIMUTH_ANGLE_B4', 'MEAN_INCIDENCE_ZENITH_ANGLE_B1', 'MEAN_INCIDENCE_AZIMUTH_ANGLE_B5', 'RADIOMETRIC_QUALITY', 'MEAN_INCIDENCE_AZIMUTH_ANGLE_B2', 'MEAN_INCIDENCE_AZIMUTH_ANGLE_B3', 'MEAN_INCIDENCE_ZENITH_ANGLE_B5', 'MEAN_INCIDENCE_AZIMUTH_ANGLE_B1', 'MEAN_INCIDENCE_ZENITH_ANGLE_B4', 'MEAN_INCIDENCE_ZENITH_ANGLE_B3', 'MEAN_INCIDENCE_ZENITH_ANGLE_B2', 'MEAN_INCIDENCE_ZENITH_ANGLE_B9', 'MEAN_INCIDENCE_ZENITH_ANGLE_B8', 'MEAN_INCIDENCE_ZENITH_ANGLE_B7', 'MEAN_INCIDENCE_ZENITH_ANGLE_B6', 'MEAN_SOLAR_ZENITH_ANGLE', 'MEAN_INCIDENCE_ZENITH_ANGLE_B8A', 'MGRS_TILE', 'CLOUDY_PIXEL_PERCENTAGE', 'GENERAL_QUALITY_FLAG', 'PRODUCT_ID', 'MEAN_INCIDENCE_ZENITH_ANGLE_B10', 'SOLAR_IRRADIANCE_B9', 'DEGRADED_MSI_DATA_PERCENTAGE', 'MEAN_INCIDENCE_ZENITH_ANGLE_B11', 'MEAN_INCIDENCE_ZENITH_ANGLE_B12', 'SOLAR_IRRADIANCE_B6', 'MEAN_INCIDENCE_AZIMUTH_ANGLE_B10', 'SOLAR_IRRADIANCE_B5', 'MEAN_INCIDENCE_AZIMUTH_ANGLE_B11', 'SOLAR_IRRADIANCE_B8', 'MEAN_INCIDENCE_AZIMUTH_ANGLE_B12', 'SOLAR_IRRADIANCE_B7', 'SOLAR_IRRADIANCE_B2', 'SOLAR_IRRADIANCE_B1', 'SOLAR_IRRADIANCE_B4', 'SOLAR_IRRADIANCE_B3', 'system:asset_size', 'system:index'])`

**Comment by kvos** [comment]
yes you can add 'GENERAL_QUALITY_FLAG' in that variable flag_names at the end and it should do. 
If you can make that small change and make a pull request to the development branch that would be great! thanks

**Comment by kvos** [comment]
issue solved
