### ISSUE TITLE
credential error -403 in connecting to GEE in juputer notebook

### ISSUE THREAD

**Issue by Ghadiri1979** [kvos/CoastSat#206]
I used to write code in the google earth engine with javascript. With that account, I have installed an env in Jupyter to access gee, It was successful and it still works. I decided to install that environment on the pc, everything is going well (install anaconda, packages, and gee authentication and getting key and then successful), But when executing the attached image code, it gives 403, and credential error. I will be grateful if you help to solve this problem. Thank you.
Best regards: Ali
[Untitled7 (2).pdf](https://github.com/kvos/CoastSat/files/6330627/Untitled7.2.pdf)
[example_jupyter.pdf](https://github.com/kvos/CoastSat/files/6330628/example_jupyter.pdf)

**Comment by kvos** [comment]
hi @Ghadiri1979 , sorry but I don't know how to solve this issue with error 403. No one has ever reported it before. Maybe check on the google earth engine issues

**Comment by Ghadiri1979** [comment]
Hi,  Dear  Kilian,
*I hope you are doing well. I just wanted to say thanks for writing
coastsat toolkit. *
* Thanks again for your help.  **The problem has been solved.  but  there
is some question about setting in coassat:*

*1-  Is it possible to call region polygon by  kml format instead of
coordinate value entering?*
*2- * *Is it possible to  Set  List  dates  ( for example   from
(1987-01-01,  2000-01-01 ) and (  2010-01_01, 2021-01-01)   insteas of
setting (1987-01-01, ,2010 -01-01)*
*3- is the alternative way for calling base shoreline instead of digitizing*
*? *
* BEST  regards,*
*Ali *

**Comment by kvos** [comment]
hi @Ghadiri1979 , there are alternatives for all these 3 questions. You can see that there is also a function to load the polygon from a kml (you can create the kml with google mymaps). To set this list you will have to create a loop around the download call. You can load your digitised shoreline as well but it will require some python coding too as you need to convert into a numpy array

**Comment by Ghadiri1979** [comment]
Thanks, I'll check it out.
