### ISSUE TITLE
merging issue in Sentinel MSI data

### ISSUE THREAD

**Issue by VINCENTAFERRER** [kvos/CoastSat#207]
Dear Vos
     AS suggested earlier, I had downloaded the CoastSat v1.1.1 and on execution, I get the error message as shown in screenshot.
![image](https://user-images.githubusercontent.com/76463942/114869878-23f9b000-9e15-11eb-9475-6bb37bd6ecd5.png)
Yet when I recheck the images, there seem to be no issues as that arised earlier (still dont know why this message pops out).
But there is a new issue as shown down while generating the jpeg images as reading the metadata:
![image](https://user-images.githubusercontent.com/76463942/114870113-6c18d280-9e15-11eb-80b7-af06f7cadf29.png)
Though I couldnt exactly troubleshoot what would be the error, I just went through the command prompt window which suggested that one image corresponding to date (02-03-2017) was missing.
      Please provide suggestions on why the data didnt download though the metadata is populated with the details and if the error shown here is due to the same or something else....

I feel I confuse a little, but i hope you could understand the issue...

the details of the AOI are attached herewith...

Thanks in advance...
[error_15-04-2021.txt](https://github.com/kvos/CoastSat/files/6317949/error_15-04-2021.txt)

_Originally posted by @VINCENTAFERRER in https://github.com/kvos/CoastSat/issues/165#issuecomment-820391857_

**Comment by kvos** [comment]
bummer, I thought we had fixed that one!
So if it prints that WARNING, you can't go ahead as the code will probably break.
I will have a look when I have time, but for the moment what you can do it deactivate the merging of S2 images, go into the coastsat folder, open SDS_download.py and comment lines 284-290. Then delete the folder with the downloaded images and restart the download from scratch.

**Comment by VINCENTAFERRER** [comment]
OK....I will try it out and await to get the issue sorted out...

Thanks ...

**Comment by kvos** [comment]
hi vincent, I tried your code and it worked on my end, it didn't throw any warning/error. 
![image](https://user-images.githubusercontent.com/7217258/116366222-68d80a80-a849-11eb-9f90-4ff9a886544c.png)
![image](https://user-images.githubusercontent.com/7217258/116366277-78575380-a849-11eb-965e-b63488c78acb.png)

**Comment by VINCENTAFERRER** [comment]
Hi Vos
    Thanks for your update. Its good the code is alright.
Actually I had used the code from the Coastsat v1.1.1 package under the release section than the general one in the front page.
I hope the package under the release section is the most recent one. If so I will check it once again and try to see if I get any such error...

regards
Vincent

**Comment by kvos** [comment]
they should be almost the same, best to always get the latest one as I don't make new releases for every update, only major ones.
Yeah it worked on my end so should work on yours too, make sure you clean up all pre-existing downloaded images and make a new download so that it's not trying to merge images downloaded previously with new ones etc...

**Comment by VINCENTAFERRER** [comment]
thanks for the suggestions....
On a update, I had used the the coastsat master package after removing all background files and finally managed to download the data. thank you once again for the support. 
I would close this issue with the following request.

It would be great if we could have an option to convert a geojson file to .pkl as well.

**Comment by VINCENTAFERRER** [comment]
Coastsat seem to give nightmares to me. When it felt contented that the error of merging S2 images are overcome in the existing ROI, now the issue reemerged for a new ROI. 
though i managed to proceed upto creating jpeg images, I feel one image is not properly merged (image attached herewith) whereas all others seem to be properly generated.
The ROI details are also provided herewith as well.
![2018-10-21-05-26-14_S2](https://user-images.githubusercontent.com/76463942/116978328-331ba180-ace1-11eb-9625-3e6170086346.jpg)

Please have a look into it.
[AOI.txt](https://github.com/kvos/CoastSat/files/6419848/AOI.txt)

**Comment by kvos** [comment]
hey vincent, welcome to the world of satellite remote sensing! there will always be images with weird artefacts and radiometry issues, cropping problems, cloud mask issues etc... there's nothing we can do about it when processing large numbers of images. I don't think that's an issue with the merging code.

**Comment by VINCENTAFERRER** [comment]
Ha.... Ha.... though well known about the issues of satellite remote sensing, expectations doesnt limit to boundaries...
Yet, i have proceeded with the shoreline extraction and didnt face any major issue... Thanks for consistently being online providing suggestions.
Regards
Vincent

**Comment by kvos** [comment]
no worries, I'll close the issue for the time being, you can reopen it if related to the merging or open a new one
