### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by arheem** [kvos/CoastSat#208]
I have used coastsat this past few months with no problems till I tried to use it today. How can I resolve this?
![Picture1](https://user-images.githubusercontent.com/69360729/115613231-ad105b80-a2db-11eb-803b-16dc8f811b42.png)

**Comment by kvos** [comment]
you need to be in the right working directory, where the coastsat folder is

**Comment by arheem** [comment]
yes. I initiated the process from the coastsat file location but to no avail.

**Comment by kvos** [comment]
that's strange, it should load those modules from the coastsat folder, can you check that you have a script named SDS_download.py in that folder?

**Comment by arheem** [comment]
resolved. cheers!

**Comment by kvos** [comment]
cool, will close the issue for the moment
