### ISSUE TITLE
PackagesNotFoundError:

### ISSUE THREAD

**Issue by hamidj2019** [kvos/CoastSat#21]
After that I tried to follow the following 3 steps:

conda create --name coastsat
conda activate coastsat
conda install <name_of_the_package>

BUT in step 3 while dealing with """earthengine-api""", I get an ERROR message. 
please see below:

(coastsat) C:\Users\TANIN>conda install earthengine-api
Collecting package metadata: done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

earthengine-api
Current channels:

https://repo.anaconda.com/pkgs/main/win-64
https://repo.anaconda.com/pkgs/main/noarch
https://repo.anaconda.com/pkgs/free/win-64
https://repo.anaconda.com/pkgs/free/noarch
https://repo.anaconda.com/pkgs/r/win-64
https://repo.anaconda.com/pkgs/r/noarch
https://repo.anaconda.com/pkgs/msys2/win-64
https://repo.anaconda.com/pkgs/msys2/noarch
To search for alternate channels that may provide the conda package you're
looking for, navigate to

https://anaconda.org
and use the search bar at the top of the page.
----------------------------------------------------------
Any ideas? inputs?

**Comment by kvos** [comment]
duplicate of #18
