### ISSUE TITLE
discreate line

### ISSUE THREAD

**Issue by Ghadiri1979** [kvos/CoastSat#211]
Dear Vos 
  I have a discrete line in output shorelines. also  In some images, despite clearness, the line is not drawn. or improperly drawn

thanks in advance.

![1990-04-24-06-40-18_L5_detection ](https://user-images.githubusercontent.com/32133661/117112803-dbdc0680-ad9e-11eb-81e3-cf8a5e49092f.jpg)
![1990-04-24-06-40-18_L5_preprocessed](https://user-images.githubusercontent.com/32133661/117112813-de3e6080-ad9e-11eb-8090-13b059fed7dd.jpg)
![image](https://user-images.githubusercontent.com/32133661/117115236-172c0480-ada2-11eb-9e87-477899816ceb.png)

**Comment by kvos** [comment]
try to increase the distance to your reference shoreline settings['max_dist_ref'] as this is what is causing those gaps.
