### ISSUE TITLE
Change output 

### ISSUE THREAD

**Issue by dak9910** [kvos/CoastSat#212]
Hi, 
I was wondering if you have any tips or ideas on how to change the output to be on a coordinate system. Doing this would allow me to compare to in situ data. Thanks for your help, 

Dakota Fee.

**Comment by kvos** [comment]
yes you can change output_epsg in the settings dictionary, just make sure it's a projected coordinate system or it won't work, it's explained in the readme somewhere. best, kilian

**Comment by dak9910** [comment]
Thanks for responding Kilian. I tried one from the suggested site and got an error and when using the default 3857, it ends up projecting the transects around a 0 Easting. Thanks again.

**Comment by kvos** [comment]
can you document the error a bit more pls?

**Comment by dak9910** [comment]
![CoastSatError](https://user-images.githubusercontent.com/65695511/118908865-023d8e00-b8d7-11eb-983a-0b758d8b6992.JPG)

**Comment by dak9910** [comment]
This is when the error pops up that wouldn't if I were to use the epsg from your example.

**Comment by kvos** [comment]
hi @dak9910 , that issue is because your output variable does not contain any shorelines I think. Can you check that?
