### ISSUE TITLE
Shoreline extraction

### ISSUE THREAD

**Issue by risanixm** [kvos/CoastSat#216]
Hi Kilian! I'm still learning about machine learning and still confused about the concept of the method you use for shoreline extraction. The method used there are two methods (classification using neural networks and segmentation using MNDWI. If you don't mind, can you explain a little about the concepts and steps to combine the two methods? And why did you choose to combine the two methods? Thanks!

**Comment by kvos** [comment]
hi, I think the best way to learn about the algorithm would be to read the papers on CoastSat https://www.sciencedirect.com/science/article/pii/S0378383918305313?via%3Dihub
https://www.sciencedirect.com/science/article/pii/S1364815219300490?via%3Dihub#ec-research-data
 let me know if you don't have access to the Coastal Eng one and I can send you a pdf version (it's also on scihub)

**Comment by risanixm** [comment]
alright, I've read both papers and now I understand, but I'm so sorry I got the paper from sci-hub because I don't have access to the Coastal Eng. Thanks @kvos !!

**Comment by kvos** [comment]
yes scihub is the best!
