### ISSUE TITLE
OSError   

### ISSUE THREAD

**Issue by clturner** [kvos/CoastSat#217]
Hello Kilian

I am having an error with Coastsat that i need some assistance with:

~/opt/anaconda3/envs/coastsat/lib/python3.7/site-packages/shapely/geos.py in load_dll(libname, fallbacks, mode)
     54         raise OSError(
     55             "Could not find lib {0} or load any of its variants {1}.".format(
-> 56                 libname, fallbacks or []))
     57 
     58 _lgeos = None

OSError: Could not find lib c or load any of its variants [].

It seems like it cant find an underlying C library? Anything you can do to help I would greatly appreciate it.

Thank you!
Chris

**Comment by kvos** [comment]
hi chris, I don't know much about OSErrors, just googled it and it seems to be a recurrent issue, try one of the solutions in the forums like https://stackoverflow.com/questions/39991765/shapely-oserror-could-not-find-lib-c-or-load-any-of-its-variants

**Comment by clturner** [comment]
Hi Kilian

This link seemed to work. Changing the one line in .../shapely/geos.py 

https://github.com/Toblerity/Shapely/commit/a34ec59a7dc9089a71968c6871e29addd872ea3b

Thank you for your help! :)

**Comment by kvos** [comment]
sounds good, will close the issue then.
