### ISSUE TITLE
CondaValueError: prefix already exists:

### ISSUE THREAD

**Issue by hamidj2019** [kvos/CoastSat#22]
Hi,
When trying to type the following "conda env create -f environment.yml -n coastsat" in the same folder as "environment.yml" exists which is in **master folder** 
.........CoastSat-master>conda env create -f environment.yml -n coastsat
a message appears as 
CondaValueError: prefix already exists: C:\Users\........\Anaconda3\envs\coastsat

Any idea why this happens?

**Comment by kvos** [comment]
duplicate of #18
