### ISSUE TITLE
Local variable "gdf_all" referenced before assignment

### ISSUE THREAD

**Issue by fed1942** [kvos/CoastSat#221]
When i run my own script "prueba.py", i get the next message error:

![Sin título](https://user-images.githubusercontent.com/78570105/122080222-7daa3680-cdd4-11eb-9f53-80e10b893254.png)

The error does not appear when i run the script example.py.

I hope you can help me. Thank you in advance.

**Comment by kvos** [comment]
yes this error means that you haven't mapped any shoreline, so the output variable is empty and when it tries to write it into a geojson it returns that error

**Comment by fed1942** [comment]
I understand. Can you think of a solution? The only changes i made to prueba.py in relation to example.py were: region of interest, date range, sitename and ouput_epsg. I ran the script with Anaconda Powershell Prompt on a 32-bit Windows PC.

**Comment by kvos** [comment]
are you using projected coordinates for output_epsg (i.e. not spherical)? 
maybe it's better if you run the script in a more interactive environment so you can debug it and look at which step is causing the issue. did you check in the detection folder to see if shorelines were being mapped?

**Comment by fed1942** [comment]
For the output epsg option I was using 4326 (WGS84). Now try 32721 (WGS84 - UTM zone 21 S; projected coordinates) and the problem is solved.

Now a different error occurred . I'll see if I can figure it out on my own. But if I can't, I'll open a new issue.

Thanks for your answer.
