### ISSUE TITLE
Training classifier

### ISSUE THREAD

**Issue by fed1942** [kvos/CoastSat#222]
When i tried to train a new CoastSat Classifier i got the following error message:

![Sin título](https://user-images.githubusercontent.com/78570105/124401500-38589500-dd00-11eb-8a6a-9afa309e37ae.png)

The error appeared only when i put LASTONINAS.kml (polygon) file in the training_sites folder. But when i tried to run the classifier with an existing .kml file (BYRON or NEWCASTLE), there was no problem.

The code i used was imported from the train_new_classifier.ipynb file because I could not run the file from the Jupyter Notebook.

I think there is a problem with the .kml file that i created myself. Any suggestion?

**Comment by kvos** [comment]
there must be an issue with the .kml file that you generated. I recommend you use Google Mymaps to create it and export as kml. Otherwise what you can do is to make a copy of one of the polygons that work and edit the file by changing the coordinates to your area of interest

**Comment by fed1942** [comment]
I modified the coordinates of one of the existings .kml files and problem solved. Thank you.
