### ISSUE TITLE
a very basic question 

### ISSUE THREAD

**Issue by junchengfl** [kvos/CoastSat#224]
Hi Kilian,
   This is Jun Cheng from University of South Florida. I am still struggling on the first step extracting the shoreline... 
   When I installed the Anaconda in Windows system, I direct the folder to the place where I installed the Anaconda3. After I typed in     "conda env create -f environment.yml -n coastsat" , I always get message like "SpecNotFound: Invalid name, try the format: user/package"... Can you give me some suggestions on this please? 
Thank you !
Jun

**Comment by kvos** [comment]
you need to navigate to the folder where you downloaded coastsat with the anaconda prompt, should look something like this

![image](https://user-images.githubusercontent.com/7217258/124877569-8e824c80-e00e-11eb-9f97-30c8c8595fe2.png)

**Comment by junchengfl** [comment]
It works! Thanks very much!!
