### ISSUE TITLE
retrieve_images not working

### ISSUE THREAD

**Issue by adebowaledaniel** [kvos/CoastSat#225]
Hi
Despite the fact that I used a rectangle with an area of 100km2 as recommended, the image retrieval function takes forever to process and eventually, nothing downloaded. Any idea what's going please, or to resolve this. It's not my internet speed because I tried downloading something else, and it worked fine.

I look forward to hearing from you.
Thanks

**Comment by kvos** [comment]
hi @adebowaledaniel , was it working with a smaller polygon? tried that first... otherwise is there any error message?

**Comment by adebowaledaniel** [comment]
Thanks, it worked perfectly for another roi. I will double-check for what is wrong with the previous one.
