### ISSUE TITLE
TypeError: in method 'CoordinateTransformation_TransformPoints', argument 1 of type 'OSRCoordinateTransformationShadow *'

### ISSUE THREAD

**Issue by adebowaledaniel** [kvos/CoastSat#226]
![image](https://user-images.githubusercontent.com/20906703/124963708-70254c80-e020-11eb-818f-8915f8b96c84.png)
There seems to be a spatial reference system error, I left it to the default 3857. Any idea suggest resolving this, please?
![image](https://user-images.githubusercontent.com/20906703/124963825-8fbc7500-e020-11eb-8be7-594aba7de434.png)

**Comment by kvos** [comment]
hi @adebowaledaniel , please try to google that error, it comes up sometimes and it's related to the gdal package. They should explain on some forums how to fix it.

Also you can try to add this line at the top after `import os` (changing the path so it goes to wherever you have gdal installed):
```
os.environ['GDAL_DATA'] = r'C:\Users\z5030440\Anaconda3\envs\coastsat\Library\share\gdal'
```

**Comment by kvos** [comment]
did you try to reinstall the gdal package?
