### ISSUE TITLE
Traceback (most recent call last):

### ISSUE THREAD

**Issue by 21overdose** [kvos/CoastSat#227]
![a1](https://user-images.githubusercontent.com/80200542/125158963-053d5800-e17d-11eb-861d-a6922990a110.jpg)

I ran the program and selected the coastline and selected the pictures manually, then I got the time series, but when I activated the command on line 150 ( transects = SDS_transects.draw_transects(output, settings) ) and ran it again, I got an error like this. What should I do?

**Comment by kvos** [comment]
check your code indentation, you may have an indentation error somewhere (adding a space somewhere)
