### ISSUE TITLE
mapping "swash bar" island

### ISSUE THREAD

**Issue by junchengfl** [kvos/CoastSat#228]
Hi Kilian,
   I am trying to apply your shoreline mapping method to track the swash bar changes at entrance of tidal inlet. The swash bar can grow to a substantial size and eventually migrate to the land( interesting LOL).    It would be ideal to include the tide correction into this mapping.  I found your model seems to consider the tidal correction only for individual cross-section profiles, rather than for the entire continuous shoreline.  Am I right? (I may understand your model wrong, correct me if that is the case)  If I use your method of shoreline extraction, how should I include the tide correction for the continuous shoreline (for my case, it would be shoreline of an island), please?
Thank you!
Jun

**Comment by kvos** [comment]
hey @junchengfl, you can check this extension of the toolbox https://github.com/mcuttler/CoastSat.islands where we look at island planforms and tidally-correct the polygons directly... you always need cross-shore transects though to know in which direction to translate the shoreline when correcting for the tide

**Comment by junchengfl** [comment]
> hey @junchengfl, you can check this extension of the toolbox https://github.com/mcuttler/CoastSat.islands where we look at island planforms and tidally-correct the polygons directly... you always need cross-shore transects though to know in which direction to translate the shoreline when correcting for the tide

Thank Kilian for your answer. A quick follow up here. The toolbox of CoastSat. islands were calibrated with shallow carbonate island, I saw the paper Cuttler et al. 2020 mentioned some major changes were conducted to adapted to this environment. For my case, only simple sandy shoreline (swash bar island) need to be addressed.  So the 'CoastSat.islands' can still be directed used ?
Thank you!

**Comment by kvos** [comment]
probably not "directly" used, you may have to combine some functions from .islands with normal coastsat...but have a good at coastsat.islands first 'as it is' and see how you go, maybe it works as well for your site.
The other idea, which also requires some development, would be to map all the shorelines, then calculate the average horizontal shorelines position for that sand bar and then create cross-shore transects to that average shoreline position and do the tidal correction along those transects. Goodluck, kilian

**Comment by junchengfl** [comment]
Thank you!
Jun
________________________
Jun Cheng
University of South Florida
School of Geosciences
Coastal Research Lab
Tampa, FL 33620
Office: CHE 110
Office Phone:813.974.2759
