### ISSUE TITLE
Possible increase of the ROI

### ISSUE THREAD

**Issue by adebowaledaniel** [kvos/CoastSat#230]
Hello @kvos 
Is it possible to increase the area of ROI above 100km2? 
The study area I'm working on is quite large, and splitting into small ROIs less than 100km2 is time-consuming as you can guess.

**Comment by kvos** [comment]
you can go as large as your computer's RAM can handle but for best accuracy keep it to 30-40kmsq, especially if there are several beaches in the ROI

**Comment by adebowaledaniel** [comment]
Thank you for the prompt response @kvos 
Well, my computer can handle that; the only issue is that whenever I increase the area, the retrieve_image seems to get stuck.
