### ISSUE TITLE
TypeError: super(type, obj): obj must be an instance or subtype of type

### ISSUE THREAD

**Issue by rdgomt** [kvos/CoastSat#231]
I'm facing this error while trying to run example.py:

**TypeError: super(type, obj): obj must be an instance or subtype of type**

![Sem título](https://user-images.githubusercontent.com/23437436/126054201-d74661b4-0f09-4bc4-8830-e31d487d90a8.png)

**Comment by kvos** [comment]
that's weird I've never seen this one... looks like a google earth engine error. can you please run 'conda list' on the anaconda prompt with the coastsat environment activated so I can see which version of gee you have

**Comment by rdgomt** [comment]
I'm using earthengine-api 0.1.273, but now I've changed ROI, date interval and the algorithm executed fine, so you can close this issue with you want. Thanks!
