### ISSUE TITLE
Worldview 2 and higher resolution satellites

### ISSUE THREAD

**Issue by jbalderamos** [kvos/CoastSat#232]
Hi Kilian, has anyone tried using coastsat with worldview2 imagery?

**Comment by kvos** [comment]
@ydoherty and I wrote some code to process Maxar imagery in a similar manner to Coastsat, check out this repo https://github.com/kvos/CoastSat.Maxar/ and look at `maxar_sl_extraction.py` and `sl_functions.py`, I think those are the last scripts that Yarran wrote on this, I hope this helps, feel free to fork
