### ISSUE TITLE
Date range setting issue

### ISSUE THREAD

**Issue by l12w** [kvos/CoastSat#236]
Hi Kilian,

I have come across an issue with using this tool for long-term detection. Using the example and the README, I am able to run the code such that satellite images from are downloaded and retrieved, and are analysed using the shoreline detection system.

Instead of covering the time period I specify in the code, it the system runs a different time period, I think to match the satellites I select. 

In this case my code was as follows for the retrieval was as below, and the time series that was produced went from 1990-2011 inclusive. I wondered if you could help me with where I am going wrong with setting dates and satellite missions? Thanks!
 
# region of interest (longitude, latitude)
polygon = [[[-119.862574, 34.409218],
            [-119.862933, 34.412243],
            [-119.845151, 34.407814],
            [-119.844399, 34.404048],
            [-119.854422, 34.407962]]] 
# it's recommended to convert the polygon to the smallest rectangle (sides parallel to coordinate axes)       
polygon = SDS_tools.smallest_rectangle(polygon)
# date range
dates = ['1990-01-01', '1995-01-01']
# satellite missions
sat_list = ['L5', 'L7', 'L8']
# name of the site
sitename = 'Isla Vista Exp to 1990'
# directory where the data will be stored
filepath = os.path.join(os.getcwd(), 'data')
# put all the inputs into a dictionnary
inputs = {'polygon': polygon, 'dates': dates, 'sat_list': sat_list, 'sitename': sitename, 'filepath':filepath}

# before downloading the images, check how many images are available for your inputs
SDS_download.check_images_available(inputs);

With the outcome – 
Images available between 1990-01-01 and 1995-01-01:
- In Landsat Tier 1 & Sentinel-2 Level-1C:
  L5: 82 images
  L7: 0 images
  L8: 0 images
  Total: 82 images
- In Landsat Tier 2:
  L5: 4 images
  L7: 0 images
  L8: 0 images
  Total: 4 images

Then the download commands – 
metadata = SDS_download.retrieve_images(inputs)

Outcome - 
Images available between 1990-01-01 and 1995-01-01:
- In Landsat Tier 1 & Sentinel-2 Level-1C:
  L5: 82 images
  L7: 0 images
  L8: 0 images
  Total: 82 images
- In Landsat Tier 2:
  L5: 4 images
  L7: 0 images
  L8: 0 images
  Total: 4 images

Downloading images:
L5: 82 images
100%
L7: 0 images

L8: 0 images

**Comment by kvos** [comment]
hi @l12w , the code only downloads the images for the dates specified, maybe there were some other files already downloaded in that folder so it's analysing them all.

**Comment by l12w** [comment]
Hiya,

Thankyou - that was the problem and I no longer have issues with date setting.
