### ISSUE TITLE
Issue with the Geojson format of outputs

### ISSUE THREAD

**Issue by l12w** [kvos/CoastSat#238]
Hi Kilian,

I am having issues as I want to export the mapped shorelines, in a format ArcMap will read, and currently the geojson format is not being read by the ArcMap conversion tool. Are there any other file types I could save the mapped shorelines as? Thanks!

**Comment by kvos** [comment]
I think you can convert a geosjon to a shapefile easily, just google geojson to shapefile. 
The other option is to go into the code where it's saving the geojson and save it as shapefile instead, see example below
![image](https://user-images.githubusercontent.com/7217258/134450296-e5a8c930-d8ae-498c-9242-0ccba6127f03.png)

**Comment by l12w** [comment]
Hiya,

Thankyou conversion tools are working. I also had anther query - what software do you use to create the geojson transect input files as I am using arcgis, and the output geojson gives me a KeyError 'name' when input into the insert transect code? If you had any tips on this I'd be very grateful to hear too.

Thanks again!

**Comment by kvos** [comment]
keyerror 'name' means that your geojson does not have an attribute called 'name'. The geojson file should look like this:
```
{
"type": "FeatureCollection",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:EPSG::28356" } },
"features": [
{ "type": "Feature", "properties": { "name": "Transect NA1" }, "geometry": { "type": "LineString", "coordinates": [ [ 342880, 6269180 ], [ 343144, 6269037 ] ] } },
{ "type": "Feature", "properties": { "name": "Transect NA2" }, "geometry": { "type": "LineString", "coordinates": [ [ 342733, 6268783 ], [ 343008, 6268664 ] ] } },
{ "type": "Feature", "properties": { "name": "Transect NA3" }, "geometry": { "type": "LineString", "coordinates": [ [ 342451, 6267913 ], [ 342746, 6267859 ] ] } },
{ "type": "Feature", "properties": { "name": "Transect NA4" }, "geometry": { "type": "LineString", "coordinates": [ [ 342460, 6267042 ], [ 342759, 6267075 ] ] } },
{ "type": "Feature", "properties": { "name": "Transect NA5" }, "geometry": { "type": "LineString", "coordinates": [ [ 342675, 6266241 ], [ 342936, 6266388 ] ] } }
]
}
```
I usually make them with QGIS
