### ISSUE TITLE
I need help for tidal correction 

### ISSUE THREAD

**Issue by B083255** [kvos/CoastSat#239]
Hi Vos My Name is Arnaud Kouekam from Cameroon PhD Student at University of Douala. I'm working on shoreline change of Cameroon coast from 1986 to present by using coastsat. Now I have a serious problem 🤣 concerning tidal correction l have already tried all your recommandations in github but nothing. I don't Know how to have a tidal data of my study area by using FES 2014. I'm blocked in this part (# **load the measured tide data**). Please help me.

here the coordinate of my study area
polygon = [[[9.088158938288675, 4.029667592089233],
          [9.092557761073099, 4.031358555658276],
          [9.073932501673685, 4.044436648659763],
          [9.071271750330911, 4.042274818042125],
          [9.071271750330911, 4.042274818042125]]];
thank you for your availability

**Comment by kvos** [comment]
I sent you the tides via emails as the file was too big for github. Once you have the tide timeseries (1984-2022 every 5 minutes) the coastsat code should be able to find the closest tide point to every image and apply tidal correction with a given slope.

**Comment by B083255** [comment]
Good evening I received your mail.Thank you for your reply kilian

KOUEKAM KENGAP Arnaud

Msc in Physical  Oceanography and Applications (CIPMA-UNESCO CHAIR)

University of Toulouse lll Paul Sabatier/University of Abomey Calavi

Assistant Researcher at the Ministry of Scientific Research and Innovation
(Cameroon)

tel: 00237691809557/0022962390504
