### ISSUE TITLE
Not able to install coastsat

### ISSUE THREAD

**Issue by 9521bhumika** [kvos/CoastSat#24]
when i tried to create environment, it shows the following error
SpecNotFound: Invalid name, try the format: user/package

**Comment by kvos** [comment]
hi @9521bhumika maybe give it a go with the Anaconda Navigator instead:
1. Open Anaconda Navigator
2. Click on Environments on the left panel
3. Click on Import and select the environment.yml file (located where you downloaded the toolbox) as specification file
