### ISSUE TITLE
time span between images

### ISSUE THREAD

**Issue by evecchi** [kvos/CoastSat#241]
Hi, I am Enrica Vecchi, PhD student at University of Bologna, in Italy. My research focuses on the analysis of obtained products on coastal areas from different kind of surveys.
I found your tool very interesting for my research!!

Anyway, I'm asking you if is it possible to set a time span for the images to be downloaded within the selected date range.
I mean, it's possible to select to download only one image each month within the selected data range?

Thank you for your availability

Enrica

**Comment by kvos** [comment]
ciao enrica, you can only select the date interval the way that is shown in the example (`dates = ['2017-12-01', '2018-01-01']`), but you don't need to download all the images in one call, so you can write a loop where you do different downloads with different date intervals (like one per month) and then all the files will be downloaded in the data folder and you can load them all by calling `metadata = SDS_download.get_metadata(inputs)`

By saying that, downloading one image each month may be risky as you may get a cloudy one and miss on a cloud free one
