### ISSUE TITLE
Hi, can u guys help me with my problem? It happens only when I use command 'L7'

### ISSUE THREAD

**Issue by alramishere** [kvos/CoastSat#243]
![Screenshot (582)](https://user-images.githubusercontent.com/66030274/137833571-b2b20e3a-e8ca-4079-ac28-5210535ac7c0.png)
![Screenshot (583)](https://user-images.githubusercontent.com/66030274/137833573-82030c2c-44f7-40c2-a113-ee3449ef9d92.png)

**Comment by kvos** [comment]
it looks like one of your images must be empty (RasterCount usually gives you the number of bands in the image). If you know when it's failing, go into your data folder and check that image file, could be corrupted or empty.
