### ISSUE TITLE
kernel died

### ISSUE THREAD

**Issue by fanqiangniubi** [kvos/CoastSat#244]
Hello, Kilian. I am a new user of GEE and jupyter notebook. This is the first time I encounter this problem. When I run the code 'SDS_preprocess.save_jpg(metadata, settings)', it told me that the kernel died. I saw a solution that it add some codes: os.environ["KMP_DUPLICATE_LIB_OK"]  =  "TRUE". However, it did not work. Someone say that may be Memory is not enough.
Thank you.
![image](https://user-images.githubusercontent.com/87556341/140418599-0f38f659-3bb2-4c79-b63d-f601a12ac2c9.png)

**Comment by hxhaoooo** [comment]
https://github.com/matplotlib/matplotlib/issues/21513

**Comment by fanqiangniubi** [comment]
Thank you, it works.
