### ISSUE TITLE
How to read the area of the "sand"?

### ISSUE THREAD

**Issue by hxhaoooo** [kvos/CoastSat#245]
I want to know the area of the "sand". Whether there has any code to achieve that?

**Comment by kvos** [comment]
you will need to write your own code to count how many sand pixels there are on each image. I think something along those lines was done by @mcuttler in the CoastSat.islands toolbox, check it out https://github.com/mcuttler/CoastSat.islands

**Comment by hxhaoooo** [comment]
Thank you, i will have a try!
