### ISSUE TITLE
Issue with Slope Estimation

### ISSUE THREAD

**Issue by seamuslo** [kvos/CoastSat#247]
Thank you again for making this great package. @kvos I hope you are enjoying your parental leave. I have a question regarding the slope estimation for when you return and are available. 

At first I was struggling with how to import the tides_sat and dates_sat data. The example uses a .pkl file, and I was unsure if there was some other part of the code that put the data into this format. Ultimately, I opted to print the tides_sat and dates_sat arrays created in the main script, save them to a CSV (attached: ) and then reimport them into the slope calculation script, as I have done here:
[tides_sat_and_dates_sat.csv](https://github.com/kvos/CoastSat/files/7584697/tides_sat_and_dates_sat.csv)
![image](https://user-images.githubusercontent.com/46720568/142942919-80334dd6-f1db-486e-8990-ba01ea58f8b1.png)

I think this worked, but correct me if something looks of here. 

Step four seems to then execute fine:
![image](https://user-images.githubusercontent.com/46720568/142943108-756fc7ff-7d5f-4abf-8fab-1e19168a2843.png)

But then I ran into issues with step 5. As I understand it, the first section of this code seeks to remove the NaNs. However, since my CSV had no Nans, I commented these lines out. However, I then get the error below:
![image](https://user-images.githubusercontent.com/46720568/142943368-be87277b-9344-4127-b51c-4b421a39ff50.png)

I googled this error, but I don't think I understand the function well enough to quite understand what the issue is here. I will keep digging, but any help you could provide would be greatly appreciated

**Comment by kvos** [comment]
hi @seamuslo , that looks good but you will need many more images to estimate the beach slope, I usually use all the Landsat imagery from 1999-2021, from my experience at least a minimum of 100 shoreline points are necessary to reconstruct the power spectrum. Anyways, the error is because `cross_distance` is a dictionary so the `composite` variable should be `cross_distance[key]`. It contains the time-series for each transect, therefore you need to loop through each transect as it's done in the example. I hope this helps, kilian

**Comment by seamuslo** [comment]
Thanks for that response @kvos . I have a follow up question. I implemented the "cross_distance[key]" change as you can see below. However, I have realized that at this point in the code, cross_distance is empty (see below):
![image](https://user-images.githubusercontent.com/46720568/144299406-e22a42f8-5c50-4489-9270-e886caeec03a.png)

To debug I printed the previous locations of cross_distance. It is populated by what seems to be the appropriate data at this point in the code:
![image](https://user-images.githubusercontent.com/46720568/144299629-8ab29157-d595-495c-b1cb-dbee082383f7.png)

However, it is empty after this portion:
![image](https://user-images.githubusercontent.com/46720568/144300286-3a58f75c-2b23-461e-8da2-ce95b85f79d9.png)

Could you explain to me conceptually the purpose of the lines after "#clip the dates between 1999 and 2020 as we need at least 2 Landsat satellites"? To your earlier comment, would this error regarding the empty cross_distance dictionary be rectified if my analysis was for a longer time period in terms of years?

**Comment by kvos** [comment]
hi seamus, the idea is to consider the period of time when at least 2 Landsat satellites are in orbit simultaneously, L5 was launched in 1984 and L7 in 1999, so from 1999 onwards they are both in orbit which makes the revisit period 8 days. I'm not sure why your cross_dist variable is empty but you should check idx_dates, see what it's in there, also check dates_sat. Maybe you can also skip that idx_dates part. But again, I don't think the algorithm can work unless there are at least around 100 datapoints,
