### ISSUE TITLE
No module named 'coastsat'

### ISSUE THREAD

**Issue by muralivyomi** [kvos/CoastSat#250]
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_7640/3769660273.py in <module>
     11 import pandas as pd
     12 from datetime import datetime
---> 13 from coastsat import SDS_download, SDS_preprocess, SDS_shoreline, SDS_tools, SDS_transects

ModuleNotFoundError: No module named 'coastsat'
Please guide me how to go further

**Comment by kvos** [comment]
you need to make sure that you are in the right working directory, where you can see the coastsat folder
