### ISSUE TITLE
muddy and turbid water conditions

### ISSUE THREAD

**Issue by risanixm** [kvos/CoastSat#253]
Hi @kvos ,

What if the beach has muddy and turbid water conditions? Will it affect the accuracy rate?

Thank You!

Risa

**Comment by kvos** [comment]
hi @risanixm , yes it will as it was designed for sandy coasts. But you can check visually what contour the toolbox is mapping and you may be able to do small adjustments for your muddy coast.

**Comment by risanixm** [comment]
I see, thank you for your answer.
thanks Kilian!
