### ISSUE TITLE
Using the Re-trained Classifier

### ISSUE THREAD

**Issue by ijcb** [kvos/CoastSat#254]
Hello everyone,

I'm a university student and I am doing a project for shoreline mapping. It seems that the default classifier is not suited for my project site so I've re-trained a new classifier using S2 images (its the satellite mission used for my project), but I don't know how to integrate it in the program. Is it through the 'sand-color' command line?

I really need your advise asap.

Thanks!

**Comment by kvos** [comment]
hi @ijcb, that's actually a good point, I think I didn't document that very well.
One way of doing it is that you replace the file under /classification/models that is called NN_4classes_S2.pkl with the new model that you trained. The it will automatically load 
The other option is that you go into the code in SDS_shoreline.py, and at lines 132 and modify that name of the model that is loaded for S2 with the one that you created.

**Comment by ijcb** [comment]
I see, thanks for the answer. I will try that and I will give you the update as soon as possible

**Comment by ijcb** [comment]
Hi, it worked for me. But I would like to know if it is possible to know the accuracy of the classified images? 

Thanks!

**Comment by kvos** [comment]
@ijcb so you can look at the accuracy metrics and the confusion matrix that are returned in the jupyter notebbok to have an idea, but given the disparity between the number of samples in each class, these metrics tend to be quite biased. The best way is to visually check that it's doing the right thing, especially mapping the sand pixels.
