### ISSUE TITLE
Conflict when installing Pyfes in coastsat env

### ISSUE THREAD

**Issue by ricsatjr** [kvos/CoastSat#259]
I noticed the environment.yml has its latest commit from 11 months ago. Are the package versions listed there still compatible with the more recent updates to coastsat? Thanks.

**Comment by kvos** [comment]
I think they are, usually people raise issues when they are not compatible anymore and then I update the .yml file
The main one that tends to loose backwards-compatibility is the earth-engine-api package

**Comment by ricsatjr** [comment]
ok. 

I was trying to install the pyfes from fbriols' channel at anaconda so I can use the coastsat.slope for tidal correction. The installation process yielded many conflicts, which based on the output, may be because of the strict channel imposed by the environment.yml file.

Here's the last part of the installation process for pyfes:

The following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.34=0
  - feature:|@/linux-64::__glibc==2.34=0
  - aiohttp -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - argon2-cffi -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - argon2-cffi-bindings -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - astropy -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - blas -> libgfortran-ng -> __glibc[version='>=2.17']
  - blosc -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - brotli -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - brotlipy -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - brunsli -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - bzip2 -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - c-ares -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - cairo -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - cffi -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - cfitsio -> libgfortran-ng -> __glibc[version='>=2.17']
  - charls -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - cryptography -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - curl -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - cytoolz -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - dbus -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - debugpy -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - expat -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - fiona -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - fontconfig -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - freetype -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - freexl -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - frozenlist -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - gdal=2.3.3 -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - geos -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - giflib -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - glib -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - google-crc32c -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - greenlet -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - grpcio -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - gst-plugins-base -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - gstreamer -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - hdf4 -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - hdf5 -> libgfortran-ng -> __glibc[version='>=2.17']
  - icu -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - imagecodecs -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - jpeg -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - json-c -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - jxrlib -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - kealib -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - kiwisolver -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - krb5 -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - lazy-object-proxy -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - lcms2 -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - lerc -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - libaec -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - libboost -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - libcrc32c -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - libcurl -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - libdap4 -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - libdeflate -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - libedit -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - libffi -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - libgcc-ng -> __glibc[version='>=2.17']
  - libgdal -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - libgfortran-ng -> __glibc[version='>=2.17']
  - libkml -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - libnetcdf -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - libpng -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - libpq -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - libprotobuf -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - libsodium -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - libspatialindex -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - libspatialite -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - libssh2 -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - libstdcxx-ng -> __glibc[version='>=2.17']
  - libtiff -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - libuuid -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - libwebp -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - libxcb -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - libxml2 -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - libzopfli -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - lz4-c -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - markupsafe -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - matplotlib -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - matplotlib-base -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - mistune -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - mkl-service -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - mkl_fft -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - mkl_random -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - multidict -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - ncurses -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - numpy -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - numpy-base -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - openjpeg -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - openssl -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - pandas=0.24.2 -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - pcre -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - pillow -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - pixman -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - poppler -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - proj4 -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - protobuf -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - psutil -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - psycopg2 -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - pyerfa -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - pyfes -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - pyproj -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - pyqt -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - pyrsistent -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - python=3.7 -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - pywavelets -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - pyyaml -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - pyzmq -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - qt -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - readline -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - regex -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - scikit-image -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - scikit-learn -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - scipy -> libgfortran-ng -> __glibc[version='>=2.17']
  - shapely -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - simplejson -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - sip -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - snappy -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - sqlalchemy -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - sqlite -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - tifffile -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - tk -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - tornado -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - typed-ast -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - ujson -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - wrapt -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - xerces-c -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - xz -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - yaml -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - yarl -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - zeromq -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - zfp -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - zlib -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - zstd -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']

Your installed version is: 2.34

Note that strict channel priority may have removed packages required for satisfiability.

**Comment by kvos** [comment]
yes, there is an issue on that in CoastSat.slopes https://github.com/kvos/CoastSat.slope/issues/15

**Comment by ricsatjr** [comment]
> yes, there is an issue on that in CoastSat.slopes [kvos/CoastSat.slope#15](https://github.com/kvos/CoastSat.slope/issues/15)

will do the separate environment solution that you proposed. thanks.

**Comment by kvos** [comment]
ok, feel free to post on that other issue if it still doesn't work with a separate env. I'm still not sure how to fix that issue as the pyfes package keeps on being updated and changing the dependencies

**Comment by kvos** [comment]
hi @ricsatjr , just found what was going on with this error. Basically, pyfes is not compatible with python 3.8, so you need python 3.7 to install pyfes and conda will not downgrade your python to a lower version. You can try to re-install coastsat on python 3.7.

**Comment by ricsatjr** [comment]
> 

Thanks @kvos ! Will try this.

**Comment by kvos** [comment]
this seems to have been resolved with more recent versions of pyfes.
