### ISSUE TITLE
Displacement between L8 and S2

### ISSUE THREAD

**Issue by raffmerlo** [kvos/CoastSat#264]
Hi Kilian,
As a result of some results, I began to observe differences between the interfaces that are remotely sensed by the Landsat 8 and Sentinel 2 missions. I looked for possible causes and found that the panchromatic band that CoastSat downloads in the region of interest is displaced with respect to the same satellite image uncropped, which can be downloaded from USGS.
Because CoastSat increases the spatial resolution of the satellite images of the Landsat 8 mission using the panchromatic band, could it be the cause that produces differences between the land-water separation of the L8 and S2 missions?
In that case, what could I modify in the script so that it doesn't improve the resolution?

I can share the .tif files for you to compare. They are from January 21, 2018, around latitude -36.307964° and longitude -56.766756°.

Thanks!

**Comment by kvos** [comment]
hi @raffmerlo , yes happy to see what is happening visually with some figures. The pansharpening is to go from 30m to 15m with the Landsat images, but it doesn't apply to all the bands, only the ones covered by the pan band.

**Comment by kvos** [comment]
the .tif files are not altered by CoastSat, they are downloaded as it is from Google Earth Engine so it must be an issue at that level. Could you quantify the offsets?

**Comment by kvos** [comment]
this should be improved with the CoastSat2.0 version
