### ISSUE TITLE
Using externally created shorelines in Shoreline analysis

### ISSUE THREAD

**Issue by GBevelio** [kvos/CoastSat#265]
Hi @kvos 
The Landsat 7 images had scanline errors so I corrected the output shorelines in GIS software. I was wondering how can I use the corrected shorelines as input within the Shoreline Analysis of CoastSat? The PKL file is accepted as an input within the tool, so is there any method to convert GEOJSON or SHP file into PKL?
I am getting the below result for my study area. I believe the irregularity is due to the scanline gaps
![Result](https://user-images.githubusercontent.com/87598327/158011798-7b501d29-c20f-4afb-a1ae-376a2a056adc.png)

Thank You

**Comment by kvos** [comment]
hi @GBevelio , did you resolve this issue? you will need to read the geojson, then format it as the .pkl `output` variable and then store it as .pkl. then you can use that file to compute the intersections with the transects

**Comment by GBevelio** [comment]
Hi @kvos. Thank you so much for your kind response. I am able to solve my issue. 
Thank You
