### ISSUE TITLE
Collection 2 and Landsat 9 support in coastsat

### ISSUE THREAD

**Issue by VINCENTAFERRER** [kvos/CoastSat#266]
Dear Kilian
     It would be great if coastsat could be enabled to download the Landsat 9 (L9) datasets  as well along with L7, L8 etc...
I would also like to update that datasets corresponding to L8 and L7 since 01 jan 2022 are also not getting listed and downloaded. The code i had used is as follows
```
# region of interest (longitude, latitude)
polygon = [[[76.508681, 9.031877],
            [76.523331, 8.977547],
            [76.536193, 8.980995],
            [76.521434, 9.035374],
            [76.508681, 9.031877]]] 
# it's recommended to convert the polygon to the smallest rectangle (sides parallel to coordinate axes)       
polygon = SDS_tools.smallest_rectangle(polygon)
# date range
dates = ['2022-01-01', '2022-03-15']
# satellite missions
sat_list = ['L7', 'L8', 'S2']
# name of the site
sitename = 'Panmana2'
# directory where the data will be stored
filepath = os.path.join(os.getcwd(), 'data')
# put all the inputs into a dictionnary
inputs = {'polygon': polygon, 'dates': dates, 'sat_list': sat_list, 'sitename': sitename, 'filepath':filepath}

# before downloading the images, check how many images are available for your inputs
SDS_download.check_images_available(inputs);
```
The results on executing the code is as follows:
![image](https://user-images.githubusercontent.com/76463942/160592807-ca9a9ee6-7a72-46cb-80f7-f6e3b11f49b6.png)

I presume the issue to be because we are selecting the tier 1 data instead of the collection 2 level 1 datasets as USGS has made recent announcements that all future datasets will be provided only as collection 2 especially after december 2021.

Please consider the above issues and an update on the code would be greatly appreciated so the the coastsat tool would find continued applications.

Thanks and regards
Vincent

**Comment by kvos** [comment]
very interesting, I had also noticed something similar, thanks for updating us on this, will change from Collection 1 to Collection 2 hoping that the formats are the same.
cheers,
Kilian

**Comment by VINCENTAFERRER** [comment]
Thanks a lot and eagerly await the release of the updated coastsat tool.
the support for the landsat 9 dataset will as well be an added advantage...

Vincent

**Comment by kvos** [comment]
it seems as simple as just changing `C01` to `C02` in the collection name. Any changes in `C02` that you are aware of in the past data? The algorithm was validated with `C01` on the last 30 years of data, but I think that validation should also stand for `C02`.

**Comment by kvos** [comment]
just saw this warning in the Google Earth Engine page:

![image](https://user-images.githubusercontent.com/7217258/161247517-231b0bbc-6945-4ed6-ba9d-0a4f55294d14.png)

I am testing using Collection 2 and so far found that there were only half the L5 images at Narrabeen. For L7 and L8 same amount of images. Will keep testing.

**Comment by kvos** [comment]
@VINCENTAFERRER
this is the comparison for the normal coastsat using Landsat Collection 1 at Narrabeen (along 5 surveyed transects):
![all_transects](https://user-images.githubusercontent.com/7217258/161453660-6f1d31f1-91f2-40ec-a6f7-4cac707cecf8.jpg)

![transect_NA1](https://user-images.githubusercontent.com/7217258/161453682-418c206e-8611-45c6-9406-fa4954c44ca0.jpg)
![transect_NA2](https://user-images.githubusercontent.com/7217258/161453687-1f30db65-1763-4440-8f33-e6f0c18fcadb.jpg)
![transect_NA2](https://user-images.githubusercontent.com/7217258/161453692-7f64a650-9155-4376-9cdd-42afe7354a14.jpg)
![transect_NA4](https://user-images.githubusercontent.com/7217258/161453695-280d2f45-6040-4c81-9310-eb3569713749.jpg)
![transect_NA5](https://user-images.githubusercontent.com/7217258/161453701-8069e44c-d562-4ee4-827d-7af91e6f306f.jpg)

I tried to replicate the same thing with Collection 2 but found the following issues:
- no Landsat 5 imagery before 1999 (Collection 1 starts in 1987 for Narrabeen)
- horizontal accuracy is not as good (see plot below). This could be for a range of reasons.
![all_transects](https://user-images.githubusercontent.com/7217258/161453813-c06d85c8-a142-44a0-b62f-acd082a1e764.jpg)

What I can do is add Collection 2 for dates after 1 Jan 2022 and keep Collection 1 for the rest.

**Comment by VINCENTAFERRER** [comment]
A very valuable and worthwhile appraisal of the two collections.
Meanwhile I would like to bring your kind attention towards the attached pdf on collection 1 vs collection 2 comparison. Going by the pdf and the observations provided herewith my thoughts goes as follows:

The collection 2 aims at harmonization of the landsat and sentinel datasets specifically in "Geometric Registration Base" which could have been one among the reasons for deviation.

Considering a wider audience, it would be great if collection 1 and collection 2 may be provided as two functions made optional so that the user can decide on the datasets to be used rather than maintaining collection1 as is and introducing collection2 for jan 2022. In addition, it would as well act as a source for accuracy assessment of the shoreline extracted elsewhere in the globe as done here for NARRA so that the scatter of the geometric error can be better quantified. 

[Landsat-C1vsC2-2021-0430-LMWS.pdf](https://github.com/kvos/CoastSat/files/8406723/Landsat-C1vsC2-2021-0430-LMWS.pdf)

I thankfully look forward to have a beta version of coastsat providing both collection1 and collection2 full access instead of collection2 for dates after jan 2022 so that I can look at how it works out for my study area.

thanks and regards

**Comment by kvos** [comment]
ok cool that should be a quick change, I will do this soon!

**Comment by kvos** [comment]
hi @VINCENTAFERRER , I think it's at the stage where you can test out if collection 2 works. 
I implemented it in the development branch, you can choose to either use collection 1 or collection 2. If collection 1 is selected, for any date after 2022, the images are taken from collection 2 automatically. Let me know how it goes. Just note that GEE are still updating their collection 2, so may be missing images.
Hopefully Landsat 9 functionality coming soon.

**Comment by VINCENTAFERRER** [comment]
Dear @kvos, I just did a very preliminary test on the number of images getting shortlisted for short term  as well as long term durations.
![image](https://user-images.githubusercontent.com/76463942/166628936-99e35557-89e1-4531-a4c8-dd8fb1f7806c.png)

![image](https://user-images.githubusercontent.com/76463942/166628974-9e26a1db-9b4c-489d-8230-d60124f6e94a.png)


The two screenshots corresponds to a short duration listing from 2019 to 2022. With all criteria set to default and interchanging C01 and C02 show a disparity in the total number of datasets listed even though the collection C01 lists datasets from 2022 as well. Especially with L7 and L8, there is some mismatch with the total images listed with respect to C01 and C02 wherein the total number of images available is 496 for C02 to that of 486 for C01.

Meanwhile, when we look at the long term duration from 1980 to 2022, the mismatch is 20 images with 967 for C01 and 987 for C02 as shown below:

![image](https://user-images.githubusercontent.com/76463942/166629453-51c96c81-cfa4-4177-81e4-07e2d3a821cf.png)

![image](https://user-images.githubusercontent.com/76463942/166629468-22fcb2ed-2b97-40b7-b61f-944102e22af8.png)

It could be seen that even though selecting C01 lists datasets from C02 as well for 2022, there still exists a disparity in the total datasets being listed when we switch between C01 and C02 which presumably points at two scenarios. 
1. C02 has more number of datasets listed than C01 irrespective of before or after 2022 because C01 also picks up data for 2022.
2. There exist some other criteria that decides on the data to be listed while selecting C01 and C02.
Hope the issue gets further complicated with inclusion of C01 & C02. 

Also when we select C01, the datasets listed upto 2021 would be from C01 and for 2022 would be of C02 thereby will it not impact the positional accuracy as we had earlier seen? It would probably mean the data listed upto 2021 should be of different positional accuracy when selecting C01 and C02.

these are some of my thoughts in this issue....

**Comment by kvos** [comment]
thanks for having a look. I think it's normal to have variable number of images from the two collections, as by reprocessing Collection 2, some images may have been moved from Tier 2 to Tier 1 (seems to be the case in your example for L7). What we need to figure out is whether the shoreline time-series derived from Collection 1 and Collection 2 align well. I would think so, but always good to double-check.
