### ISSUE TITLE
Unable import transects from QGIS geojson file

### ISSUE THREAD

**Issue by PavanSaiG** [kvos/CoastSat#267]
I am using QGIS to draw transect lines on location. I exported in format of geojson but whenever i tried to call transects_from_geojson method it is throwing error saying Multilinestring exception ...I even tried to write a code myself to convert transects from shape file but it didn't work...Please help asap
Thank you

**Comment by PavanSaiG** [comment]
Here is that method I wrote myself to get transects from shape file

def transects_from_shapefile(filename):
    """
    Reads transect coordinates from a .shp file.
    
    Arguments:
    -----------
    filename: str
        contains the path and filename of the shp file to be loaded
        
    Returns:    
    -----------
    transects: dict
        contains the X and Y coordinates of each transect
        
    """  
    
    path =  filename
    points = fiona.open(path)

    geoms = [ shape(feat["geometry"]) for feat in points ]

    transects = dict()
    i = 0
    for geom in geoms:
        a = utm.from_latlon(geoms[i].xy[0][0],geoms[i].xy[1][0])
        b = utm.from_latlon(geoms[i].xy[0][1],geoms[i].xy[1][1])
        c = [a[1],a[0]]
        d = [b[1],b[0]]
        transects[i] = np.array([c,d])
        i+=1
    print('%d transects have been loaded' % len(transects.keys()))

    return transects

**Comment by PavanSaiG** [comment]
I need transects at 100m equal distance from the start to end of location. Please let me know if there is any possibility of doing it using Coastsat

**Comment by kvos** [comment]
you can do this with GRASS GIS, there is a function called v_transects that can create 100 m spaced perpendicular transects along a linestring

**Comment by PavanSaiG** [comment]
Can we develop a function so that it can automatically create transects with 100m distance in CoastSat itself ?

**Comment by PavanSaiG** [comment]
Dear kvos, I am currently doing my project using CoastSat. I was working on this problem like for two months. I can't figure out where I was doing wrong. Everything was perfectly running till one of my PhD lead got doubt in drawing transects randomly. My thesis submission is due on May 4th. They are giving me pressure to submit asap. Please help me to get through this problem. Look into this and just give me an idea to proceed further.
Thanks in advance..

**Comment by PavanSaiG** [comment]
Above code is working for shape files!...Issue is resolved...Thank you!
