### ISSUE TITLE
Option to skip post-SLC L7 images

### ISSUE THREAD

**Issue by murrayford** [kvos/CoastSat#268]
Hey Killian, excellent work and docs here. Tiny suggestion - any thoughts on having a flag for pre-SLC error L7 imagery? For some small AOI's post SLC imagery is still useful as the beach can fit in a gap. On longer beaches they'll frequently be affected by SLC error imagery. Something like a "include SLC affected imagery?" Yes/No flag when setting sat_list?

**Comment by kvos** [comment]
hey murray, that's a good idea, will add it to the todo list of enhancements, thanks.

**Comment by kvos** [comment]
completed (only took 2 years)
