### ISSUE TITLE
How to get the output coordinates (geojson) in geographical coordinate system?

### ISSUE THREAD

**Issue by salmiah-ls** [kvos/CoastSat#269]
To map the shoreline, we have to set the output coordinates to cartesian coordinate system `(output_espg).`

Is there any way to set the output coordinates into geographical coordinate system (lon, lat)?
I need the output (geojson) to be imported to external map.

Thank you

**Comment by kvos** [comment]
hi @salmiah-ls , no there isn't unfortunately, the toolbox is using shapely for handling geometries and it assumes projected coordinates (cartesian grid with Eastings and Northings)
