### ISSUE TITLE
the problem of Batch shoreline detection

### ISSUE THREAD

**Issue by love1991126** [kvos/CoastSat#27]
Hi kvos,

When I finished "Batch shoreline detection" this step, it shows something wrong and reminded  me" linestrings must have at least 2 coordinate tuples"

and when i run " plot the time-series of shoreline change along each transect" this stage, there should be a line chart representing the trend, but it can't display, only a blank is displayed.

i m very grateful if you can point out my problem. 

Thank you very much 

best,

yuan
![图片 1](https://user-images.githubusercontent.com/51474910/61376185-0b790080-a8e4-11e9-9906-6b8507bfdadd.png)

**Comment by kvos** [comment]
@love1991126 yes I am aware of this error, I means that no shorelines could be mapped so it is not able to write the .geojson file that contains LineStrings for each shoreline. Could you see mapped shorelines when going through the images with keep/skip? If it couldn't map shorelines it is normal that it doesn't show any time-series of shoreline change when computing the intersections. You may also want to check that you are using a projected coordinate system in settings['espg_out'] and not a spherical system.

**Comment by love1991126** [comment]
HI kvos,

Thank you for your reply. yes  i agree with you ,I also think that the coordinates of the coastline may be problematic, but when I try two or three sets of coordinates, and even change the shape of my interception coordinates, I still can't get results. It always shows this error.

yes i can see mapped shorelines when going through the images with keep/skip.

![1](https://user-images.githubusercontent.com/51474910/61570765-201aeb80-aad2-11e9-867c-d4dc232cb23d.jpeg)
![图片 21](https://user-images.githubusercontent.com/51474910/61570802-61130000-aad2-11e9-8318-fb8f94aef8f2.png)

![WechatIMG4738](https://user-images.githubusercontent.com/51474910/61571327-febbfe80-aad5-11e9-93c2-e467f7763967.jpeg)

so could you kindly tell me which colour do you think is the correct coastline interception, please?

thank you very much 

best ,

yuan

**Comment by kvos** [comment]
you can open SDS_shoreline.py and comment lines 815 to 820. Then it should not try to write a .geojson any more and you won't have that error. 

This is a quick and dirty solution, to investigate the error more I will need the entire error message + the settings that you defined, thanks

**Comment by love1991126** [comment]
HI Kvos,

thank you for your kindly help.  I have solved all the problems after I updated all of packages,and I have got the final image. Thank you very much for your help and your prompt reply.

best, 

yuan 
![final 分析图](https://user-images.githubusercontent.com/51474910/61577985-9b13ee80-ab32-11e9-9e04-df48b10ddc02.png)

**Comment by kvos** [comment]
ok perfect, I will then close the issue.
cheers,
Kilian
