### ISSUE TITLE
ImportError: Convolution C extension is missing. Try re-building astropy.

### ISSUE THREAD

**Issue by JBWoerdman** [kvos/CoastSat#271]
Hi @kvos,

I'm having a hard time getting the initial settings to work.
The following errors are prompt:

import os
import numpy as np
import pickle
import warnings
warnings.filterwarnings("ignore")
import matplotlib
matplotlib.use('Qt5Agg')
import matplotlib.pyplot as plt
from matplotlib import gridspec
plt.ion()
import pandas as pd
from datetime import datetime
from coastsat import SDS_download, SDS_preprocess, SDS_shoreline, SDS_tools, SDS_transects
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
~\Anaconda3\envs\coastsat\lib\site-packages\astropy\convolution\convolve.py in <module>
     24 try:
---> 25     _convolve = load_library("_convolve", LIBRARY_PATH)
     26 except Exception:

~\Anaconda3\envs\coastsat\lib\site-packages\numpy\ctypeslib.py in load_library(libname, loader_path)
    153         ## if no successful return in the libname_ext loop:
--> 154         raise OSError("no file with expected extension")
    155 

OSError: no file with expected extension

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_20324\3769660273.py in <module>
     11 import pandas as pd
     12 from datetime import datetime
---> 13 from coastsat import SDS_download, SDS_preprocess, SDS_shoreline, SDS_tools, SDS_transects

~\CoastSat-master\coastsat\SDS_download.py in <module>
     30 
     31 # CoastSat modules
---> 32 from coastsat import SDS_preprocess, SDS_tools, gdal_merge
     33 
     34 np.seterr(all='ignore') # raise/ignore divisions by 0 and nans

~\CoastSat-master\coastsat\SDS_preprocess.py in <module>
     27 
     28 # CoastSat modules
---> 29 from coastsat import SDS_tools
     30 
     31 np.seterr(all='ignore') # raise/ignore divisions by 0 and nans

~\CoastSat-master\coastsat\SDS_tools.py in <module>
     16 from shapely import geometry
     17 import skimage.transform as transform
---> 18 from astropy.convolution import convolve
     19 
     20 np.seterr(all='ignore') # raise/ignore divisions by 0 and nans

~\Anaconda3\envs\coastsat\lib\site-packages\astropy\convolution\__init__.py in <module>
      6 from .utils import discretize_model, KernelSizeError  # noqa
      7 
----> 8 from .convolve import convolve, convolve_fft, interpolate_replace_nans, convolve_models, convolve_models_fft  # noqa
      9 
     10 # Deprecated kernels that are not defined in __all__

~\Anaconda3\envs\coastsat\lib\site-packages\astropy\convolution\convolve.py in <module>
     25     _convolve = load_library("_convolve", LIBRARY_PATH)
     26 except Exception:
---> 27     raise ImportError("Convolution C extension is missing. Try re-building astropy.")
     28 
     29 # The GIL is automatically released by default when calling functions imported

ImportError: Convolution C extension is missing. Try re-building astropy.

To resolve the errors I have already done the steps as suggested in #42, although the earthengine authentication happened without any problems. Furthermore, I tried to reinstall anaconda, created multiple new environments and downloaded a new folder of CoastSat-master. Still the same issues raise. Do you perhaps have any idea how to get it working?

Thanks! 
Best, Jelle

**Comment by JBWoerdman** [comment]
Thanks for your reply! I will try to reinstall the environment right away.

**Comment by JBWoerdman** [comment]
> hi jelle, there seems to be an issue that is raised with the new version of the `astropy` library. Can you try the following:
> 
> * remove all existing environments (`conda env remove --name myenv`). You can check the names of the environments that you have installed with `conda env list`
> * run `conda clean --all`
> * run `conda update -n base -c defaults conda`
> * try to re-install with the environment.yml contained in this zip file [zip.zip](https://github.com/kvos/CoastSat/files/8591316/zip.zip)
> 
> let me know if this fixes it and I will update the environment.yml file in the repo

In the previous occasions that I installed the environment it took about 5-10 min. However, now it is still running for 38 min. Is that how it is supposed to be?

**Comment by kvos** [comment]
oh should be too much to process for conda.
what you can do is to install them in multiple steps with conda install
start with `conda install -c conda-forge earthengine-api=0.1.236`
then `conda install gdal geopandas`
then `conda install scikit-image`, `conda install astropy`, `conda install spyder notebook`

**Comment by JBWoerdman** [comment]
Hi Kilian,

got it installed for most of the packages. However, the earthengine-api and forge are not found in the channel. Any ideas to overcome this? The following comments are stated when trying to install the first line of code that you provided:

(coastsat) C:\Users\922462\CoastSat-master>conda install -c conda forge earthengine-api=0.1.236
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - earthengine-api=0.1.236
  - forge

Current channels:

  - https://conda.anaconda.org/conda/win-64
  - https://conda.anaconda.org/conda/noarch
  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

**Comment by JBWoerdman** [comment]
Hi Kilian,

It worked! The errors are no longer showing and it seems to download the example images!
Thanks for the help!

**Comment by kvos** [comment]
great! will need to update the doco, did you end up entering the conda install commands for each package?

**Comment by JBWoerdman** [comment]
Yep! Ik ran  each package separately after creating An empty environment.

**Comment by kvos** [comment]
I've updated the changes on how to install the environment in the dev branch, will close here for now
