### ISSUE TITLE
ModuleNotFoundError: No module named 'fcntl'

### ISSUE THREAD

**Issue by phamduonghung** [kvos/CoastSat#272]
**Dear, 
I am running your toolbox on my laptop with Win 10, but I always get the following error. I tried some suggestions found in the internet, for instance, [this one](https://stackoverflow.com/questions/45228395/error-no-module-named-fcntl), but I could not resolve this problem. Could you please help me? Thank you in advance. 

Best regards,** 

___---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-121e24c40f27> in <module>
     11 import pandas as pd
     12 from datetime import datetime
---> 13 from coastsat import SDS_download, SDS_preprocess, SDS_shoreline, SDS_tools, SDS_transects

~\Desktop\CoastSat-master\coastsat\SDS_download.py in <module>
     13 
     14 # earth engine module
---> 15 import ee
     16 
     17 # modules to download, unzip and stack the images

~\anaconda3\lib\site-packages\ee\__init__.py in <module>
----> 1 from .main import main

~\anaconda3\lib\site-packages\ee\main.py in <module>
      3 import subprocess
      4 import sys
----> 5 import blessings
      6 import re
      7 import os

~\anaconda3\lib\site-packages\blessings\__init__.py in <module>
      5 import curses
      6 from curses import setupterm, tigetnum, tigetstr, tparm
----> 7 from fcntl import ioctl
      8 from six import text_type, string_types
      9 

ModuleNotFoundError: No module named 'fcntl'___

**Comment by kvos** [comment]
I have made some changes on how to install the `coastsat` environment, do you want to try this in the `development branch`?

**Comment by phamduonghung** [comment]
Following your updated instruction, the program is running now. Thank you very much.
