### ISSUE TITLE
GDAL Import exception

### ISSUE THREAD

**Issue by rodrigofrcs** [kvos/CoastSat#274]
Please change GDAL import mode in the file coastsat/SDS_download.py to "from osgeo import gdal". Thanks for the excellent work!

**Comment by kvos** [comment]
hi @rodrigofrcs , thanks for the feedback, what should I change it to?

**Comment by rodrigofrcs** [comment]
Hi. After the last version, it is exception that the import "import gdal" is deprecated. Is this returned only to me?

**Comment by kvos** [comment]
ah ok, when did you install the environment? it may be that I am running an older version of gdal. Is it raisin an error or a warning?
