### ISSUE TITLE
Shoreline extraction issues

### ISSUE THREAD

**Issue by Captain-timo** [kvos/CoastSat#276]
@kvos 
First of all, thank you very much for sharing this toolbox, but I encountered a strange bug in the process of using it.
![image](https://user-images.githubusercontent.com/105362419/167847037-256f1607-7435-453a-9ee5-57296509ade6.png)
When I get to this point, the shoreline extraction program becomes unresponsive, and strangely enough the satellite image processing works fine for the other years. After entering this state the computer memory will be used until it is completely exhausted. I have checked similar problems and solutions from other users, but none of them seem to work here.
![image](https://user-images.githubusercontent.com/105362419/167849033-331d6ddc-af64-447b-93dc-79c551b1e27e.png)
![image](https://user-images.githubusercontent.com/105362419/167849389-a703dcb8-83c7-4ea6-a40c-6882e3892f46.png)
In my experience so far, this bug has appeared in the L5, L7, L8 series, and I suspect in the S2 series as well, I will post my research area below with information on the satellite images where the bug appears, if that helps you troubleshoot it.
[[[110.5838577881875,19.153562137932926],
             [110.60909201059961,19.153562137932926],
             [110.60909201059961,19.200986719369098],
             [110.5838577881875,19.200986719369098],
             [110.5838577881875,19.153562137932926]]]
L5-2001-10-02
L8-2019-07-16
Anyway, this toolbox is really great!
I really hope this bug gets fixed soon, after all, I am indeed a programming noob, thank you very much!!!
Good luck on your research journey!!!

**Comment by kvos** [comment]
hi @Captain-timo , must be some weird image where the file is a bit funny. You should go manually in the folder with the images and delete that image (all bands and metadata)

**Comment by kvos** [comment]
will close for the time being, feel free to reopen if you have more info
