### ISSUE TITLE
gdal error

### ISSUE THREAD

**Issue by TGISer** [kvos/CoastSat#278]
Hi there,

when I run SDS_preprocess.save_jpg(metadata, settings) it showed that ModuleNotFoundError: No module named '_gdal_array', I attched the error below, my gdal version is 2.3.3 and python version is 2.8.

Thank you so much for your help!

File ~/Desktop/coding/BlueCarbon/CoastSat-master/coastsat/SDS_preprocess.py:638, in save_jpg(metadata, settings, **kwargs)
    636 fn = SDS_tools.get_filenames(filenames[i],filepath, satname)
    637 # read and preprocess image
--> 638 im_ms, georef, cloud_mask, im_extra, im_QA, im_nodata = preprocess_single(fn, satname, settings['cloud_mask_issue'])
    640 # compute cloud_cover percentage (with no data pixels)
    641 cloud_cover_combined = np.divide(sum(sum(cloud_mask.astype(int))),
    642                         (cloud_mask.shape[0]*cloud_mask.shape[1]))

File ~/Desktop/coding/BlueCarbon/CoastSat-master/coastsat/SDS_preprocess.py:259, in preprocess_single(fn, satname, cloud_mask_issue)
    257 data = gdal.Open(fn10, gdal.GA_ReadOnly)
    258 georef = np.array(data.GetGeoTransform())
--> 259 bands = [data.GetRasterBand(k + 1).ReadAsArray() for k in range(data.RasterCount)]
    260 im10 = np.stack(bands, 2)
    261 im10 = im10/10000 # TOA scaled to 10000

File ~/Desktop/coding/BlueCarbon/CoastSat-master/coastsat/SDS_preprocess.py:259, in <listcomp>(.0)
    257 data = gdal.Open(fn10, gdal.GA_ReadOnly)
    258 georef = np.array(data.GetGeoTransform())
--> 259 bands = [data.GetRasterBand(k + 1).ReadAsArray() for k in range(data.RasterCount)]
    260 im10 = np.stack(bands, 2)
    261 im10 = im10/10000 # TOA scaled to 10000

File ~/opt/anaconda3/envs/bcmap/lib/python3.8/site-packages/osgeo/gdal.py:2605, in Band.ReadAsArray(self, xoff, yoff, win_xsize, win_ysize, buf_xsize, buf_ysize, buf_type, buf_obj, resample_alg, callback, callback_data)
   2597 def ReadAsArray(self, xoff=0, yoff=0, win_xsize=None, win_ysize=None,
   2598                 buf_xsize=None, buf_ysize=None, buf_type=None, buf_obj=None,
   2599                 resample_alg = GRIORA_NearestNeighbour,
   2600                 callback = None,
   2601                 callback_data = None):
   2602     """ Reading a chunk of a GDAL band into a numpy array. The optional (buf_xsize,buf_ysize,buf_type)
   2603     parameters should generally not be specified if buf_obj is specified. The array is returned"""
-> 2605     from . import gdalnumeric
   2607     return gdalnumeric.BandReadAsArray( self, xoff, yoff,
   2608                                         win_xsize, win_ysize,
   2609                                         buf_xsize, buf_ysize, buf_type, buf_obj,
   2610                                         resample_alg = resample_alg,
   2611                                         callback = callback,
   2612                                         callback_data = callback_data)

File ~/opt/anaconda3/envs/bcmap/lib/python3.8/site-packages/osgeo/gdalnumeric.py:1, in <module>
----> 1 from osgeo.gdal_array import *
      2 from numpy import *

File ~/opt/anaconda3/envs/bcmap/lib/python3.8/site-packages/osgeo/gdal_array.py:28, in <module>
     26                 fp.close()
     27             return _mod
---> 28     _gdal_array = swig_import_helper()
     29     del swig_import_helper
     30 else:

File ~/opt/anaconda3/envs/bcmap/lib/python3.8/site-packages/osgeo/gdal_array.py:20, in swig_import_helper()
     18     fp, pathname, description = imp.find_module('_gdal_array', [dirname(__file__)])
     19 except ImportError:
---> 20     import _gdal_array
     21     return _gdal_array
     22 if fp is not None:

ModuleNotFoundError: No module named '_gdal_array'

**Comment by kvos** [comment]
don't know why this is happening to you, have you tried googling the error to see if the gdal community has reported it before?

**Comment by YonniYe** [comment]
Hi, I met the same problem. A mixture of packages from `default` and `conda-forge` channels for the dependencies lead to the dilemma of importing them. The failure of importing `gdal_array` can be attributed to the wrong version of gdal, which may not connect with `numpy` correctly (my wrong gdal version is 2.3.3). I tried to use `conda install gdal --force-reinstall` after I ensured the installation of `numpy`, but it still did not work. Finally, I found a feasible way to fix it, which is to reinstall the necessary packages with correct dependencies. Here is what I done to solve the problem:
```
conda env remove -n coastsat
conda create -n coastsat python=3.8
conda activate coastsat
conda install -c conda-forge geopandas earthengine-api scikit-image matplotlib astropy notebook -y
pip install pyqt5
```

Now `coastsat` works fine to me :)

**Comment by kvos** [comment]
thanks @YonniYe for the suggestion, will test it out and update the documentation if it works.
Is there a reason why it\s better not to mix `default` and `conda-forge`? Some packages are only available on conda-forge.
Also, why is the `pyqt5` dependency needed and why are you installing it with `pip`?

**Comment by YonniYe** [comment]
@kvos Hi kvos, [a QA in stackoverflow](https://stackoverflow.com/questions/39857289/should-conda-or-conda-forge-be-used-for-python-environments) talks about why it is recommended to use `conda-forge` solely. The reasons include: (1) the packages in `conda-forge` may be more up-to-date; (2) some packages may not be available in `defaults`; and (3)the `conda-forge` and `defaults` are not 100% compatible. So it is advisable not to mix multiple channels. [Another link](https://conda-forge.org/docs/user/tipsandtricks.html#using-multiple-channels) from `conda-forge` discusses it.

The reason why I install `pyqt5` is that your amazing program makes it a dependency. I guess the function of interactive drawing may require this package, and the environment I configure does not install it automatically. I know it is not a good idea to mix `conda` and `pip` as the installed packages may conflict, but `pyqt5` is ONLY available in `PyPI`. So I have no choice but to download it through `pip`. Luckily, there have been no conflicts since then.

By the way, I tried `CoastSat` on my M1 Mac, and I guess this issue may not occur on a Windows platform (I have not tested it yet).

**Comment by kvos** [comment]
great thanks @YonniYe , I tested your way of installing it and it worked perfectly! just updated the documentation
