### ISSUE TITLE
import geojson into ArcGIS

### ISSUE THREAD

**Issue by VINCENTAFERRER** [kvos/CoastSat#281]
Dear Kilian
     Off late, I encounter an issue related to importing geojson files generated from coastsat into ArcGIS PRO 2.8. 
Earlier I could seamlessly import the geojson shoreline files from coastsat into ArcGIS without any issue with projections or spatial referencing. But using the recent version of coastsat creates issues with the spatial referencing while the geojson file gets successfully imported into ArcGIS PRO. when I look into the spatial reference of the two files imported from the earlier and most recent coastsat version, I come across one difference as shown in the screenshot below:
![image](https://user-images.githubusercontent.com/76463942/172312631-92b46223-c10a-430e-a164-93fc8dec02ed.png)
![image](https://user-images.githubusercontent.com/76463942/172312795-de4545ee-8cc6-4e32-8d98-27dbc49c4831.png)
The first image corresponds to the spatial reference details as imported by ArcGIS PRO from the geojson file generated from earlier coastsat version. It mentions two spatial referencing - the Projected Coordinate System (EPSG - 3857) and the Geographic Coordinate System (EPSG - 4326).
But in the second image which corresponds to the spatial reference of that of the imported geojson file from the most recent coastsat version into ArcGIS PRO, we see that only the Geographic coordinate system (EPSG - 4326) is defined. Unfortunately, the geojson file imported as shapefiles are wrongly projected and displays in a wrong geographic region.
While it could be assumed to be the issue with that of ArcGIS PRO, I see that I use the same version of ArcGIS PRO to import the two geojson files and only difference arises in the version of the coastsat being used to generate the geojson file.

Hence I bring it to your kind attention and eargerly await a positive response.

In connection with our earlier discussion on the accuracy of C01 and C02 landsat collections, I am stuck with importing the generated shorelines into arcgis so that I can see how both performs in shoreline extraction and shoreline change statistics.

**Comment by kvos** [comment]
yes, my guess it that this is because off late GeoJSON files need to be in epsg 4326, that's the standard now. So when you go in with 3857 in the GeoJSON it thinks it's in 4326.
You can convert your geojson to 4326 before saving it with a one-liner:
`gdf.to_crs(epsg=4326)`

**Comment by VINCENTAFERRER** [comment]
I hope I shall look into it and update any progress on this...
