### ISSUE TITLE
ModuleNotFoundError: No module named 'coastsat'

### ISSUE THREAD

**Issue by abangega** [kvos/CoastSat#282]
![image](https://user-images.githubusercontent.com/107164520/172757475-be7cafc1-cb2f-4a7a-a6ca-f1cbee72c4b6.png)

Can someone help me with this?? Coastsat is not a module right? then how do I import the SDS_download, SDS_preprocess, SDS_shoreline, SDS_tools, SDS_transects? any reply is appreciated. thanks!

**Comment by abangega** [comment]
![image](https://user-images.githubusercontent.com/107164520/172782616-fafa7a30-1a7e-4c0a-a821-37b7fcacb6d5.png)

Fixed it! Turned out that need to download the latest coastsat source code on the 'releases' section

**Comment by nashwa2010** [comment]
i also have come up with the same error,what should i do ?
