### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by awkis23** [kvos/CoastSat#283]
<img width="922" alt="Screen Shot 2022-06-18 at 3 06 12" src="https://user-images.githubusercontent.com/67011241/174354184-87fd376c-09fa-4beb-91e1-708bb328cfe2.png">

Hi Vos, I need your help.
When I try to run this step, it took so much time. Already been 1 hour but it is not downloading (image attached). What do you think about this matter?
Thank you in advance for your help.

**Comment by awkis23** [comment]
I have tried to make it smaller (less than 80 km^2), but the problem still occurs.

**Comment by Labrador120** [comment]
Hello, I have the same problem when I try to run the code the first time, without following the comment instraction, I think you are missing to add the list of satellites did you choose to take the picture from there, make sure you have set like the picture below
![Screenshot 2022-06-25 192256](https://user-images.githubusercontent.com/108193861/175786215-16508a86-8167-4a5c-a4bc-074392571785.jpg)

**Comment by kvos** [comment]
hi all, it must be stuck in some kind of loop. I'm working on a fix, will provide a updated version of coastsat very soon so you can try it out

**Comment by kvos** [comment]
I think @awkis23, it's an issue with Collection 2 as you are requesting dates past 2022. I'll fix it but in the meanwhile you can request dates before 2022 and should be good

**Comment by awkis23** [comment]
<img width="1085" alt="Screen Shot 2022-06-27 at 14 13 59" src="https://user-images.githubusercontent.com/67011241/175864886-a6eb891d-d318-418b-9a48-ad0454bcc7fb.png">
I follow your suggestion but it still doesn't work.

**Comment by kvos** [comment]
this should be fixed in CoastSat 2.0, make sure you download everything in a new folder
