### ISSUE TITLE
Authorisation Error

### ISSUE THREAD

**Issue by Bizzer30** [kvos/CoastSat#284]
I'm not open Anaconda Prompt to link your environment to the GEE server: earthengine authenticate .

**Comment by kvos** [comment]
hi @Bizzer30 , you must have an older version of the earthengine-api. Try to update it with `conda update earthengine-api` or re-install the coastsat environment as explained in the latest README file

**Comment by Bizzer30** [comment]
Thank you ,I followed the steps in README file and still couldn't do it. I can not open  to the GEE server earthengine-api .
