### ISSUE TITLE
EarthEngine Authentication error

### ISSUE THREAD

**Issue by VINCENTAFERRER** [kvos/CoastSat#286]
currently the 'earthengine authenticate' command fails with an error message as follows:

![image](https://user-images.githubusercontent.com/76463942/175235732-980605b1-7a9b-4a7b-9188-bd2638c270e4.png)

The error persists even after reinstalling anaconda and creating new COASTSAT environment. The update syntax 'conda update earthengine-api' also couldnt solve the issue...

Support please...

**Comment by kvos** [comment]
check out #285
