### ISSUE TITLE
Problem with setting up GDAL in environment

### ISSUE THREAD

**Issue by VHeimhuber** [kvos/CoastSat#287]
I'm having trouble setting up the Coastsat environment in accordance with the instructions via conda. After setting it up, I'm getting the following error when trying to load the GDAL package: 

DLL load failed while importing gdal: The specified module could not be found.

Is anyone else getting this? Any workarounds?

**Comment by artrob** [comment]
Hi @VHeimhuber 

I have the same problem when I install this environment on my desktop computer (I tried again today)

On my laptop I made the installation few weeks ago and it works perfectly. I am exploring the differences between the 2 install. 
From what I can see there is a difference in terms of package version for gdal in the two installations. 
On my desktop computer (not working), I have: gdal                      3.0.2            py38hb978731_2
On my laptop computer (working), I have: gdal                      3.5.0            py38hf334de5_4   conda-forge
May be the conda-forge should be added to the default channel before doing the installation... I will have a look.

**Comment by artrob** [comment]
It seems to be a solution to have gdal working correctly ! (i.e. to be able to use "from osgeo import gdal") !
You can try this :
- remove your coastsat env : conda env remove --name coastsat
- add conda-forge channel to your conda config: conda config --add channels conda-forge
- install again the coastsat env as explained in the README.md
May be there is other way to force the conda-forge channel to be used for installation without alteting the conda config.

However, I don't know yet if there will be some side effects of having most of packages installed from the conda-forge. I hope not. An idea about this @kvos ?

**Comment by kvos** [comment]
you're the GDAL master @artrob! I've seen a few posts about this gdal issue on stackexchange and they refer to it as the "DLL hell"... it seems like the only way to fix it is to re-install things with trial and error until it works and hope that you don't ever have to update the environment. I think the difference between the main channel and conda-forge is who maintains the channel, so usually less compatibility issues using the main channel which is directly maintained by the anaconda team.

**Comment by VHeimhuber** [comment]
Thanks, @artrob and @kvos - I'll give it a try!
