### ISSUE TITLE
GeoJSON cleaning?

### ISSUE THREAD

**Issue by tolandwehr** [kvos/CoastSat#288]
Hi there, 

not too much experience with GIS, so possibility that this issue might be superfluous:

GeoJSON outputs are always interconnected and closed polygons. I.e.,

I. if there are some islands in a delta that appear and disappear over the years, the GeoJSON output gets really messy, especially for years and decades to monitor. The points of the actually separated islands are interconnected.
II. first and last point of shorelines are connected to close the polygon. Again, a messy impression.

Is there any quick way (on the coding or GIS site) to solve this? For sure, I cannot be the first one to have the issue.

Any hint or links is highly appreciated.
Thanks in advance!

**Comment by kvos** [comment]
hi @tolandwehr , have you tried using the 'points' option when saving the shorelines as GeoJSON?
The problem when using Linesterings is that the toolbox works with numpy arrays, which don't have connectivity, so when the corordinates are copied into a GeoJSON the linestrings are kind of randomly connected

**Comment by tolandwehr** [comment]
Hi!

Yes, the suggestion (any maybe the new version) resolved the issue! I thought I already posted it. Thank you @kvos for following up ;-)!
