### ISSUE TITLE
About SDS

### ISSUE THREAD

**Issue by hamidj2019** [kvos/CoastSat#29]
Hi,
I was double checking things and have been also looking into some updates here.
I have seen the following update about 20 days ago:
update SDS_prepocess.py

Could you please advise if I need to update something in the master folder because of this?

Best regards

**Comment by kvos** [comment]
Yes you always need to pull the latest updates...if you have cloned the repository (for example with Github Desktop) you should receive a notification every time I (or others) commit changes to the code, and have the option to update your version. I recommend you download Github Desktop as it has a graphical interface
