### ISSUE TITLE
Potential issue with SDS.tools.convert_epsg with latest GDAL version

### ISSUE THREAD

**Issue by VHeimhuber** [kvos/CoastSat#290]
Hi all,

I seem to be running into issues with the SDS.tools.convert_epsg function that only occurs in an environment that I recently set up with the updated instructions in the readme. I believe it has to do with updates that occurred from GDAL 2 to 3. The code works perfectly fine in my old environment that runs on GDAL 2. something. 

Basically, the function returns empty coordinates. I'm wondering if anyone else is using GDAL 3 and has encountered a similar issue. 

I'm thinking it may occur at this step: inSpatialRef.ImportFromEPSG, since GDAL made some changes there as stated on their pages: 

"This method try to attach a 3-parameter or 7-parameter Helmert transformation to WGS84 when there is one and only one such method available for the CRS. This behavior might not always be desirable, so starting with GDAL 3.0.3, the OSR_ADD_TOWGS84_ON_IMPORT_FROM_EPSG configuration option can be set to NO to disable this behavior."

Thanks, T.

**Comment by kvos** [comment]
the new installation procedure should solve this issue
