### ISSUE TITLE
Image downloading issue

### ISSUE THREAD

**Issue by GowriRavichandran** [kvos/CoastSat#296]
Hi @kvos ,
  When I try to run the following line in example.ipynb file, it doesn't downloading any images and its loading for a long time . And it doesn't give any error too!

metadata = SDS_download.retrieve_images(inputs)

it creates new folder inside data folder but doesn't produce any results. Please help me out in this!

**Comment by kvos** [comment]
it seems to be a recurring issue, is this with the Narrabeen polygon in the example?

**Comment by kvos** [comment]
try the new version CoastSat 2.0, it should work fine now

**Comment by kvos** [comment]
will close the issue for now, reopen if issue still showing up in the new release
