### ISSUE TITLE
Downloading error with new function

### ISSUE THREAD

**Issue by pgurruchaga** [kvos/CoastSat#300]
Hi, I'm trying to use coastsat with the new update so I've replaced my old functions with the new ones in coastsat folder. Now I'm getting the following error when downloading Landsat images (didn't happen with sentinel ones since it was able to download them).

![imagen](https://user-images.githubusercontent.com/74714396/182394887-ae66b160-03a6-4d91-a36d-b2001965f8e2.png)

Thank you,
Paula.

**Comment by kvos** [comment]
mm interesting, are you using Collection 2 maybe? I'll check, I think I know what it is, it probably cannot find a band with 'QA' in the name in Collection 2 images. will fix it, thanks for the reporting it

**Comment by pgurruchaga** [comment]
No, it's actually collection 1. 
`# choose Landsat collection 'C01' or 'C02'
collection = 'C01'`
Thank you!

**Comment by kvos** [comment]
ok, can you set dates before 2022? because from 2022 onwards it directly switches to Collection 2 even if you specify Collection 1

**Comment by pgurruchaga** [comment]
sorry, didn't realize that. With different dates I get another error:
![imagen](https://user-images.githubusercontent.com/74714396/182451810-ab1db24c-154e-4e1c-9235-40b2d37402b4.png)

but that one seems to be something about my computer and not about the code itself.

**Comment by kvos** [comment]
ok, i think this permission error is due to the previous error that crashed the code somewhere in between downloads.
Can you please try the following @pgurruchaga :
- delete download folder or create a new one with a different sitename with dates before 2022 Collection 1 and see if the issue comes up
- share your inputs dictionary so I can recreate the issue for the Collection 2 part (after 2022)
thanks

**Comment by pgurruchaga** [comment]
You're right, it worked for dates before 2022 in a new folder.
These are my inputs:
[CS_RAMIREZ_polygon.csv](https://github.com/kvos/CoastSat/files/9260124/CS_RAMIREZ_polygon.csv)
[CS_RAMIREZ_ref.csv](https://github.com/kvos/CoastSat/files/9260125/CS_RAMIREZ_ref.csv)
[COASTSNAP_RAMIREZ.zip](https://github.com/kvos/CoastSat/files/9260173/COASTSNAP_RAMIREZ.zip)

Thank you

**Comment by kvos** [comment]
@pgurruchaga - error fixed, it was something silly, the name of the QA band has changed in Collection 2, it's not called `BQA` anymore but `QA_PIXEL` , so it could not find it. 
I would still be cautious using Collection 2 images in automatic mode as it seems that the cloud mask is not picking up the clouds, maybe the values of the mask have changed as well.

**Comment by kvos** [comment]
also fixed the cloud mask issue I think, let me know if anything shows up again, will close the issue for now
