### ISSUE TITLE
Zipfile error when downloading

### ISSUE THREAD

**Issue by JanTiede** [kvos/CoastSat#301]
Hi Kilian,
with CoastSat 2.0 I get the following error when downloading images:
![image](https://user-images.githubusercontent.com/69578620/182604774-97ce494d-e0c1-4b04-922e-4b407ed199d4.png)
It seems to download the images just fine and then just stops with that error message.

Cheers
Jan

**Comment by JanTiede** [comment]
The problem was that files downloaded with an earlier coastsat version were still in the download folder.

**Comment by kvos** [comment]
@JanTiede what's the status on this issue?
try to create a new sitename as the folder structure of the tif files has changed so it won't be compatible with images downloaded with the previous version

**Comment by JanTiede** [comment]
@kvos I tried that first and started with a clean data folder. It still stopped.
When it stops there is a temp.zip left in the data folder. Did any of the package change with the upgrade to 2.0?

**Comment by kvos** [comment]
the unzip package should be the same. Can you send me your inputs dictionary , I will check it out

**Comment by kvos** [comment]
I managed to reproduce the error, will see if I can fix it sometime this week

**Comment by kvos** [comment]
see if the new commit on the `development` branch fixes it. It does on my end.

**Comment by kvos** [comment]
this issue has been fixed, see #315
