### ISSUE TITLE
'Adjust detetcion' error

### ISSUE THREAD

**Issue by eddylr** [kvos/CoastSat#305]
Hi Kilian,

I've been following your code for a while, it has been really helpful.
With the recent update I've been getting an error when activating 'Adjust Detection' , previous versions didn't show it.

Here's the error dscription:

![image](https://user-images.githubusercontent.com/110738991/183260325-7e75a8a5-6867-4211-b945-17c5f72795b8.png)

Do you know what is causing it?

Thanks, 
Eddy R.

**Comment by kvos** [comment]
good catch, I forgot to update the `process_shoreline()` function call in `adjust_detection`. 
Just pushed a fix to the master, you can check if it's working now
