### ISSUE TITLE
Loading measured tide data - error

### ISSUE THREAD

**Issue by Anish0323** [kvos/CoastSat#316]
I get the following error while trying to upload the tidal data. The data is also attached. 
--------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Input In [40], in <cell line: 4>()
      2 filepath = os.path.join(os.getcwd(),'examples','Qasibale_Tides_.csv')
      3 tide_data = pd.read_csv(filepath, parse_dates=['dates'])
----> 4 dates_ts = [_.to_pydatetime() for _ in tide_data['dates']]
      5 tides_ts = np.array(tide_data['tide'])

Input In [40], in <listcomp>(.0)
      2 filepath = os.path.join(os.getcwd(),'examples','Qasibale_Tides_.csv')
      3 tide_data = pd.read_csv(filepath, parse_dates=['dates'])
----> 4 dates_ts = [_.to_pydatetime() for _ in tide_data['dates']]
      5 tides_ts = np.array(tide_data['tide'])

AttributeError: 'str' object has no attribute 'to_pydatetime'
[Qasibale_Tides_.csv](https://github.com/kvos/CoastSat/files/9398619/Qasibale_Tides_.csv)

Any assistance will be appreciated.

Thanks!

**Comment by kvos** [comment]
this means that pandas wasn't able to parse your dates. I'm guessing your dates come as a string so you could convert them to datetime with the function datetime.strptime(string,format), google it to see the doc.

**Comment by Anish0323** [comment]
Thanks... will try that.

**Comment by Njutap** [comment]
Hello kvos

I would like to know how I can save the tide data from FES2014 over the study period as a .csv file. In order to use it in the part 4 Tide Correction as tide data. 

Thanks
![Image1](https://user-images.githubusercontent.com/62559776/188290427-161ca700-f21b-4a05-ae06-2f0d8d76b723.png)

**Comment by kvos** [comment]
I think it's a good question for @Anish0323 as that is exactly what he has done!

**Comment by Njutap** [comment]
Thanks Kvos
I will ask the question to

**Comment by Njutap** [comment]
Thanks @kvos 
I return the question to @Anish0323

**Comment by juni666666** [comment]
PLEASE HELP WITH THE COMMENT
HOW DO I GET THE TIDAL DATA INTO A CSV

**Comment by Njutap** [comment]
He @juni666666 
# Save the measurement data as a .csv file
import pandas as pd
df = pd.DataFrame(tide_fes,dates_fes)
df.to_csv('Tide_fes.csv',sep=',')
