### ISSUE TITLE
Gcloud issue when running earthengine authenticate

### ISSUE THREAD

**Issue by JohanCamilo15** [kvos/CoastSat#317]
Hello Kvos

It is possible solution in error: The version of the app you're using doesn't include the latest security features to keep you protected. Please make sure to download from a trusted source and update to the latest, most secure version? 

Thanks.

**Comment by JohanCamilo15** [comment]
> Same here - also installed the cloud cli - no difference. Have also updated the api to no effect.

Exactly. Now is not possible open the CoastSat.

**Comment by IAINATTWATER** [comment]
Mine was for authenticating the earth engine in order to use the python api - is that a different issue?

**Comment by JohanCamilo15** [comment]
> Mine was for authenticating the earth engine in order to use the python api - is that a different issue?

Is the same problem. Does it work for you?

**Comment by IAINATTWATER** [comment]
here's my fix. Installed version 0.1.317 of ee. Launch a python console -> import ee -> ee.__version__ and see what version is actually installed. Mine reported 0.1.186 **despite already doing an update**. I use conda so installed using conda install earthengine-api==0.1.317 and all is good. Note that I had already installed and configured gcloud. Hope it helps you.

**Comment by IAINATTWATER** [comment]
Hi

Assuming you have conda package manager installed (if not then other PM will do), create a new python environment with 

> conda create --name myenv

Where myenv is what you want to call the new environment. Then activate **(make sure you do this)** the newly created env with

> conda activate myenv

Again if you used a different name than myenv then use that different name here.

 Then install the latest version on the engine with

> conda install earthengine-api==0.1.317


Then follow the instructions to install gcloud:

[https://cloud.google.com/sdk/docs/install-sdk](url)

You should then be able to authenticate - the browser will open after you enter the authenticate command and should not give you the 400 error like yesterday.

Hope this helps.

Cheers
,

**Comment by JohanCamilo15** [comment]
The instructions did not work for me. Can we do a meeting or a video? Thanks
Johan Casadiego
