### ISSUE TITLE
Offline-use after download

### ISSUE THREAD

**Issue by bergsmaE** [kvos/CoastSat#32]
Hi Kilian,

Awesome tool! It worked in a jiffy and tried it on my holiday-beach: smooth and easy.
Now. I wanted to work off-line after I download the data but I see you initialise the Google Earth Engine toolbox also if you just want to load the metadata. I think this is not necessary. There is just a tiny change needed for this and I don't think it is worth to make a pull-request etc.

Can you move;
    ee.Initialize()

within
def retrieve_images(inputs):

Then you only initialise the server when it is really needed. For the users, it then becomes
from coastsat.SDS_download import get_metadata to work offline... (small detail)

Cheers,

Erwin

**Comment by kvos** [comment]
thanks @bergsmaE for your feedback and suggestion, I've just pushed that change to the dev branch, it makes more sense that way!
