### ISSUE TITLE
Download lasts forever at 2.0. Try/Except issue?

### ISSUE THREAD

**Issue by tolandwehr** [kvos/CoastSat#320]
Hi there!

Returned after a while for a new project with coastsat. Discovered that there is a 2.0 version, so updated all the packages described in the instructions and cloned the 05/09/22 repo into the directory of the environment.

Slightly modified the example notebook to see how it works. Only changes: 1. S2 2. New `sitename` 3. New polygon coordinates:

```
[[[
        -36.4982986,
        -10.4951602
      ],
      [
        -36.4292908,
        -10.5812076
      ],
      [
        -36.3080978,
        -10.4435203
      ],
      [
        -36.3530731,
        -10.3945726
      ],
      [
        -36.4982986,
        -10.4951602
      ]]]
```

Everything seems fine until downloading the images. The download obviously gets stuck. When downloading images prior to 2022, the download count ticks up to a low percentage number, which represents literally the fraction of the first image. I.e: 10 images --> Download counter ticks up 10%, then gets stuck. For time intervals including 2022, no percentage count appears. 

No file directory corresponding with `sitename` is created at `envs\CoastSat-master\data` as it was prior to 2.0. No file gets actually downloaded. No error is produced at the example notebook. It seems that the code loops forever.

At #315 you mentioned a try/ecempt solution, but I am not sure how to implement this. Is there an example or was an implementation you made?

Already a big thanks for all hints and help!
Tobias

**Comment by kvos** [comment]
yes, there is a try/except structure which hides the error outputs, which is a problem at the moment.
I just ran your polygon without that structure and the error that shows up is

![image](https://user-images.githubusercontent.com/7217258/188395241-13dc2680-7c91-4590-91a3-7eebdc040753.png)

this means that your polygon is way too big so it can't be downloaded as there is a limit on how much can be requested from GEE. Try to make a smaller polygon, ideally not more than 50 sqkm
