### ISSUE TITLE
problem with SDS_preprocess.get_reference and output.

### ISSUE THREAD

**Issue by VuHoangDao** [kvos/CoastSat#321]
I have downloaded the image from Lansat7 but I  can not run the image. I am looking it in the folder jpg_files\preprocessed but I don't see any images that I downloaded.
![image](https://user-images.githubusercontent.com/112917719/188549481-216ea0c1-582b-46ba-b82d-ae2ecbf17e34.png)
![image](https://user-images.githubusercontent.com/112917719/188549413-c4be37f3-2a6e-42b2-879b-6fc70a6b08bc.png)
![image](https://user-images.githubusercontent.com/112917719/188549601-a526418c-ef63-429c-a1f3-0bc3a1fd5568.png)

**Comment by kvos** [comment]
it means no images meet your criteria for clouds. You can add more images by adding more satellite missions and expanding the date range

**Comment by VuHoangDao** [comment]
I have three more questions:
1. I try to download images from Sentinel 2 but it doesn't run the process 
![image](https://user-images.githubusercontent.com/112917719/188777568-741cb87c-a5f2-4a74-a1df-96788b637e92.png)
2. When I try to download images from Landsat8, it download failed, and I try to download the image again many times but it got the same error
![image](https://user-images.githubusercontent.com/112917719/188779495-e6bb4f8c-6f5f-4119-974c-5405af6a1ad2.png)
![image](https://user-images.githubusercontent.com/112917719/188779977-44ce30e7-d23b-425e-a896-d421022b3e6c.png)
3. I can only download Landsat 7 image but it can't run because in the file "SDS_preprocess.py", the definition of "get_reference_sl(metadata, settings": 
![image](https://user-images.githubusercontent.com/112917719/188780434-a51b7199-f8d3-4931-9544-0a0980b08e39.png)

**Comment by VuHoangDao** [comment]
For Landsat8 download images, the error is:
HttpError                                 Traceback (most recent call last)
File E:\CoastSAT\envs\coastsat\lib\site-packages\ee\data.py:328, in _execute_cloud_call(call, num_retries)
    327 try:
--> 328   return call.execute(num_retries=num_retries)
    329 except googleapiclient.errors.HttpError as e:

File E:\CoastSAT\envs\coastsat\lib\site-packages\googleapiclient\_helpers.py:134, in positional.<locals>.positional_decorator.<locals>.positional_wrapper(*args, **kwargs)
    133         logger.warning(message)
--> 134 return wrapped(*args, **kwargs)

File E:\CoastSAT\envs\coastsat\lib\site-packages\googleapiclient\http.py:915, in HttpRequest.execute(self, http, num_retries)
    914 if resp.status >= 300:
--> 915     raise HttpError(resp, content, uri=self.uri)
    916 return self.postproc(resp, content)

HttpError: <HttpError 400 when requesting https://earthengine.googleapis.com/v1alpha/projects/earthengine-legacy/thumbnails?fields=name&alt=json returned "Total request size (102294276 bytes) must be less than or equal to 50331648 bytes.". Details: "Total request size (102294276 bytes) must be less than or equal to 50331648 bytes.">

During handling of the above exception, another exception occurred:

EEException                               Traceback (most recent call last)
File ~\CoastSat-master\coastsat\SDS_download.py:253, in retrieve_images(inputs)
    252 try:    
--> 253     fn_ms, fn_QA = download_tif(image_ee,ee_region_ms,bands['ms'],fp_ms)
    254     fn_pan = download_tif(image_ee,ee_region_pan,bands['pan'],fp_pan)

File ~\CoastSat-master\coastsat\SDS_download.py:690, in download_tif(image, polygon, bands, filepath)
    687 # for the newer versions of ee
    688 else:       
    689     # crop and download
--> 690     download_id = ee.data.getDownloadId({'image': image,
    691                                          'region': polygon,
    692                                          'bands': bands,
    693                                          'filePerBand': True,
    694                                          'name': 'image'})
    695     response = requests.get(ee.data.makeDownloadUrl(download_id))  

File E:\CoastSAT\envs\coastsat\lib\site-packages\ee\data.py:969, in getDownloadId(params)
    967   request['bandIds'] = _cloud_api_utils.convert_to_band_list(
    968       [band['id'] for band in bands])
--> 969 result = _execute_cloud_call(
    970     _get_cloud_api_resource().projects().thumbnails().create(
    971         parent=_get_projects_path(), fields='name', body=request))
    972 return {'docid': result['name'], 'token': ''}

File E:\CoastSAT\envs\coastsat\lib\site-packages\ee\data.py:330, in _execute_cloud_call(call, num_retries)
    329 except googleapiclient.errors.HttpError as e:
--> 330   raise _translate_cloud_exception(e)

EEException: Total request size (102294276 bytes) must be less than or equal to 50331648 bytes.

During handling of the above exception, another exception occurred:

Exception                                 Traceback (most recent call last)
Input In [3], in <cell line: 2>()
      1 # inputs['include_T2'] = True
----> 2 metadata = SDS_download.retrieve_images(inputs)

File ~\CoastSat-master\coastsat\SDS_download.py:260, in retrieve_images(inputs)
    258 count += 1
    259 if count > 100:
--> 260     raise Exception('Too many attempts, crashed while downloading image %s'%im_meta['id'])
    261 else:
    262     continue

Exception: Too many attempts, crashed while downloading image LANDSAT/LC08/C01/T1_TOA/LC08_154234_20190522

**Comment by kvos** [comment]
your polygon is too big, you need to make it smaller cause GEE does not let you download so much data

**Comment by VuHoangDao** [comment]
I scale it down to 44 square kilometers but it still can't download the image from sentinel 2 and Landsat8.
![image](https://user-images.githubusercontent.com/112917719/188849315-239921c6-8d3b-45b9-a088-597e9beab51d.png)
![image](https://user-images.githubusercontent.com/112917719/188850279-659ddcde-2721-4ccc-81e0-9fed174fa716.png)
![image](https://user-images.githubusercontent.com/112917719/188850620-776ff6bd-3d3d-4938-95c9-91c85b85ab22.png)

**Comment by kvos** [comment]
try to make it even smaller, if you give a non-rectangular area, it will automatically make it a rectangle so then the area will increase. Try to stay around 25sqkm rectangle for optimal performance. You can always split your region in multiple polygons.

**Comment by VuHoangDao** [comment]
I make it even smaller in my case study area ( down to 4.21 Square Kilometers) but it still got the same error.
![image](https://user-images.githubusercontent.com/112917719/189293470-712f3408-8ada-4b96-a688-a1a79c5aebe8.png)
![image](https://user-images.githubusercontent.com/112917719/189293479-344c96b0-1d42-430d-87e5-5149ed957018.png)
![image](https://user-images.githubusercontent.com/112917719/189293492-311f2450-0ce5-4d09-bc4f-7bcb5a74228a.png)
![image](https://user-images.githubusercontent.com/112917719/189293508-398c190c-ff8e-47a1-9711-4de68a562928.png)

**Comment by kvos** [comment]
oh, you have inverted latitude and longitude in your polygon

**Comment by VuHoangDao** [comment]
I have already defined the shoreline but got the index error. I don't understand why it doesn't have an axis.
![image](https://user-images.githubusercontent.com/112917719/189302577-69fd3c77-05e3-4eb5-8e00-f0efbbb8102b.png)
![image](https://user-images.githubusercontent.com/112917719/189302550-d9fa1b5b-6e41-45f6-b6c0-264172254826.png)

**Comment by kvos** [comment]
did you click on the 'end' button after digitising the shoreline?

**Comment by kvos** [comment]
any update on this issue @VuHoangDao ?

**Comment by VuHoangDao** [comment]
Yes, I am still keep learning the tools box. And I will send you some of my
question so far with my issues.
For now I study master course in Germany and I really want to apply
CoastSat tools box in my Master Thesis.
Thank you for your supporting.

Best regards,
Hoang.
