### ISSUE TITLE
SDS_preprocess.save_jpg(metadata, settings)

### ISSUE THREAD

**Issue by juni666666** [kvos/CoastSat#325]
--> 615 im_ms, georef, cloud_mask, im_extra, im_QA, im_nodata = preprocess_single(fn, satname, settings['cloud_mask_issue'],settings['pan_off'], collection)

--> 171     georef = np.array(data.GetGeoTransform())
                   

'NoneType' object has no attribute 'GetGeoTransform'

hi kvos , first of all great work on the toolkit, 
secondly im having issue when i run the command line stated in the subject of this message

![Screenshot 2022-09-11 021300](https://user-images.githubusercontent.com/113264536/189501978-9d259cbd-2af4-4966-828a-5954d2406687.jpg)

**Comment by kvos** [comment]
this means that there are no images matching your settings that can be saved as jpg, you can download more images or relax the cloud threshold parameter
