### ISSUE TITLE
FileExistsError: [WinError 183] Cannot create a file when that file already exists

### ISSUE THREAD

**Issue by Aghnar2010** [kvos/CoastSat#331]
Hi Kvos,

Since the last update of the functions in the coastsat folder, it is impossible to download S2 images without getting the error  :

"FileExistsError: [WinError 183] Cannot create a file when that file already exists"

I could not solve the problem on my side without taking an old version of the functions.

Anyway, congratulations for this great work.

**Comment by kvos** [comment]
ok, can you please share your code so I can recreate the issue? make sure you delete any existing file before starting the download.

**Comment by Aghnar2010** [comment]
Yes, I have deleted the folder where the conflict occurs each time, but always this error at the fifth or sixth S2 image. Everything else is fine for images L5, L7, L8 and L9.

 My code :

```
# region of interest (longitude, latitude in WGS84)
polygon = [[[3.034008, 42.721002],
            [3.042999, 42.721000],
            [3.043008, 42.707004],
            [3.033978, 42.707030],
            [3.034008, 42.721002]]]
# can also be loaded from a .kml polygon
# kml_polygon = os.path.join(os.getcwd(), 'examples', 'NARRA_polygon.kml')
# polygon = SDS_tools.polygon_from_kml(kml_polygon)
# convert polygon to a smallest rectangle (sides parallel to coordinate axes)
polygon = SDS_tools.smallest_rectangle(polygon)

# date range
dates = ['1984-01-01', '2022-09-27']

# satellite missions
sat_list = ['L5', 'L7', 'L8', 'L9', 'S2']
collection = 'C01' # choose Landsat collection 'C01' or 'C02'
# name of the site
sitename = 'TET'

# filepath where data will be stored
filepath_data = os.path.join(os.getcwd(), 'data')

# put all the inputs into a dictionnary
inputs = {
    'polygon': polygon,
    'dates': dates,
    'sat_list': sat_list,
    'sitename': sitename,
    'filepath': filepath_data,
    'landsat_collection': collection
        }

# before downloading the images, check how many images are available for your inputs
SDS_download.check_images_available(inputs);

#%% 2. Retrieve images

# only uncomment this line if you want Landsat Tier 2 images (not suitable for time-series analysis)
# inputs['include_T2'] = True

# retrieve satellite images from GEE
metadata = SDS_download.retrieve_images(inputs)
```

**Comment by kvos** [comment]
thanks for the details, it seems to be the same issue as #333 with duplicates going all over the place. Maybe I will revert to the previous version in the meanwhile as it needs some troubleshooting. I recommend you skip Sentinel-2 for the time being (there is L7, L8 and L9 currently in orbit providing good temporal depth).

**Comment by kvos** [comment]
when I run your site for these dates it works fine:
![image](https://user-images.githubusercontent.com/7217258/193183957-eb69a934-d108-482b-8849-e833e0e2268f.png)

when I run the initial date 2015-08-02 though there are a lot of duplicates (more than 4 so it fails). I will fix that shortly and you can test it again.

**Comment by kvos** [comment]
ok I think it's fixed! try the latest version and let me know if it processes everything.
![2015-08-02-10-49-03_S2](https://user-images.githubusercontent.com/7217258/193185539-355dd722-0e88-4bf9-802c-839956e74846.jpg)

**Comment by Aghnar2010** [comment]
It's fine for me, it works perfectly as before.
Thank you for your quick solution.
