### ISSUE TITLE
csv file question

### ISSUE THREAD

**Issue by juni666666** [kvos/CoastSat#332]
how do we get the csv file required here ? i have downloaded the tide model from fes2014 and used in coast sat slope master
![kvos coastsat qs](https://user-images.githubusercontent.com/113264536/192849874-32c8f9cf-1b00-4134-a145-4f9ccee55bd9.jpg)

**Comment by kvos** [comment]
I don't think there is code to write the csv file but you can get the time-series from the CoastSat.slope functions and then just google how to write a pandas.Dataframe into a csv file

**Comment by juni666666** [comment]
please explain to me how will i get the time series a soft copy i am getting only visual representation
