### ISSUE TITLE
Images downloading error: get_metadata function

### ISSUE THREAD

**Issue by MarcosTomasi** [kvos/CoastSat#335]
Hello,

Since I did the 2022/05/02 updates, I am having problems to execute the code. I think i done the update in the right way. My problem comes from in the images downloading process. This is the log i am getting:

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
Cell In [3], line 2
      1 # inputs['include_T2'] = True
----> 2 metadata = **SDS_download.retrieve_images(inputs)**

File D:\DDocumentos\RiscPorts\CoastSat\CoastSat-master\coastsat\SDS_download.py:374, in retrieve_images(inputs)
    371     print('')
    373 # once all images have been downloaded, load metadata from .txt files
--> 374 metadata = **get_metadata(inputs)**
    375 # merge overlapping images (necessary only if the polygon is at the boundary of an image)
    376 if 'S2' in metadata.keys():

File D:\DDocumentos\RiscPorts\CoastSat\CoastSat-master\coastsat\SDS_download.py:433, in get_metadata(inputs)
    429 for im_meta in filenames_meta:
    430     # read them and extract the metadata info: filename, georeferencing accuracy
    431     # epsg code and date
    432     with open(os.path.join(filepath_meta, im_meta), 'r') as f:
--> 433         filename = **f.readline().split('\t')[1].replace('\n','')**
    434         acc_georef = float(f.readline().split('\t')[1].replace('\n',''))
    435         epsg = int(f.readline().split('\t')[1].replace('\n',''))

IndexError: list index out of range

---------------------------------------------------------------------------

Do you have a clue how to fix it?

Thank you for your attention.

**Comment by kvos** [comment]
can you pls send your code so I can recreate the issue?

**Comment by MarcosTomasi** [comment]
Sure!
I am usig the example that is wrote on the github as base, so there no big changes. I did no changes any thing in the functions, just the infos in the first chunk.

```
%load_ext autoreload
%autoreload 2
import os
import numpy as np
import pickle
import warnings
warnings.filterwarnings("ignore")
import matplotlib
matplotlib.use('Qt5Agg')
import matplotlib.pyplot as plt
from matplotlib import gridspec
plt.ion()
import pandas as pd
from datetime import datetime
from coastsat import SDS_download, SDS_preprocess, SDS_shoreline, SDS_tools, SDS_transects
```

```
polygon = [[
            [-48.50197792053223,-27.758025947422095],
            [-48.49418878555298,-27.758025947422095],
            [-48.49418878555298,-27.750297404566336],
            [-48.50197792053223,-27.750297404566336],
            [-48.50197792053223,-27.758025947422095]
          ]]
polygon = SDS_tools.smallest_rectangle(polygon)
dates = ['1984-01-01', '2022-09-01']
sat_list = ['L5','L7','L8','L9']
collection = 'C02'
sitename = 'Rafaela_Ruassa'
filepath = os.path.join(os.getcwd(), 'data')
inputs = {'polygon': polygon, 'dates': dates, 'sat_list': sat_list, 'sitename': sitename, 'filepath':filepath,
         'landsat_collection': collection}

SDS_download.check_images_available(inputs);
```
Then is printed the following

Number of images available between 1984-01-01 and 2022-09-01:
- In Landsat Tier 1 & Sentinel-2 Level-1C:
     L5: 437 images
     L7: 693 images
     L8: 277 images
     L9: 22 images
  Total to download: 1429 images
- In Landsat Tier 2 (not suitable for time-series analysis):
     L5: 105 images
     L7: 116 images
     L8: 73 images
  Total Tier 2: 294 images

Downloading images:
L5: 437 images
100%
L7: 693 images
97%
Download failed, trying again...
100%
L8: 277 images
100%
L9: 22 images
100%
`

Then I recieve the mensage error. Note that: 
''L7: 693 images
97%
Download failed, trying again...''
I tried a couple of time to re-download and I recieve the same error.

**Comment by kvos** [comment]
ok it seems like the downloads went fine but it's not able to retrieve the metadata...I will try your example and let you know how it goes. Have you tried with collection one? does the same error pop up?

**Comment by MarcosTomasi** [comment]
No, I didn't try with collection one

**Comment by MarcosTomasi** [comment]
All rigth, but when i saied "I think i done the update in the right way", means that i deleted and re-downloaded everything some times. But i'll try it again and feedback you.

**Comment by MarcosTomasi** [comment]
Feedback:
I had to delete and re-create the env to make the program work again. Thanks for your atention.

**Comment by MarcosTomasi** [comment]
The error had show up again. The solution above worked just in the first test.

**Comment by MarcosTomasi** [comment]
ok, fiz tudo de novo: criei um novo env, em outro diretório e fiz alguns testes. Aparentemente esse erro foi corrigido. Mas agora tenho outro:

**Comment by MarcosTomasi** [comment]
i just quit from windows
