### ISSUE TITLE
Could not get the tidally-corrected time-series changes with old version Coastsat code

### ISSUE THREAD

**Issue by wilsonsa1129** [kvos/CoastSat#336]
Hi Kilian, 

I am still using the old version of Coastsat code to get beach slop and tide information from the FES2014 tide model. I could get the beach slop value. However, when I worked on the last step, which got the tidally-corrected time-series changes. I keep getting error on it. Are there any problems with the code, or am just I saving in the wrong space? Moreover, I accidentally deleted the code for store the tidally-corrected time-series in a .csv file since it said "setting" is not defined. Thanks for your kind assistance. 

Best Regards,
Wilson Sahmet 

![image](https://user-images.githubusercontent.com/115060761/193985745-53565a53-e03c-4184-8a13-31953e453c03.png)

New update:
Here is my code for the whole tide correction section.
![image](https://user-images.githubusercontent.com/115060761/193994639-b0ff381f-9ced-4911-8573-bfddaa462233.png)
![image](https://user-images.githubusercontent.com/115060761/193994728-da34a3c0-5235-4fc7-ab24-7cc48f7f7333.png)
![image](https://user-images.githubusercontent.com/115060761/193994766-1aeaa8c1-46b3-4c0b-aa17-0ca990f4e786.png)
![image](https://user-images.githubusercontent.com/115060761/193994812-cf385b35-1dc5-49fd-9190-332bc369ee51.png)
![image](https://user-images.githubusercontent.com/115060761/193994853-88008d6e-85ea-4bcd-bdb3-488f6357d241.png)
![image](https://user-images.githubusercontent.com/115060761/193994894-5ef77765-18b0-46e2-b60f-b374be244960.png)
![image](https://user-images.githubusercontent.com/115060761/193994983-44d83b79-33aa-4522-8b28-6b0563928f84.png)

**Comment by wilsonsa1129** [comment]
Here is my code for the whole tide correction section.
![image](https://user-images.githubusercontent.com/115060761/193994639-b0ff381f-9ced-4911-8573-bfddaa462233.png)
![image](https://user-images.githubusercontent.com/115060761/193994728-da34a3c0-5235-4fc7-ab24-7cc48f7f7333.png)
![image](https://user-images.githubusercontent.com/115060761/193994766-1aeaa8c1-46b3-4c0b-aa17-0ca990f4e786.png)
![image](https://user-images.githubusercontent.com/115060761/193994812-cf385b35-1dc5-49fd-9190-332bc369ee51.png)
![image](https://user-images.githubusercontent.com/115060761/193994853-88008d6e-85ea-4bcd-bdb3-488f6357d241.png)
![image](https://user-images.githubusercontent.com/115060761/193994894-5ef77765-18b0-46e2-b60f-b374be244960.png)
![image](https://user-images.githubusercontent.com/115060761/193994983-44d83b79-33aa-4522-8b28-6b0563928f84.png)

**Comment by kvos** [comment]
hi @wilsonsa1129 , not sure why the shape of output['dates'] and cross_distance[key] do not match...they should match if you have processed the same output into cross_distance. Did you manage to fix this problem?

**Comment by wilsonsa1129** [comment]
Yes, I have fixed it, thanks, Killian.
