### ISSUE TITLE
Gdal geopandas version compatibility

### ISSUE THREAD

**Issue by Imanflow** [kvos/CoastSat#347]
First of all I'm sorry to open this issue again, I seen all the already closed issues already, and tried all the solutions, but still it did not work for me. 

But there is something that puzzles me:

In all answers, when talking about installing, no version of geopandas is given. The only place where I've seen a version mentioned is about gdal, and is version 2.3.3.

Nowadays installing geopandas 0.12 comes with gdal 3.5.3. 

Is needed the 2.3.3 version specifically needed?

**Comment by kvos** [comment]
hi @Imanflow , can you let anaconda decide the best version for gdal, geopandas etc? it will do this automatically when you do not specify a version

**Comment by Imanflow** [comment]
Hi @kvos. Yes, I let it download the latest. Funny enough, instead of using example.py I tried the jupyter notebook, using the exact same conda environment, and now it works. So there is something very fishy there, that I can't really understand.

**Comment by kvos** [comment]
what IDE were you using to run example.py?
