### ISSUE TITLE
Earth engine

### ISSUE THREAD

**Issue by JeromeCuroy** [kvos/CoastSat#35]
Hi,
I am trying to run your script but I seem to be stuck on earthengine authenticate , it says it is not recognised as an internal or external command. I m not an experienced programmer I am just ok at following instructions when they are very detailled. Any idea why I cannot link ee to anaconda please?
Thank you
Jerome

**Comment by kvos** [comment]
@JeromeCuroy  can you please share a screenshot of the error? 
Are you on the Anaconda Prompt (not Anaconda PowerShell Prompt)? did you activate the **coastsat** environment with `conda activate coastsat`?

**Comment by SBFRF** [comment]
@JeromeCuroy is this similar to issue #33

**Comment by JeromeCuroy** [comment]
Hi,
Sorry my bad, I just did not realise that google API was not a default plugin when installing anaconda.
Thank you for your prompt reply
Jerome

**Comment by kvos** [comment]
ok, let me know if you were able to run the example jupyter notebook so I can close this issue. 
cheers, Kilian

**Comment by JeromeCuroy** [comment]
Hi Kilian,
Yes I was able to run the example. It’s just my computer that is a bit of a slug.
If I have a bit of an input, there is a maximum of plot points when you do the curvature that you might want to warn people about. At least that is a message I got when I was trying it out on a very long and sinuous beach.
Thank you

**Comment by kvos** [comment]
Oh yes you are right, there is a limit of 50'000 points that you can click for the reference shoreline, I'll increase this for the next update, cheers

**Comment by JeromeCuroy** [comment]
Hi Kilian,
Sorry, I am not a programmer and know nothing about programming or python. I definitely did not input 50 000 points but the script stopped and I thought is was saying that I drew too many points. I am just trying to find an easy way to digitize about 400km of shoreline from the 90s to nowadays that would not involve me doing it by “hand” on arcmap.
Again, I am sorry for my inexperience.
Jerome

**Comment by kvos** [comment]
no worries @JeromeCuroy , this forum is to ask questions, there's no bad questions. When clicking the reference shoreline, if you click on the scroll wheel or any key it will stop, maybe this could have happened. If you are planning to do 400km of coastline with CoastSat, I would suggest that you break it down in smaller polygons (<100km^2), as otherwise processing such large images will be extremely slow.

**Comment by JeromeCuroy** [comment]
Thank you for the advice Kilian.
