### ISSUE TITLE
Update example files with new geopandas CRS definition

### ISSUE THREAD

**Issue by Imanflow** [kvos/CoastSat#350]
In the example code, this line `gdf.crs = {'init':'epsg:'+str(settings['output_epsg'])}` does not store properly the crs. The correct way is nowadays:

```
from pyproj import CRS
gdf.crs =  CRS(settings['output_epsg'])# set layer projection
```

**Comment by kvos** [comment]
good point, that was the old geopandas/pyproj I guess. I'll make this change when I have time, or if you want you can also submit a Pull Request and I will approve it, thanks
