### ISSUE TITLE
Problem about tidal correction along each transect

### ISSUE THREAD

**Issue by PattrakornMinn** [kvos/CoastSat#351]
Hi kvos,

Thank you so much for this model.
I am trying to use it in my project and I have some problem with the tidal correction in each transect.
The problem is when I run the code :

# tidal correction along each transect
reference_elevation = 0 # elevation at which you would like the shoreline time-series to be
beach_slope = 0.13 
cross_distance_tidally_corrected = {}
for key in cross_distance.keys():
    correction = (tides_sat-reference_elevation)/beach_slope
    cross_distance_tidally_corrected[key] = cross_distance[key] + correction
    
# store the tidally-corrected time-series in a .csv file
out_dict = dict([])
out_dict['dates'] = dates_sat
for key in cross_distance_tidally_corrected.keys():
    out_dict[key] = cross_distance_tidally_corrected[key]
df = pd.DataFrame(out_dict)
fn = os.path.join(settings['inputs']['filepath'],settings['inputs']['sitename'],
                  'transect_time_series_tidally_corrected.csv')
df.to_csv(fn, sep=',')
print('Tidally-corrected time-series of the shoreline change along the transects saved as:\n%s'%fn)

# plot the time-series of shoreline change (both raw and tidally-corrected)
fig = plt.figure(figsize=[15,8], tight_layout=True)
gs = gridspec.GridSpec(len(cross_distance),1)
gs.update(left=0.05, right=0.95, bottom=0.05, top=0.95, hspace=0.05)
for i,key in enumerate(cross_distance.keys()):
    if np.all(np.isnan(cross_distance[key])):
        continue
    ax = fig.add_subplot(gs[i,0])
    ax.grid(linestyle=':', color='0.5')
    ax.set_ylim([-50,50])
    ax.plot(output['dates'], cross_distance[key]- np.nanmedian(cross_distance[key]), '-o', ms=6, mfc='w', label='raw')
    ax.plot(output['dates'], cross_distance_tidally_corrected[key]- np.nanmedian(cross_distance[key]), '-o', ms=6, mfc='w', label='tidally-corrected')
    ax.set_ylabel('distance [m]', fontsize=12)
    ax.text(0.5,0.95, key, bbox=dict(boxstyle="square", ec='k',fc='w'), ha='center',
            va='top', transform=ax.transAxes, fontsize=14)
ax.legend();

The error message is about:
---------------------------------------------------------------------------
UFuncTypeError                            Traceback (most recent call last)
Cell In [38], line 6
      4 cross_distance_tidally_corrected = {}
      5 for key in cross_distance.keys():
----> 6     correction = (tides_sat-reference_elevation)/beach_slope
      7     cross_distance_tidally_corrected[key] = cross_distance[key] + correction
      9 # store the tidally-corrected time-series in a .csv file

UFuncTypeError: ufunc 'subtract' did not contain a loop with signature matching types (dtype('<U5'), dtype('int32')) -> None

Do you have any ideas that why it is not working?
I have already got the tide level at the data times by using the hourly tide data from the tidal gauge near the study area.

Thank you so much

**Comment by kvos** [comment]
check the format of tides_sat, it should be a numpy.array

**Comment by kvos** [comment]
you need to check if it's an array or not
