### ISSUE TITLE
Tidal data correction

### ISSUE THREAD

**Issue by JPPereira93** [kvos/CoastSat#353]
Hello!

I've been using the coastsat toolkit (which is amazing tbh), and I wanted to do tidal waves corrections in my AOI. 

[[[[56.3622607818], 25.0285846976],[[56.3723029723],25.0285846976],[[56.3723029723],25.0427793001],[[56.3622607818], 25.0427793001],[[56.3622607818],25.0285846976]]] Kalba Beach (United Arabe Emirates)

![image](https://user-images.githubusercontent.com/90710707/203110726-b084e378-8525-4427-a0c8-19a8790aba29.png)

However, I can't find relevant data for my dataset, I've encountered this portal (https://psmsl.org/data/obtaining/map.html#plotTab) which has some, but around 2019, for my region, it doesn't have any data.

Any idea how I can get more information? Thank you!

**Comment by kvos** [comment]
if you're AOI has a very small tidal range and low wave energy, you may try first without tidal/wave correction.
In absence of in situ data, you will need to use global products, for tides you can use FES2014, I've written a tutorial on how to install it in CoastSat.slope: https://github.com/kvos/CoastSat.slope/blob/master/doc/FES2014_installation.md
For waves I would recommend ERA5 reanalysis dataset from ECMWF, find the closest grid point and download the 3-hourly data.
All the best, Kilian
