### ISSUE TITLE
Earthengine Authenticate Error

### ISSUE THREAD

**Issue by LucyV13** [kvos/CoastSat#355]
I have been trying to install coastsat following the instructions given. I have created an environment and been given access to google earth engine but when I go to authenticate the earth engine, this error occcurs:
![CoastSat Error 2](https://user-images.githubusercontent.com/119439437/204592142-494ca40e-09f7-4913-bb30-4d5d3ff77f63.PNG)

I then downloaded gcloud through the link suggested on here, and it installed 'Google Cloud SDK Shell'
![Coast Sat Error 4](https://user-images.githubusercontent.com/119439437/204593275-3be7623f-7502-4940-b11c-6b9efb08a48c.PNG) but when I retry authenticating earth engine it still doesn't work.

Does anyone have any suggestions to help me? Thank you!!

**Comment by JPPereira93** [comment]
try 

https://github.com/kvos/CoastSat/issues/354

https://github.com/kvos/CoastSat/issues/348

**Comment by LucyV13** [comment]
This worked, thank you so much!

**Comment by kvos** [comment]
the command proposed as a solution in #354 has been added to the documentation and should fix this issue in the future
