### ISSUE TITLE
SDS_Download Intermittent Key Error

### ISSUE THREAD

**Issue by NO645** [kvos/CoastSat#356]
On some downloads, but not all, I am getting a key error for the S2 images:

```
Downloading images:
L5: 0 images

L8: 276 images
100%
S2: 488 images
5%Traceback (most recent call last):

  File "C:\Users\RDCHLNRO\AppData\Local\Temp\1\ipykernel_21560\385949588.py", line 52, in <cell line: 13>
    metadata = SDS_download.retrieve_images(inputs) # retrives the satellite images from Google Earth Engine

  File "C:\Users\RDCHLNRO\AppData\Local\Continuum\anaconda3\envs\coastsat11152022\lib\site-packages\coastsat\SDS_download.py", line 168, in retrieve_images
    im_quality.append(im_meta['properties']['RADIOMETRIC_QUALITY'])

KeyError: 'RADIOMETRIC_QUALITY'
```
This is using coastsat v2, updated on 11/15/22.

It seems the error occurs when asking for more than a few years back in time. My polygon and dates were:

```
[[[-75.88742210674313, 44.42448173297042],
  [-75.8644394655225, 44.405199663513955],
  [-75.89153144550296, 44.37290825116044],
  [-75.9145140867236, 44.392190320616905],
  [-75.88742210674313, 44.42448173297042]]]
 ['2012-01-01', '2022-02-07']

```

Let me know if any other information would help! Thank you!

**Comment by kvos** [comment]
hi @NO645 , will check it out, I think I know what it is since I just recently added the RADIOMETRIC_QUALITY to the metadata, will let you know soon (in the meanwhile you can revert to a previous version before the RADIOMETRIC_QUALITY was added, check the commit names)

**Comment by kvos** [comment]
this has been fixed, thanks for reporting the bug.

**Comment by NO645** [comment]
Just wanted to say thanks for looking at this, I was away when you responded.
