### ISSUE TITLE
problem with SDS_download.py

### ISSUE THREAD

**Issue by Phuongtran75** [kvos/CoastSat#357]
Dear Kovs
I run it but having problem. I find this file, but it still doesn't have the expected result

 
![image](https://user-images.githubusercontent.com/118723548/208600711-eb903dc5-1dd9-4639-827c-ddf2f5858385.png)
![image](https://user-images.githubusercontent.com/118723548/208600742-0de49f4c-1abc-49ee-b23b-76ff267ad600.png)
![image](https://user-images.githubusercontent.com/118723548/208600787-d15d36c8-592e-4717-8e5d-36f76a781c1f.png)
![image](https://user-images.githubusercontent.com/118723548/208600847-4f4cadf6-41ee-44be-940f-82ccfea20262.png)
![image](https://user-images.githubusercontent.com/118723548/208600884-7d5dae9d-a509-411b-8583-f2afb4f48691.png)

**Comment by kvos** [comment]
did you do `earthengine authenticate`? it's not initialising your GEE session properly.

**Comment by Phuongtran75** [comment]
Yes, I did earthengine authenticate but I don't know why I don't know why it's not register yet

![image](https://user-images.githubusercontent.com/118723548/208776062-11e37a88-1c0c-4012-aa98-9decc8f3918f.png)

**Comment by kvos** [comment]
it seems like it's all good now, I will close the issue (reopen if still some issues)
