### ISSUE TITLE
Error while running: from coastsat import based commands

### ISSUE THREAD

**Issue by gchaithali** [kvos/CoastSat#358]
We tried installing the environment for using Coastsat; however, we are facing an error inspite of successful previous steps while running the following command:
from coastsat import SDS_download, SDS_preprocess, SDS_shoreline, SDS_tools, SDS_transects

The error reads:"No module named coastsat".

**Comment by kvos** [comment]
hi, are you using Jupyter notebook? make sure that you first navigate to the working folder (above the \coastsat folder) and then try again
