### ISSUE TITLE
Issue with SDS_shoreline.extract_shorelines 

### ISSUE THREAD

**Issue by kcoastal1** [kvos/CoastSat#36]
Hi,

After downloading the master version for Coastsat on my Mac, I appear to be having issues with running the `SDS_shoreline.extract_shorelines` routine in example workbook. 

When I run the routine a new window with three figures opens up. But nothing happens when I click on either `keep` or `skip`. In the jupiter notebook it says the shoreline analysis has reached 14%. Im also prompted with the following message any time I try to click the skip or keep buttons in the picture: `QTimer::singleShot: Timers cannot have negative timeouts`. The window will close if I press escape though.

See screenshots below. 

I have also tried this on my Windows computer and get stuck on the same bit which makes me think that there might be an issue with the `SDS_shoreline.extract_shorelines` routine. 

Would  be grateful for any ideas. 

![Screenshot 2019-10-06 at 22 34 07](https://user-images.githubusercontent.com/31092385/66276464-52dfaf00-e88b-11e9-9004-3d1bcd738bf5.png)
![Screenshot 2019-10-06 at 22 34 17](https://user-images.githubusercontent.com/31092385/66276465-52dfaf00-e88b-11e9-8a16-2648cc272056.png)
![Screenshot 2019-10-06 at 22 34 35](https://user-images.githubusercontent.com/31092385/66276466-52dfaf00-e88b-11e9-999f-8e5a6d98be87.png)

**Comment by kvos** [comment]
Hey @kcoastal1, you have to use the keyboard arrows instead of clicking on keep/skip, so right arrow for keep and left arrow for skip

**Comment by kcoastal1** [comment]
Hi Kvos, thanks for the quick response. I must admit I feel a little stupid now! 

I do have another question but I'll open another issue as its not related to this.

**Comment by SBFRF** [comment]
@kvos  this is helpful, i ran into the same problem, may i suggest providing directions on the plot dialogue screen? or if you tell me where that plot is generated, i can create a pull request
