### ISSUE TITLE
Meaning of geoaccurac?

### ISSUE THREAD

**Issue by GBevelio** [kvos/CoastSat#360]
Sir, May I know the exact meaning of the 'geoaccurac' field within the generated output coastlines.
Your kind help is very much appreciated.
Thanks & Regards
Bevelio Goes

**Comment by kvos** [comment]
hi @GBevelio , it is the georeferencing accuracy of the each from which the shoreline was mapped. For Landsat images it's the RMSE computed by NASA/USGS with ground control points on the image. For Sentinel-2 it's only a flat (1 = passed, -1 = failed), where the threshold to pass is RMSE < 20 m.

**Comment by GBevelio** [comment]
Thanks a lot Sir for your kind help.
