### ISSUE TITLE
boolean index did not match indexed array along dimension 0; dimension is 139 but corresponding boolean dimension is 141

### ISSUE THREAD

**Issue by Phuongtran75** [kvos/CoastSat#361]
Hi, I have the new issue about Despiking the time-series

My issuse:
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
Input In [49], in <cell line: 6>()
      1 # remove outliers in the time-series (coastal despiking)
      2 settings_outliers = {'max_cross_change':   100,             # maximum cross-shore change observable between consecutive timesteps
      3                      'otsu_threshold':     [-.5,0],        # min and max intensity threshold use for contouring the shoreline
      4                      'plot_fig':           True,           # whether to plot the intermediate steps
      5                     }
----> 6 cross_distance = SDS_transects.reject_outliers(cross_distance,output,settings_outliers)

File ~\Documents\Phuong\research\3\CoastSat-master\coastsat\SDS_transects.py:451, in reject_outliers(cross_distance, output, settings)
    449 idx_kept = []
    450 for date in output['dates']: idx_kept.append(date in dates3)
--> 451 chainage[~np.array(idx_kept)] = np.nan
    452 # store in chain_dict
    453 chain_dict[key] = chainage

IndexError: boolean index did not match indexed array along dimension 0; dimension is 139 but corresponding boolean dimension is 141

Can you help me explain?

**Comment by kvos** [comment]
ok it seems like the arrays are not the same size. can you provide your variables so I can check what's going on?

**Comment by Phuongtran75** [comment]
Thank you very much, I finished it.

**Comment by billskyy** [comment]
> Thank you very much, I finished it.

Heloo can you show me how you finished this problem cuz i got the same problem and i still cant figure it out
Thank you

**Comment by Phuongtran75** [comment]
Hi. In my case, it is the different data size because a number has been
typed by removing duplicates and images with incorrect georeferencing.
Therefore, I found the removed images and times in transect_time_series
and transect_time_series_tidally_corrected excel. After that I add a blank
row between the lost data and run it again.

Thanks.

[image: image.png]
---------------------------------------------------------------------
Trần Thị Hoài Phương

*Division of **Information and Data *
*Disaster Management Policy and Technology Center*
*Vietnam Disaster Management Authority*

*No 54 Lane 102 Truong Chinh str., Dong Da dist., Hanoi*

*Mobile: +84 (0) 989297570*
*E-mail: ***@***.*** ***@***.***>*


Vào Th 4, 22 thg 2, 2023 vào lúc 16:11 billskyy ***@***.***>
đã viết:

**Comment by billskyy** [comment]
hello thanks for your help but after i did that way, there is another error in monthly and seasonal average, the graph is not showing did you meet the same problem? if yes how do you solve it?
Thank you so much
