### ISSUE TITLE
EPSG CODE CHANGE ERROR

### ISSUE THREAD

**Issue by juni666666** [kvos/CoastSat#362]
I try to change my output epsg code to 4326 but it gives me the error "output does not contain any mapped shorelines, however shorelines are mapped.
![image](https://user-images.githubusercontent.com/113264536/212871587-796f9dd2-47ba-4c39-959e-919c85941996.png)

**Comment by kvos** [comment]
yes you cannot use a spherical coordinate system (lat/lon), only use projected coordinate systems (eastings/northings)!
