### ISSUE TITLE
Satellite images smaller than user-defined extraction polygon

### ISSUE THREAD

**Issue by simonweppe** [kvos/CoastSat#363]
Hi there, 
Thanks a lot for your work.

Im trying to download some S2 imagery for a given area, and get only a small part of the extraction polygon I defined.
Is this simply due to imagery availability (i.e. not available for a part of the polygon)  ?

**Comment by simonweppe** [comment]
More context @kvos 
- area is definitely smaller than 100km2
- extraction works well when using the polygon in the example, and some other places too. 

I'll try to dig in the code to see what could happen. Thanks

**Comment by kvos** [comment]
hi @simonweppe , can you show me how the image looks like? it could be that your ROI is at the edge of an S2 tile. You can download the kml with the S2 tiles here https://sentinel.esa.int/web/sentinel/missions/sentinel-2/data-products and check.

**Comment by simonweppe** [comment]
Thanks Killlian !
Indeed ! my ROI goes a bit  beyond 59GLJ (to the west), but it's also fully included in one (58GGP).

![Screenshot from 2023-01-18 21-25-59](https://user-images.githubusercontent.com/7277011/213289071-ad37f10c-bca9-4e56-803b-5b1788606af7.png)
![Screenshot from 2023-01-18 21-25-35](https://user-images.githubusercontent.com/7277011/213289078-8dd59ad8-e1d4-44b1-ae42-08f9f9218251.png)



Extracted image looks like this - cropped about when the tile stops.

![2022-03-02-22-39-12_RGB_S2](https://user-images.githubusercontent.com/7277011/213288066-630087ae-b13c-4e66-87b0-7bfa6ce2af95.jpg)

Can I try to manually specify which tile to use ?

**Comment by kvos** [comment]
hi simon, great that you found a workaround to get the right tile. I used to have a function to merge overlapping S2 tiles to have a full ROI at the boundary (with gdal_merge) but it had a lot of bugs and was causing a lot of errors as it couldn't resolve all the possible cases of overlaps. If you can make your hack more generic (making it an input parameter to specify the S2 tile manually) that would be great, then you can make a pull request and I will test it and approve it, thanks!

**Comment by kvos** [comment]
#366
