### ISSUE TITLE
extract_shoreline

### ISSUE THREAD

**Issue by Mtanishita** [kvos/CoastSat#364]
I am a new user of Anaconda3 and jupyter notebook.

example_jupyter.ipynb 

%matplotlib qt
output = SDS_shoreline.extract_shorelines(metadata, settings)

AttributeError: module 'importlib.resources' has no attribute 'files'

Should I change to importlib-resources ?

My environments are as follows.
importlib-resources 5.2, 
pillow=6.2.2 and python 3.8.

**Comment by Mtanishita** [comment]
I renewed [SDS_shoreline.py] file today(19JAN2023). Then new error occurred. 

FileNotFoundError: [Errno 2] No such file or directory:

In my computer, there is no directory named '\\classification\\models'.
What is the problem? - PATH setting or os.path?

**Comment by kvos** [comment]
the environment looks good. Did you open the jupyter notebook in the directory when you have downloaded coastsat?

**Comment by Mtanishita** [comment]
I re-installed anaconda3 again. Then not coastsat, but  another os error occurred.

>conda info --envs
# conda environments:
#
base                  *  C:\Users\Masayoshi Tanishita\anaconda3
coastsat                 C:\Users\Masayoshi Tanishita\anaconda3\envs\coastsat

>conda activate coastsat
The system can not find the specified path.
C:\Users\Masayoshi Tanishita>set "GDAL_DRIVER_PATH="
C:\Users\Masayoshi Tanishita>rem proj-data is installed because its license was copied over

I realized that due to this path error, I could not install any other packages in anaconda prompt.
So I checked my environment and confirmed the following path is set.
%USERPROFILE%\Anaconda3\scripts

Should I unistall anaconda3 again?  Thank you in advance.

**Comment by Mtanishita** [comment]
I re-installed anaconda3 again. I found that I intentionally downgraded pillow=6.2.2, then the previous "GDAL_DRIVER_PATH" error message showed up. SO, I just follow your guidance.  
Then new trouble occurred when check_detection.
A figure appears, however,  "the right arrow (⇨) to keep the shoreline or left arrow (⇦) to skip" does not work(nothing change when clicking an arrow), only <esc> works well. 
7 files are stored in my data folder. How should I do?

**Comment by Mtanishita** [comment]
Sorry, not click on the figure, but I should press arrows on my keyboard!

**Comment by kvos** [comment]
I believe this one is solved
