### ISSUE TITLE
Inlettracker-Earth Engine Authentication issue 

### ISSUE THREAD

**Issue by Jeffysj** [kvos/CoastSat#367]
Access blocked-Authorization error is throwing up while authenticating earth engine in inlettracker. Tried updating earthengine-api still not working.

**Comment by reshmarechu16** [comment]
Yeah. Even I also tried installing inlet tracker. The same issue popped up.

**Comment by kvos** [comment]
hi all, I think InletTracker is not being maintained any more. You can try to install the environment using the coastsat instructions and then run it from there

**Comment by reshmarechu16** [comment]
Thank you! 
Coastsat and inlet tracker was successfully installed. But, when I am running th
![Capture](https://user-images.githubusercontent.com/123159444/216307363-04acd9a1-4aef-4438-af30-6b7d9a96a9b8.JPG)
e example file from coastsat, proxy error is coming.

**Comment by kvos** [comment]
I am not sure about this one, can you check what version of earthengine-api you have installed?

**Comment by kvos** [comment]
ok please post those issues on the inlet tracker github page. I will close this issue
