### ISSUE TITLE
Shoreline not getting drawn in good images

### ISSUE THREAD

**Issue by NO645** [kvos/CoastSat#370]
I am running coastsat over a large number of 3km stretches of shoreline. I've started seeing many cases where the algorithm seems unable to draw a shoreline in an image that appears to be very high-quality:

![WhatHappened](https://user-images.githubusercontent.com/53620309/219495471-afc438b8-cbd7-497f-a423-21fb48911ac6.png)

In this example above the algorithm was not limited by a reference line, and the min beach area was set to zero. I can provide all of the settings if they would help.

If it's of any use I've noticed that this only seems to happen when the land is in the northern portion of the image, and the water in the southern. It almost never happens in the reverse case.

I was hoping you might have some thoughts about what was happening.

Thank you very much!

**Comment by kvos** [comment]
can you try to define a reference shoreline? or a set of reference shorelines for the different sandy bits
