### ISSUE TITLE
Boolean index always didnt match while plot Otsu thresholds for the mapped shorelines

### ISSUE THREAD

**Issue by billskyy** [kvos/CoastSat#372]
Hey thanks for your work
I tried to run cosatsat in different locations and always got the same error and I don't know where the problem is coming from can you help me troubleshoot.
Thank You

![error](https://user-images.githubusercontent.com/125845065/220246191-34e4db19-e2c0-46e5-b068-5ac3dff04937.jpg)

**Comment by kvos** [comment]
can you check the dimensions of cross-shore distance and output['dates']? these must match

**Comment by LucyV13** [comment]
Hi, I am having the same issue. I am being stupid, where are the 'cross-shore distance' and 'output['dates']' in the code as I can't seem to find what needs to match?
Thanks!

**Comment by czarnes22** [comment]
@LucyV13  @kvos Can You explain this issue to me? where  are the cross-shore distance and output[date]? Thanks
