### ISSUE TITLE
merge results

### ISSUE THREAD

**Issue by danielbar206** [kvos/CoastSat#374]
Hi,

if I downloaded  and processed yesterday shorelines for group of images from 2021
ant today I'm doing the same process for 2022, how can I merge the output.pkl files?
to see everything in the same plot
or, how can I append data into it?  
thanks!

**Comment by kvos** [comment]
hi @danielbar206 , you can download the images in different batches but the code will then read them all, so there isn't at the moment a function to merge the output files but you could easily write one (they are dictionaries).
