### ISSUE TITLE
'NoneType' object has no attribute 'GetGeoTransform'

### ISSUE THREAD

**Issue by aamunq** [kvos/CoastSat#376]
hey kvos,
i try to saves .jpg files of the preprocessed satellite images, but i got an error like this :
thanks for your help.
![image](https://user-images.githubusercontent.com/77184091/222586885-b0340981-34f3-4f51-8804-66b2c4b3de7b.png)

**Comment by kvos** [comment]
@aamunq , it means that one of the images could not be read properly
