### ISSUE TITLE
Sentinel-Data will not be retrieved by GEE in a particular ROI, but not other ROI

### ISSUE THREAD

**Issue by tolandwehr** [kvos/CoastSat#377]
I was trying to determine coastline changes from 1984 until 2023-03-03 in the following polygon, which is roughly 50km²

```
[
    [
      [
        0.5843353,
        40.5954643
      ],
      [
        0.5915451,
        40.5404504
      ],
      [
        0.725441,
        40.5547949
      ],
      [
        0.7271576,
        40.6027613
      ],
      [
        0.5843353,
        40.5954643
      ]
    ]
  ]
```
The function to retrieve images will run forever when trying to fetch Sentinel data. `SDS_download.check_images_available(inputs) ` lists Landsat data, but stops when it should reach Sentinel data. Other ROIs nearby or far away do not seem to be affected so far.

Lot of thanks in advance for any idea what is happening and a big thanks already for the Repo as a whole!
Tobias

**Comment by kvos** [comment]
thanks for reporting this @tolandwehr , there are still some issues with the Sentinel 2 tiles, will look into it when I have time.
