### ISSUE TITLE
Download Issues

### ISSUE THREAD

**Issue by LucyV13** [kvos/CoastSat#379]
Hi,

I am trying to download 738 images for my region of interest in the date range 01/01/2000 to 31/12/2022. When I try to download the images, I get to around 10% of the way through and the following error appears. This seems to be an error within the background code? Does anyone have any suggestions of how I can fix this?
![image](https://user-images.githubusercontent.com/119439437/223131168-2f2cf62f-e642-48ce-b843-f608185b1291.png)
![image](https://user-images.githubusercontent.com/119439437/223131297-9133b640-9b48-42f4-be4e-6e83c0ac2f21.png)

Thank you!

**Comment by kvos** [comment]
yes this is an error with the code, can you share your inputs as a txt file and I will run them to troubleshoot, thanks
