### ISSUE TITLE
conda activate versus source activate

### ISSUE THREAD

**Issue by AndresSepulveda** [kvos/CoastSat#38]
In my machine one has to use source activate, not conda activate

  mosa@parti-mosa:~/CoastSat$ conda activate coastsat

  CommandNotFoundError: 'activate is not a conda command.
  Did you mean 'source activate'?

  mosa@parti-mosa:~/CoastSat$ source activate coastsat

  (coastsat) mosa@parti-mosa:~/CoastSat$

**Comment by MOnrust** [comment]
Hi Andres,

Look at this StackOverflow discussion:
[https://stackoverflow.com/questions/49600611/python-anaconda-should-i-use-conda-activate-or-source-activate-in-linux](https://stackoverflow.com/questions/49600611/python-anaconda-should-i-use-conda-activate-or-source-activate-in-linux)

`conda activate` is not incorrect and is preferred over `source activate`

It can give problems however when conda is not in your PATH. I assume that `source activate` might also work.

**Comment by kvos** [comment]
thanks for answering this one @MOnrust!
