### ISSUE TITLE
Unable to tidally-correct data

### ISSUE THREAD

**Issue by LucyV13** [kvos/CoastSat#380]
Hi,

I am trying to tidally-correct my data using a .csv file. My data is within the date range 01/01/2022 and 31/03/2022; this is also the date range of my tidal data. However, when I try to run the code, the following error appears:
![image](https://user-images.githubusercontent.com/119439437/223132010-63885000-55f4-482a-bd8e-292286351295.png)
![image](https://user-images.githubusercontent.com/119439437/223132140-34603d20-7b92-482a-b27c-8442f9d69992.png)

I have tried to change the data range of my tidal data to the exact time range and extended time ranges but nothing seems to work. I have seen some issues on here with similar problems however, they were using tidal models not .csv files. Does anyone have any suggestions how I can make this work?

Thank you!

**Comment by munawirbintang** [comment]
Hi Lucy,
I encountered a similar problem. In my case, my tidal.csv file was incomplete, it did not include the time zome (+00:00).
After adding this to the csv, the error is solved.

Good luck, Munawir

**Comment by LucyV13** [comment]
Hi Munawir,

Thank you for this! It seems to of solved that first issue but it is now returning this error when I run it.
![New Tidal Error](https://user-images.githubusercontent.com/119439437/223177974-49cea49f-37fe-448e-8094-e14ed4c704a5.PNG)

Does anyone have any ideas how to fix this?

Thank you,
Lucy

**Comment by munawirbintang** [comment]
Hi,
Can you share the csv file? I wonder if there is an incorrect format in the file.
To my experience, the format is quite strict.
Cheers,

**Comment by munawirbintang** [comment]
Hi,
I checked the data, I think the format is correct. But at the end (after 2022-12-31), if found lines with only {,}.
I think you can try deleted this and run the script again.

Cheers,

**Comment by LucyV13** [comment]
Hi,
I have gone through and deleted those but unfortunately it is still returning the same error :(

Thank you for your suggestions and help though!

**Comment by kvos** [comment]
hi @LucyV13 just make your dates offset aware by running pytz.utc.localize(datetime)
