### ISSUE TITLE
cloud cover settings

### ISSUE THREAD

**Issue by mkewsds12** [kvos/CoastSat#381]
This is a great project, but how do I set the cloud cover threshold when retrieving images in the first place? It will always retrieve some images with large cloud content, which will affect the follow-up work. I have seen the remove_cloudy_images function, how does this function modify the value in metadata? thank you very much for your help!

**Comment by kvos** [comment]
@mkewsds12 , I think that function remove_cloudy_images has a hardcoded threshold of 0.99 as fully cloudy images were breaking the code, you can go into the code and change it if you like

**Comment by mkewsds12** [comment]
Thanks a lot, I have changed the situation with other settings
