### ISSUE TITLE
Study area is too small

### ISSUE THREAD

**Issue by xiyang712** [kvos/CoastSat#384]
Hi Killian Vos,

Since my research area is relatively small (the area is about 1km×0.5km), there will be mosaics in the image, which makes me unable to distinguish the position of the waterline. May I ask what parameters can be adjusted so that the image does not need to be placed very large, so that I can set it Reference to coastline and next steps?

Regards,
Ruiyang Xu

![屏幕截图 2023-03-10 213739](https://user-images.githubusercontent.com/115886880/224330980-bfc9663c-7285-4f08-bf6c-562a29e4c818.png)

**Comment by kvos** [comment]
you can still draw the reference shoreline on that image no?
