### ISSUE TITLE
Inlettracker issue

### ISSUE THREAD

**Issue by reshmarechu16** [kvos/CoastSat#385]
training datasets are not generating. Only a blank image is popping up.
![Figure_1](https://user-images.githubusercontent.com/123159444/225232167-bc3a60fd-2cc8-43be-b790-12de466a2838.png)

**Comment by kvos** [comment]
not sure what is happening, which function are you calling?

**Comment by reshmarechu16** [comment]
This one..

Training_data_df = InletTracker_tools.create_training_data(metadata,
settings, settings_training)

**Comment by kvos** [comment]
I'm not maintaing inlet tracker, you may want to post in that github repo
