### ISSUE TITLE
How to recover already mapped shorelines?

### ISSUE THREAD

**Issue by LucyV13** [kvos/CoastSat#386]
Hi,

I have detected all of my shorelines and they are located in the output folder as stated in the code. However, when I went to continue my code, my laptop crashed so I had to start CoastSat again, this meant rerunning all my code. 

I get to the 'batch shoreline detection' section and it wants me to complete the shoreline detection process again but I have already completed this. However, without running this I have no 'output' defined in the next section. Please see below.
![Output Error Labelled](https://user-images.githubusercontent.com/119439437/226335600-4e673d1f-fb30-472c-9c5c-28eb6f339a37.png)
Is there a piece of code I can use so the output links to my folder with the shorelines I had detected previously rather than detecting them all again?

Thank you,
Lucy

**Comment by kvos** [comment]
hi @LucyV13 , did you save an output.pkl file? did you save the detection as .jpg files in /detection?
If you have either of those, there is a way to recover it, otherwise I fear it's lost.

**Comment by LucyV13** [comment]
Hi, I have saved as .jpg files in /detection!

**Comment by kvos** [comment]
ok so you need to write a script that matches the dates of the saved jpg files with the filenames in the metadata variables. I may have one somewhere, will look for it. If you're not too experience working in python it may be easier to remap them.

**Comment by LucyV13** [comment]
Hi,

I have used:
filepath = os.path.join(inputs['filepath'],sitename)
with open(os.path.join(filepath,sitename+'_output'+'.pkl'),'rb') as f:
    output=pickle.load(f)

It has seemed to of worked!

**Comment by AfeeraSyakirin** [comment]
> Hi,
> 
> I have used: filepath = os.path.join(inputs['filepath'],sitename) with open(os.path.join(filepath,sitename+'_output'+'.pkl'),'rb') as f: output=pickle.load(f)
> 
> It has seemed to of worked!

Hi, in which code cell did you insert this script? I also experienced in the same issue that I need to map the shoreline over and over again. I have 391 images to map and that's the nightmare of me to map it all over again. :D

**Comment by LucyV13** [comment]
That was the same for me! 

I replaced:
%matplotlib qt
output = SDS_shoreline.extract_shorelines(metadata, settings)

with the above code and it worked great!
