### ISSUE TITLE
Not able to read transect from .geojson

### ISSUE THREAD

**Issue by MinniAlex** [kvos/CoastSat#388]
Hi There,

I've never been able to get the geojson file transects working have you got any tips for sorting it out please? I've got a bunch of transects that have been converted into geojson in the same projection but i keep getting this error:

![image](https://user-images.githubusercontent.com/128595890/226885859-70cbaa02-a562-4835-87f6-dffef08bff6c.png)

Any tips to get it working please? I have about 80 transects so ideally I'd like to avoid putting them in manually if possible!

thank you !

Alex

**Comment by kvos** [comment]
I think you geojson is a multi-linestring, while that function was written to read a bunch of linestrings (which are different). You need to modify the function to read the multi-linestring or modify the geojson file to have separate linestring entries
