### ISSUE TITLE
Time-series of shoreline change along each transect

### ISSUE THREAD

**Issue by AfeeraSyakirin** [kvos/CoastSat#390]
![image](https://user-images.githubusercontent.com/129128758/228729312-b9a3f025-9d51-4554-b2b6-7ac420b07318.png)

Hi!

I have issue with the plot of time-series of shoreline change along each transect here as shown above. I have plot 6 transects but when I want to plot it, only 1 plot appears and the other 5 are missing. Can I know what is the cause of this?

**Comment by kvos** [comment]
not sure, you need to adjust the part of the code that makes the plot (with matplotlib) based on your data. The code that is provided is just an example. Good luck.
