### ISSUE TITLE
Issue in installing aviso-fes

### ISSUE THREAD

**Issue by mdsuganya1979** [kvos/CoastSat#391]
Hi,
I am Mary from India working as a scientist in coastal department. I am trying to install [aviso-fes](https://github.com/CNES/aviso-fes). While building and installing cmake, the error prompts as  'cmake' is not recognized as an internal or external command, operable program or batch file. Can anyone please give me a solution for this.

Regards,
Mary

**Comment by kvos** [comment]
You can install it with conda which compiles it for you, check out the instructions here https://github.com/kvos/CoastSat.slope/blob/master/doc/FES2014_installation.md

**Comment by mdsuganya1979** [comment]
Thank you
