### ISSUE TITLE
No cloud free images available

### ISSUE THREAD

**Issue by Phuongtran75** [kvos/CoastSat#392]
Dear Kvos,

When I downloaded the images of L5, L7, L8, S2 from 1984-2014 with 15% cloudy, I got the error as below:
![image](https://user-images.githubusercontent.com/118723548/229438947-2edfa350-4eb5-46d7-95d9-c9d21b2c7819.png)

When I adjusted the cloud coverage gradually from 15 to 50%, this error still appears. Can you tell me how to fix it?
Thank you.

**Comment by kvos** [comment]
can you check how many images were downloaded in each collection? this may tell me more about what the issue could be.

**Comment by Phuongtran75** [comment]
Total images downloaded is 143 images.
![image](https://user-images.githubusercontent.com/118723548/230601993-d9d08d91-a720-4404-bd90-50bc8ffec0b0.png)
