### ISSUE TITLE
Re-training the classifier

### ISSUE THREAD

**Issue by tofivan** [kvos/CoastSat#393]
Hello, I am a beginner and thank you for providing such excellent resources. I recently encountered a problem where I needed to retrain the classifier. How can I make sure that the retrained classifier is being used? Below is the directory where I placed it: C:\CoastSat\CoastSat_master\classification\models.

**Comment by kvos** [comment]
you need to go in the code of SDS_shoreline.py and change the location where the classifier is loaded

**Comment by tofivan** [comment]
Hi kvos, thank you for your response. I will try to update the training data.
