### ISSUE TITLE
Can not identify coastline

### ISSUE THREAD

**Issue by Yibing-1** [kvos/CoastSat#395]
Hey thanks for your work
I tried to run cosatsat in different locations and always got the same error and I don't know where the problem is coming from can you help me troubleshoot.All my steps have followed your steps, and I have also done reference shoreline . However, the situation below will appear in mine, and the coastline cannot appear.It can only identify sand,white-water,water.
Thank You
![1325c4422fc20e3ad3218cb8d9da235](https://user-images.githubusercontent.com/128706812/232949449-add2118f-3166-4679-85f0-f356b7b7858b.png)

![12173f0e58f6910f683373669a5c86a](https://user-images.githubusercontent.com/128706812/232949415-db164cb0-67c6-458f-8c52-9ad0b971e143.png)

**Comment by kvos** [comment]
can you share all your inputs so I can have a look at what may be going wrong?
