### ISSUE TITLE
geojson export

### ISSUE THREAD

**Issue by mkewsds12** [kvos/CoastSat#398]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[18], line 3
      1 from pyproj import CRS
      2 geomtype = 'lines' 
----> 3 gdf = SDS_tools.output_to_gdf(output, geomtype)
      4 if gdf is None:
      5     raise Exception("output does not contain any mapped shorelines")

File E:\CoastSat-master\CoastSat-master\coastsat\SDS_tools.py:713, in output_to_gdf(output, geomtype)
    711             gdf_all = gdf
    712         else:
--> 713             gdf_all = gdf_all.append(gdf)
    714         counter = counter + 1
    716 return gdf_all

File D:\Anaconda3\envs\coastsat\lib\site-packages\pandas\core\generic.py:5989, in NDFrame.__getattr__(self, name)
   5982 if (
   5983     name not in self._internal_names_set
   5984     and name not in self._metadata
   5985     and name not in self._accessors
   5986     and self._info_axis._can_hold_identifiers_and_holds_name(name)
   5987 ):
   5988     return self[name]
-> 5989 return object.__getattribute__(self, name)

AttributeError: 'GeoDataFrame' object has no attribute 'append'

The exported data includes Landsat 8 and Sentinel 2.

**Comment by lexterspiritus97** [comment]
MMmmm, hello mkewsds12, I got similar issue, seems to be that, the frame.append was deprecated. You can search in the web.

**Comment by kvos** [comment]
this has been fixed! #400
