### ISSUE TITLE
ortophotos applicability

### ISSUE THREAD

**Issue by siclku** [kvos/CoastSat#399]
Hey, 
First of all, thank you for your work!

Is it possible to import ortophotos/aerial photos to the tool and thereby increase spatial resolution of the data? 
I'm currently investigating morphodynamics in a small scale area with relatively small rates of changes.

Kind Regards

**Comment by kvos** [comment]
hi @siclku , unfortunately it's not possible to use aerial photos into coastsat but a similar method can be applied to RGB imagery, see the repository here https://github.com/ydoherty/CoastSat.PlanetScope . But you will have to adapt it to your input imagery.
