### ISSUE TITLE
Unable to convert GeoJSON

### ISSUE THREAD

**Issue by mkewsds12** [kvos/CoastSat#401]
AttributeError                            Traceback (most recent call last)
Cell In[27], line 3
      1 from pyproj import CRS
      2 geomtype = 'lines' 
----> 3 gdf = SDS_tools.output_to_gdf(output, geomtype)
      4 if gdf is None:
      5     raise Exception("output does not contain any mapped shorelines")

File E:\CoastSat-master\CoastSat-master\coastsat\SDS_tools.py:713, in output_to_gdf(output, geomtype)
    711             gdf_all = gdf
    712         else:
--> 713             gdf_all = gdf_all.append(gdf)
    714         counter = counter + 1
    716 return gdf_all

File D:\Anaconda3\envs\coastsat\lib\site-packages\pandas\core\generic.py:5989, in NDFrame.__getattr__(self, name)
   5982 if (
   5983     name not in self._internal_names_set
   5984     and name not in self._metadata
   5985     and name not in self._accessors
   5986     and self._info_axis._can_hold_identifiers_and_holds_name(name)
   5987 ):
   5988     return self[name]
-> 5989 return object.__getattribute__(self, name)

AttributeError: 'GeoDataFrame' object has no attribute 'append'

**Comment by kvos** [comment]
I have just fixed this in #400 , download the latest version, replace SDS_tools.py with the new file and you should be fine

**Comment by mkewsds12** [comment]
Thanks！！！！

**Comment by alvarezkarinar** [comment]
Hi there, I downloaded the most recently updated SDS_tools.py file (downloaded in May) but am getting the same or a similar erro as mkewsds12 above got. Error message below: 
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Input In [13], in <cell line: 2>()
      1 get_ipython().run_line_magic('matplotlib', 'qt')
----> 2 transects = SDS_transects.draw_transects(output, settings)

File ~\Documents\CoastSat-master\coastsat\SDS_transects.py:155, in draw_transects(output, settings)
    152     plt.draw()
    154 # save transects.geojson
--> 155 gdf = SDS_tools.transects_to_gdf(transects)
    156 # set projection
    157 gdf.crs = {'init':'epsg:'+str(settings['output_epsg'])}

File ~\Documents\CoastSat-master\coastsat\SDS_tools.py:748, in transects_to_gdf(transects)
    746         gdf_all = gdf
    747     else:
--> 748         gdf_all = gdf_all.append(gdf)
    750 return gdf_all

File ~\AppData\Local\anaconda3\envs\coastsat\lib\site-packages\pandas\core\generic.py:5989, in NDFrame.__getattr__(self, name)
   5982 if (
   5983     name not in self._internal_names_set
   5984     and name not in self._metadata
   5985     and name not in self._accessors
   5986     and self._info_axis._can_hold_identifiers_and_holds_name(name)
   5987 ):
   5988     return self[name]
-> 5989 return object.__getattribute__(self, name)

AttributeError: 'GeoDataFrame' object has no attribute 'append'

**Comment by alvarezkarinar** [comment]
Update: Line 748 still has 
gdf_all = gdf_all.append(gdf)
which will return the attribute error: 
AttributeError: 'GeoDataFrame' object has no attribute 'append'

By subsitituting line 748 with the following: 
gdf_all = pd.concat([gdf_all, gdf])
the code runs successfully. 

Thanks to this thread for the troubleshooting! https://github.com/kvos/CoastSat/issues/396
