### ISSUE TITLE
Affected by Landsat 7 SLC, How to extract the coastline data from 2012？

### ISSUE THREAD

**Issue by ongraiso** [kvos/CoastSat#402]
Affected by Landsat 7 SLC, there are a large number of stripes on the image. How to extract the coastline data from 2012? In 2012, only Landsat 7 images were available, without Landsat 5 and 8 images

**Comment by kvos** [comment]
there is nothing to do about the stripes but you can still map shorelines, the code is written to handle those cases. Just you won't have the full shoreline but some gaps that move around the images.
