### ISSUE TITLE
Training classifier

### ISSUE THREAD

**Issue by pdmini** [kvos/CoastSat#404]
while trying to evaluate the classifier getting the following error :

![error_](https://user-images.githubusercontent.com/121238961/236402129-e16ef6d7-1007-4a22-8aae-716ac9f8545f.JPG)

**Comment by kvos** [comment]
thanks for reporting all these issues, it needed a major update in the classification module, I just fixed it in the latest version
you should get jpg files like the one below saved in the folder
![BYRON2019-04-12-23-41-59](https://github.com/kvos/CoastSat/assets/7217258/4e8e88f3-e753-4089-82ae-88fff0525d6b)
