### ISSUE TITLE
MODULE NOT FOUND 

### ISSUE THREAD

**Issue by mathe11** [kvos/CoastSat#408]
I have followed the steps, but i'm facing this issue, what did i miss? 

![Capture d’écran 2023-06-05 094157](https://github.com/kvos/CoastSat/assets/128747045/c88982e8-e545-4019-8e38-09f9d7cc77a6)

**Comment by kvos** [comment]
you have to be in the right directory, use the cd command to open the notebook in the directory where you have coastsat

**Comment by mathe11** [comment]
Thank you, it's working now.
