### ISSUE TITLE
Problem on SDS_preprocess

### ISSUE THREAD

**Issue by Aghnar2010** [kvos/CoastSat#409]
Hello,

When i run the command 
SDS_preprocess.save_jpg(metadata, settings)

i have this problem
![image](https://github.com/kvos/CoastSat/assets/109345782/ec4c46ee-f40c-46f9-b50e-120ea9ce4045)

This seems to me similar with the problems 396, 397, 398, 400, 401.

Thanks

**Comment by kvos** [comment]
yes I just fixed it in the latest version

**Comment by Aghnar2010** [comment]
Thanks for your reply, but I'm having this problem with the latest version of the code available online (I've just tested it again).

**Comment by kvos** [comment]
sorry the problem was still there, the latest pull request by @KristenSplinter fixed it #410
