### ISSUE TITLE
preprocess RGB error

### ISSUE THREAD

**Issue by yochiokta** [kvos/CoastSat#414]
Hi I have problem in the preprocessed data always appear  remove_small_objects() got an unexpected keyword argument 'in_place'

Saving images as jpg:
S2: 2 images
100%
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[32], line 1
----> 1 SDS_preprocess.save_jpg(metadata, settings)

File ~/Documents/CoastSat-master/coastsat/SDS_preprocess.py:589, in save_jpg(metadata, settings, **kwargs)
    587 fn = SDS_tools.get_filenames(filenames[i],filepath, satname)
    588 # read and preprocess image
--> 589 im_ms, georef, cloud_mask, im_extra, im_QA, im_nodata = preprocess_single(fn, satname, settings['cloud_mask_issue'],
    590                                                                           settings['pan_off'], collection)
    592 # compute cloud_cover percentage (with no data pixels)
    593 cloud_cover_combined = np.divide(sum(sum(cloud_mask.astype(int))),
    594                         (cloud_mask.shape[0]*cloud_mask.shape[1]))

File ~/Documents/CoastSat-master/coastsat/SDS_preprocess.py:244, in preprocess_single(fn, satname, cloud_mask_issue, pan_off, collection)
    242 bands = [data.GetRasterBand(k + 1).ReadAsArray() for k in range(data.RasterCount)]
    243 im_QA = bands[0]
--> 244 cloud_mask = create_cloud_mask(im_QA, satname, cloud_mask_issue, collection)
    245 # check if -inf or nan values on any band and create nodata image
    246 im_nodata = np.zeros(cloud_mask.shape).astype(bool)

File ~/Documents/CoastSat-master/coastsat/SDS_preprocess.py:331, in create_cloud_mask(im_QA, satname, cloud_mask_issue, collection)
    328 # remove cloud pixels that form very thin features. These are beach or swash pixels that are
    329 # erroneously identified as clouds by the CFMASK algorithm applied to the images by the USGS.
    330 if sum(sum(cloud_mask)) > 0 and sum(sum(~cloud_mask)) > 0:
--> 331     morphology.remove_small_objects(cloud_mask, min_size=40, connectivity=1, in_place=True)
    333     if cloud_mask_issue:
    334         elem = morphology.square(6) # use a square of width 6 pixels

TypeError: remove_small_objects() got an unexpected keyword argument 'in_place'

Hope you can give any solutions, thankyou

**Comment by yochiokta** [comment]
And I also still have error in the Mapping shorelines:
S2:   100%
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[34], line 2
      1 get_ipython().run_line_magic('matplotlib', 'qt')
----> 2 output = SDS_shoreline.extract_shorelines(metadata, settings)

File ~/Documents/CoastSat-master/coastsat/SDS_shoreline.py:150, in extract_shorelines(metadata, settings)
    148 fn = SDS_tools.get_filenames(filenames[i],filepath, satname)
    149 # preprocess image (cloud mask + pansharpening/downsampling)
--> 150 im_ms, georef, cloud_mask, im_extra, im_QA, im_nodata = SDS_preprocess.preprocess_single(fn, satname, 
    151                                                                                          settings['cloud_mask_issue'], 
    152                                                                                          settings['pan_off'],
    153                                                                                          collection)
    154 # get image spatial reference system (epsg code) from metadata dict
    155 image_epsg = metadata[satname]['epsg'][i]

File ~/Documents/CoastSat-master/coastsat/SDS_preprocess.py:244, in preprocess_single(fn, satname, cloud_mask_issue, pan_off, collection)
    242 bands = [data.GetRasterBand(k + 1).ReadAsArray() for k in range(data.RasterCount)]
    243 im_QA = bands[0]
--> 244 cloud_mask = create_cloud_mask(im_QA, satname, cloud_mask_issue, collection)
    245 # check if -inf or nan values on any band and create nodata image
    246 im_nodata = np.zeros(cloud_mask.shape).astype(bool)

File ~/Documents/CoastSat-master/coastsat/SDS_preprocess.py:331, in create_cloud_mask(im_QA, satname, cloud_mask_issue, collection)
    328 # remove cloud pixels that form very thin features. These are beach or swash pixels that are
    329 # erroneously identified as clouds by the CFMASK algorithm applied to the images by the USGS.
    330 if sum(sum(cloud_mask)) > 0 and sum(sum(~cloud_mask)) > 0:
--> 331     morphology.remove_small_objects(cloud_mask, min_size=40, connectivity=1, in_place=True)
    333     if cloud_mask_issue:
    334         elem = morphology.square(6) # use a square of width 6 pixels

TypeError: remove_small_objects() got an unexpected keyword argument 'in_place'

**Comment by kvos** [comment]
I thought I fixed this error due to the in_place parameter being deprecated. 

Can you download the new version of coastsat and try again?
