### ISSUE TITLE
Save .jpg of the preprocessed RGB images 

### ISSUE THREAD

**Issue by tofivan** [kvos/CoastSat#415]
Hey @kvos

I ENCOUNTERED AN ISSUE when I attempted to process Landsat-7 and Landsat-8 images simultaneously. Everything went smoothly with the Landsat 7 images, but I received the following error when processing the Landsat 8 images:
AttributeError: 'NoneType' object has no attribute 'RasterCount.'

![螢幕擷取畫面 2023-06-10 180332](https://github.com/kvos/CoastSat/assets/35683839/653c11b8-0420-4ca9-9896-745dbd6e7182)

Can Landsat-7 and Landsat-8 images be processed simultaneously?

**Comment by kvos** [comment]
yes the code usually processes all the images together. looks like the info in your metadata file doesn't match the files that are actually there, can you delete everything under /data and try downloading again?

**Comment by tofivan** [comment]
Thank you, I've checked the images I downloaded. After deleting the ones with abnormal numbers, everything is functioning normally.

![螢幕擷取畫面 2023-06-10 184240](https://github.com/kvos/CoastSat/assets/35683839/58bb5ae7-2108-4269-b0d1-c1719d86eba4)

**Comment by kvos** [comment]
ok but it must work without manually deleting images, let me know if you how to recreate the error and I can test it out
