### ISSUE TITLE
Classifier replacement

### ISSUE THREAD

**Issue by mkewsds12** [kvos/CoastSat#419]
I am looking forward to your answer on how to replace the existing classifier with a new one that you have trained.

**Comment by kvos** [comment]
you will need to store it under /classification/models, then open SDS_shorelines.py and at the lines 119-134 change the path to load your own pickle file.

**Comment by czarnes22** [comment]
Hi Killian, about this i have a problem. i change the path at the lines for S2 (just for test), and i have an error, but i have a file in models folder:  
[Errno 2] No such file or directory: 'C:\\Users\\Kamil\\Desktop\\CoastSat_2_4\\classification\\models\\przyklad_new.pkl'
![image](https://github.com/kvos/CoastSat/assets/150695939/e1d81720-229b-4473-83bb-b3bd8920b74d)
