### ISSUE TITLE
Retrieving images not working

### ISSUE THREAD

**Issue by sjdijsselbloem** [kvos/CoastSat#420]
Hi!

I've been working with CoastSat for a while now, extremely useful tool in my opinion! Thanks for that! 

Recently I reinstalled the whole CoastSat toolbox (new PC), but I'm now running into an error that I cannot get my head around. 
![Capture](https://github.com/kvos/CoastSat/assets/61553046/9018f648-77d9-4a86-8b58-e2400cd40ecc)

With this code, the script is able to identify the available images. However, when I want to download them, it doesn't seem to work:
![image](https://github.com/kvos/CoastSat/assets/61553046/0dec8901-73a8-4ad7-966c-b0f5fb09ff69)

It seems like a very regular request. I tried with different date ranges, different satellite missions, different polygon. Seem error keeps occurring. 

Do you have any idea where to look?

Thanks!

**Comment by kvos** [comment]
I'm guessing that the issue is that you downloaded the new coastsat but are still using a /data folder with the old coastsat images which are not compatible any more. Try to delete/move the old /data folder and create a new empty one.

**Comment by sjdijsselbloem** [comment]
Hi! 

Thanks for your swift reply! I downloaded the new coastsat on my new laptop, so there shouldn't be any traces left of the old coastsat, as this was installed on a different laptop. Do you have any other idea where to look for solutions?

Thanks

**Comment by kvos** [comment]
also delete the /data folder (or rename it) so that it can download on a new folder without existing files

**Comment by kvos** [comment]
I think this is also due to the new HARMONIZED collection, can you try with dates before 2022? and then with dates after 2022-02-01? 
see the screenshot here from GEE page 
![image](https://github.com/kvos/CoastSat/assets/7217258/94000e8a-1181-4c93-b4bf-c57e1578579f)

**Comment by sjdijsselbloem** [comment]
I tried, both resulting in the same error unfortunately...

**Comment by kvos** [comment]
seems to be a recurrent issue over the last few days, see #422 . send me the inputs (txt file not screenshot) and I will troubleshoot

**Comment by kvos** [comment]
see answers to issues #425 #431 #422
