### ISSUE TITLE
Attribute error occurring during sentinel 2 operations

### ISSUE THREAD

**Issue by anaghapilangu** [kvos/CoastSat#422]
When I am operating Coastsat with only Sentinel 2 data, this error keeps occurring:

runfile('C:/CoastSat-master/example.py', wdir='C:/CoastSat-master')
Number of images available between 2016-01-01 and 2018-01-01:
- In Sentinel-2 Level-1C:
     S2: 110 images
  Total to download: 110 images

Downloading images:
S2: 110 images
Traceback (most recent call last):

  File ~\anaconda3\envs\coastsat\lib\site-packages\spyder_kernels\py3compat.py:356 in compat_exec
    exec(code, globals, locals)

  File c:\coastsat-master\example.py:66
    metadata = SDS_download.retrieve_images(inputs)

  File C:\CoastSat-master\coastsat\SDS_download.py:220 in retrieve_images
    warp_image_to_target(fn_in,fn_out,fn_target,double_res=False,resampling_method='bilinear')

  File C:\CoastSat-master\coastsat\SDS_download.py:613 in warp_image_to_target
    georef_target = np.array(im_target.GetGeoTransform())

AttributeError: 'NoneType' object has no attribute 'GetGeoTransform'

why is that? Can you please help me

**Comment by kvos** [comment]
I am not sure but it could be that there were already some files in your /data folder, try to start a new one and download from scratch

**Comment by kvos** [comment]
maybe this issue could be due to this issue with the new harmonized collection:
![image](https://github.com/kvos/CoastSat/assets/7217258/0b42263e-bbea-421d-b9a4-3baa35e2bd16)

can you test to see if there is a difference before and after 2022? thanks

**Comment by kvos** [comment]
seems to be a recurrent issue over the last few days, see #422 . send me the inputs (txt file not screenshot) and I will troubleshoot

**Comment by anaghapilangu** [comment]
[baga beach.zip](https://github.com/kvos/CoastSat/files/11980431/baga.beach.zip)

**Comment by kvos** [comment]
I have tested the areas for two other issues that had the same error #425 #431 and it worked fine on my end so I think it is just a matter of cleaning up the /data folder, starting a new one and using the latest version of the code
