### ISSUE TITLE
Single shoreline shows up in QGIS instead of multiple

### ISSUE THREAD

**Issue by BenhurGit77** [kvos/CoastSat#423]
Hi @kvos Im getting only one shoreline data stored in geojson file despite mapping shorelines for 48 images. But in the figure plot all shorelines appear. What could have gone wrong? I really appreciate any help you can provide.

**Comment by kvos** [comment]
how many shorelines are in the output variable? maybe it didn't save them correctly ro geojson

**Comment by RabbitRustler** [comment]
Excuse me, I want to say I'm having the same problem as you. There is only one coastline in the JSON file, but there are all of them in the figure. Is your problem solved？can you give me a reference about how to solve it?

**Comment by BenhurGit77** [comment]
Hi, @RabbitRustler I still didnt understand why that happened. But, my issue got solved when I replaced the old packages with the newly updated packages.
