### ISSUE TITLE
Specific area images are not downloading

### ISSUE THREAD

**Issue by BlooD-21** [kvos/CoastSat#425]
Hello Kilian,
I'm using coastsat as part of my dissertation. It is running exactly in my device but while running the coordinates for my location, images are not forming. I've tried using different satellite data and none is available from them. But using any other location's coordinates as input I got downloaded images..  I've used the same on other devices , there also it is showing the same.  Attaching some coordinates of my location (Odisha, India).
Please check using using them and provide me  a solution.

polygon = [[[19.294982, 84.957139],
            [19.292843, 84.958832],
            [19.299021, 84.966390],
            [19.301228, 84.964522],
            [19.294982, 84.957139]]]

Point | Latitude,Longitude

      1 | 19.121990, 84.783691
      2 | 19.120476, 84.797894
      3 | 19.194165, 84.845704
      4 | 19.196569, 84.834920

Point | Latitude,Longitude
     
      1 | 19.194165, 84.845704
      2 | 19.196569, 84.834920
      3 | 19.254195,  84.917025
      4 | 19.260950,  84.904716

Point | Latitude,Longitude

      1 | 19.260950,  84.904716 
      2 | 19.254195,  84.917025
      3 | 19.260850, 84.924845
      4 | 19.266275, 84.916493

**Comment by kvos** [comment]
try to swap the coordinates, lon first then lat

**Comment by BlooD-21** [comment]
It worked, thank you.

**Comment by BlooD-21** [comment]
It worked, Thank you.

**Comment by BlooD-21** [comment]
Hi Kilian,
As per your suggestion I have modified and Landsat data are now available, but for Sentinel 2 the following error is popping up.
Tried S2 for other locations and it is available.
 I need to add multiple satellite data for verification for submitting my thesis, please suggest me a way.
![1 (1)](https://github.com/kvos/CoastSat/assets/137854230/094cd201-252f-456c-a068-8af2da98f822)
![1 (2)](https://github.com/kvos/CoastSat/assets/137854230/a7d57a19-a176-405a-8214-568c24137fd1)

**Comment by kvos** [comment]
ok this seem to be a recurrent issue reported 3 times in the last few days, can you send me your inputs as txt file so I can copy paste them and troubleshoot?

**Comment by BlooD-21** [comment]
# region of interest (longitude, latitude in WGS84)
polygon = [[[84.762904, 19.079329],
            [84.766415, 19.077809],
            [84.798390, 19.123179],
            [84.787181, 19.119610],
            [84.762904, 19.079329]]]

# date range
dates = ['2016-01-01', '2022-12-31']

# satellite missions
sat_list = ['S2']
collection = 'C02' # choose Landsat collection 'C01' or 'C02'
# name of the site
sitename = 'OD'

'output_epsg': 28356

this is my first sector , should I add more inputs.

**Comment by kvos** [comment]
it's working for me. pls try to start the downloads on a new folder with the latest version of the code.
![2022-01-02-05-03-23_S2](https://github.com/kvos/CoastSat/assets/7217258/80f4ea17-ede9-47eb-983a-43a30af75cd9)

**Comment by BlooD-21** [comment]
Thank you Kilian.

**Comment by BlooD-21** [comment]
Thank you for the support.
