### ISSUE TITLE
Extract satellite images for different date ranges

### ISSUE THREAD

**Issue by ipons00** [kvos/CoastSat#426]
Hi Kilian,

I'm using the CoastSat tool for my master's degree thesis. It works fine but I would like to extract the shoreline of any given place, but instead of comparing the images obtained for a specific date range (i.e. 04-01-2020 to 05-01-2020) I would like to obtain the images for many date ranges in order to compare the shoreline evolution through the years (i.e. [04-01-2020 to 05-01-2020], [04-01-2021 to 05-01-2021], [04-01-2022 to 05-01-2022]... etc.)

I tried to extend the date range so it included the three years but it downloads way too many images and it takes too long to process. In addition, I'm just interested in obtaining the least cloudy images for the months of February/May. Is there a way to do this? 

Thank you in advance, I'd like to express my compliments for developing such a cool and interesting tool.

-Ian.

**Comment by kvos** [comment]
cheers Ian. You can do that by writing a loop that iterates over the dates that you are interested in and call retrieve _images() multiple times. it's not set up at the moment to download specific dates, just all images within a range
