### ISSUE TITLE
How to retrieve SCL band from Sentinel2

### ISSUE THREAD

**Issue by Figas23** [kvos/CoastSat#427]
Hello. 

First of all, great job with the repository. I'm sorry if my question is stupid but this is my first time using this repository.

I was trying to download the SCL band from Sentinel2 using the SDS_download.py script. I guess I would need to add the 'SCL' in the list of the 'S2' key in the bands_dict dictionary, but I am not being able to download it. Could you explain me what do I might be doing wrong? Maybe the name of that band is not actually 'SCL'.

Thank you in advance.

**Comment by kvos** [comment]
hey luis, what is the SLC band? if you need a different band or different product (like surface reflectance) then it is a bit more involved as you will need to change things in SDS_download.py, but it's possible.

**Comment by Figas23** [comment]
Hello Kilian. 
Scene Classification Layer (SCL) distinguishes between cloudy, clear and water pixels. The resulting SCL is used for cirrus cloud correction in the processing chain. It is also commonly applied in further analysis as a cloud mask, which removes unwanted cloudy pixels from the multispectral observations.
Yes I believe I have to change things in the SDS_download.py, but i wanted to make sure that its possible to download this band.

Thank you.

**Comment by kvos** [comment]
hey @Figas23 , I actually just pushed an update where I'm getting the cloud mask from s2cloudless which is available in GEE, have a go with the latest version of the code to see if the S2 cloud mask improves. you Will need to redownload the images. 

Okok the SCL is in level2A surface reflectance, so it's not available in level 2C top of atmosphere that we are using in coastsat
