### ISSUE TITLE
pan sharpening of images being failing

### ISSUE THREAD

**Issue by anaghapilangu** [kvos/CoastSat#428]
i have been doing CoastSat operations taking only landsat 7,8 and9 the images failed to do pansharpening.
![2018-02-03-05-30-16_L7](https://github.com/kvos/CoastSat/assets/137163077/68b9965c-fae2-4956-9d83-6a2c0f5711e5)
![2018-02-27-05-28-20_L8](https://github.com/kvos/CoastSat/assets/137163077/873244f9-0f12-42d2-be66-cb3212a9569e)
![2018-03-07-05-29-55_L7](https://github.com/kvos/CoastSat/assets/137163077/a216ee1e-5855-41aa-a4bf-020cee42b580)
![2018-03-23-05-29-42_L7](https://github.com/kvos/CoastSat/assets/137163077/f3637ed4-9e5e-459c-8b5c-bee6714bee72)

**Comment by kvos** [comment]
nothing has failed, that is the scan line error in Landsat 7 images from 2001, there's nothing to do about it but you can still get good shoreline data in between the bands. From 2022, Landsat 9 can be used to replaced LAndsat 7.
