### ISSUE TITLE
pansharpening keep failing and ms file is not supporting or showing as corrupted

### ISSUE THREAD

**Issue by anaghapilangu** [kvos/CoastSat#429]
![1](https://github.com/kvos/CoastSat/assets/137163077/e57f513c-c27e-402f-8eec-32a009edc5c8)
![2](https://github.com/kvos/CoastSat/assets/137163077/8acbc7d0-2749-4831-b5fa-08e725abf406)
after completion of loading  key error : 'auto prc' keep appearing.
![3](https://github.com/kvos/CoastSat/assets/137163077/aaa8a17c-514e-496a-b4e3-1bfaa553f576)

**Comment by kvos** [comment]
you must have in `settings_transect` a field called `auto_prc`, if not it will break.

**Comment by anaghapilangu** [comment]
can you explain bit more, i have been stuck with this for days..

**Comment by anaghapilangu** [comment]
and one transects are loading in another epsg also..
![4](https://github.com/kvos/CoastSat/assets/137163077/4d16b7ca-e756-4d66-be6c-db7098b2b6b5)
