### ISSUE TITLE
Issue with reading the Excel Sheet for tide data

### ISSUE THREAD

**Issue by jobthoma97** [kvos/CoastSat#436]
Excel Sheet : 
[GOA_2020.csv](https://github.com/kvos/CoastSat/files/12434897/GOA_2020.csv)
Shoreline dates : 
![image_2023-08-25_112902258](https://github.com/kvos/CoastSat/assets/85024689/00d2cac0-55a2-4196-8f8e-878f695fc381)
Error Screenshot : ![image_2023-08-25_112439410](https://github.com/kvos/CoastSat/assets/85024689/a000782a-643a-4c52-93dc-fc504e516f3d)

This is the error which I'm getting. I tried to format the length of the Excel sheet. I also set the dates in the proper order as the same format of the sample Excel sheet provided with the Package.
Still its showing error.

**Comment by kvos** [comment]
this means that some dates has a timezone (offset-aware) and others have not (offset-naive). You need to make sure that they are all in the same format. you can add a utc timezone with pytz.utc.localize(your_date)

**Comment by jobthoma97** [comment]
Thank you @kvos, I'll try the giving solution.
Thanks a lot.
