### ISSUE TITLE
How to solve the errors in the attached files?

### ISSUE THREAD

**Issue by scanhanga** [kvos/CoastSat#437]
Hi all
I am trying to run a  script to recovery the time series of coastline, in specific site here in my country, by using the CoastSat application/software. When I run the python script those errors, that are in the attached file, come to my screen. Can someone assist me on the identification of the possible solution, to overcome this? 

I would appreciate, if I could get the needed assistance. Best Regards.

[Erros_CoastSat_14092023.docx](https://github.com/kvos/CoastSat/files/12607500/Erros_CoastSat_14092023.docx)

**Comment by kvos** [comment]
can you pls describe the issue here directly? no word doc, just explain clearly the problem and how to reproduce it
