### ISSUE TITLE
Tidal correction problems with dates and install 

### ISSUE THREAD

**Issue by xiyang712** [kvos/CoastSat#438]
Hi Kilian, So sorry.

I have encountered some problems now, the date I set is [2015-01-01', '2023-01-01'], but the tide level correction step has the following error.
![image](https://github.com/kvos/CoastSat/assets/115886880/38e51652-efd5-4967-ad57-8ac683609b29)

Later, I set the period length to one month （2017-12-01,2018-01-01）, but it did not report an error. I tried many reasons but failed. So I would like to ask why this happens. Attached below are my steps to install FES2014.
![image](https://github.com/kvos/CoastSat/assets/115886880/6b0b1f1c-da59-44f4-b9d7-6e55a3b1720d)
![image](https://github.com/kvos/CoastSat/assets/115886880/7b36590d-8134-4e4a-bdeb-2b6e30958abd)

Thank you Kilian.

**Comment by kvos** [comment]
it's because you are loading the tides from a csv that does not contain dates up to 2023. that's why it works till 2018

**Comment by xiyang712** [comment]
Does that mean that the tide level is from the previous example and not from the FES2014 I installed? If so, then my fes2014 is still not installed successfully.

**Comment by xiyang712** [comment]
![image](https://github.com/kvos/CoastSat/assets/115886880/1736148f-48ba-4ef1-9b02-b7860ac1639e)
This is my error message step in coastsat.slope

**Comment by kvos** [comment]
did you install the pyfes module as in the instructions in coastsat.slope?

**Comment by xiyang712** [comment]
I followed the request and passed the command 'conda list'. It can be seen that the package contains pyfes, but the following error message still appears: No module named 'pyfes'. Below is a screenshot of my installation steps.
![image](https://github.com/kvos/CoastSat/assets/115886880/3ce64725-0c9e-40a9-9e8c-66493fb07bea)
![image](https://github.com/kvos/CoastSat/assets/115886880/acddc815-e38f-4d90-8645-0f3a66765802)
![image](https://github.com/kvos/CoastSat/assets/115886880/d1dea642-0d1d-4392-9814-5d667d6992f5)

**Comment by czarnes22** [comment]
Hello Kylian, So, i have "Time-series do not cover the range of your input dates ". I have a CSV file with my own sea level measurements. I am attaching to the conversation. I don't really understand the path I should take to full success from the analysis

1. where and what should I change to go to recognize tidal correction. Is the "slope" add-on necessary in this? 
How to fix the error "Time-serier..." 


In the case of a combination of CoastSat and CoastSat.slope programs: 
2. slope calculation: do I need to have access from FES2014 to global tide levels? 
	a) if yes: how to extract the "sha256sum" file? What commands, programs to use? 
	b) if not: how to change the csv file to pkl, which is written in option 2?

[PNKaff_tides1.zip](https://github.com/kvos/CoastSat/files/13537164/PNKaff_tides1.zip)
