### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by Yeray2023EO** [kvos/CoastSat#439]
Hi, I was trying to link my environment to the GEE server. And I got the following error: 

_(coastsat) C:\Users\GSI>earthengine authenticate --auth_mode=notebook
'earthengine' is not recognized as an internal or external command,
operable program or batch file.

Thanks, 

Yeray

**Comment by Yeray2023EO** [comment]
I tried through Anaconda prompt and Google Cloud. Same error. See the screenshots attached below. 
![Anaconda prompt- screenshot](https://github.com/kvos/CoastSat/assets/145126789/9644a6b6-abe3-48e2-b064-6cee587f2045)
![Google cloud sdk shell - screenshot](https://github.com/kvos/CoastSat/assets/145126789/63712a27-a680-425a-b2e3-d1a1830ef327)

**Comment by kvos** [comment]
you need to install gcloud and it will initialise for you
https://developers.google.com/earth-engine/guides/auth

**Comment by kvos** [comment]
try to run `gcloud init`

**Comment by Yeray2023EO** [comment]
Thanks, now looks to be working
