### ISSUE TITLE
Calculation of features not robust towards nan values

### ISSUE THREAD

**Issue by borgstad** [kvos/CoastSat#44]
In `calculate_feature` a feature vector is generated for each pixel not obscured by clouds. The feature vector consists of five bands and a corresponding normalized difference index. This yields in total ten bands. For each of these bands, the standard deviation is calculated, and this is where things go wrong. The function `image_std`, used to calculated the standard deviation, uses `uniform_filter` from Scipy to do so. I have expierenced problems in accordance with this issue: https://github.com/scipy/scipy/issues/7818. I.e., whenever a pixel is assigned nan, all values proceding this pixel values in the convolution will have value nan.

The issue can be very easily replicated:
```
im_ms, georef, cloud_mask, im_extra, im_QA, im_nodata = SDS_preprocess.preprocess_single(fn,
                                                                                             satname,
                                                                                             cloud_mask_problem)

# will results in channel 9- 19 of im_features equal nan
im_ms[0,0,:] = np.nan
im_features = SDS_shoreline.calculate_features(im_ms, cloud_mask, ~im_nodata)

# check if all elements are nan
im_features[:,:,10:].flatten().all() == True
```

The problem can be mitigated easily by using a convolution library that handles nan values. Astropy (https://docs.astropy.org/en/stable/convolution/) is one such library

**Comment by kvos** [comment]
hi @borgstad , thanks for picking this up. The image classification can be improved with a convolution that can handle NaN values. Did you already implement the fix with astropy yourself? Is it as fast as the scipy `uniform_filter`? It would be great if you could make a pull request, thanks!

**Comment by kvos** [comment]
I gave it a go and astropy's convolution library fixed the problem of NaNs spreading through the convolution (see figure below). Thanks @borgstad  for the suggestion! I'll update the `image_std()` function asap.
 
![scipy_vs_astropy](https://user-images.githubusercontent.com/7217258/69201807-a2581100-0b93-11ea-965e-4aa77b78f35a.png)
