### ISSUE TITLE
Question: How to correctively use the Tidal Correction?

### ISSUE THREAD

**Issue by ecnun** [kvos/CoastSat#441]
Congratulations for the toolbox.

I think this tool is so useful and amazing! Now I have two questions:
1. In the Tidal Correction section, you said it should two requirements: Times-series of water/tide level and an estimation of the beach-face slope, and now I successfully run the FES2014 and CoastSat.Slope (python3.7), if I run the CoastSat.Slope means the two requirements are both solved and I don't find the tide level again?
2. In the picture(see picture below), it should add the .csv file, but I use the FES2014 model, In the CoastSat.slope it use the FES2014 conveniently, I don't konw how to solve the .csv file. Whether I use the FES2014, do I not need to load the .csv file, If so,how do I modify the code.  
![image](https://github.com/kvos/CoastSat/assets/132353187/13e0f331-fe7b-4e6c-bc2a-6c247086cafe)

Thanks in advance.

**Comment by kvos** [comment]
you can skip the csv file part if you are using FES2014, just replace `tides_sat` with the tides that you obtained from FES2014 for the dates in which the images were taken. You can then use that for tidal correction.
