### ISSUE TITLE
Asking about shorelines shapefile

### ISSUE THREAD

**Issue by HoangDaoVu** [kvos/CoastSat#443]
how can I download shorelines for each year in polygon or shapefile ?
![image](https://github.com/kvos/CoastSat/assets/112382197/0a7b9706-e5dd-49b7-8af0-6bcdfebc9f8b)

**Comment by kvos** [comment]
this is explained in the readme and there is a cell in the jupyter notebook that does that. Change .geojson to .shp to get a shapefile.
