### ISSUE TITLE
Tidal correction using AVISO data

### ISSUE THREAD

**Issue by MReznikS** [kvos/CoastSat#444]
Hi! 
I am trying to run the tidal correction part in CoastSat but with AVISO data instead of .cvs data. I have successfully done CoastSat.Slope example in which AVISO tidal data was used correctly. However, I am having trouble using it at CoastSat routine. Is this possible to make the tidal correction using the .nc files obtained from AVISO+? If so, can you help me or guide me with the code? 
I think I would need to change this part: 

# load the measured tide data
**filepath = os.path.join(os.getcwd(),'examples','NARRA_tides.csv')**
tide_data = pd.read_csv(filepath)
dates_ts = [pd.to_datetime(_).to_pydatetime() for _ in tide_data['dates']]
tides_ts = np.array(tide_data['tide'])

# get tide levels corresponding to the time of image acquisition
dates_sat = output['dates']
tides_sat = SDS_tools.get_closest_datapoint(dates_sat, dates_ts, tides_ts)

# plot the subsampled tide data
fig, ax = plt.subplots(1,1,figsize=(15,4), tight_layout=True)
ax.grid(which='major', linestyle=':', color='0.5')
ax.plot(dates_ts, tides_ts, '-', color='0.6', label='all time-series')
ax.plot(dates_sat, tides_sat, '-o', color='k', ms=6, mfc='w',lw=1, label='image acquisition')
ax.set(ylabel='tide level [m]',xlim=[dates_sat[0],dates_sat[-1]], title='Water levels at the time of image acquisition');
ax.legend();

Thanks a lot for sharing all of your work! amazing. :)

**Comment by kvos** [comment]
hi @MReznikS , yes that is possible. Unfortunately the repos are separate, which is not ideal but more practical for me maintaning them. What I suggest you do is that you generate the time-series in your CoastSat.Slopes environment, then save as a .csv file, and read that csv file in your CoastSat environment, does this make sense?

**Comment by kvos** [comment]
if it can help, this is the function that CoastSat.slope is using to get the tides from FES for your satellite dates:
```
def compute_tide_dates(coords,dates,ocean_tide,load_tide):
    'compute time-series of water level for a location and dates (using a dates vector)'
    dates_np = np.empty((len(dates),), dtype='datetime64[us]')
    for i,date in enumerate(dates):
        dates_np[i] = datetime(date.year,date.month,date.day,date.hour,date.minute,date.second)
    lons = coords[0]*np.ones(len(dates))
    lats = coords[1]*np.ones(len(dates))
    # compute heights for ocean tide and loadings
    ocean_short, ocean_long, min_points = ocean_tide.calculate(lons, lats, dates_np)
    load_short, load_long, min_points = load_tide.calculate(lons, lats, dates_np)
    # sum up all components and convert from cm to m
    tide_level = (ocean_short + ocean_long + load_short + load_long)/100

    return tide_level
```

**Comment by MReznikS** [comment]
Excellent, thank you. I was able to export them from CostSat.Slope as .csv file with the following lines: 
data = {
    'dates_fes': dates_fes,
    'tide_fes': tide_fes,
    
}

df = pd.DataFrame(data)

import os

directorio_destino = r'C:\Users\mrezniks\Documents\Codigos_MRS\CoastSat.slope-master\Datos-marea'

if not os.path.exists(directorio_destino):
    os.makedirs(directorio_destino)

ruta_completa = os.path.join(directorio_destino, 'datos_tide-fes.csv')

df.to_csv(ruta_completa, index=False)

print(f"Los datos se han guardado en: {ruta_completa}")

I will incorporate them to CoastSat and read that csv file to make the tidal correction. Thanks for the tip @kvos !! :D
