### ISSUE TITLE
Computing transect shoreline intersections

### ISSUE THREAD

**Issue by lovleenac** [kvos/CoastSat#445]
Hi Kilian,

When running the section computing the shoreline intersection I get the following error (attached below). On further inspection of the python code in the master folder I realized that the libraries are named differently. So the code in the notebook is unable to find "prc_multiple" as it is named as "auto_prc" in the python script (attached below). Moreover the notebook is searching for this in line 400 of the script which doesn't exist in the python script in the master folder. 

I'm wondering if any modifications have been made which hasn't been updated?

Any help would be greatly appreciate :)

Cheers,
Lovleen
![image](https://github.com/kvos/CoastSat/assets/37291615/99ec2bf3-1710-421a-a2a9-caf92eac4513)
![image](https://github.com/kvos/CoastSat/assets/37291615/4d4e95ed-06e3-4da4-8366-181c3babb11f)

**Comment by kvos** [comment]
hi @lovleenac , yes I remember fixing this bug. Are you using the latest version of python code and notebook? feel free to change it in your notebook so it matches the same name as in the python function and you should be good to go.
