### ISSUE TITLE
Discontinuous Shoreline

### ISSUE THREAD

**Issue by IdhamN** [kvos/CoastSat#446]
Hi Kilian.
I used the coastsat to extract the shoreline in my research area, (Dumai, Indonesia).
When I extracted the shoreline, I had issues with my shoreline like the picture below.
any lead for this?

I am looking forward to hearing from you
Thank you in advance 

![image](https://github.com/kvos/CoastSat/assets/142526270/6f0dcc4a-8e73-42a2-ab68-e2cc130b744d)
![image](https://github.com/kvos/CoastSat/assets/142526270/264c61c3-5c47-4551-8b9d-2930035e9c99)

**Comment by kvos** [comment]
hi @IdhamN , this is interesting, a few questions to understand better what the issue could be:
- are you using a reference shoreline? what is the max_dist_ref parameter that you are using?
- have you set cloud_mask issue = True?
- what have you set for dist_clouds?
It could be that there are individual cloudy pixels and then if you are using dist_clouds = 300 m it removes all shoreline points within 300 m from a cloud pixel. It could also be that you are too far from your reference shoreline.

**Comment by IdhamN** [comment]
Hi Kilian,

Previously, I used the default max_dist_ref (100), but now I have set it to 200, and it seems to be working.

I would like to ask another question. I will take 20 years from 2003-2023 to analyse the shoreline. I got 28 shorelines from 2004 to 2023 after extracting the shoreline step, but when I looked at the tides model by FES 2014, I only had tides from 2004-2017. When I try to make a tidal correction I get this error: "**Exception: Time-series do not cover the range of your input dates**". Do you have any suggestions? Do I need to change the shoreline to refer to tide dates? Is there another way?

I'm looking forward to hearing from you
Thank you in advance, Kilian.

Regards

**Comment by kvos** [comment]
can you extend your fes2014 tide time-series? they are forecasted tides so you can run them to 2030 if you'd like
