### ISSUE TITLE
Pyqt5 issue

### ISSUE THREAD

**Issue by cearlie** [kvos/CoastSat#448]
Hi there, hope you can help. I am having trouble, I think with Pyqt5 as I cannot run the jupyter notebook. Pip install pyqt5 seemed to work with no problems however I face this error when I try to run the first cell in the first example. 
I have python 3.11.5 installed on an M1 mac. I see that gcloud CLI requires python 3.8-3.10 but I am not sure that is the problem..yet..until I get to that stage, anyway!
This is the error I keep getting....

File ~/anaconda3/envs/coastsat/lib/python3.12/site-packages/IPython/external/qt_loaders.py:236, in import_pyqt5()
    229 def import_pyqt5():
    230     """
    231     Import PyQt5
    232 
    233     ImportErrors raised within this function are non-recoverable
    234     """
--> 236     from PyQt5 import QtCore, QtSvg, QtWidgets, QtGui
    238     # Alias PyQt-specific functions for PySide compatibility.
    239     QtCore.Signal = QtCore.pyqtSignal

Hope you can help

**Comment by kvos** [comment]
i'm on python 3.11.4 and all working well. Not sure how to fix this problem, can you uninstall pyqt5 and try to run without it?

**Comment by cearlie** [comment]
ive run it with pyqt6 and this seems to work. All works well on a PC with pyqt5 however...

**Comment by kvos** [comment]
strange, let's park it for the moment and reopen if it occurs again
