### ISSUE TITLE
Choosing only one date of each year

### ISSUE THREAD

**Issue by subhasis1983** [kvos/CoastSat#45]
Sir,
I need to analyse the shoreline change of a particular season  and want to take one data  in every one/ five yera. Can you please tell, how to define ?

regards,
Subhasis

**Comment by kvos** [comment]
Hi @subhasis1983 , you can easily do that by putting a loop around `SDS_download.retrieve_images(inputs)` and modifying the variable `inputs['dates']` with the periods that you want to analyse, then you will only download images for those periods
