### ISSUE TITLE
Can This Work Used to get tidal shorelines?

### ISSUE THREAD

**Issue by ecnun** [kvos/CoastSat#450]
Thank you for your excellent work!
I think I have a interesting idea, but I don't know if this idea is useful for something. Your work is good at extracting shorelines at beach area, now I have a new work for getting the tidal shorelines. I am not sure if this is feasible, or I can change some codes to do it. Shortly speaking, I am not sure your work can be used to get tidal shorelines.
Thank you in advance!

**Comment by kvos** [comment]
hi @ecnun , mapping shorelines/waterlines on macrotidal environments it's challenging. You can play with the thresholding and see how that goes but it's a current area of active research.

**Comment by ecnun** [comment]
Thank you!
I‘ve tried to change the thresholding, but the results was not so good. So I try something new to do it.
