### ISSUE TITLE
ee attribute error: module 'ee' has no attribute 'Initialize'

### ISSUE THREAD

**Issue by xueruz** [kvos/CoastSat#451]
Hi all, 

I followed the directions in the README: created the coastsat environment and activated the Google Earth Engine API. I tried to run worked_example.ipynb, but I received an attribute error. This is the traceback: 

> AttributeError                            Traceback (most recent call last)
> File ~/Downloads/CoastSat-master/coastsat/SDS_download.py:541, in check_images_available(inputs)
>     540 try:
> --> 541     ee.ImageCollection('LANDSAT/LT05/C01/T1_TOA')
>     542 except:
> 
> AttributeError: module 'ee' has no attribute 'ImageCollection'
> 
> During handling of the above exception, another exception occurred:
> 
> AttributeError                            Traceback (most recent call last)
> Cell In[2], line 31
>      26 inputs = {'polygon': polygon, 'dates': dates, 'sat_list': sat_list, 'sitename': sitename, 'filepath':filepath,
>      27          'landsat_collection': collection}
>      28 # optionally, you can select your Sentinel-2 tile to avoid duplicates from multiple tiles
>      29 # inputs['S2tile'] = '56HLH'
>      30 # before downloading the images, check how many images are available for your inputs
> ---> 31 SDS_download.check_images_available(inputs);
> 
> File ~/Downloads/CoastSat-master/coastsat/SDS_download.py:543, in check_images_available(inputs)
>     541     ee.ImageCollection('LANDSAT/LT05/C01/T1_TOA')
>     542 except:
> --> 543     ee.Initialize()
>     545 print('Number of images available between %s and %s:'%(dates_str[0],dates_str[1]), end='\n')
>     547 # get images in Landsat Tier 1 as well as Sentinel Level-1C
> 
> AttributeError: module 'ee' has no attribute 'Initialize'

I checked conda list and ee is installed as one of the packages in the environment. Did I miss a step in the installation process? 

In addition, I had experienced an error with the module ‘StringIO’ not being detected, but I went into the ‘ee’ package and resolved that by changing “import StringIO” to “from io import StringIO”. Not sure if this has any influence on issues later down the line.

**Comment by kvos** [comment]
that is very strange, ee should have a method .Initialize(). what version of earthengine-api are you using?

**Comment by xueruz** [comment]
I’m using version 0.1.377.

**Comment by kvos** [comment]
that seems correct, try to delete your environment and restart, there must be an issue with your current conda environment.
