### ISSUE TITLE
s2cloudless datatype not compatible for gdal translation

### ISSUE THREAD

**Issue by sjdijsselbloem** [kvos/CoastSat#452]
Hi Killian,

I earlier opened issue #420, where we could not locate the error, as your script was running fine. I now dived deeper into it, and located the issue.

823 |  outds = gdal.Translate(os.path.join(filepath,filename), outds) 

They outcome of this line is None, which leads to the error a bit later in the code. 

Warning 1: ms_bands.tif: Unable to export GeoTIFF file with different datatypes per different bands. All bands should have the same types in TIFF.
ERROR 1: ZIPDecode:Decoding error at scanline 0
ERROR 1: TIFFReadEncodedTile() failed.
ERROR 1: <path>\data\location\S2\ms\image.B2.tif, band 1: IReadBlock failed at X offset 0, Y offset 0: TIFFReadEncodedTile() failed.

When we look into the temporary vrt file, all tiff files are listed. For all Bxx files, the dataType="UInt16", but for the s2cloudless the dataType="Byte". Not sure if this warning relates to the error. But there appears to be an error in reading the geotiff file.

Do you think this is gdal related? Which version are you running the coastsat toolbox with?

Thanks!

Kind Regards,

Stijn

**Comment by kvos** [comment]
I think that warning is ok, just ignore. The error though it's strange, never seen it before. I'm currently using gdal version gdal                      3.7.0           py311hf43951c_2    conda-forge, with python 3.11 and everything works fine

**Comment by sjdijsselbloem** [comment]
![image](https://github.com/kvos/CoastSat/assets/61553046/be02413a-4dc1-4556-9b13-1cf183fe5eba)

Just for the record, these files for the sentinel imagery are the correct ones? Or any missing?

**Comment by sjdijsselbloem** [comment]
Made a new environment, installed everything from scratch and now it works properly!

Thanks!

**Comment by kvos** [comment]
good to hear that everything works, it's often the solution to reset the environment. I recommend using Mamba instead of conda, way less issues.

What happens during download is that a zip file is downloaded from GEE with a file for each band as you showed, then Gdal preprocessed those bands and puts them together into the final file structure (mask, ms, swir, meta).
