### ISSUE TITLE
S2cloudless and KML format

### ISSUE THREAD

**Issue by czarnes22** [kvos/CoastSat#454]
Hi Killian, 
Sorry to bother you. It is highly likely that it is a small, unnecessary problem that I am facing at the start. After completing the KML etc., an error is displayed: 
![image](https://github.com/kvos/CoastSat/assets/150695939/de973c94-4e91-4159-8249-9d6a00adb3b1)
I tried to do this with an irregular, regular shape. I must be doing something wrong. He who asks, does not err. Please, clarify. 
Sincerely, 
Kamil

**Comment by kvos** [comment]
hi kamil, you can just skip that conversion to smallest_rectangle, I think it is now done automatically in GEE, have a go without. 
The issue must be something with the format of your KML that is different than usual, it's expecting a polygon geometry and getting a point.

**Comment by kvos** [comment]
I think that error is from my latest update, will check it and get back to you asap

**Comment by kvos** [comment]
fixed in latest commit
