### ISSUE TITLE
Can Coastsat be used to map seawater/freshwater interface?

### ISSUE THREAD

**Issue by xiyang712** [kvos/CoastSat#455]
Hi Killian，

 I have been using your coastline identification product for a year now and I am very satisfied with its performance. Currently, I am working on the identification and extraction of ocean fronts using satellite remote sensing. These fronts are narrow transition zones between two or more water bodies with distinct characteristics. The main types of fronts I am extracting are suspended sediment fronts (Figure 1) . The salt front or Yangtze River Estuary plume front, as shown in Figure 2, is formed further offshore and closer to the open sea, primarily due to the significant difference in salinity concentration between the water masses on both sides.

We used the Canny algorithm to identify the front, but manual identification is a significant challenge due to the large number of satellite images. Therefore, we plan to use this toolkit to implement the algorithm for automatic extraction. Do you have any insights or considerations regarding this?

Thanks!

Figure 1
![image](https://github.com/kvos/CoastSat/assets/115886880/ad15ec73-ffff-40ab-ba7c-fdaca65a580e)
Figure 2
![image](https://github.com/kvos/CoastSat/assets/115886880/cb9b409e-829d-425c-a8df-de142d11d41b)

**Comment by kvos** [comment]
hi @xiyang712 , thanks for posting this question here, that's an interesting problem. 
Have you been able to discern and manually digitise the saltwater front on Sentinel-2 imagery?
The normalised turbidity index in this [paper](https://www.sciencedirect.com/science/article/pii/S0034425706002811?via%3Dihub) maybe provides some contrast for automated boundary detection. 
Good luck and would be nice to hear how it is going. cheers, kilian

**Comment by xiyang712** [comment]
Hi Killian，

We used your suggestion to follow up the identification work using coastsat. For hanging sand fronts, we found that the step of classifying the images was able to clearly identify the suspended sand front (the interface between water and whitewater, yellow circle position), but since the algorithm detects the coastline, it resulted in not detecting the location of the fronts, so may I ask where to start if we want to debug it?
For example, to make the detected frontal line between water and whitewater, or either not to show the coastline, and subsequently use the canny operator for boundary recognition （Location of the red line）, do you have any suggestions for this?
![2017-07-05-02-35-22_S2](https://github.com/kvos/CoastSat/assets/115886880/76a6656e-ef40-48c2-ab40-84de0b3d7ef7)
