### ISSUE TITLE
Animation is not ordered in a date sequence

### ISSUE THREAD

**Issue by philosadelphos** [kvos/CoastSat#457]
When executing the following code step:
«fn_animation = os.path.join(inputs['filepath'],inputs['sitename'], '%s_animation_RGB.mp4'%inputs['sitename'])
fp_images = os.path.join(inputs['filepath'], inputs['sitename'], 'jpg_files', 'preprocessed')
fps = 4 # frames per second in animation
SDS_tools.make_animation_mp4(fp_images, fps, fn_animation)»

The mp4 video is not ordered by date, but in a random order. How can this issue be solved?
Thank you

**Comment by kvos** [comment]
Ok, I have just added that function so it's likely I didn't check for the order. I will fix it asap, the script is reading the images from the folder directly, in windows is ordered by dates by default but could be different in other os.

**Comment by kvos** [comment]
fixed this in latest update

**Comment by philosadelphos** [comment]
> Ok, I have just added that function so it's likely I didn't check for the order. I will fix it asap, the script is reading the images from the folder directly, in windows is ordered by dates by default but could be different in other os.

I'm working in linux mint OS. Thanks! Amazing work! Well-done!
