### ISSUE TITLE
multi reference shoreline .geojson not proper working

### ISSUE THREAD

**Issue by gianfrancodp** [kvos/CoastSat#459]
I use this repo in my doctorate program in last two month.
Trying to accelerate the task of preparation of input data, I've created a .geojson file with 2 or more feature to indicate the reference shoreline.
In this case, (in case of a presence of a .geojson file with reference shoreline) only the first reference shoreline was used by classification algorithm.

I've try to use the same .geojson generated by manual input of reference shoreline with the same problem.

Congratulation for this repo @kvos

**Comment by kvos** [comment]
you need to modify the code, instead of using the built in function, write a new function that reads all the features in the .geojson file and converts them to numpy array and then assign this to settings['reference_shoreline'] and it should work.
