### ISSUE TITLE
Download issue with L9 and S2 cloud mask

### ISSUE THREAD

**Issue by seba3784** [kvos/CoastSat#460]
Hi! The first issue is when I try download the Landsat 9 images:

![image](https://github.com/kvos/CoastSat/assets/151748900/d846fd6c-5117-4e7d-81a1-5eac90344649)

The second is this:

![image](https://github.com/kvos/CoastSat/assets/151748900/fc75c6f0-3dc3-4443-849c-2c8ad3e5680e)

**Comment by kvos** [comment]
hi @seba3784 , thanks for reporting this, I knew the second one would happen eventually but needed an example to troubleshoot, can you pls send me your inputs as .txt and I will look into it. In the meanwhile you can focus on L5, L7, L8. cheers, Kilian

**Comment by seba3784** [comment]
Thank you Kilian, here is the code:

[code_L9_S2_issues.txt](https://github.com/kvos/CoastSat/files/13450069/code_L9_S2_issues.txt)

I tested today and the S2 works. The error was with the yesterday's date (2023-11-22). If you entered until 2023-11-21 was no problem with the S2s. But today runs good.

The L9 still failing.

The polygon values are this:
[[[-56.403, -34.848], [-56.388, -34.848], [-56.388, -34.841], [-56.403, -34.841], [-56.403, -34.848]]]

Cheers,
Sebastian

**Comment by kvos** [comment]
thanks for testing, that's good to know that the cloud mask layer gets updated at a different frequency as the S2 imagery, so there is a lag between the two. I'll see how to handle that.

For the L9, it was something silly (L9 colelction does not have a Tier2 like the other Landsat collections), just fixed it in latest update.

**Comment by seba3784** [comment]
Thanks Kilian!
