### ISSUE TITLE
Error in preprocess L5 cloud mask

### ISSUE THREAD

**Issue by seba3784** [kvos/CoastSat#461]
Hello there. I found this issue processing L5 images:

![image](https://github.com/kvos/CoastSat/assets/151748900/3bad88f6-3432-4eb4-989d-c14dd968d40c)

My inputs:
[code_L5_issue_clouds.txt](https://github.com/kvos/CoastSat/files/13452092/code_L5_issue_clouds.txt)

I noticed that it always processes until the 21-jul-2000 in diferents sections

Cheers,
Sebastián

**Comment by seba3784** [comment]
Update: I found a solution: eliminate the duplicate files in the folder L5/meta and run this line again: 
`metadata = SDS_download.get_metadata(inputs)`

**Comment by kvos** [comment]
what was the name of the duplicated files? the issue there is that whatever filename is written in the metadata file cannot be found in so it's an empty gdal object.

**Comment by seba3784** [comment]
Always ends in "_dup1".
For example: 2000-07-21-13-21-43_L5_COL_08_ACT_dup1

**Comment by kvos** [comment]
ok those duplicates are annoying because they break the code, I'll see what's going and try to replicate the error with your inputs

**Comment by kvos** [comment]
I wasn't able to reproduce this error, maybe you already had some files there and downloaded again. Will close for the time being.
