### ISSUE TITLE
UnavailableInvalidChannel: HTTP 404 NOT FOUND for channel earthengine-api <https://conda.anaconda.org/earthengine-api>

### ISSUE THREAD

**Issue by Scoobys-keeper** [kvos/CoastSat#463]
Hi there- Seems I am unable to move past the error below when following this installation guide. I have seen help online to change these settings but haven't seen exactly what to change them to. Thank you for your patience and help! 

`(coastsat) willyphillips@192 python % conda install -c earthengine-api scikit-image matplotlib astropy notebook -y

UnavailableInvalidChannel: HTTP 404 NOT FOUND for channel earthengine-api <https://conda.anaconda.org/earthengine-api>

`The channel is not accessible or is invalid.

You will need to adjust your conda configuration to proceed.
Use `conda config --show channels` to view your configuration's current state,
and use `conda config --show-sources` to view config file locations.

`
(coastsat) willyphillips@192 python % conda config --show channels
channels: []
(coastsat) willyphillips@192 python % conda config --show-sources
==> /Users/willyphillips/.condarc <==
channels: []

==> cmd_line <==
debug: False
json: False
'

**Comment by kvos** [comment]
my bad, the command was not written properly in the documentation, it's `conda install -c conda-forge earthengine-api scikit-image matplotlib astropy notebook -y`

**Comment by Scoobys-keeper** [comment]
Thanks so much! I was able to trouble shoot that after a couple days and meant to update here. Thanks for all your time!
