### ISSUE TITLE
Doesn't plot final seasonal and monthly trend figures

### ISSUE THREAD

**Issue by willhankinson** [kvos/CoastSat#465]
The entire notebook works perfectly up until this very final point.  When I run code blocks 1.6.0.2. 5.2 Seasonal averaging and long-term trends and 1.6.0.3. 5.3 Monthly averages, nothing happens.  It doesn't give me any error message so I am assuming the code is correct, it just doesn't plot the figures.  The kernel runs and turns grey for half a second and then stops, with nothing happening.

Any ideas on how to resolve this?

Thanks

**Comment by kvos** [comment]
@willhankinson can you post an example/screenshot? is this with the Narrabeen data?
