### ISSUE TITLE
After opening the clash proxy software, some errors message appears

### ISSUE THREAD

**Issue by Amary0** [kvos/CoastSat#466]
Due to special reasons, I need to connect to the proxy tool to access GEE in my region, but after opening the clash proxy tool, many link errors occurred: SSLError                                  Traceback (most recent call last)
SSLError: TLS/SSL connection has been closed (EOF) (_ssl.c:1131)

The above exception was the direct cause of the following exception:

ProxyError                                Traceback (most recent call last)
ProxyError: ('Unable to connect to proxy', SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1131)')))

**Comment by kvos** [comment]
sorry @Amary0  but that is an external issue, your firewall must be blocking the google.apis.com domain.
