### ISSUE TITLE
Tidal Correction data error:''value' must be an instance of str or bytes, not a float'

### ISSUE THREAD

**Issue by VuHoangDao** [kvos/CoastSat#467]
Hi Mr. V.Killian,
I have this problem when I run the tide data from 1990 to 2022; however, when I run from 1990-2000, 2000-2010, 2010-2015, and 2015-2022 with this data.
How can I fix this issue?
Hoping response from you.
![image](https://github.com/kvos/CoastSat/assets/112917719/be38e406-5b3b-4ec1-87a9-3499b986f5da)
![image](https://github.com/kvos/CoastSat/assets/112917719/d839c42e-09b1-4d55-9bb8-ef51b0f52daf)
![image](https://github.com/kvos/CoastSat/assets/112917719/6700fac7-581f-424e-b272-769b9fbccbd3)
![image](https://github.com/kvos/CoastSat/assets/112917719/0ffcb1f5-143b-4d89-9b81-f9d04c518ffd)
![image](https://github.com/kvos/CoastSat/assets/112917719/76b02f00-4e3b-4808-85d7-e2b5c4a35453)
![image](https://github.com/kvos/CoastSat/assets/112917719/fc07e0d6-dfaa-4264-b90d-778aa5080f6b)

**Comment by kvos** [comment]
@VuHoangDao can you please show the full error message?

**Comment by VuHoangDao** [comment]
Here is the full error message.
![image](https://github.com/kvos/CoastSat/assets/112917719/025f4777-642f-492e-ad1a-5a95b7761871)
![image](https://github.com/kvos/CoastSat/assets/112917719/b259e9c7-4b82-4e09-881e-14112ab0f98a)
![image](https://github.com/kvos/CoastSat/assets/112917719/86ff52b0-20c5-4bf1-90cb-6d11c2d0f316)

**Comment by VuHoangDao** [comment]
I also do the next step, and it got the error of tides_sat should be float data instead of string data.
![image](https://github.com/kvos/CoastSat/assets/112917719/74161333-55c6-4df6-897f-b1c36968d6e3)
![image](https://github.com/kvos/CoastSat/assets/112917719/0379a32f-b250-45fa-972e-a1a1ef249888)

**Comment by VuHoangDao** [comment]
Now, I can run pass this error, however when I try with this case study area, I got this problem ( image 3). When I check the time beetween 2010 to 2015 have images with 10% cloud cover
![image](https://github.com/kvos/CoastSat/assets/112917719/90374c30-2cf1-42b1-a62a-a46a64b64ead)
![image](https://github.com/kvos/CoastSat/assets/112917719/0912a427-e7a3-4e73-b7fa-ff9162909b23)
![image](https://github.com/kvos/CoastSat/assets/112917719/71213855-bd2b-4155-a02b-b6618a50f2d0)

**Comment by VuHoangDao** [comment]
As you can see, in 2000-04-29, have the image with no cloud cover.
![image](https://github.com/kvos/CoastSat/assets/112917719/689638cf-7b8e-4208-bfa1-dbf940594eeb)
I want to calculate Seasonal averaging and long-term trends of the time 2000 to 2010, 2010 to 2015, 
I can run pass the time 1990 to 2000, 2015 to 2022, and 1990 to 2022. 
Can you give me some feed back. 
Thank you so much.

**Comment by kvos** [comment]
the issue with your tides is that the values were put into a string instead of float, I think this happens when you have NaN valuesi in the csv file. You can try to run `tide_ts = np.array([float(_) for _ in tide_ts])` see if it fixes it, otherwise specify the nan values when loading the csv

**Comment by kvos** [comment]
any updates on this issue? I will close it for the time being, feel free to reopen.
