### ISSUE TITLE
Quick question about water level correction

### ISSUE THREAD

**Issue by czarnes22** [kvos/CoastSat#468]
Hello, shoud I use a water level observations or predicted tide (astronomical) to mesasure tidal correction? 
Best regards, 
Kamil 

![image](https://github.com/kvos/CoastSat/assets/150695939/7b313c4b-dee2-4255-aec5-9f5ed237c015)

Can someone help me with the data of water level based of aviso? or downloaded it and send me in dm? i have a big problem with this, and i have only date from 1993 to 2023. for this coordinates: 
#polygon = [[[11.80787, 78.67525],
#            [11.83078, 78.67525],
#            [11.83078, 78.66248],
#            [11.80787, 78.66248],
#            [11.80787, 78.67525]]]

**Comment by kvos** [comment]
use observed if you have it available, it's more accurate than modelled tides.
