### ISSUE TITLE
Problem with GEE

### ISSUE THREAD

**Issue by AVane501** [kvos/CoastSat#469]
Can you help me?
Why isn't GEE automatically activated?

**Comment by kvos** [comment]
please follow the installation instructions and raise an issue with a specifc error, thanks

**Comment by AVane501** [comment]
Seguí todos los pasos, pero la autenticación no se realiza automáticamente, cuando ejecuto el código en Jupyter me sale un error incluso después de que la aplicación Google Cloud dice que todo finalizó exitosamente.

Me dijeron que autenticara GEE en Anaconda, pero aparece el siguiente error:
Advertencia de usuario: su aplicación se ha autenticado utilizando las credenciales de usuario final del SDK de Google Cloud sin un proyecto de cuota. Es posible que reciba un error de "cuota excedida" o "API no habilitada". Consulte la siguiente página para solucionar problemas: https://cloud.google.com/docs/authentication/adc-troubleshooting/user-creds .
advertencias.warn(_CLOUD_SDK_CREDENTIALS_WARNING)
Autenticar: las credenciales ya existen. Utilice --force para actualizar.
