### ISSUE TITLE
CoastSAT seasonal and monthly average graphs 

### ISSUE THREAD

**Issue by rhoden1** [kvos/CoastSat#472]
Hi,
I was looking for some advice for producing the final seasonal and monthly average for shoreline changes on the coastsat program at steps 1.6.0.2. 5.2 Seasonal averaging and long-term trends, 1.6.0.3. 5.3 Monthly averages. I have completed and loaded each other section leading up to these and it has produced the correct graphs such as the tidal correction graphs at stage 1.5.4 however when I went to load these last sections nothing appeared. All other sections either showed the graph in that window or created another window with the graph however nothing happened for this step. The circle on the top right which indicates whether the step is running or is completed appears hollow to suggest it has run but graph appears. I have a large data set of accepted shorelines which I initially thought could've been the problem. So I was just wondering if you have any suggestions about what the issue could be and how I could fix it. (My study area is Newgale, Wales)
Thank you very much!!! :)

**Comment by kvos** [comment]
can you please provide more details and screenshots so I can help

**Comment by rhoden1** [comment]
Hi, 
I restarted the Kernel and re-ran all stages of the code and the seasonal and monthly averaging graphs still did not appear. I double checked incase they were produced in other window but couldn't find this. As you can see at the bottom of all the screenshots provided the code has been run and completed to 100% in all sections above the 1.6.0.2 5.2 and 1.6.0.3 5.3. I counted through how many sample shorelines were accepted in the detection stage and I got a total of around 164, this is the only factor I can think that has impacted the production of the graphs possibly? Hopefully this is enough detail? Otherwise let me know! Thank you very much. 
(I have attached screenshots of all stages of my code to hopefully help :) )
 
<img width="1126" alt="Screenshot 2024-01-07 at 17 57 03" src="https://github.com/kvos/CoastSat/assets/154602302/25df9684-4533-41ed-87e8-56b253974f8a">
<img width="1126" alt="Screenshot 2024-01-07 at 17 57 17" src="https://github.com/kvos/CoastSat/assets/154602302/7261a2fb-dfa6-4cba-83dc-7d1549e33b90">
<img width="1126" alt="Screenshot 2024-01-07 at 17 57 23" src="https://github.com/kvos/CoastSat/assets/154602302/8e5993b0-9ebd-4368-8e87-8ebca5703c6f">
<img width="1126" alt="Screenshot 2024-01-07 at 17 57 30" src="https://github.com/kvos/CoastSat/assets/154602302/1baa27f5-f6c6-49a7-a1d0-4739eed4f435">
<img width="1126" alt="Screenshot 2024-01-07 at 17 57 40" src="https://github.com/kvos/CoastSat/assets/154602302/d18d5936-ad73-4d5d-82a4-0c5cf88a1d41">
<img width="1126" alt="Screenshot 2024-01-07 at 17 58 14" src="https://github.com/kvos/CoastSat/assets/154602302/78d03e42-bc46-45ec-9948-f946a2b51801">
<img width="1126" alt="Screenshot 2024-01-07 at 18 01 19" src="https://github.com/kvos/CoastSat/assets/154602302/de5bbd5d-48a2-47e1-9638-c046ce83fba1">
<img width="1126" alt="Screenshot 2024-01-07 at 18 01 22" src="https://github.com/kvos/CoastSat/assets/154602302/e4602e11-a2b0-4691-8d71-0827b768011b">
<img width="1126" alt="Screenshot 2024-01-07 at 18 01 26" src="https://github.com/kvos/CoastSat/assets/154602302/b2e9043b-d713-4845-8028-1ed458db958b">
<img width="1126" alt="Screenshot 2024-01-07 at 18 01 34" src="https://github.com/kvos/CoastSat/assets/154602302/b4967083-9793-4714-aea7-92994d5594ab">
<img width="1126" alt="Screenshot 2024-01-07 at 18 01 39" src="https://github.com/kvos/CoastSat/assets/154602302/0f4bdfb7-7e9f-4e0b-ba8c-fab7ad4c9a55">

**Comment by rhoden1** [comment]
(Also just in case it makes a difference I used option 3 to create my transects)

**Comment by kvos** [comment]
did you make sure that the transects are in the same coordinate system as the shorelines? the one that you specified in settings['output_epsg']. Try to plot the transects on top of the shoreline to check that, cell [11] in your screenshot

**Comment by rhoden1** [comment]
I was meant to say I've been using option 1 sorry for the transects, where I draw them onto the shoreline graph - this worked and allowed me to reach the stage just before the seasonal averages with all the graphs and plots being produced as expected. I also tried option 3 just now to see if that made any difference however that wouldn't work either?

**Comment by rhoden1** [comment]
So I managed to code all of these graphs after the transect positioning stage:
<img width="1508" alt="Screenshot 2024-01-09 at 20 56 04" src="https://github.com/kvos/CoastSat/assets/154602302/dea6adac-f457-4e05-bb6a-4006f67a4b96">
<img width="1508" alt="Screenshot 2024-01-09 at 20 56 12" src="https://github.com/kvos/CoastSat/assets/154602302/8a653f66-10d2-45f7-af3e-a63c3eb3b36f">
<img width="1552" alt="Screenshot 2024-01-09 at 20 56 58" src="https://github.com/kvos/CoastSat/assets/154602302/7f30f052-4f8c-4027-ab37-6a7300fe4e7e">

**Comment by kvos** [comment]
it looks good, just strange that you don't get the seasonal averaging plots.

**Comment by kvos** [comment]
any update on this issue? I will close for the time being, feel free to reopen if needed.
