### ISSUE TITLE
tidal correction plus setup and runup correction!

### ISSUE THREAD

**Issue by ecnun** [kvos/CoastSat#474]
Dear professor,
    I am writing to enquire about how tide plus runup, setup are included in CoastSat.
    In 2.4 tidal correction section, you said castelle et al. did some work about improving the accuracy of extracting shoreline. And then I read carefully this project(Satellite-derived shoreline detection at a high-energy meso-macrotidal beach), but I don't know how it works, and this question  has been troubling me for a long time. I want to know that if I want to incorporate setup and runup correction in the basis of Coastsat, how do I make modifications, whether by altering the code in CoastSat or through other methods?
    Thank you for your patience and cooperation and I look forward to hearing from you soon!

**Comment by kvos** [comment]
hi @ecnun , you will need wave data and beach slope data to estimate setup/runup at the shoreline and then apply that correct to the time-series. You can find code to do that on the latest benchmark repository: https://github.com/SatelliteShorelines/SDS_Benchmark/blob/main/5_evaluate_wave_correction.ipynb. ERA5 wave data is global and freely available. You can also contact Bruno Castelle or Kat Konstantinou for more info on the water level corrections. The recent paper by Konstantinou focuses on water level corrections.

**Comment by ecnun** [comment]
Thank you so much, I think your excellenct work really helps me!
