### ISSUE TITLE
fail to digitize a reference shoreline

### ISSUE THREAD

**Issue by ecnun** [kvos/CoastSat#475]
Dear @kvos 
I feel so sorry to bother you again.When I want to digitize a reference shoreline, I choose the time of 1990-2005, but it failed(see below). And I change the time range(2010-2020), other settings aren't changed, then it works, I feel so confused!
![image](https://github.com/kvos/CoastSat/assets/132353187/5baf3929-87da-417c-b25d-40c16a4da5de)

**Comment by kvos** [comment]
To digitise a shoreline the code is looking for a low cloud image from S2, L8 or L5, if you only have L7 images it produces this exception as it's harder to digitise on L7 due to the diagonal bands of no data. You can create the reference shoreline on any image and then use it for you project.

**Comment by ecnun** [comment]
Dear @kvos 
Thank you so much! The images I downloaded are from L5 and L7, I don't know why the L5 images is not working.
