### ISSUE TITLE
KeyError: 'dimensions' when retrieving S2 imagery

### ISSUE THREAD

**Issue by jammy-data** [kvos/CoastSat#477]
Hi!

I'm currently trying to retrieve shorelines for areas of the tropics. When using the SDS_download.retrieve_images(input) function, I'm able to download Landsat data okay (L5, L7), but when attempting to download S2 data I get the following error:

```
    205 # first delete dimensions key from dictionnary
    206 # otherwise the entire image is extracted (don't know why)
    207 im_bands = image_ee.getInfo()['bands']
--> 208 for j in range(len(im_bands)): del im_bands[j]['dimensions']
    210 #=============================================================================================#
    211 # Landsat 5 download
    212 #=============================================================================================#
    213 if satname == 'L5':

KeyError: 'dimensions'
```

My input variable is as follows:
```
{'polygon': [[[-82.21821320470379, 9.319888981769637],
   [-82.18277399134152, 9.319888981769637],
   [-82.18277399134152, 9.381213196253213],
   [-82.21821320470379, 9.381213196253213],
   [-82.21821320470379, 9.319888981769637]]],
 'dates': ['2016-01-01', '2020-01-01'],
 'sat_list': ['S2'],
 'sitename': 'ZAPA',
 'filepath': 'my_filepath',
 'landsat_collection': 'C02',
 'S2tile': '17PLL'}
```

when running the SDS_download.check_images_available(inputs); function, I get the following output:
```
Number of images available between 2016-01-01 and 2020-01-01:
- In Landsat Tier 1 & Sentinel-2 Level-1C:
Only keeping user-defined S2tile : 17PLL
     S2: 156 images
  Total to download: 156 images
```

The function appears to work for some areas, but for others I'm getting the KeyError: 'dimensions' error. Could be the way ee is picking up the data?

Many thanks Kilian. For the areas that I have been able to map in this region, Coastsat has been a wonderfully insightful and user-friendly tool. Keep up the good work :)

**Comment by gianfrancodp** [comment]
me too on Sentinel2 datasets

**Comment by evecchi** [comment]
same problem for me

**Comment by kvos** [comment]
ok seems to be something on the GEE side, can you comment that line 208 and see what happens? thanks

**Comment by evecchi** [comment]
But I have the same problem whatever the satellite mission used

**Comment by jammy-data** [comment]
> Now the error is not reported. It starts downloading but saying:
> 
> "Download failed, trying again.."

Yep, the same thing happens to me.

**Comment by kvos** [comment]
ok I will take a look asap. only S2 or also Landsat?

**Comment by jammy-data** [comment]
Looks like just S2

**Comment by kvos** [comment]
also raising that error on my end, so definitely something changed in GEE. Will troubleshoot and let you all know.

**Comment by kvos** [comment]
spotted the issue! GEE have added new bands to the S2 scenes, mostly cloudy masks. These do not have a 'dimensions' field.
![image](https://github.com/kvos/CoastSat/assets/7217258/206104ef-1370-451d-bc43-fa4dcff08124)

So I have removed those masks, update your coastsat code and it should all work again!

**Comment by collinjroland** [comment]
I pulled the most recent code and the issue was resolved, thanks Kilian!

**Comment by jammy-data** [comment]
Yep, all working my end too. Thank you Kilian!

**Comment by gianfrancodp** [comment]
Thank K!

**Comment by evecchi** [comment]
Hi everyone! I've encountered this old issue with Sentinel-2 images depending on the selected period.
I previously downloaded the entire 2020-2024 period without any problems. Is anyone else experiencing this?
