### ISSUE TITLE
Spyder: QWidget: Must construct a Qapplication before a Qwidget.

### ISSUE THREAD

**Issue by JuliaS343** [kvos/CoastSat#479]
Hi! I hope you can help. I am currently trying to install the coastsat environment but with spyder included. I am using a yaml file to install the packages.
yaml file:
name: coastsat
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10
  - geopandas
  - earthengine-api
  - scikit-image
  - matplotlib
  - astropy
  - notebook
  - spyder
  - spyder-terminal
  - pip
  - pip:
    - pyqt5
    - imageio-ffmpeg

However, when everything is installed and I try to launch Spyder within the coastsat environment I get the following message: QWidget: Must construct a Qapplication before a Qwidget. It seems that maybe the versions of Pyqt5 and Spyder are not compatible with each other.  It also doesn't seem to work if I follow the instructions on the website and then afterwards install Spyder (with conda install Spyder). Do you know how I can resolve this issue?

**Comment by kvos** [comment]
a good work around is to downloand Mamba and then open the Miniforge Prompt and reinstall everything following the CoastSat commands but using `mamba` instead of `conda`. It is much faster and much better at resolving conflicts so allows you to install spyder too. Have a go and let me know if any issues.

**Comment by JuliaS343** [comment]
Hi Kvos, I tried it today with Miniforge and with the yaml file. However, I still get the same message when launching Spyder. I can have another try without the yaml file and then following the coastsat commands, but where can I best add spyder in these lines?

**Comment by kvos** [comment]
I think it's better not to use yml file but instead enter the commands one by one. Follow the order on the README and add at the end `mamba install -c conda-forge spyder`. That's the way I install the environment.

**Comment by JuliaS343** [comment]
Yes that worked. Thank you!
