### ISSUE TITLE
Trying to retrieve GG imagery

### ISSUE THREAD

**Issue by melimore86** [kvos/CoastSat#48]
I'm trying to use my study site in the GEE and I'm using this code

polygon = [[[29.242207, -83.090314],
            [29.229097, -83.092357],
            [29.229088, -83.068519],
            [29.245553, -83.068872]]]   

dates = ['2015-01-01', '2017-012-01']

sat_list = ['L5']

sitename = 'LCR'

filepath = os.path.join(os.getcwd(), 'data')

inputs = {'polygon': polygon, 'dates': dates, 'sat_list': sat_list, 'sitename': sitename, 'filepath':filepath}

I was getting an error 404, but I enabled the widgets and that went away. It just keeps loading without downloading any images. I can send a screenshot too if that helps. Can you check if that range works for you?

**Comment by kvos** [comment]
hi @melimore86 , the polygon should have 5 pairs of coordinates, where the last pair is identical to the first one. Let me know if this fixes the issue. Also error 404 may happen if your request to Google Earth Engine has not been approved yet

**Comment by melimore86** [comment]
I was able to use my google API token for your example code, so I think it should work for the new coordinates I put it.  I added the fifth pair of coordinates, and it still just loading, with no number of downloaded images in the Downloading Images: . Should the coordinates of the polygon be certain clock-wise or counterclockwise in the code?

**Comment by kvos** [comment]
so the problem is that there are no L5 images for the dates that you selected, unfortunately L5 stopped in 2011...try changing the sat_list to 'L7', 'L8', 'S2' and you will get plenty of images

**Comment by melimore86** [comment]
Maybe it just takes a long time to locate and retrieve the images. I changed L5 to 'L7', 'L8' and it just keeps trying to download. Like a never-ending loading loop.

**Comment by melimore86** [comment]
nvmd I totally figured it out, typos. I'm not getting any images, I might have to expand my polygon.
