### ISSUE TITLE
Downloading question and reference shoreline question

### ISSUE THREAD

**Issue by ecnun** [kvos/CoastSat#480]
Dear @kvos 
Thank you so much for your great work! And I have two questions that have been bothering me for a long time.
The first question: When I run the step shown in Figure 1(downloading the images from GEE), it always displays that there is a connection issue, I have never encountered this problem when downloading smaller amounts of data before, and I try it again and again, but it doesn't works. So I would like to ask if you have ever encountered this situation before, and how should this issue be resolved?
The second question: About one month ago, I consulted you with a question. You said that the landsat7 images cannot be used for reference shoreline and that images from other images should be used instead. However, I am facing an issue, I have downloaded over 100 images from landsat5 for the time span of 1986-2000, only 2 images from landsat7, but it still doesn't works(please see Figure2).
![image](https://github.com/kvos/CoastSat/assets/132353187/6e0bf082-0967-4c89-a880-b72ad89d04cb)
![image](https://github.com/kvos/CoastSat/assets/132353187/49320017-bb5b-4e07-9bfe-8ec357745bb4)

**Comment by ecnun** [comment]
![image](https://github.com/kvos/CoastSat/assets/132353187/07094039-bdb7-4b70-8e5f-cdd641619a05)
This picture is a supplementary image to the Figure 1.

**Comment by kvos** [comment]
hi @ecnun , for the HTTPSConection error this is probably due to a firewall on your side, try to suspend any firewall so that you can make the API requests to earthengine.googleapis.com.

For the second, you need to download a S2/L8/L9 image to digitise the shoreline.

**Comment by ecnun** [comment]
Thank you so much，I will try it again.
