### ISSUE TITLE
Sentinel-2 images failed to download

### ISSUE THREAD

**Issue by claudioasn** [kvos/CoastSat#481]
Hello, I have tried to implement CoastSat, but the Sentinel-2 images are always giving an error when downloading, as shown in the attached images. Landsat works. I've tried updating the SDS_download file that was recently modified, but it didn't work either. Are we making a mistake in the code?

![Imagem do WhatsApp de 2024-02-26 à(s) 13 33 04_347eb4d5](https://github.com/kvos/CoastSat/assets/104084558/66d44529-12a0-4e2f-b989-c127ee4f9c90)

![Imagem do WhatsApp de 2024-02-26 à(s) 13 34 25_cdbedda1](https://github.com/kvos/CoastSat/assets/104084558/1a4df6a5-658a-44a9-ac02-ec40221e4c8a)

**Comment by kvos** [comment]
thanks for reporting this, I think it's the latest change that I have done. I have just reverted it, so take the latest version of SDS_download.py and try again, let me know

**Comment by claudioasn** [comment]
Thanks @kvos . It worked now to download the sentinel-2 images. But now we are getting a new error when we try to use the transects. We vectorize them in qgis, saved in geojson and tried to use, but we are having this error:

![Imagem do WhatsApp de 2024-02-29 à(s) 12 43 07_6cb26d3f](https://github.com/kvos/CoastSat/assets/104084558/89886b35-8e94-413d-8c04-d547e346c7c8)

Any ideas? The geojson we are using is attached.

[transectos_beberibe_canto_verde.zip](https://github.com/kvos/CoastSat/files/14450744/transectos_beberibe_canto_verde.zip)

**Comment by amycarrillo164** [comment]
Hi @kvos. I'm having a similar issue with the the data download. 
![Screenshot 2024-03-02 155827](https://github.com/kvos/CoastSat/assets/121639717/33095159-9783-46cd-bcc1-a9baaa8642c5)

**Comment by kvos** [comment]
they need to have a field called 'name' with the identifier for each transect. Also make sure they are in the same projected coordinate system as the shorelines.
