### ISSUE TITLE
CoastSat running on Colab: error with the pyfes package

### ISSUE THREAD

**Issue by cianfabio** [kvos/CoastSat#482]
Hi,
I'm trying to run CoastSat on Colab. I managed to get it running until the point where pyfes is needed. I managed to install pyfes but when I run the following line:

```
# Option 1. if FES2014 global tide model is setup
# point to the folder where you downloaded the .nc files
filepath = r'/content/drive/MyDrive/aviso-fes-main/data/fes2014'
config_ocean = os.path.join(filepath, 'ocean_tide.ini') # change to ocean_tide.ini
config_load =  os.path.join(filepath, 'load_tide.ini')  # change to load_tide.ini
ocean_tide = pyfes.Handler("ocean", "io", config_ocean)
load_tide = pyfes.Handler("radial", "io", config_load)
```
I get the following error:

```
AttributeError                            Traceback (most recent call last)
[<ipython-input-14-f2ca7493019e>](https://localhost:8080/#) in <cell line: 7>()
      5 config_ocean = os.path.join(filepath, 'ocean_tide.ini') # change to ocean_tide.ini
      6 config_load =  os.path.join(filepath, 'load_tide.ini')  # change to load_tide.ini
----> 7 ocean_tide = pyfes.Handler("ocean", "io", config_ocean)
      8 load_tide = pyfes.Handler("radial", "io", config_load)
      9 

AttributeError: module 'pyfes' has no attribute 'Handler'
```

Any idea?
Thanks

**Comment by kvos** [comment]
hi @cianfabio, I don't think you will be able to run that tide component in collab as you need to have all the NETCDF files with the tidal components stored locally to run pyfes. Better run it in a normal jupyter notebook and download the tide files as described in the documentation to install pyfes (sing in to aviso, download 8gb of netcdf files etc). Documentation here https://github.com/kvos/CoastSat.slope/blob/master/doc/FES2014_installation.md
