### ISSUE TITLE
L7 scanline error

### ISSUE THREAD

**Issue by yukinoashita** [kvos/CoastSat#484]
![Figure_error](https://github.com/kvos/CoastSat/assets/132147461/1e3c804f-9b33-44c5-9f6b-261675dd5634)

hi, Dr. kilian

When I extract the coastline of Egmond, sometimes a part of the coastline cannot be drawn (as shown in the picture below, you can see a gap in the upper part of the coastline).

I have already set 'dist_clouds' to 10, so it should not be a problem caused by this parameter. Do you have any thoughts on this issue?

thank you!

**Comment by kvos** [comment]
hi @yukinoashita , I think that has more to do with the minimum shoreline length parameter, if the shoreline map is shorter than the length specified by that paremeter it gets discarded. I think you will struggle to find a way to map those little corners of L7 imagery without introducing too much noise.

Kilian

**Comment by jimpaulobautista** [comment]
Hi, are you using Landsat 7 on your analysis? If yes, the lines might be due to scanline error (diagonal white lines)  of the satellite images and not the performance of CoastSat. 

jim

**Comment by yukinoashita** [comment]
> Hi, are you using Landsat 7 on your analysis? If yes, the lines might be due to scanline error (diagonal white lines) of the satellite images and not the performance of CoastSat.
> 
> jim

hi, yes! thank you for the reply, I have checked the output geojson file, it really have some scanling error.... how could I fix it?

**Comment by jimpaulobautista** [comment]
There's no way to fix this unless you use other processing steps which are outside of the functionalities of CoastSat. Consider using Landsat 8 if there's an available data for it.
