### ISSUE TITLE
Error about SDS_download.retrieve_images(inputs) 

### ISSUE THREAD

**Issue by wangth6** [kvos/CoastSat#485]
<img width="793" alt="屏幕截图 2024-03-19 013325" src="https://github.com/kvos/CoastSat/assets/163897795/acedada3-7f42-411e-abf6-ebee2f6125f9">
 Hi @kvos , could give me some suggestion?
The download for satellite S2 image ' failed due to AttributeError
Attempt 1/3 failed with error: SSLError

**Comment by kvos** [comment]
this doesn't look like the coastsat output , can you send your inputs so I can test, thanks
