### ISSUE TITLE
Images not downloading

### ISSUE THREAD

**Issue by lsaamu** [kvos/CoastSat#487]
Hi Vos.

I am new to coastsat. I tried to run your code in your EVA island project and it gives me this error below:

RefreshError: ('invalid_grant: Token has been expired or revoked.', {'error': 'invalid_grant', 'error_description': 'Token has been expired or revoked.'})

Can you explain what caused this error?

Thanks

**Comment by kvos** [comment]
try to run:
```
import ee
ee.Authenticate()
```
This should authenticate you again.

**Comment by lsaamu** [comment]
> try to run:
> 
> ```
> import ee
> ee.Authenticate()
> ```
> 
> This should authenticate you again.

Thanks Vos, it successfully run. I tried it on my study site Tepuka Cay in Tuvalu, and it only shows this output below.
![image](https://github.com/kvos/CoastSat/assets/37644514/aa1d6aab-c5dc-4d15-8325-1abc15bd3b28)
It does not show the number of images like when I run it for EVA, it shows the number of images available to download. Do you think it's because there are no images available on those dates mentioned in the code?
![Screenshot 2024-04-11 130737](https://github.com/kvos/CoastSat/assets/37644514/cf3a952c-8e6b-440e-8a35-6b11c95f5342)

**Comment by kvos** [comment]
I'm not sure, can you post your full settings so I can have a look?

**Comment by lsaamu** [comment]
> I'm not sure, can you post your full settings so I can have a look?

Hi Vos,

Find attached below image for my setting...

![image](https://github.com/kvos/CoastSat/assets/37644514/c82dc44e-cc67-489a-b977-48f18dec67c1)

Thanks

**Comment by kvos** [comment]
@lsaamu can you please share the kml file?

**Comment by kvos** [comment]
closing for now, reopen it if needed
