### ISSUE TITLE
Coastline extraction from Planet Images

### ISSUE THREAD

**Issue by Jenny-hub** [kvos/CoastSat#49]
Hello! Congratulations for Coast Sat, I really like it. I have a question for you. Is it possible somehow to extract coastlines from Planet Imagery? I already have some images saved in my laptop. What changes should I try in the code? I tried to run it as it is and I have an error message 'no L7 images'.

Thank you

**Comment by kvos** [comment]
hi @Jenny-hub , at the moment CoastSat does not support Planet Labs imagery but we are working on implementing this, it should be ready shortly, I'll let you know.

**Comment by Jenny-hub** [comment]
Hi! Thank you very much for your response. Please let me know because I would like to use it (with the references of course) to my master thesis. Do you believe it will be available in the next 2 months?

**Comment by kvos** [comment]
hi @Jenny-hub, unfortunately as the Christmas break is coming soon, everything will be on hold until next year mid-Jan/Feb...

**Comment by natarslan** [comment]
This would be a fantastic implementation. I can use this for my thesis also. Would love to get updates on this.

**Comment by kvos** [comment]
yes so @ydoherty is currently developing the automatic shoreline detection on Planet Labs imagery, you can follow his fork of CoastSat for updates. The shorelines derived from Planet Labs imagery will also be validated against in situ data. If you have images and associated groundtruth shoreline data you can also contribute to the validation.

**Comment by ydoherty** [comment]
Hi @natarslan, the CoastSat.PlanetScope repo is now live. Apologies for the long wait and hope it's not too late! 

https://github.com/ydoherty/CoastSat.PlanetScope

**Comment by ydoherty** [comment]
Hi @Jenny-hub @natarslan, the CoastSat.PlanetScope repo is now live. Apologies for the long wait and hope it's not too late! 

https://github.com/ydoherty/CoastSat.PlanetScope

**Comment by natarslan** [comment]
Thank you for the update. It looks amazing and Im looking forward to testing it.

Have a lovely day.
Nat

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by kvos** [comment]
just a quick update on this, a preprint has now been uploaded https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4052360
and toolbox is still being maintained
