### ISSUE TITLE
The meanings of the values before and after tidal adjustment, respectively.

### ISSUE THREAD

**Issue by ecnun** [kvos/CoastSat#491]
Thank you for your good work!
I have a problem that troubling me a long time. If the data in the file named "transect_time_series" indeed represents the distance from a starting point on land to the extracted coastline, then the same data in another file named "transect_time_tidally_series" should also represent this distance. If this is the case, I have a question: why would the shoreline, after being adjusted for tide levels, be closer to the sea rather than moving towards the land, as is typically expected?"(see below: the value 157.3456 is the original value, and the 159.6383 is the value after tidal adjustment.) And I would like to know what the numbers 157.3456 and 159.6383 represent respectively. I am concerned that my understanding may be incorrect.
Thank you so much, our team has already conducted extensive research on the coastline of Eastern China using CoastSat, and we hope to have the opportunity to continue collaborating with you!
![image](https://github.com/kvos/CoastSat/assets/132353187/008c07cf-5170-41b5-a252-94b54dc9e2d4)

**Comment by kvos** [comment]
if that image was taken on high tide, then when you apply a tidal correction you will move the shoreline seawards to mean sea level. On the other hand if the image is taken at low tide, then you move the shoreline landwards towards mean sea level. I hope this makes sense.

**Comment by ecnun** [comment]
Thank you, I found that there is a difference between the datum plane of FES2014 and the commonly used datum plane in China. FES2014 uses the mean sea level, while China uses the mean high tide level as the baseline for coastal line measurement.
