### ISSUE TITLE
error while downloading

### ISSUE THREAD

**Issue by Karorolina** [kvos/CoastSat#497]
EDIT: Problem solved: I had to manually create a destination folder in coastsat data folder. After I have created one - the script started to work. 

Hello,
I try to download the Landsat9 data 01-02-2022 - 01-01-2022. After the command:

metadata = SDS_download.retrieve_images(inputs)_

I get the error message (pasted below). The coastsal works fine on exemplary data from kvos Github - example from Narrabeen-Collaroy beach (Australia). Thanks in advance for help. Please see below for the error message:

---------------------------------------------------------------------------
HttpError                                 Traceback (most recent call last)
File ~\anaconda3\envs\coastsat\Lib\site-packages\ee\data.py:402,**** in _execute_cloud_call(call, num_retries)
    401 try:
--> 402   return call.execute(num_retries=num_retries)
    403 except googleapiclient.errors.HttpError as e:

File ~\anaconda3\envs\coastsat\Lib\site-packages\googleapiclient\_helpers.py:130, in positional.<locals>.positional_decorator.<locals>.positional_wrapper(*args, **kwargs)
    129         logger.warning(message)
--> 130 return wrapped(*args, **kwargs)

File ~\anaconda3\envs\coastsat\Lib\site-packages\googleapiclient\http.py:938, in HttpRequest.execute(self, http, num_retries)
    937 if resp.status >= 300:
--> 938     raise HttpError(resp, content, uri=self.uri)
    939 return self.postproc(resp, content)

HttpError: <HttpError 400 when requesting https://earthengine.googleapis.com/v1/projects/ee-km429km429/value:compute?prettyPrint=false&alt=json returned "Geometry.transform: Unable to transform geometry to EPSG:32608: affine [30.0, 0.0, 291585.0, 0.0, -30.0, 6631515.0]". Details: "Geometry.transform: Unable to transform geometry to EPSG:32608: affine [30.0, 0.0, 291585.0, 0.0, -30.0, 6631515.0]">

During handling of the above exception, another exception occurred:

EEException                               Traceback (most recent call last)
Cell In[3], line 2
      1 #inputs['include_T2'] = True
----> 2 metadata = SDS_download.retrieve_images(inputs)

File ~\Documents\coastsat\coastsat\SDS_download.py:286, in retrieve_images(inputs)
    284 proj_ms = image_ee.select('B1').projection()
    285 proj_pan = image_ee.select('B8').projection()
--> 286 ee_region_ms = adjust_polygon(inputs['polygon'],proj_ms)
    287 ee_region_pan = adjust_polygon(inputs['polygon'],proj_pan)
    289 # download both ms and pan bands from EE

File ~\Documents\coastsat\coastsat\SDS_download.py:745, in adjust_polygon(polygon, proj)
    743 polygon_ee = ee.Geometry.Polygon(polygon)    
    744 # convert polygon to image coordinates
--> 745 polygon_coords = np.array(ee.List(polygon_ee.transform(proj, 1).coordinates().get(0)).getInfo())
    746 # make it a rectangle
    747 xmin = np.min(polygon_coords[:,0])

File ~\anaconda3\envs\coastsat\Lib\site-packages\ee\computedobject.py:107, in ComputedObject.getInfo(self)
    101 def getInfo(self) -> Optional[Any]:
    102   """Fetch and return information about this object.
    103 
    104   Returns:
    105     The object can evaluate to anything.
    106   """
--> 107   return data.computeValue(self)

File ~\anaconda3\envs\coastsat\Lib\site-packages\ee\data.py:1107, in computeValue(obj)
   1104 body = {'expression': serializer.encode(obj, for_cloud_api=True)}
   1105 _maybe_populate_workload_tag(body)
-> 1107 return _execute_cloud_call(
   1108     _get_cloud_projects()
   1109     .value()
   1110     .compute(body=body, project=_get_projects_path(), prettyPrint=False)
   1111 )['result']

File ~\anaconda3\envs\coastsat\Lib\site-packages\ee\data.py:404, in _execute_cloud_call(call, num_retries)
    402   return call.execute(num_retries=num_retries)
    403 except googleapiclient.errors.HttpError as e:
--> 404   raise _translate_cloud_exception(e)

EEException: Geometry.transform: Unable to transform geometry to EPSG:32608: affine [30.0, 0.0, 291585.0, 0.0, -30.0, 6631515.0]

**Comment by kvos** [comment]
your dates are inverted

**Comment by Karorolina** [comment]
Perfect!!!! Thank you - I am just trying to fix that...
Greetings, Karolina
________________________________
Od: Kilian Vos ***@***.***>
Wysłane: piątek, 24 maja 2024 15:42
Do: kvos/CoastSat ***@***.***>
DW: Karolina Leszczyńska ***@***.***>; Author ***@***.***>
Temat: Re: [kvos/CoastSat] error while downloading (Issue #497)


your dates are inverted

**Comment by Karorolina** [comment]
I did fixe the dates, they are not inverted anymore, however the error persists... I am new to phyton, however it seems to me that there is something wrong with the path... Is it?

**Comment by kvos** [comment]
can you share your inputs? if it worked with NArrabeen example it must be a formatting issue with the new inputs that you provided.

**Comment by Karorolina** [comment]
Thank you Kilian, the problem solved without sharing the inputs.  I had to manually create a destination folder in coastsat data folder. After I have created one - the script started to work.

**Comment by kvos** [comment]
ok will close the issue for now
