### ISSUE TITLE
Transect issues

### ISSUE THREAD

**Issue by jobthoma97** [kvos/CoastSat#499]
Hi @kvos ,

I have loaded the transects using coordinates.

I was able to load it successfully. In the transect plot it's showing all the 5 transects but after computing the transects, on the multiple subplot graph figure its only showing for transect  number 4.

In the Excel sheet also its showing the distance for 1 transect.

How to resolve this ?

Below I have attached the images.
Transect Plot Map.
![Coastsat_TransectPlot](https://github.com/kvos/CoastSat/assets/85024689/b386f798-5fa3-4ab6-b043-ca7df208c53f)

Transect Subplot Graph.
![Coastsat_TransectPlot2](https://github.com/kvos/CoastSat/assets/85024689/d1819327-fe3d-49d5-aa24-1e508f4730ed)

Transect distance CSV.
![Coastsat_TransectPlot3](https://github.com/kvos/CoastSat/assets/85024689/7b9d34ee-ccbb-4996-a67b-73fe3992c4f7)

**Comment by 2320sharon** [comment]
Hi @jobthoma97 

The reason you only see a single transect plotted is because only that transect intersected your shoreline. In the CSV the date represents the time the shoreline was captured and each column is the transect ID. All the transects except  NA4 are blank which means they didn't intersect the shoreline captured in 2018. Without knowing your shoreline data I can't tell why that's the case, but I hope this helps!

It might be worth double checking that the shoreline and the transects are in the same CRS. I've made that mistake a lot.

**Comment by jobthoma97** [comment]
Hi @2320sharon ,

Thank you for replying.

I cross checked the CRS for transect and the CoastSat_Shoreline for 2018, they are both on the same CRS(32614).

I overlayed the transects and the output shoreline from CoastSat in QGIS, they intersect with the transects.

Below I have attached the Metadata, HTML FIle of the Jupyter Notebook and the output of shoreline overlayed on the transects.
Please have a look.

##-----------------Jupyter Script PDF File -------------------------------##
[San_Jose_Texas.pdf](https://github.com/user-attachments/files/15812507/San_Jose_Texas.pdf)



##-----------------Transect Metadata -------------------------------##
![Coastsat_Transects_pts](https://github.com/kvos/CoastSat/assets/85024689/8838f598-e5be-4cde-8826-733555b08272)




##-----------------Shoreline Metadata -------------------------------##
![Coastsat_Shoreline_2018](https://github.com/kvos/CoastSat/assets/85024689/a7468901-98ba-4756-9fc1-40ee01204347)





##-----------------Output File of Shoreline from CoastSat and Transect shapefile -------------------------------##



![Coastsat_Transects_Shoreline](https://github.com/kvos/CoastSat/assets/85024689/8f997790-85d0-4f81-893d-61cc90ac5552)

**Comment by kvos** [comment]
hi @jobthoma97 , so you only have 1 shoreline mapped but you should get a value for each transect, not just NA4. Can you try to run the simple compute intersections? see what happens. I'm guessing some of the QC parameters is discarding the intersections for the other transects...
![image](https://github.com/kvos/CoastSat/assets/7217258/f02f0f4d-9b7f-4182-a400-1329e938b49f)

**Comment by jobthoma97** [comment]
Hello @kvos ,

Thank you for the reply. 
I forgot to mention, I was able to resolve the error.

Yes I have only one shoreline and as you said it should give the value for each transect.
The issue was with the length of the transects from on-shore to the shoreline intersection point.

The length for NA1 from on-shore to the shoreline intersection point was 1.207 KM, for NA2 it was 1.270 KM, NA3 it was 1.083 KM, NA5 it was 1.302 KM and NA4 it was 0.966 KM.

Then later I shorten the length of the transects and it was able to plot all subplots for 5 transect intersection points.

Then for confirmation I checked the python script for SDS_transects.py and on line 220 " idx_dist = np.logical_and(d_line <= settings['along_dist'], d_origin <= 1000)"  this was mentioned as well on line 321 "idx_dist = np.logical_and(d_line <= along_dist, d_origin <= 1000)". 

I think this was the reason it was only plotting for NA4. 

Am I on the right track or something else was the reason for this to happen.

**Comment by kvos** [comment]
that's exactly it, I had forgotten about that hard-coded 1km distance. Maybe we should increase it to 5km? we need to restrict it somehow as the equation we're using is point to line distance, which is not limited by distance and in case of someone putting transects that are not in the same coordinates as the shorelines it will give some false results. What do you think @2320sharon  @jobthoma97 ?

**Comment by 2320sharon** [comment]
I'm happy I could help @jobthoma97 . I'm glad you got it all sorted out.

@kvos we've also run into issues with the hardcoded max distance of 1km in `idx_dist = np.logical_and(d_line <= settings['along_dist'], d_origin <= 1000)`.  Just like @jobthoma97 we couldn't figure out why we weren't getting shorelines with our long transects. I think having a new setting called something like `max_distance_origin` to control this hard coded parameter would be useful. Some kind of log or error message to capture the points that were filtered out by  `idx_dist = np.logical_and(d_line <= settings['along_dist'], d_origin <= 1000)` could be helpful too.
