### ISSUE TITLE
Digitise reference shoreline issue

### ISSUE THREAD

**Issue by ncirrito** [kvos/CoastSat#502]
Hi Kilian

Any chance you can help debug on why I keep getting an index issue after using the interactive reference shoreline clicking.

thanks! ![Screenshot 2024-06-13 at 11 20 10 AM](https://github.com/kvos/CoastSat/assets/147433881/c7e053f0-445c-427a-b968-bfbfd9c31604)

**Comment by kvos** [comment]
I need a bit more info about this error. Where you just digitising a shoreline or multiple? can you show a screnshot of the shoreline you digitised

**Comment by ncirrito** [comment]
I was just attempting to digitize a shoreline for 'usa_CA_0010', but I
often receive this error when cycling through updates for the entire coast.
At times, the reference shoreline coordinates are saved, allowing the rest
of the code to continue running. I have included a screenshot from when I
ran 'usa_CA_0011', where the reference shoreline works after manually
clicking through. I have also included the code I am using. Thank you in
advance!


Nick Cirrito, MAS
Coastal Processes Group <https://siocpg.ucsd.edu/> | Field Researcher II
***@***.*** | (626) 833-7187

**Comment by randibolt** [comment]
Hi Kilian,
Can you help me? I always get errors with this syntax. Thx
![image](https://github.com/kvos/CoastSat/assets/173237988/f9dd4e81-066a-43da-9ac9-a5b707b99975)

**Comment by kvos** [comment]
> the reference shoreline coordinates are saved, allowing the rest of the code to continue running. I have included a screenshot from when I ran 'usa_CA_0011', where the reference shoreline works after manually clicking through. I have also included the code I am using. Thank you in advance!

I can't see the code nor screenshot.

**Comment by kvos** [comment]
> Hi Kilian, Can you help me? I always get errors with this syntax. Thx ![image](https://private-user-images.githubusercontent.com/173237988/341170811-f9dd4e81-066a-43da-9ac9-a5b707b99975.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkwMTEwMjYsIm5iZiI6MTcxOTAxMDcyNiwicGF0aCI6Ii8xNzMyMzc5ODgvMzQxMTcwODExLWY5ZGQ0ZTgxLTA2NmEtNDNkYS05YWM5LWE1YjcwN2I5OTk3NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyMVQyMjU4NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNmY3MmVhMjNiN2VjODI4ZDE0NjVhNzdkMTcxNGRhODEwMjc1MzQ0ZDg4NzA1ZmM4MmE1ZDY1OTdkNDczYjA0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._3ek5RywyOVi53BVxm62Ht6jnXElj0-pGF1577T5Flw)

please open a separate issue and add more information about this issue and how to recreate it, otherwise I can't help

**Comment by ncirrito** [comment]
![Screenshot 2024-06-24 at 9 53 39 AM](https://github.com/kvos/CoastSat/assets/147433881/5f039616-35c2-4727-9c63-d618059432b1)
<img width="1908" alt="Screenshot 2024-06-24 at 9 53 46 AM" src="https://github.com/kvos/CoastSat/assets/147433881/a9505df7-203b-46dc-a948-4aada538cb26">
My apologies, here is a screenshot of the shoreline I digitized. Thank You!

**Comment by kvos** [comment]
did you try clicking on the "end" button once digitised?

**Comment by ncirrito** [comment]
https://github.com/kvos/CoastSat/assets/147433881/08720ea5-cc85-4f3b-9c15-4c63726a282a

It will not allow me to select 'end'. I have a attached a video for reference.

**Comment by kvos** [comment]
that's strange, try to click close to the button but not on the button. Alternatively, try using the right arrow on keyboard
