### ISSUE TITLE
Nan values in cross distance

### ISSUE THREAD

**Issue by evecchi** [kvos/CoastSat#504]
Hello @kvos,

I'm encountering an issue with the cross-distance calculation. I have generated my transects as geojson and loaded them into Jupyter. Everything seems to be functioning correctly until the point where the cross distances are computed, because I'm getting NaN values for several of them.
I don't think the issue is related to the CRS, since some distances have reasonable values, and I've also verified how the starting and ending points are defined for each transect.

I attach here an image.
![Screenshot 2024-06-14 101750](https://github.com/kvos/CoastSat/assets/91685773/f6beff22-db0d-48f7-9841-4a5e4c4727d9)
 What would you suggest?

Thank you in advance.

Enrica

**Comment by kvos** [comment]
are the transects longer than 1km? there is something hard-coded to be within 1km from transect origin, see issue #499 . 
Please try first to compute the intersections with the normal function SDS_transects.compute_intersections(), before using the QA version that has more parameters. Let me know if that fixes the issue.

**Comment by evecchi** [comment]
Actually no, they are shorter! I'll have a look at that issue and let you know.
Thanks!

**Comment by kvos** [comment]
did you try the simple compute_intersections()?

**Comment by evecchi** [comment]
I found that the issue is related to the clipping operation of the output points I added to the script.
While in Qgis I can see that the Coastsat output points and the clipped ones have the same extension, for example when I plot them by:

_fig = plt.figure()
plt.axis('equal')
plt.xlabel('Eastings')
plt.ylabel('Northings')
plt.grid(linestyle=':', color='0.5')

for i in range(len(output['shorelines'])):
    sl = output['shorelines'][i]
    date = output['dates'][i]
    plt.plot(sl[:,0], sl[:,1], '.', label=date.strftime('%d-%m-%Y'))
#plt.legend();_

the extension of the clipped dataset is smaller and equal to the area where the transect values are computed.
I will try to fix this by analysing which parameter of my clipping operation can affect how the dataset extension is read.
Do you have any suggestions?

Thanks

Enrica
