### ISSUE TITLE
the change of slope

### ISSUE THREAD

**Issue by ecnun** [kvos/CoastSat#505]
Hi @kvos 
I have a question, I understand that the slope remains constant throughtout the operation, regardless of the time span, I am not sure if my understanding is correct. If I extract this beach over a long time scale, the beach slope will change, Is there any simple method for handling this question?

**Comment by kvos** [comment]
hi @ecnun , no there isn't really. If you have measured slopes from topographic surveys you can use time-varying slopes for your tidal correction, otherwise if you are getting the slope from CoastSat.slope it's a single estimate for the whole period.

**Comment by ecnun** [comment]
ok,thank you so much
