### ISSUE TITLE
Unable to download images

### ISSUE THREAD

**Issue by devas-hub** [kvos/CoastSat#506]
Hi Sir.

I tried to run this code for the Indian Wes Coast (Kerala), and I am getting the following error:

########################################################
# region of interest (longitude, latitude) for the Kerala coast
     
polygon = [[[76.19354816240269, 10.194892828303509],
    [76.09654129601165, 10.160805367504707],
    [76.22587839113135, 9.753616721843557],
    [76.32057162148686, 9.780930081992864],
    [76.19354816240269, 10.194892828303509]]]
# it's recommended to convert the polygon to the smallest rectangle (sides parallel to coordinate axes)       
polygon = SDS_tools.smallest_rectangle(polygon)
# date range
dates = ['2016-03-01', '2016-05-01']
# satellite missions ['L5','L7','L8','L9','S2']
sat_list = ['S2']
# choose Landsat collection 'C01' or 'C02'
collection = 'C02'
# name of the site
sitename = 'Keralacoast'
# directory where the data will be stored
filepath = os.path.join(os.getcwd(), 'data')
# put all the inputs into a dictionary
inputs = {'polygon': polygon, 'dates': dates, 'sat_list': sat_list, 'sitename': sitename, 'filepath':filepath,
         'landsat_collection': collection}
# before downloading the images, check how many images are available for your inputs
SDS_download.check_images_available(inputs)
##################################################################
No error here in the above cell
##################################################################
Number of images available between 2016-03-01 and 2016-05-01:
- In Landsat Tier 1 & Sentinel-2 Level-1C:
     S2: 12 images
  Total to download: 12 images

Downloading images:
S2: 12 images

Download failed, trying again...

Download failed, trying again...

Download failed, trying again...

Download failed, trying again...

Download failed, trying again...

Download failed, trying again...

Download failed, trying again...

Download failed, trying again...

###################################################################
here, this is the error I have been getting

Could you please explain what I am doing wrong here?

Thanks

**Comment by kvos** [comment]
maybe your polygon is too big, try with a smaller polygon, less than 100 sqkm to see if it works

**Comment by devas-hub** [comment]
The polygon size was taken for a small beach and worked perfectly!
