### ISSUE TITLE
CRSError: Invalid projection: EPSG:32756: (Internal Proj Error: proj_create: no database context specified)

### ISSUE THREAD

**Issue by Phuongtran75** [kvos/CoastSat#507]
Dear Kvos,

When I run your original code, I encounter an issue. Could you please help me check why it's causing an error?

Thanks,
---------------------------------------------------------------------------
CRSError                                  Traceback (most recent call last)
Cell In[21], line 2
      1 get_ipython().run_line_magic('matplotlib', 'qt')
----> 2 settings['reference_shoreline'] = SDS_preprocess.get_reference_sl(metadata, settings)
      3 settings['max_dist_ref'] = 100 # max distance (in meters) allowed from the reference shoreline

File ~\OneDrive\Phuong_research\THESIS_PHUONG\CoastSat-master_new\CoastSat-master\coastsat\SDS_preprocess.py:981, in get_reference_sl(metadata, settings)
    979 # convert world image coordinates to user-defined coordinate system
    980 image_epsg = metadata[satname]['epsg'][i]
--> 981 pts_coords = SDS_tools.convert_epsg(pts_sl, image_epsg, settings['output_epsg'])
    983 # save the reference shoreline as .pkl
    984 filepath = os.path.join(filepath_data, sitename)

File ~\OneDrive\Phuong_research\THESIS_PHUONG\CoastSat-master_new\CoastSat-master\coastsat\SDS_tools.py:145, in convert_epsg(points, epsg_in, epsg_out)
    123 """
    124 Converts from one spatial reference to another using the epsg codes
    125 
   (...)
    141     
    142 """
    144 # define transformer
--> 145 proj = pyproj.Transformer.from_crs(epsg_in, epsg_out, always_xy=True)
    147 # transform points
    148 if type(points) is list:

File ~\anaconda3\envs\coastsat\lib\site-packages\pyproj\transformer.py:627, in Transformer.from_crs(crs_from, crs_to, always_xy, area_of_interest, authority, accuracy, allow_ballpark, force_over, only_best)
    552 @staticmethod
    553 def from_crs(
    554     crs_from: Any,
   (...)
    562     only_best: Optional[bool] = None,
    563 ) -> "Transformer":
    564     """Make a Transformer from a :obj:`pyproj.crs.CRS` or input used to create one.
    565 
    566     See:
   (...)
    623 
    624     """
    625     return Transformer(
    626         TransformerFromCRS(
--> 627             cstrencode(CRS.from_user_input(crs_from).srs),
    628             cstrencode(CRS.from_user_input(crs_to).srs),
    629             always_xy=always_xy,
    630             area_of_interest=area_of_interest,
    631             authority=authority,
    632             accuracy=accuracy if accuracy is None else str(accuracy),
    633             allow_ballpark=allow_ballpark,
    634             force_over=force_over,
    635             only_best=only_best,
    636         )
    637     )

File ~\anaconda3\envs\coastsat\lib\site-packages\pyproj\crs\crs.py:501, in CRS.from_user_input(cls, value, **kwargs)
    499 if isinstance(value, cls):
    500     return value
--> 501 return cls(value, **kwargs)

File ~\anaconda3\envs\coastsat\lib\site-packages\pyproj\crs\crs.py:348, in CRS.__init__(self, projparams, **kwargs)
    346     self._local.crs = projparams
    347 else:
--> 348     self._local.crs = _CRS(self.srs)

File ~\anaconda3\envs\coastsat\lib\site-packages\pyproj\_crs.pyx:2378, in pyproj._crs._CRS.__init__()

CRSError: Invalid projection: EPSG:32756: (Internal Proj Error: proj_create: no database context specified)

**Comment by kvos** [comment]
this is an issue with your `pyproj` installation, see this one https://github.com/geopandas/geopandas/issues/1887

So try to re-install pyproj with conda.
`conda activate coastsat`
`conda install pyproj`

**Comment by Phuongtran75** [comment]
I installed and ran it successfully. Thanks
