### ISSUE TITLE
Is it acceptable to use L7 data?

### ISSUE THREAD

**Issue by saidiksh** [kvos/CoastSat#509]
Hello Dr. Kilian Vos,
I would like to know if using L7 data for my study area is acceptable. I know it has SLC error, but just want to know if coastsat still manages to extract shoreline correctly or not. I just need a brief explanation of how it works with L7

Thank You

**Comment by kvos** [comment]
yes it works with L7, you will get shorelines for the areas that are not covered by the diagonal bands. The bands move around from image to image so eventually you get full coverage. If you read the paper you will see that the accuracy from the shorelines extracted with L7 is similar to L8. So a part from SLC, L7 is great in my opinion.

**Comment by saidiksh** [comment]
thank you so much, Sir. I'm getting another error in dispiking that is when I get this bad georeferencing and duplicate image I get errors in the dispiking, all the time, and the total number of duplicate and bad georef is the dimention and corresponding Boolean dimension.
I have uploaded the screenshots 
thank you 
![Screenshot 2024-07-01 121818](https://github.com/kvos/CoastSat/assets/173790246/ff103581-263a-4286-b76a-2fc8e3c93ff7)
![1](https://github.com/kvos/CoastSat/assets/173790246/bc74f1a7-6fcf-4662-845a-b6c281e75d3f)

**Comment by kvos** [comment]
there must be something with the order in which you ran things. output and cross_distance should have the same number of points. Try to run it again from top to bottom.

**Comment by saidiksh** [comment]
My issue has been resolved.
Thank you, sir.
