### ISSUE TITLE
Manual removal of images

### ISSUE THREAD

**Issue by Jand607** [kvos/CoastSat#511]
Kia ora from Auckland! I am using CoastSat for my final-year civil engineering research project.

I've downloaded Sentinel-2 footage of Waimarama beach in Hawkes Bay of the North Island. About half contained proper imagery for the full area. Unfortunately, around half of the images contained a thin rectangle only displaying ocean, i.e. the majority of my ROI for these images was simply white pixels. I've attached an example of each kind of image:

![2015-11-28-22-15-49_S2](https://github.com/kvos/CoastSat/assets/170785170/c1a536c5-1a11-48b7-a3e6-f3c9d9e78c08)
![2015-12-08-22-15-50_S2](https://github.com/kvos/CoastSat/assets/170785170/61a36f61-7a0d-43d7-90e0-28c479f038ed)

I have removed all of the low quality images from my preprocessed folder, however, the metadata file is still linked to the original full set of images, including the poor quality ones. 

How can I change the metadata file such that it only includes the high quality images I have in my preprocessed folder?

Thanks!

**Comment by kvos** [comment]
hi @Jand607 , what I recommend is that you specify the S2 tile in your inputs so you only get the clips from the tile that fully covers your area of interest. I've attached the file, identify the tile that covers your area and then put it into `inputs['S2tile'] = '56HLH'`. That will avoid all the duplicates and small crop images. But make sure you make a clean download in a new folder.
[Sentinel-2-Shapefile-Index-master.zip](https://github.com/user-attachments/files/16091498/Sentinel-2-Shapefile-Index-master.zip)

**Comment by Jand607** [comment]
Cheers Kilian, that's fixed the issue! 
I have applied for a permit for PlanetScope satellite imagery in order to obtain a 3m pixel. Do you have any recommendations for how I would apply CoastSat to this data?

**Comment by kvos** [comment]
yes there is a link the the CoastSat.PlanetScope toolbox in the README
