### ISSUE TITLE
SDS_preprocess reference shoreline numpy error

### ISSUE THREAD

**Issue by climeyG** [kvos/CoastSat#515]
When I run the reference shoreline process, I end up with the error: AttributeError: module 'numpy' has no attribute 'math'. Assistance will be appreciated. 

![Numpy math](https://github.com/kvos/CoastSat/assets/87015529/19afc6a2-aee4-4edb-afea-d784e1d42279)

**Comment by thekester** [comment]
Hello, you could add import math on SDS_preprocess.py and replace `phi = np.pi/2 - np.math.atan2(deltax, deltay)` by  `phi = np.pi/2 - math.atan2(deltax, deltay)  `

**Comment by climeyG** [comment]
Thanks. That sorts it out. Is it indicative of an install issue on my side?

**Comment by thekester** [comment]
Since numpy doesn't often have an attribute called "math," I'm honestly not sure why np.math works for me. It's a mystery of Python!

**Comment by kvos** [comment]
@climeyG  can you please check which version of numpy you are running.
In Anaconda Prompt type:
`conda activate coastsat`
`conda list numpy`

**Comment by climeyG** [comment]
version 2.0.0

**Comment by kvos** [comment]
yep that makes sense. can you check where `np.math.atan2` has ended in numpy 2.0.0?

**Comment by climeyG** [comment]
Hi Kilian

Sorry, you're dealing with someone with no coding background, bumbling
along. How would I do that?
I can trace this back to the _init_.py module, but that's as far as my
limited knowledge goes.

Gerard

**Comment by climeyG** [comment]
[image: image.png]

**Comment by thekester** [comment]
Hello, i  check where np.math.atan2 has ended in numpy 2.0.0 with that AI generated code

#import math
import numpy as np

# Scalar values
x = 3
y = 4

# Using math.atan2 via np.math
result_scalar = np.math.atan2(y, x)
print("Result for scalars with np.math.atan2:", result_scalar)

# Array values
x_array = np.array([3, 1, -1, -3])
y_array = np.array([4, 2, -2, -4])

# Using numpy.arctan2 for arrays
result_array = np.arctan2(y_array, x_array)
print("Result for arrays with np.arctan2:", result_array)

When i try to execute the code, i got:

DeprecationWarning: `np.math` is a deprecated alias for the standard library `math` module (Deprecated Numpy 1.25). Replace usages of `np.math` with `math`

**Comment by thekester** [comment]
When i execute the script i got the following error Traceback (most recent call last):
  File "/home/athena/Document/coastsatv2/CoastSat-master/CoastSat-master/example.py", line 108, in <module>
    settings['reference_shoreline'] = SDS_preprocess.get_reference_sl(metadata, settings)
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/athena/Document/coastsatv2/CoastSat-master/CoastSat-master/coastsat/SDS_preprocess.py", line 942, in get_reference_sl
    phi = np.pi/2 - np.math.atan2(deltax, deltay)
                    ^^^^^^^
  File "/home/athena/miniconda3/envs/coastsat/lib/python3.12/site-packages/numpy/__init__.py", line 410, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'math'. Did you mean: 'emath'?

**Comment by kvos** [comment]
ok so `np.arctan2()` is the solution? if you want to PR this one too that would be great, otherwise I'll make the update. Thanks again for looking into this!

**Comment by thekester** [comment]
Yes, in my opinion, using `np.arctan2()` is the appropriate solution because `deltax` and `deltay` are of type `np.float64`. This ensures better compatibility and avoids potential issues that could arise from using the standard library's `math.atan2()`.

I've created a PR to address this issue: https://github.com/kvos/CoastSat/pull/520 , thanks again for that amazing project !
