### ISSUE TITLE
RefreshError: ('invalid_scope: Bad Request', {'error': 'invalid_scope', 'error_description': 'Bad Request'})

### ISSUE THREAD

**Issue by AbdelazizOuzaka10** [kvos/CoastSat#516]
When I execute the second line of the code which contains the polygon definition, it gives me the error in the title.

**Comment by dudu2112** [comment]
same here

**Comment by kvos** [comment]
try ee.Authenticate() first

**Comment by kvos** [comment]
@AbdelazizOuzaka10 @dudu2112 there is a new authentication function added by @thekester , sync your coastsat version (or download the latest version of coastsat and overwrite the SDS_download.py file with the new one). This should fix those authentication errors.
