### ISSUE TITLE
[Depreciation Warning] : landsat_c1_to_c2

### ISSUE THREAD

**Issue by thekester** [kvos/CoastSat#517]
Hello, i got that DeprecationWarning when i try to execute the code

Attention required for LANDSAT/LT05/C01/T1_TOA! You are using a deprecated asset.
To ensure continued functionality, please update it by July 1, 2024.
Learn more: https://developers.google.com/earth-engine/landsat_c1_to_c2

  warnings.warn(warning, category=DeprecationWarning)

![landsatdepreciationwarning](https://github.com/user-attachments/assets/9f3216ca-47b0-401e-8c6d-31b4fcdee6ad)

in SDS_download.py eight occurrences of T1_TOA in check_images_available function and  get_image_info

**Comment by kvos** [comment]
did you specify inputs['landsat_collection'] = 'C02'? if you specify collection 1 you should not get that warning, if you still do let me know. I want to keep collection 1 in there as some people may have extracted shorelines a while back and the only way they can reproduce their results is using collection 1.

**Comment by thekester** [comment]
When I use collection = 'C01', I get that DeprecationWarning. However, if I use collection = 'C02', I do not get this DeprecationWarning.

**Comment by kvos** [comment]
yes I think they removed Collection 1 this week. Will adjust the code soon.

**Comment by thekester** [comment]
Closed by #526
