### ISSUE TITLE
UTC time zone

### ISSUE THREAD

**Issue by ecnun** [kvos/CoastSat#527]
Hello, @kvos 
I want to know if there is a time zone issue with the output result. As shown in the figure, the time definitely does not match the time of the region I am studying. My region is eight hours ahead of the UTC time zone. Should I first change it to the time in my time zone?
![image](https://github.com/user-attachments/assets/be8bf14d-4e6f-42a7-ae93-c239167e23a0)

**Comment by kvos** [comment]
all dates are in UTC. if you want to change you can do +- timedelta(hours=x)

**Comment by ecnun** [comment]
Thank you so much, I will do it!
