### ISSUE TITLE
Tide Data

### ISSUE THREAD

**Issue by jobthoma97** [kvos/CoastSat#529]
I have few query regarding the use of tide data in CoastSat for tidal correction.

1. Is it possible to use Daily tide data for tidal correction, If not what's the reason behind it ?
2.  Can we use High tide and Low tide information from Tide Chart Table for tidal correction, If yes what's the best way to do it ?

Thank you in advance!

**Comment by kvos** [comment]
for tidal correction you would need 15 mimutes time-step in your tidal time-series. This is because you need to know the tide level at the time of image acquisition.
