### ISSUE TITLE
Shoreline detection of Marawila beach

### ISSUE THREAD

**Issue by erandaperera** [kvos/CoastSat#53]
Dear all,

I started using CoastSat recently and found it to be a very useful tool. I recommended the software to one undergraduate project where the student will be using the tool 
![2017-12-22-05-07-59_S2](https://user-images.githubusercontent.com/58412110/69931660-17a9d700-14ee-11ea-91af-b76dcf48a539.jpg)
to assess the long-term (20+ years) shoreline change at a beach in Sri Lanka- Marawila beach (https://www.google.com/maps/search/marawila+beach/@7.4124624,79.8009101,14z/data=!3m1!4b1). 

The student has successfully completed the example on Narra Beach given in GitHub. After changing only the co-ordinates of the example (so that it would match Marawila beach), the code was executed. However, we see that the quality of the images obtained is not clear - they appear pixelated (see attached image) which would clearly affect the shoreline detection stage as well. Clearly, there needs to be some adjustment to shoreline detection parameters in the code, but we are not sure how to fine-tune these parameters to get a reasonably accurate detection of the shoreline for Marawila. Could anybody give some suggestions, based on your experience, to improve this?

Any help is highly appreciated.

Kind regards

**Comment by kvos** [comment]
hi @erandaperera,

I just had a look at Marawila and was able to get nice imagery, so there must be a problem with the way you/your student have defined the coordinates. You can also use google Mymaps to create a rectangle of the area of interest and then export it as a .KML. You can then load into CoastSat with the function `polygon = SDS_tools.polygon_from_kml(kml_polygon)`

Looks like a cool site, good luck!

![2019-10-13-05-16-44_S2](https://user-images.githubusercontent.com/7217258/69935598-7cceee00-1529-11ea-9175-879fe43eb727.jpg)

![2019-10-18-05-16-46_S2](https://user-images.githubusercontent.com/7217258/69935581-73458600-1529-11ea-8f59-3e0122c241da.jpg)

**Comment by erandaperera** [comment]
Hi @kvos 
Thanks a lot for this help Kilian. So it looks like we have made a mistake with the coordinates of Marawila beach. I will recommend using Mymaps and exporting the coordinates as a .KML to get more accurate coordinates. 

Again, thanks a lot!
