### ISSUE TITLE
Download failed even when using really small polygon

### ISSUE THREAD

**Issue by Ruubmaster** [kvos/CoastSat#531]
Hi, I was trying to download images for an island in the Netherlands, but I got this error: 
**GEE initialized (existing token).
Number of images available between 2017-03-01 and 2017-03-31:
- In Landsat Tier 1 & Sentinel-2 Level-1C:
     S2: 2 images
  Total to download: 2 images

Downloading images:
S2: 2 images

Download failed, trying again...**

After the error I reduced the polygon size, which didn't help. Then I just tried the Narra beach example and I get the same error. I have deleted google CLI and installed it again but nothing works. Does anyone know what might solve this issue?

**Comment by kvos** [comment]
the only way is to print the error of why it failed. Can you share your inputs as txt file? then I can test

**Comment by Ruubmaster** [comment]
Thanks for your reply! I don't really get an error message, except 'download failed, trying again...'. For the inputs I just used the example.py file, and only changed the dates to the last month of 2021. When I try to run the example jupyter notebook it also returns download failed.

**Comment by kvos** [comment]
this should be fixed now, see #533. Update your version of SDS_download.py with the latest and it should work.

**Comment by Ruubmaster** [comment]
Thanks it works now!
