### ISSUE TITLE
error while downloading

### ISSUE THREAD

**Issue by Fadill-77** [kvos/CoastSat#533]
Hello
I have followed the installation steps as provided and then ran the example with some changes to the date range. but I can't download the image, the terminal displays "download failed, trying again..." several times and then an error appears.  I have tried updating the earthengine -api but it still shows the same error.
Thanks in advance for your help. Please see below for the error message:
EDIT : looks like @Ruubmaster is also having the same problem #531
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
File [~\Downloads\CoastSat-2.7\CoastSat-2.7\coastsat\SDS_download.py:389](http://localhost:8888/lab/tree/Downloads/CoastSat-2.7/CoastSat-2.7/~/Downloads/CoastSat-2.7/CoastSat-2.7/coastsat/SDS_download.py#line=388), in retrieve_images(inputs)
    388 try:    
--> 389     fn_ms = download_tif(image_ee,ee_region_ms,bands['ms'],fp_ms,satname)
    390     fn_swir = download_tif(image_ee,ee_region_swir,bands['swir'],fp_swir,satname)

File [~\Downloads\CoastSat-2.7\CoastSat-2.7\coastsat\SDS_download.py:804](http://localhost:8888/lab/tree/Downloads/CoastSat-2.7/CoastSat-2.7/~/Downloads/CoastSat-2.7/CoastSat-2.7/coastsat/SDS_download.py#line=803), in download_tif(image, polygon, bands, filepath, satname)
    803 # for the old version of ee raise an exception
--> 804 if int(ee.__version__[-3:]) <= 201:
    805     raise Exception('CoastSat2.0 and above is not compatible with earthengine-api version below 0.1.201.' +\
    806                     'Try downloading a previous CoastSat version (1.x).')

ValueError: invalid literal for int() with base 10: '0.0'

During handling of the above exception, another exception occurred:

Exception                                 Traceback (most recent call last)
Cell In[4], line 2
      1 # inputs['include_T2'] = True
----> 2 metadata = SDS_download.retrieve_images(inputs)

File [~\Downloads\CoastSat-2.7\CoastSat-2.7\coastsat\SDS_download.py:398](http://localhost:8888/lab/tree/Downloads/CoastSat-2.7/CoastSat-2.7/~/Downloads/CoastSat-2.7/CoastSat-2.7/coastsat/SDS_download.py#line=397), in retrieve_images(inputs)
    396 count += 1
    397 if count > 100:
--> 398     raise Exception('Too many attempts, crashed while downloading image %s'%im_meta['id'])
    399 else:
    400     continue             

Exception: Too many attempts, crashed while downloading image COPERNICUS/S2_HARMONIZED/20151218T235302_20151218T235455_T56HLH

**Comment by kvos** [comment]
thanks for reporting, it seems like there's a new version of the earthengine-api, will fix this today

**Comment by kvos** [comment]
fixed, update your repo and try again pls
