### ISSUE TITLE
Masking Build_Up Feature as cloud

### ISSUE THREAD

**Issue by jobthoma97** [kvos/CoastSat#534]
Hello @kvos ,

I was trying to run the CoastSat toolkit on Wajima, Noto Region, Japan.

Certain areas on the images were masked, First I thought its actual cloud. Then this happened to some other images as well. To check the clouds, I opened some satellite image and there were no clouds. What I noticed was, there were some build up area with high reflectance. Maybe because  of this, the code was considering them as clouds and masking the image. Due to which its not mapping the shoreline for the masked area. 

How to resolve this!!!!
Your help would be appreciated.

RGB image opened in QGIS (High reflectance area marked with yellow circle):
![RGB](https://github.com/user-attachments/assets/7d4e005c-877d-48ff-ac40-0c00ce0d290d)

FCC image opened in QGIS (High reflectance area marked with yellow circle):
![FCC](https://github.com/user-attachments/assets/bd3d768c-bc3a-4a39-b887-e70bb4ec64f3)

Cloud Masked Image:
![1991-04-12-00-49-38_L5](https://github.com/user-attachments/assets/96333f54-5e52-4874-bf06-c1cd596851c8)

**Comment by kvos** [comment]
hi @jobthoma97 , yes it's possible the CFMASK algorithm applied on Landsat tends to create false positives on very bright features. Have you tried using `settings['cloud_mask_issue'] = True`? This should help. If the problem persists let me know, there is another solution.

**Comment by jobthoma97** [comment]
Hello @kvos, Thank you for replying.

Initially, 'cloud_mask_issue' was set to "False" but I'm encountering the same issue after setting it to "True".

**Comment by kvos** [comment]
ok then go /coastsat/SDS_preprocess.py and change line 390:
`elem = morphology.square(6) # use a square of width 6 pixels`
if you change that 6 to 8 for example, it may get you rid of that issue.

**Comment by jobthoma97** [comment]
Thank you, I'll try doing the given solution.

But this "elem = morphology.square(6)" is not available on line 390, for me its on line 335.

And is it okay if I use the updated code for different period or different study area or should I change only for those area/period when it reads false positive pixel value. Will this affect the resolution of the shoreline ?

**Comment by jobthoma97** [comment]
Hi @kvos ,
I was able to remove the mask, for me pixel width of 8 was not working. I tried it using all different values and pixel width 30 removed the cloud mask.

Will this reduce the accuracy of shoreline extraction?
Is it okay to set "elem = morphology.square(30)" as pixel width for different period for the same study area ?

**Comment by kvos** [comment]
that's a lot, I think you may end up missing the real clouds this way but you can test.
