### ISSUE TITLE
Date range for tide prediction different to date range for images

### ISSUE THREAD

**Issue by phillipjws** [kvos/CoastSat#539]
Hello,

I'm just getting acquainted with CoastSat and FES2022 and I am curious as to why in example.py, the date range used for image acquisition is 
```
# date range
dates = ['1984-01-01', '2025-01-01']
```
and then later in the same file, specifically when using pyfes to predict the tides, the date range is:
```
# get tides time-series (15 minutes timestep)
date_range = [pytz.utc.localize(datetime(2024,1,1)),
              pytz.utc.localize(datetime(2025,1,1))]
timestep = 900 # seconds
```

I was trying to run my own trial with a different location, and I used the same dates for both, is the cut due to computation time? Or does the algorithm only need one year of data to adjust the entire dataset?

Thanks

**Comment by kvos** [comment]
oh that's because I copied it across from the notebook example which only runs one year. You should use same date range for both. I'll fix that.
