### ISSUE TITLE
Broken GDAL package

### ISSUE THREAD

**Issue by Julai091** [kvos/CoastSat#54]
Hi Kilian,

Im so sorry, i know that Issue #15 is closed but im facing the same problem with **TypeError: in method 'CoordinateTransformation_TransformPoints', argument 1 of type 'OSRCoordinateTransformationShadow *'**
I runned the example.py before and it was all good. But now t doesnt work i dont know why.  I cleaned it all and  re-installed the CoastSat environment several times, and still not working. :(

Any clues?
TypeError                                 Traceback (most recent call last)
<ipython-input-6-78c4e5dc2bfe> in <module>
      1 get_ipython().run_line_magic('matplotlib', 'qt')
----> 2 output = SDS_shoreline.extract_shorelines(metadata, settings)

~\Anaconda3\Scripts\Coast\coastsat\SDS_shoreline.py in extract_shorelines(metadata, settings)
    773 
    774             # process the water contours into a shoreline
--> 775             shoreline = process_shoreline(contours_mwi, cloud_mask, georef, image_epsg, settings)
    776 
    777             # visualise the mapped shorelines, there are two options:

~\Anaconda3\Scripts\Coast\coastsat\SDS_shoreline.py in process_shoreline(contours, cloud_mask, georef, image_epsg, settings)
    413     contours_world = SDS_tools.convert_pix2world(contours, georef)
    414     # convert world coordinates to desired spatial reference system
--> 415     contours_epsg = SDS_tools.convert_epsg(contours_world, image_epsg, settings['output_epsg'])
    416     # remove contours that have a perimeter < min_length_sl (provided in settings dict)
    417     # this enables to remove the very small contours that do not correspond to the shoreline

~\Anaconda3\Scripts\Coast\coastsat\SDS_tools.py in convert_epsg(points, epsg_in, epsg_out)
    140         # iterate over the list
    141         for i, arr in enumerate(points):
--> 142             points_converted.append(np.array(coordTransform.TransformPoints(arr)))
    143     elif type(points) is np.ndarray:
    144         points_converted = np.array(coordTransform.TransformPoints(points))

~\Anaconda3\lib\site-packages\osgeo\osr.py in TransformPoints(self, *args)
   1286     def TransformPoints(self, *args):
   1287         """TransformPoints(CoordinateTransformation self, int nCount)"""
-> 1288         return _osr.CoordinateTransformation_TransformPoints(self, *args)
   1289 
   1290 CoordinateTransformation_swigregister = _osr.CoordinateTransformation_swigregister

TypeError: in method 'CoordinateTransformation_TransformPoints', argument 1 of type 'OSRCoordinateTransformationShadow *'

Thank you

Juliana

**Comment by kvos** [comment]
hey juliana, yeah that error keeps on popping up without any reason. You may have updated your coastsat environment and now the **gdal** package is broken and this error comes up. 

I recommend you try to re-install gdal on your current coastsat environment (even if it's already installed) with `conda install gdal=2.3.3`. Before re-installing though make sure you clean everything with `conda clean --all`

**Comment by Julai091** [comment]
Still trying...but nothing seems to work. Tried pip install as well.

**Comment by kvos** [comment]
pip install doesn't work for GDAL according to #55 , I think you need to reset Anaconda and do the installation again...

**Comment by camarenaamaury** [comment]
Hi Kvos,
I worked with CoastSat a few months ago and it worked fine for a couple sites (thanks for the development).
Last week I started working with it again, and I keep running into the same error as Julai091, I already cleaned my environment, re installed gdal (version-2.3.3), created the environment from scratch again, but is still giving the same error message. 
Any other ideas are appreciated.
Thanks,
Amaury

**Comment by Julai091** [comment]
Ok...i'll do that.


Em qua, 18 de dez de 2019 6:00 AM, Kilian Vos <notifications@github.com>
escreveu:

**Comment by kvos** [comment]
@camarenaamaury - it's an issue that raises when you update anaconda and it breaks the gdal package.  I've had this problem before too and the only way to fix it was to uninstall anaconda and re-install it.

**Comment by kvos** [comment]
hey @Julai091 and @camarenaamaury , I've had a look in the forums and apparently this error pops up when `proj4` is missing, according to this [post](https://stackoverflow.com/questions/25367075/plot-tif-gdal-raster-using-matplotlib-basemap). Try to run this command in the anaconda prompt with `coastsat`environment activated: 

`conda install -c https://conda.binstar.org/jgomezdans proj4`

**Comment by camarenaamaury** [comment]
Thanks @kvos.
I tried this and still ran into the same issue. 
I will install everything from scratch again.

**Comment by kvos** [comment]
is the issue persisting? I will close the issue but feel free to reopen

**Comment by Alan19922015** [comment]
Which Anaconda3 version  is most stable ? I try to use newest anaconda3 and get the TypeError: in method 'CoordinateTransformation_TransformPoints after digitize the coastsat? Which version do you based on? I‘m testing the Anaocnda3.

**Comment by PenchalaVineeth** [comment]
Hi Kvos,

I worked with coastsat I am facing an issue i.e., " 'CoordinateTransformation_TransformPoints', argument 1 of type 'OSRCoordinateTransformationShadow *'". I uninstalled coastsat environment and reinstalled and also gdal but no use can you please suggest me some solution.
 
Thanks,
vineeth

**Comment by kvos** [comment]
I don't know what the solution to that error is, it's related to the installation of gdal, try to google it and there must be some posts on it on stackoverflow. After you uninstalled coastsat, did you run conda clean --all?
