### ISSUE TITLE
Tidal Correction - FES2022b - Issue with Longitude Data in ocean_tide NetCDF Files

### ISSUE THREAD

**Issue by ruby-vallarino** [kvos/CoastSat#540]
Hello everyone,

I’m currently working with the NetCDF files provided in the ocean_tide folder (FES2022b), and I’ve encountered an issue with the longitude data that seems to be incorrect.

Upon inspecting the files, I noticed that the longitude (lon) variable has invalid values. Specifically, the valid_min and valid_max attributes are both set to 0.0, which is not typical for longitude data. Additionally, the longitude array itself seems to be filled with either 0s or _FillValues (e.g., 1.84467440737096e+19), indicating missing or invalid data.

But when I run the code, it only provides tidal data for the eastern coast of Australia. However, I’ve tried several other locations, such as the Pacific coast of the Americas and the coast of Portugal, but no tidal data is generated for these areas.

Has anyone else encountered this issue with the longitude data? Is there a fix or workaround available for this, or could this be an issue with the dataset itself?

Any advice or insights would be greatly appreciated!

Thanks in advance for your help.

**Comment by phillipjws** [comment]
I was able to solve my issue by moving the point used in calculating the tides further away from the land, as well as ensuring I gave the longitude in the range (0, 360) as opposed to (-180, 180). I'm working in a bay, in an inlet, and so was too close to the land. If there is not enough existing data points, pyfes will interpolate the data using surrounding points, and if one of these ends up being on land, this is where you get the NaN values. 

Hopefully this helps you fix your error.

**Comment by ruby-vallarino** [comment]
@phillipjws Thank you for the suggestion to resolve the issue with the longitude in the ocean_tide NC files. I am working in the Gulf of Panama in Central America, and I hope this will work so I can continue with the tidal correction. However, yesterday I tried moving the point to almost the middle of the Gulf and still did not get results for the tidal time series.

Thanks again for your help!

**Comment by kvos** [comment]
have you tried using longitudes between 0 and 360? instead of -180 to 180

**Comment by ruby-vallarino** [comment]
@kvos @phillipjws Thank you very much for your help!!! I have successfully obtained the tide data for my study area.
