### ISSUE TITLE
incorrect polygon

### ISSUE THREAD

**Issue by evecchi** [kvos/CoastSat#543]
Hi kvos,

I'm really struggling to find the error when I try to download the data in my area.
I have tried various options, but none of them seem to work.
The error seems to be related to how the images are cropped.
My polygon has these vertices:
polygon = [[[12.458397, 44.144865], [12.498427, 44.114516], [12.518709, 44.125247], [12.480872, 44.157841], [12.458397, 44.144865]]]

I have attached the images of QGIS and Coasatsat.

Where am I making a mistake?

Thank you
Enrica
![issue](https://github.com/user-attachments/assets/a149f6f7-61d4-4286-bbb3-c7667f32d87b)
![issue2](https://github.com/user-attachments/assets/ae8019a6-d8e1-46d8-81f7-85fb5e8373b0)

**Comment by kvos** [comment]
is this resolved?

**Comment by evecchi** [comment]
Yes, it was due to the S2 polygon tiles.

Thanks!
