### ISSUE TITLE
Issues in lagoon-area

### ISSUE THREAD

**Issue by evecchi** [kvos/CoastSat#544]
Hi kvos,

I'm using your tool to map a complex area in Northeastern Italy, where there is a lagoon system located behind a flat beach. The algorithm alternates between capturing the boundaries of the lagoon and the sea, which makes it challenging to obtain an accurate shoreline.

I have attached a figure of the area for your reference. If you have any suggestions to improve this process, I would greatly appreciate your help!
![issue2](https://github.com/user-attachments/assets/2b490384-3636-49f4-8bb3-33fd35697ee6)

Thank you,

Enrica

**Comment by kvos** [comment]
hi @evecchi , have you used a reference shoreline? you can play with the max_distance threshold to try and restrict the detection from the lagoon. This may not work if lagoon is very close but try it.

If you get two detections, one for the lagoon and one for the shoreline, that is fine as you can the address the double intersections in `compute_intersections_QC()`. Read what the parameters do, there's a way to get it to always pick the waterline that is further offshore when there are multiple intersections along a transect.

**Comment by kvos** [comment]
can you post a screenshot?

**Comment by evecchi** [comment]
Solved! I used the advanced setting and modified the transects lenghts and now results are awesome!

thank you!
