### ISSUE TITLE
Installation, environment and packages

### ISSUE THREAD

**Issue by Diogoo21** [kvos/CoastSat#546]
I am having troubles with the Gdal package and other versions.

Could you please share the environment file or the packages and python versions?

Thank you.

**Comment by kvos** [comment]
hi @Diogoo21 , I'm currently on Python 3.10 with gdal 3.9.2.
See this environment file: [environment.txt](https://github.com/user-attachments/files/17679047/environment.txt)
I prefer not to lock versions as they change constantly but that one works for sure.

**Comment by kvos** [comment]
reopen if not solved
