### ISSUE TITLE
Error setting up environment

### ISSUE THREAD

**Issue by elvencricketer** [kvos/CoastSat#550]
Hi!

I am a total noob so please forgive silly questions. I keep getting an error when attempting to load modules. See below. Any help would be appreciated!

Thankyou 

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[1], line 15
     13 import pytz
     14 from pyproj import CRS
---> 15 from coastsat import SDS_download, SDS_preprocess, SDS_shoreline, SDS_tools, SDS_transects

ImportError: cannot import name 'SDS_download' from 'coastsat' (unknown location)

**Comment by kvos** [comment]
your working directory needs to be in the same location as the /coastsat folder. Are you using jupyter lab?

**Comment by elvencricketer** [comment]
Yep using Jupyter lab. Both my notebook and coastsat folder are in the same folder.

Kira Woods
Senior Scientist: Geomorphology
[A logo for a science and management company  Description automatically generated with low confidence]

e.   ***@***.******@***.***>
m.  0480 322 590
w.  Streamology<http://www.streamology.com.au/>
Part Ground Floor, 380 Docklands Drive,  Docklands, Vic 3008


***@***.******@***.***

***@***.***<https://www.instagram.com/Streamology_/?hl=en>

***@***.***<https://www.linkedin.com/company/streamology-waterway-science-and-management/mycompany/?viewAsMember=true>


   [A red sign with white arrows  Description automatically generated]    [A yellow square with white arrows  Description automatically generated]    [A blue and white sign with white check marks  Description automatically generated]

Streamology acknowledges the Traditional Owners of the lands on which we work and we pay our respects to Elders past, present and emerging

**Comment by elvencricketer** [comment]
I tried re-installing and didn't realise i had an install error.... any tips on this error?


(coastsat) C:\Users\KiraWoods>pip install pyqt5 imageio-ffmpeg
Collecting pyqt5
  Using cached PyQt5-5.15.11-cp38-abi3-win_amd64.whl.metadata (2.1 kB)
Collecting imageio-ffmpeg
  Using cached imageio_ffmpeg-0.5.1-py3-none-win_amd64.whl.metadata (1.6 kB)
Collecting PyQt5-sip<13,>=12.15 (from pyqt5)
  Using cached PyQt5_sip-12.15.0.tar.gz (104 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting PyQt5-Qt5<5.16.0,>=5.15.2 (from pyqt5)
  Using cached PyQt5_Qt5-5.15.2-py3-none-win_amd64.whl.metadata (552 bytes)
Requirement already satisfied: setuptools in c:\users\kirawoods\miniforge3\envs\coastsat\lib\site-packages (from imageio-ffmpeg) (75.3.0)
Using cached PyQt5-5.15.11-cp38-abi3-win_amd64.whl (6.9 MB)
Using cached imageio_ffmpeg-0.5.1-py3-none-win_amd64.whl (22.6 MB)
Using cached PyQt5_Qt5-5.15.2-py3-none-win_amd64.whl (50.1 MB)
Building wheels for collected packages: PyQt5-sip
  Building wheel for PyQt5-sip (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for PyQt5-sip (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [9 lines of output]
      running bdist_wheel
      running build
      running build_ext
      building 'PyQt5.sip' extension
      creating build\temp.win-amd64-cpython-313\Release
      "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.42.34433\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Users\KiraWoods\miniforge3\envs\coastsat\include -IC:\Users\KiraWoods\miniforge3\envs\coastsat\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.42.34433\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.42.34433\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" /Tcapiversions.c /Fobuild\temp.win-amd64-cpython-313\Release\apiversions.obj
      apiversions.c
      C:\Users\KiraWoods\miniforge3\envs\coastsat\include\pyconfig.h(59): fatal error C1083: Cannot open include file: 'io.h': No such file or directory
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.42.34433\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for PyQt5-sip
Failed to build PyQt5-sip
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (PyQt5-sip)

**Comment by elvencricketer** [comment]
I've gotten past my initial error but now i have a new one. when running the initial settings i get: "no module named osgeo"

any suggestions? I have GDAL installed but still getting the error

**Comment by kvos** [comment]
activate your environment and type again `mamba install gdal`
that should solve your problem

**Comment by kvos** [comment]
did this work? reopen if not
