### ISSUE TITLE
methodology/ technique used for calculating shoreline change trend?

### ISSUE THREAD

**Issue by saidiksh** [kvos/CoastSat#552]
hello @kvos 
Does CoastSat use Linear Regression Rate (LRR) or any other specific statistical method to determine the rate of change in shoreline position over time?

**Comment by kvos** [comment]
yes when you use SDS_transects.seasonal_averages() to make seasonal averages and extract long-term trends it uses a linear regression rate on the time-series

**Comment by saidiksh** [comment]
Thank You so much sir.
