### ISSUE TITLE
Error in retrieving satellite images 

### ISSUE THREAD

**Issue by erandaperera** [kvos/CoastSat#61]
Dear all, 

I am using CoastSat to obtain shoreline images of Marawila beach (Sri Lanka) before the year 2016. I used a .KML file generated from My Maps, using this, I input the coordinates of the coastal region to CoastSat. The time period was also selected as 2015/02/01 to 2015/12/01. 

At this point, there was an error called  "Unbound Local Error" - please see the screenshot below:

![img3](https://user-images.githubusercontent.com/58412110/71011670-d16e8d80-2113-11ea-82c5-d75efc44c82f.jpg)

Please note that this error did not occur for shoreline images obtained *after* the year 2016. So this seemed to be quite strange. I would highly appreciate it if you could provide a suggestion to help to resolve this problem. 

Thanks a lot. 

Kind regards
Eranda

**Comment by kvos** [comment]
I have never seen this error, could you please provide your settings and polygon so I can reproduce this error, thanks

**Comment by erandaperera** [comment]
Dear Kilian,
Thank you for your reply. I'm sending herewith as much detail as possible so that it would be easier to diagnose the problem. 
 
I have changed the dates, polygon name, min beach area, buffer size and minimum length, as seen below: 

![s1](https://user-images.githubusercontent.com/58412110/71137085-f4d92b80-222c-11ea-93be-818d2f86f273.png)

![s2](https://user-images.githubusercontent.com/58412110/71137101-fe629380-222c-11ea-957d-1898e9f70521.png)

The polygon coordinates are given through a .KML file (uploaded to Google Drive: https://drive.google.com/open?id=17VDzYrbigAr2yaqXshRIkM909Vri8s-R). 

The error found was for satellite images *before* 2016: 

![s3](https://user-images.githubusercontent.com/58412110/71137193-471a4c80-222d-11ea-8a05-ac5af5ddb8a0.png)

However, for images *after* 2016, the code worked fine: 

![s4](https://user-images.githubusercontent.com/58412110/71137252-7335cd80-222d-11ea-9c59-915cb9111a83.png)

![s5](https://user-images.githubusercontent.com/58412110/71137267-834dad00-222d-11ea-8340-387dea83c5bf.png)

The images we were able to output were: 

![s6](https://user-images.githubusercontent.com/58412110/71137297-a4ae9900-222d-11ea-8481-96c64d46b18d.png)

Thank you very much for any suggestion regarding this issue. 

Best regards
Eranda

**Comment by kvos** [comment]
it's because there are no S2 images of your ROI in 2015 (Sentinel-2a was launched in mid-2015 but probably took some time before being fully operation, you can read this [paper](https://www.sciencedirect.com/science/article/abs/pii/S0378383918305313?via%3Dihub), Figure 1, before downloading the images so you know which images are available when). 

I would also suggest that you decrease your `min_beach_area` parameter as it is too high and it will never map sand pixels like this, setting between 1000 and 5000 should be ok. Also the `buffer_size` seems a bit small.
