### ISSUE TITLE
Images not downloading and tidal correction

### ISSUE THREAD

**Issue by AISWARYA7866** [kvos/CoastSat#62]
Hello Killan,
I started using coastsat as a part of my dissertation. I  have successfully completed  the example on Narra beach. After changing the coordinates and site name of the example, the code was executed, but no images were downloaded. I'm preparing script in spyder and running the same in anaconda prompt.Here I'm attaching the screen shots please check the same and give a suitable reply.
<img width="476" alt="anaconda prompt" src="https://user-images.githubusercontent.com/58928891/71058333-79706f00-2185-11ea-9c93-2d4c897fdce4.PNG">
<img width="960" alt="cap1" src="https://user-images.githubusercontent.com/58928891/71058343-868d5e00-2185-11ea-93ad-625259ec967e.PNG">
<img width="949" alt="2" src="https://user-images.githubusercontent.com/58928891/71058353-90af5c80-2185-11ea-96e1-62fa5d6a5b8c.PNG">

**Comment by kvos** [comment]
hi @AISWARYA7866 , what is the size of your polygon? it seems to be really massive, spanning 4-5 degrees in latitude. As mentioned on the README your polygon should be smaller than 100 square km, if larger split it into smaller ones.

PS you can also run your script directly in Spyder

**Comment by AISWARYA7866** [comment]
Hai Killan, when i reduced the size of the polygon  i got the images. But
it takes long time to map the shorelines .Only  33 percentage of the
mapping process is completed yet now ( it takes more than 3 hrs to complete
33 percentage  of the mapping process).Actually how long it takes to map
the shoreline?These are the coordinates which i used ..
[[[75.51194444, 11.66416667],
  [75.58527778, 11.66555556],
  [75.62166667, 11.58666667],
  [75.55083333, 11.57388889],
  [75.51194444, 11.66416667]]]
location :chombola beach ,kozhikode
dates = ['2017-12-01', '2018-01-01']
please check the same and mention if there is any error.

**Comment by kvos** [comment]
what is the area of your polygon? you're probably still downloading the images not mapping the shorelines, try to make it smaller to speed up things

**Comment by AISWARYA7866** [comment]
The area of the selected polygon is 80 square km (length 10km ,breadth
8km). We are trying process the sentinel images during 01st Dec 2017 to
01st January 2018 as a trail. there are 6 images and 6 images are already
downloaded.Please refer to the screen shot. The shoreline mapping procedure
is being done for 33% and stopped with error 'timers cannot have
negative timeouts'.

Please let me know how to solve this issue.

Thank you
--
Aishwarya

**Comment by AISWARYA7866** [comment]
Hai kilian,
I have to use the keyboard arrows instead of clicking on keep/skip, then also the shoreline mapping procedure is being done for 90% and stopped with error 'timers cannot have negative timeout'.Please let me know  how to solve this issue.
<img width="719" alt="new error" src="https://user-images.githubusercontent.com/58928891/71884749-e496db00-315e-11ea-9b71-33754d301a42.PNG">

**Comment by kvos** [comment]
yes it's normal to use the keyboard for keep/skip. I've never seen this error, can you share your `changed.py` script so I can try it out

**Comment by AISWARYA7866** [comment]
<img width="580" alt="snip5" src="https://user-images.githubusercontent.com/58928891/71893075-9d194a80-3170-11ea-8238-bed991d2026b.PNG">
Hai Killan, 
This is my script
<img width="575" alt="snip 1" src="https://user-images.githubusercontent.com/58928891/71893017-79560480-3170-11ea-8579-48cfe7c79e02.PNG">
<img width="580" alt="snip2" src="https://user-images.githubusercontent.com/58928891/71893039-87a42080-3170-11ea-9210-fbcfae1cfefd.PNG">
<img width="616" alt="snip3" src="https://user-images.githubusercontent.com/58928891/71893052-8f63c500-3170-11ea-96dc-489dc192488a.PNG">
<img width="619" alt="snip4" src="https://user-images.githubusercontent.com/58928891/71893063-968ad300-3170-11ea-9931-8b83cbfffaff.PNG">

**Comment by AISWARYA7866** [comment]
Hai killan,
This is my script
<img width="575" alt="snip 1" src="https://user-images.githubusercontent.com/58928891/71893153-ccc85280-3170-11ea-8ab1-72076f756000.PNG">
<img width="580" alt="snip2" src="https://user-images.githubusercontent.com/58928891/71893165-d5208d80-3170-11ea-903e-1084fa8719d6.PNG">
<img width="616" alt="snip3" src="https://user-images.githubusercontent.com/58928891/71893175-dbaf0500-3170-11ea-8e5a-df42109b6fb6.PNG">
<img width="619" alt="snip4" src="https://user-images.githubusercontent.com/58928891/71893185-e5d10380-3170-11ea-976a-0b084f526b14.PNG">
<img width="580" alt="snip5" src="https://user-images.githubusercontent.com/58928891/71893199-ecf81180-3170-11ea-839a-7f3061058050.PNG">

**Comment by kvos** [comment]
can you please copy/paste the code instead of screenshots, thx

**Comment by AISWARYA7866** [comment]
# -*- coding: utf-8 -*-
"""
Created on Tue Jan  7 13:57:17 2020

@author: mithun
"""

# -*- coding: utf-8 -*-
"""
Created on Mon Jan  6 10:08:33 2020

@author: mithun
"""

# -*- coding: utf-8 -*-
"""
Created on Fri Dec 27 14:18:23 2019

@author: mithun
"""

#==========================================================#
#Shoreline extraction from satellite images
#==========================================================#

# Kilian Vos WRL 2018

#%% 1. Initial settings

# load modules
import os#
import numpy as np
import pickle
import warnings
warnings.filterwarnings("ignore")
import matplotlib.pyplot as plt
from coastsat import SDS_download, SDS_preprocess, SDS_shoreline, SDS_tools, SDS_transects

# region of interest (longitude, latitude in WGS84)
polygon = [[[76.75805556, 8.63389167],
            [76.79750000, 8.65536667],
            [76.85166667, 8.58764167],
            [76.81305556, 8.56238611],
            [76.75805556, 8.63389167]]]
# can also be loaded from a .kml polygon
#kml_polygon = os.path.join(os.getcwd(), 'examples', 'NARRA_polygon.kml')
#polygon = SDS_tools.polygon_from_kml(kml_polygon)
       
# date range
dates = ['2019-09-01', '2019-10-01']

# satellite missions
sat_list = ['S2']

# name of the site
sitename = 'muthalapozhii'

# filepath where data will be stored
filepath_data = os.path.join(os.getcwd(), 'data')

# put all the inputs into a dictionnary
inputs = {
    'polygon': polygon,
    'dates': dates,
    'sat_list': sat_list,
    'sitename': sitename,
    'filepath': filepath_data
        }

#%% 2. Retrieve images

# retrieve satellite images from GEE
metadata = SDS_download.retrieve_images(inputs)

# if you have already downloaded the images, just load the metadata file
metadata = SDS_download.get_metadata(inputs) 

#%% 3. Batch shoreline detection
    
# settings for the shoreline extraction
settings = { 
    # general parameters:
    'cloud_thresh': 0.5,        # threshold on maximum cloud cover
    'output_epsg': 32643,       # epsg code of spatial reference system desired for the output   
    # quality control:
    'check_detection': True,    # if True, shows each shoreline detection to the user for validation
    'save_figure': True,        # if True, saves a figure showing the mapped shoreline for each image
    # add the inputs defined previously
    'inputs': inputs,
    # [ONLY FOR ADVANCED USERS] shoreline detection parameters:
    'min_beach_area': 4500,     # minimum area (in metres^2) for an object to be labelled as a beach
    'buffer_size': 150,         # radius (in metres) of the buffer around sandy pixels considered in the shoreline detection
    'min_length_sl': 200,       # minimum length (in metres) of shoreline perimeter to be valid
    'cloud_mask_issue': False,  # switch this parameter to True if sand pixels are masked (in black) on many images  
    'sand_color': 'default',    # 'default', 'dark' (for grey/black sand beaches) or 'bright' (for white sand beaches)
}

# [OPTIONAL] preprocess images (cloud masking, pansharpening/down-sampling)
SDS_preprocess.save_jpg(metadata, settings)

# [OPTIONAL] create a reference shoreline (helps to identify outliers and false detections)
settings['reference_shoreline'] = SDS_preprocess.get_reference_sl(metadata, settings)
# set the max distance (in meters) allowed from the reference shoreline for a detected shoreline to be valid
settings['max_dist_ref'] = 100        

# extract shorelines from all images (also saves output.pkl and shorelines.kml)
output = SDS_shoreline.extract_shorelines(metadata, settings)

# plot the mapped shorelines
fig = plt.figure()
plt.axis('equal')
plt.xlabel('Eastings')
plt.ylabel('Northings')
plt.grid(linestyle=':', color='0.5')
for i in range(len(output['shorelines'])):
    sl = output['shorelines'][i]
    date = output['dates'][i]
    plt.plot(sl[:,0], sl[:,1], '.', label=date.strftime('%d-%m-%Y'))
plt.legend()
mng = plt.get_current_fig_manager()                                         
mng.window.showMaximized()    
fig.set_size_inches([15.76,  8.52])

#%% 4. Shoreline analysis

# if you have already mapped the shorelines, load the output.pkl file
filepath = os.path.join(inputs['filepath'], sitename)
with open(os.path.join(filepath, sitename + '_output' + '.pkl'), 'rb') as f:
    output = pickle.load(f) 

# now we have to define cross-shore transects over which to quantify the shoreline changes
# each transect is defined by two points, its origin and a second point that defines its orientation

# there are 3 options to create the transects:
# - option 1: draw the shore-normal transects along the beach
# - option 2: load the transect coordinates from a .kml file
# - option 3: create the transects manually by providing the coordinates

# option 1: draw origin of transect first and then a second point to define the orientation
transects = SDS_transects.draw_transects(output, settings)
    
# option 2: load the transects from a .geojson file
#geojson_file = os.path.join(os.getcwd(), 'examples', 'NARRA_transects.geojson')
#transects = SDS_tools.transects_from_geojson(geojson_file)

# option 3: create the transects by manually providing the coordinates of two points 
#transects = dict([])
#transects['Transect 1'] = np.array([[342836, 6269215], [343315, 6269071]])
#transects['Transect 2'] = np.array([[342482, 6268466], [342958, 6268310]])
#transects['Transect 3'] = np.array([[342185, 6267650], [342685, 6267641]])
   
# intersect the transects with the 2D shorelines to obtain time-series of cross-shore distance
settings['along_dist'] = 25
cross_distance = SDS_transects.compute_intersection(output, transects, settings) 

# plot the time-series
from matplotlib import gridspec
fig = plt.figure()
gs = gridspec.GridSpec(len(cross_distance),1)
gs.update(left=0.05, right=0.95, bottom=0.05, top=0.95, hspace=0.05)
for i,key in enumerate(cross_distance.keys()):
    if np.all(np.isnan(cross_distance[key])):
        continue
    ax = fig.add_subplot(gs[i,0])
    ax.grid(linestyle=':', color='0.5')
    ax.set_ylim([-50,50])
    ax.plot(output['dates'], cross_distance[key]- np.nanmedian(cross_distance[key]), '-^', markersize=6)
    ax.set_ylabel('distance [m]', fontsize=12)
    ax.text(0.5,0.95,'Transect ' + key, bbox=dict(boxstyle="square", ec='k',fc='w'), ha='center',
            va='top', transform=ax.transAxes, fontsize=14)
mng = plt.get_current_fig_manager()                                         
mng.window.showMaximized()    
fig.set_size_inches([15.76,  8.52])

**Comment by AISWARYA7866** [comment]
import os#
import numpy as np
import pickle
import warnings
warnings.filterwarnings("ignore")
import matplotlib.pyplot as plt
from coastsat import SDS_download, SDS_preprocess, SDS_shoreline, SDS_tools, SDS_transects

# region of interest (longitude, latitude in WGS84)
polygon = [[[76.75805556, 8.63389167],
            [76.79750000, 8.65536667],
            [76.85166667, 8.58764167],
            [76.81305556, 8.56238611],
            [76.75805556, 8.63389167]]]
dates = ['2019-09-01', '2019-10-01']
sat_list = ['S2']
sitename = 'muthalapozhii'
filepath_data = os.path.join(os.getcwd(), 'data')
inputs = {
    'polygon': polygon,
    'dates': dates,
    'sat_list': sat_list,
    'sitename': sitename,
    'filepath': filepath_data
        }
metadata = SDS_download.retrieve_images(inputs)
metadata = SDS_download.get_metadata(inputs) settings = { 
    # general parameters:
    'cloud_thresh': 0.5,        # threshold on maximum cloud cover
    'output_epsg': 32643,       # epsg code of spatial reference system desired for the output   
    # quality control:
    'check_detection': True,    # if True, shows each shoreline detection to the user for validation
    'save_figure': True,        # if True, saves a figure showing the mapped shoreline for each image
    # add the inputs defined previously
    'inputs': inputs,
    # [ONLY FOR ADVANCED USERS] shoreline detection parameters:
    'min_beach_area': 4500,     # minimum area (in metres^2) for an object to be labelled as a beach
    'buffer_size': 150,         # radius (in metres) of the buffer around sandy pixels considered in the shoreline detection
    'min_length_sl': 200,       # minimum length (in metres) of shoreline perimeter to be valid
    'cloud_mask_issue': False,  # switch this parameter to True if sand pixels are masked (in black) on many images  
    'sand_color': 'default',    # 'default', 'dark' (for grey/black sand beaches) or 'bright' (for white sand beaches)
}
SDS_preprocess.save_jpg(metadata, settings)

# [OPTIONAL] create a reference shoreline (helps to identify outliers and false detections)
settings['reference_shoreline'] = SDS_preprocess.get_reference_sl(metadata, settings)
# set the max distance (in meters) allowed from the reference shoreline for a detected shoreline to be valid
settings['max_dist_ref'] = 100        

# extract shorelines from all images (also saves output.pkl and shorelines.kml)
output = SDS_shoreline.extract_shorelines(metadata, settings)

# plot the mapped shorelines
fig = plt.figure()
plt.axis('equal')
plt.xlabel('Eastings')
plt.ylabel('Northings')
plt.grid(linestyle=':', color='0.5')
for i in range(len(output['shorelines'])):
    sl = output['shorelines'][i]
    date = output['dates'][i]
    plt.plot(sl[:,0], sl[:,1], '.', label=date.strftime('%d-%m-%Y'))
plt.legend()
mng = plt.get_current_fig_manager()                                         
mng.window.showMaximized()    
fig.set_size_inches([15.76,  8.52])

filepath = os.path.join(inputs['filepath'], sitename)
with open(os.path.join(filepath, sitename + '_output' + '.pkl'), 'rb') as f:
    output = pickle.load(f) 
transects = SDS_transects.draw_transects(output, settings)

settings['along_dist'] = 25
cross_distance = SDS_transects.compute_intersection(output, transects, settings) 

# plot the time-series
from matplotlib import gridspec
fig = plt.figure()
gs = gridspec.GridSpec(len(cross_distance),1)
gs.update(left=0.05, right=0.95, bottom=0.05, top=0.95, hspace=0.05)
for i,key in enumerate(cross_distance.keys()):
    if np.all(np.isnan(cross_distance[key])):
        continue
    ax = fig.add_subplot(gs[i,0])
    ax.grid(linestyle=':', color='0.5')
    ax.set_ylim([-50,50])
    ax.plot(output['dates'], cross_distance[key]- np.nanmedian(cross_distance[key]), '-^', markersize=6)
    ax.set_ylabel('distance [m]', fontsize=12)
    ax.text(0.5,0.95,'Transect ' + key, bbox=dict(boxstyle="square", ec='k',fc='w'), ha='center',
            va='top', transform=ax.transAxes, fontsize=14)
mng = plt.get_current_fig_manager()                                         
mng.window.showMaximized()    
fig.set_size_inches([15.76,  8.52])

**Comment by kvos** [comment]
it worked for me...the QTimer warnings just because you are running it directly from the command line, if you run it in spyder it doesn't show up...

from the 11 images, only 1 had less than 50% cloud cover: 
![2019-09-21-05-26-35_S2](https://user-images.githubusercontent.com/7217258/71974734-875c6180-3212-11ea-952f-1884e6266423.jpg)

**Comment by AISWARYA7866** [comment]
Hai killan,
 when i set  the axis limit to [-80,80] the fig 2 is not responding why this happens.These are the coordinates which i used ..
polygon =[[[76.81305556, 8.56238611],
            [76.85166667, 8.58764167],
            [76.94277778, 8.48084167],
            [76.86555556, 8.48718889],
            [76.81305556, 8.56238611]]]
dates =  ['2016-09-01', '2019-12-01']
sat_list = ['S2']
sitename = 'puthenthope'
 output_epsg: 32643

**Comment by kvos** [comment]
can you please send the full script to I can try it out? or are you working on a fork of coastsat that I can access?

**Comment by AISWARYA7866** [comment]
# -*- coding: utf-8 -*-
"""
Created on Fri Dec 27 13:33:54 2019

@author: mithun
"""

#==========================================================#
#==========================================================#

# Kilian Vos WRL 2018

#%% 1. Initial settings

# load modules
import os#
import numpy as np
import pickle
import warnings
warnings.filterwarnings("ignore")
import matplotlib.pyplot as plt
from coastsat import SDS_download, SDS_preprocess, SDS_shoreline, SDS_tools, SDS_transects
polygon = [[[76.81305556, 8.56238611],
            [76.85166667, 8.58764167],
            [76.94277778, 8.48084167],
            [76.86555556, 8.48718889],
            [76.81305556, 8.56238611]]]
      
dates = ['2016-09-01', '2019-12-01'
sat_list = ['S2
sitename = 'puthenthope'

filepath_data = os.path.join(os.getcwd(), 'data')

inputs = {
    'polygon': polygon,
    'dates': dates,
    'sat_list': sat_list,
    'sitename': sitename,
    'filepath': filepath_data
        }
metadata = SDS_download.retrieve_images(inputs)
metadata = SDS_download.get_metadata(inputs) 
settings = { 
 
    'cloud_thresh': 0.5,        # threshold on maximum cloud cover
    'output_epsg': 32643,       # epsg code of spatial reference system desired for the output   
    # quality control:
    'check_detection': True,    # if True, shows each shoreline detection to the user for validation
    'save_figure': True,        # if True, saves a figure showing the mapped shoreline for each image
    'inputs': inputs,
    'min_beach_area': 4500,     # minimum area (in metres^2) for an object to be labelled as a beach
    'buffer_size': 150,         # radius (in metres) of the buffer around sandy pixels considered in the shoreline detection
    'min_length_sl': 200,       # minimum length (in metres) of shoreline perimeter to be valid
    'cloud_mask_issue': False,  # switch this parameter to True if sand pixels are masked (in black) on many images  
    'sand_color': 'default',    # 'default', 'dark' (for grey/black sand beaches) or 'bright' (for white sand beaches)
SDS_preprocess.save_jpg(metadata, settings)
settings['reference_shoreline'] = SDS_preprocess.get_reference_sl(metadata, settings
settings['max_dist_ref'] = 100        
output = SDS_shoreline.extract_shorelines(metadata, settings)
fig = plt.figure()
plt.axis('equal')
plt.xlabel('Eastings')
plt.ylabel('Northings')
plt.grid(linestyle=':', color='0.5')
for i in range(len(output['shorelines'])):
    sl = output['shorelines'][i]
    date = output['dates'][i]
    plt.plot(sl[:,0], sl[:,1], '.', label=date.strftime('%d-%m-%Y'))
plt.legend()
mng = plt.get_current_fig_manager()                                         
mng.window.showMaximized()    
fig.set_size_inches([15.76,  8.52])
filepath = os.path.join(inputs['filepath'], sitename)
with open(os.path.join(filepath, sitename + '_output' + '.pkl'), 'rb') as f:
    output = pickle.load(f) 

# now we have to define cross-shore transects over which to quantify the shoreline changes
# each transect is defined by two points, its origin and a second point that defines its orientation

# there are 3 options to create the transects:
# - option 1: draw the shore-normal transects along the beach
# - option 2: load the transect coordinates from a .kml file
# - option 3: create the transects manually by providing the coordinates

# option 1: draw origin of transect first and then a second point to define the orientation
transects = SDS_transects.draw_transects(output, settings)
    
# option 2: load the transects from a .geojson file
#geojson_file = os.path.join(os.getcwd(), 'examples', 'NARRA_transects.geojson')
#transects = SDS_tools.transects_from_geojson(geojson_file)

# option 3: create the transects by manually providing the coordinates of two points 
#transects = dict([])
#transects['Transect 1'] = np.array([[342836, 6269215], [343315, 6269071]])
#transects['Transect 2'] = np.array([[342482, 6268466], [342958, 6268310]])
#transects['Transect 3'] = np.array([[342185, 6267650], [342685, 6267641]])
   
# intersect the transects with the 2D shorelines to obtain time-series of cross-shore distance
settings['along_dist'] = 25
cross_distance = SDS_transects.compute_intersection(output, transects, settings) 
from matplotlib import gridspec
fig = plt.figure()
gs = gridspec.GridSpec(len(cross_distance),1)
gs.update(left=0.05, right=0.95, bottom=0.05, top=0.95, hspace=0.05)
for i,key in enumerate(cross_distance.keys()):
    if np.all(np.isnan(cross_distance[key])):
        continue
    ax = fig.add_subplot(gs[i,0])
    ax.grid(linestyle=':', color='0.5')
    ax.set_ylim([-80,80])
    ax.plot(output['dates'], cross_distance[key]- np.nanmedian(cross_distance[key]), '-^', markersize=6)
    ax.set_ylabel('distance [m]', fontsize=12)
    ax.text(0.5,0.95,'Transect ' + key, bbox=dict(boxstyle="square", ec='k',fc='w'), ha='center',
            va='top', transform=ax.transAxes, fontsize=14)
mng = plt.get_current_fig_manager()                                         
mng.window.showMaximized()    
fig.set_size_inches([15.76,  8.52])

# satellite missions
sat_list = ['S2']

# name of the site
sitename = 'puthenthope'

# filepath where data will be stored
filepath_data = os.path.join(os.getcwd(), 'data')

# put all the inputs into a dictionnary
inputs = {
    'polygon': polygon,
    'dates': dates,
    'sat_list': sat_list,
    'sitename': sitename,
    'filepath': filepath_data
        }

#%% 2. Retrieve images

# retrieve satellite images from GEE
metadata = SDS_download.retrieve_images(inputs)

# if you have already downloaded the images, just load the metadata file
metadata = SDS_download.get_metadata(inputs) 
# settings for the shoreline extraction
settings = { 
    # general parameters:
    'cloud_thresh': 0.5,        # threshold on maximum cloud cover
    'output_epsg': 32643,       # epsg code of spatial reference system desired for the output   
    # quality control:
    'check_detection': True,    # if True, shows each shoreline detection to the user for validation
    'save_figure': True,        # if True, saves a figure showing the mapped shoreline for each image
    # add the inputs defined previously
    'inputs': inputs,
    # [ONLY FOR ADVANCED USERS] shoreline detection parameters:
    'min_beach_area': 4500,     # minimum area (in metres^2) for an object to be labelled as a beach
    'buffer_size': 150,         # radius (in metres) of the buffer around sandy pixels considered in the shoreline detection
    'min_length_sl': 200,       # minimum length (in metres) of shoreline perimeter to be valid
    'cloud_mask_issue': False,  # switch this parameter to True if sand pixels are masked (in black) on many images  
    'sand_color': 'default',    # 'default', 'dark' (for grey/black sand beaches) or 'bright' (for white sand beaches)
}

# [OPTIONAL] preprocess images (cloud masking, pansharpening/down-sampling)
SDS_preprocess.save_jpg(metadata, settings)

# [OPTIONAL] create a reference shoreline (helps to identify outliers and false detections)
settings['reference_shoreline'] = SDS_preprocess.get_reference_sl(metadata, settings)
# set the max distance (in meters) allowed from the reference shoreline for a detected shoreline to be valid
settings['max_dist_ref'] = 100        

# extract shorelines from all images (also saves output.pkl and shorelines.kml)
output = SDS_shoreline.extract_shorelines(metadata, settings)

# plot the mapped shorelines
fig = plt.figure()
plt.axis('equal')
plt.xlabel('Eastings')
plt.ylabel('Northings')
plt.grid(linestyle=':', color='0.5')
for i in range(len(output['shorelines'])):
    sl = output['shorelines'][i]
    date = output['dates'][i]
    plt.plot(sl[:,0], sl[:,1], '.', label=date.strftime('%d-%m-%Y'))
plt.legend()
mng = plt.get_current_fig_manager()                                         
mng.window.showMaximized()    
fig.set_size_inches([15.76,  8.52])

# if you have already mapped the shorelines, load the output.pkl file
filepath = os.path.join(inputs['filepath'], sitename)
with open(os.path.join(filepath, sitename + '_output' + '.pkl'), 'rb') as f:
    output = pickle.load(f) 

# now we have to define cross-shore transects over which to quantify the shoreline changes
# each transect is defined by two points, its origin and a second point that defines its orientation

# there are 3 options to create the transects:
# - option 1: draw the shore-normal transects along the beach
# - option 2: load the transect coordinates from a .kml file
# - option 3: create the transects manually by providing the coordinates

# option 1: draw origin of transect first and then a second point to define the orientation
transects = SDS_transects.draw_transects(output, settings)
    
# option 2: load the transects from a .geojson file
#geojson_file = os.path.join(os.getcwd(), 'examples', 'NARRA_transects.geojson')
#transects = SDS_tools.transects_from_geojson(geojson_file)

# option 3: create the transects by manually providing the coordinates of two points 
#transects = dict([])
#transects['Transect 1'] = np.array([[342836, 6269215], [343315, 6269071]])
#transects['Transect 2'] = np.array([[342482, 6268466], [342958, 6268310]])
#transects['Transect 3'] = np.array([[342185, 6267650], [342685, 6267641]])
   
# intersect the transects with the 2D shorelines to obtain time-series of cross-shore distance
settings['along_dist'] = 25
cross_distance = SDS_transects.compute_intersection(output, transects, settings) 

# plot the time-series
from matplotlib import gridspec
fig = plt.figure()
gs = gridspec.GridSpec(len(cross_distance),1)
gs.update(left=0.05, right=0.95, bottom=0.05, top=0.95, hspace=0.05)
for i,key in enumerate(cross_distance.keys()):
    if np.all(np.isnan(cross_distance[key])):
        continue
    ax = fig.add_subplot(gs[i,0])
    ax.grid(linestyle=':', color='0.5')
    ax.set_ylim([-25,75])
    ax.plot(output['dates'], cross_distance[key]- np.nanmedian(cross_distance[key]), '-^', markersize=6)
    ax.set_ylabel('distance [m]', fontsize=12)
    ax.text(0.5,0.95,'Transect ' + key, bbox=dict(boxstyle="square", ec='k',fc='w'), ha='center',
            va='top', transform=ax.transAxes, fontsize=14)
mng = plt.get_current_fig_manager()                                         
mng.window.showMaximized()    
fig.set_size_inches([15.76,  8.52])

**Comment by AISWARYA7866** [comment]
import os#
import numpy as np
import pickle
import warnings
warnings.filterwarnings("ignore")
import matplotlib.pyplot as plt
from coastsat import SDS_download, SDS_preprocess, SDS_shoreline, SDS_tools, SDS_transects
polygon = [[[76.81305556, 8.56238611],
            [76.85166667, 8.58764167],
            [76.94277778, 8.48084167],
            [76.86555556, 8.48718889],
            [76.81305556, 8.56238611]]]
dates = ['2016-09-01', '2019-12-01']
sat_list = ['S2']
sitename = 'puthenthope'
filepath_data = os.path.join(os.getcwd(), 'data')
inputs = {
    'polygon': polygon,
    'dates': dates,
    'sat_list': sat_list,
    'sitename': sitename,
    'filepath': filepath_data
        }
metadata = SDS_download.retrieve_images(inputs)
metadata = SDS_download.get_metadata(inputs) 
settings = { 
cloud_thresh': 0.5,        # threshold on maximum cloud cover
    'output_epsg': 32643,       # epsg code of spatial reference system desired for the output   
    # quality control:
    'check_detection': True,    # if True, shows each shoreline detection to the user for validation
    'save_figure': True,        # if True, saves a figure showing the mapped shoreline for each image
    # add the inputs defined previously
    'inputs': inputs,
    # [ONLY FOR ADVANCED USERS] shoreline detection parameters:
    'min_beach_area': 4500,     # minimum area (in metres^2) for an object to be labelled as a beach
    'buffer_size': 150,         # radius (in metres) of the buffer around sandy pixels considered in the shoreline detection
    'min_length_sl': 200,       # minimum length (in metres) of shoreline perimeter to be valid
    'cloud_mask_issue': False,  # switch this parameter to True if sand pixels are masked (in black) on many images  
    'sand_color': 'default',    # 'default', 'dark' (for grey/black sand beaches) or 'bright' (for white sand beaches)
}
SDS_preprocess.save_jpg(metadata, settings)
settings['reference_shoreline'] = SDS_preprocess.get_reference_sl(metadata, settings)
settings['max_dist_ref'] = 100      
output = SDS_shoreline.extract_shorelines(metadata, settings)
fig = plt.figure()
plt.axis('equal')
plt.xlabel('Eastings')
plt.ylabel('Northings')
plt.grid(linestyle=':', color='0.5')
for i in range(len(output['shorelines'])):
    sl = output['shorelines'][i]
    date = output['dates'][i]
    plt.plot(sl[:,0], sl[:,1], '.', label=date.strftime('%d-%m-%Y'))
plt.legend()
mng = plt.get_current_fig_manager()                                         
mng.window.showMaximized()    
fig.set_size_inches([15.76,  8.52])
filepath = os.path.join(inputs['filepath'], sitename)
with open(os.path.join(filepath, sitename + '_output' + '.pkl'), 'rb') as f:
    output = pickle.load(f) 
transects = SDS_transects.draw_transects(output, settings)
    settings['along_dist'] = 25
cross_distance = SDS_transects.compute_intersection(output, transects, settings) 
from matplotlib import gridspec
fig = plt.figure()
gs = gridspec.GridSpec(len(cross_distance),1)
gs.update(left=0.05, right=0.95, bottom=0.05, top=0.95, hspace=0.05)
for i,key in enumerate(cross_distance.keys()):
    if np.all(np.isnan(cross_distance[key])):
        continue
    ax = fig.add_subplot(gs[i,0])
    ax.grid(linestyle=':', color='0.5')
    ax.set_ylim([-80,80])
    ax.plot(output['dates'], cross_distance[key]- np.nanmedian(cross_distance[key]), '-^', markersize=6)
    ax.set_ylabel('distance [m]', fontsize=12)
    ax.text(0.5,0.95,'Transect ' + key, bbox=dict(boxstyle="square", ec='k',fc='w'), ha='center',
            va='top', transform=ax.transAxes, fontsize=14)
mng = plt.get_current_fig_manager()                                         
mng.window.showMaximized()    
fig.set_size_inches([15.76,  8.52])
sat_list = ['S2']
sitename = 'puthenthope'
filepath_data = os.path.join(os.getcwd(), 'data')
inputs = {
    'polygon': polygon,
    'dates': dates,
    'sat_list': sat_list,
    'sitename': sitename,
    'filepath': filepath_data
        }
metadata = SDS_download.retrieve_images(inputs)
metadata = SDS_download.get_metadata(inputs) 
settings = { 
    'cloud_thresh': 0.5,        
    'output_epsg': 32643,        
    'check_detection': True,   
    'save_figure': True,        
    'inputs': inputs,
    'min_beach_area': 4500,    
    'buffer_size': 150,         
    'min_length_sl': 200,       
    'cloud_mask_issue': False,  
    'sand_color': 'default', 
 SDS_preprocess.save_jpg(metadata, settings)
settings['reference_shoreline'] = SDS_preprocess.get_reference_sl(metadata, settings)
settings['max_dist_ref'] = 100 
    output = SDS_shoreline.extract_shorelines(metadata, settings)
fig = plt.figure()
plt.axis('equal')
plt.xlabel('Eastings')
plt.ylabel('Northings')
plt.grid(linestyle=':', color='0.5')
for i in range(len(output['shorelines'])):
    sl = output['shorelines'][i]
    date = output['dates'][i]
    plt.plot(sl[:,0], sl[:,1], '.', label=date.strftime('%d-%m-%Y'))
plt.legend()
mng = plt.get_current_fig_manager()                                         
mng.window.showMaximized()    
fig.set_size_inches([15.76,  8.52])
filepath = os.path.join(inputs['filepath'], sitename)
with open(os.path.join(filepath, sitename + '_output' + '.pkl'), 'rb') as f:
    output = pickle.load(f) 
transects = SDS_transects.draw_transects(output, settings)
settings['along_dist'] = 25
cross_distance = SDS_transects.compute_intersection(output, transects, settings) 
from matplotlib import gridspec
fig = plt.figure()
gs = gridspec.GridSpec(len(cross_distance),1)
gs.update(left=0.05, right=0.95, bottom=0.05, top=0.95, hspace=0.05)
for i,key in enumerate(cross_distance.keys()):
    if np.all(np.isnan(cross_distance[key])):
        continue
    ax = fig.add_subplot(gs[i,0])
    ax.grid(linestyle=':', color='0.5')
    ax.set_ylim([-25,75])
    ax.plot(output['dates'], cross_distance[key]- np.nanmedian(cross_distance[key]), '-^', markersize=6)
    ax.set_ylabel('distance [m]', fontsize=12)
    ax.text(0.5,0.95,'Transect ' + key, bbox=dict(boxstyle="square", ec='k',fc='w'), ha='center',
            va='top', transform=ax.transAxes, fontsize=14)
mng = plt.get_current_fig_manager()                                         
mng.window.showMaximized()    
fig.set_size_inches([15.76,  8.52])

**Comment by kvos** [comment]
I tried your code and got this for the time-series (I didn't run the entire dataset, just a few images, and I didn't use a reference shoreline):
![Figure_2](https://user-images.githubusercontent.com/7217258/73511554-0facdb80-443a-11ea-9b18-afa21db197d8.png)
So maybe the issue is with your reference shoreline, make sure you zoom in when you digitise it (you can delete points by right-click) and set the max_dist_ref accordingly.

I also recommend you make your polygon smaller, it takes forever to process such large images

**Comment by AISWARYA7866** [comment]
Hai Kilian,
i got stuck with the problem in tidal correction so can you give me an explanation about how you applied the tidal correction, and  also how you generated tidally corrected figure.Hope you will reply soon. thank you
 


Aiswarya

**Comment by kvos** [comment]
hi @AISWARYA7866 , tidal correction is explained in the publications, basically you have to do the following:
- compute the intersections with the shorelines along the transects
- get the tide level corresponding to each date in output['dates']
- get an estimate of the beach face slope at each transect 
- compute: tide level/beach face slope
- add this to the time-series that you obtained in step 1

**Comment by AISWARYA7866** [comment]
Hai kilian
 here i have selected 5 transect locations as shown  below , but i got result only for 2 transects why this happen so can you explain?
![puthenthope_transect_locations](https://user-images.githubusercontent.com/58928891/86744560-5345ea00-c057-11ea-935f-a703a671c678.jpg)
![puthenthope fig 2](https://user-images.githubusercontent.com/58928891/86744683-6953aa80-c057-11ea-9d2a-b31c3f8ec4fc.png)
