### ISSUE TITLE
coastline as well as the inner side islands are also extracted

### ISSUE THREAD

**Issue by pradhancda** [kvos/CoastSat#64]
Sir,

Please suggest to extract only the coastline. coastline as well as the inner side islands are also extracted.

![Figure_1](https://user-images.githubusercontent.com/48046958/71818926-58c67580-30b0-11ea-8dc9-916d4818e046.jpeg)

regards.
subhasis

**Comment by kvos** [comment]
you need to add a `reference shoreline` and set a reasonable `max_dist_ref` (by default 100m)
