### ISSUE TITLE
Time-series of shoreline change in .csv file

### ISSUE THREAD

**Issue by Lukas-va** [kvos/CoastSat#67]
Hello again,

so far the software works very well and I am glad with the results it provides! However, the very last step when you plot the time series of shoreline change could be improved I believe. 

The resulting time series are confusing and there is nothing much you can do. With the provided figure it is only possible to alter the very first transect shoreline time-series visualization. No matter if I choose a second transect, the changes only apply to the first one... for example if I want to adjust the bottom and top boundaries (yes, I can do that before I run the command, however shoreline position on a first transect and the last one, e.g. 200 meters away, is different).

It would be great if the time series data could be extracted to an excel compatible file for example, where you could fit a trend, better compare with in-situ measurements, etc.
Even a .txt file would do good with information on the date and shoreline position in each of the transects.

Let me know if that would be possible or perhaps there are alternative solutions? Everything else is fine!:)

All the best,
Lukas

**Comment by kvos** [comment]
Ok thanks for feedback Lukas, I will think about this add-on. The figure in the example is very basic and is there just as a template to be modified by the users.
In the meanwhile you can write a .csv or .txt file with Python, and if you do your *pull request* will be much appreciated! 👍

**Comment by Lukas-va** [comment]
Thanks for the advice! It is the first time I am having experience with python, so I have no idea how to export the time-series data to a .txt file. 
I will talk to the guys working with python at my office. Will let you know how it went!

**Comment by kvos** [comment]
hi @Lukas-va , I have added a function to save the dates and time-series of shoreline change along the transects in a .csv file. Download the [development branch](https://github.com/kvos/CoastSat/tree/development) and test it out, when you run `SDS_transects.compute_intersections` it should also save the time-series in a .csv. Let me know how it goes

**Comment by Lukas-va** [comment]
Hi Kilian,

Sounds amazing! I will try it out. Will also try some other things too. Basically my next big step is to evaluate your software output data, comparing it with in-situ measurements.

Have a great day,
Lukas

**Comment by kvos** [comment]
I am closing the issue, feel free to reopen it if something goes wrong when saving the time-series of shoreline change as a .csv file
