### ISSUE TITLE
Problem S2 images

### ISSUE THREAD

**Issue by tonycoppola** [kvos/CoastSat#72]
Hi Kilian, as mentioned above (# 50) I have a problem with S2 images, the shoreline are overly offshore.
Whith the same S2 images in QGIS I calculated NDWI ((B3-B8)/(B3+B8)), whith the threshold equal to 0, and I got better results. In this way I can use two images with the same spatial resolution, rather than proceeding with interpolations (as in the MNDWI calculation).
The difference between the two shorelines is 17-22 meters. 
Below you can see two examples
What do you think about it?
Greetings from Italy

![10 aprile](https://user-images.githubusercontent.com/57672328/73960809-ce21a200-490b-11ea-800c-71061faec444.jpg)
![19_luglio](https://user-images.githubusercontent.com/57672328/73960820-d548b000-490b-11ea-89d9-82ee35b5b7b2.jpg)

**Comment by kvos** [comment]
hi tony, you are right there is clearly an issue there, 20m offset is huge. I will reopen issue #50 so we can continue there.
