### ISSUE TITLE
How to retrieve metadata without downloading images?

### ISSUE THREAD

**Issue by yongjingmao** [kvos/CoastSat#73]
Hello Killan,

When retrieving metadata for satellite images, are there any options to download the metadata ( .txt) files only? Sometimes it is time-consuming to download satellite image (".tif") files.

**Comment by phke5716** [comment]
@yongjingmao  there is a separate option to retrieve the metadata from pre-harvest images. See @kvos  README.

**Comment by kvos** [comment]
hey @yongjingmao, I have made a new update to the master branch and now you can get the metadata of the images by calling SDS_download.check_image_availability(inputs), where inputs is the dictionnary that you set up at the beginning of the script. This will return 2 lists: the first one with the metadata of all the images available for Landsat (Tier 1) and Sentinel-2 (Level-1C) and the second one with all the images available in Landsat (Tier 2). I hope this helps.

**Comment by yongjingmao** [comment]
Hey @kvos,  thank you for the update! This solves the problem.
