### ISSUE TITLE
CoastSat not working due to Pillow 7.0

### ISSUE THREAD

**Issue by MarcelliNos92** [kvos/CoastSat#74]
![image](https://user-images.githubusercontent.com/45711498/74039282-76da0b00-49b9-11ea-801d-3b312efd4bb9.png)

Hi,

I have encountered the following issues as in the picture. It seems that new version of CoastSat is not compatibile with Pillow environment, so there a need for going back to lower version which is 6.2.
With this change the CoastSat is working as before.

Hope it is helpful,

Marcin

**Comment by kvos** [comment]
thanks for picking that up. I just saw this matplotlib issue https://github.com/matplotlib/matplotlib/issues/16083 explaining that the format .jpg is not supported anymore. This is also what was happening in issue #70. 

I guess one way to solve this is to go back to a lower version of pillow, or saving the images in a different format, maybe .png?

**Comment by kvos** [comment]
updated the `master` branch and added Pillow version 6.2 in the environment.yml file (PR #76)
