### ISSUE TITLE
metadata = SDS_download.retrieve_images(inputs)

### ISSUE THREAD

**Issue by IMRAN5379** [kvos/CoastSat#78]
TimeoutError                              Traceback (most recent call last)
<ipython-input-5-81739100d1f3> in <module>
----> 1 metadata = SDS_download.retrieve_images(inputs)

~\Desktop\P work\CoastSat-master\coastsat\SDS_download.py in retrieve_images(inputs)
     76 
     77     # initialise connection with GEE server
---> 78     ee.Initialize()
     79 
     80     # check image availability

~\Anaconda3\envs\coastsat\lib\site-packages\ee\__init__.py in Initialize(credentials, opt_url, use_cloud_api, cloud_api_key)
    103       cloud_api_key=cloud_api_key)
    104   # Initialize the dynamically loaded functions on the objects that want them.
--> 105   ApiFunction.initialize()
    106   Element.initialize()
    107   Image.initialize()

~\Anaconda3\envs\coastsat\lib\site-packages\ee\apifunction.py in initialize(cls)
    150     """Initializes the list of signatures from the Earth Engine front-end."""
    151     if not cls._api:
--> 152       signatures = data.getAlgorithms()
    153       api = {}
    154       for name, sig in signatures.items():

~\Anaconda3\envs\coastsat\lib\site-packages\ee\data.py in getAlgorithms()
    648                 is not specified.
    649   """
--> 650   return send_('/algorithms', {}, 'GET')
    651 
    652 

~\Anaconda3\envs\coastsat\lib\site-packages\ee\data.py in send_(path, params, opt_method, opt_raw)
   1159     return response, content
   1160 
-> 1161   response, content = send_with_backoff()
   1162 
   1163   # Call the profile hook if present. Note that this is done before we handle

~\Anaconda3\envs\coastsat\lib\site-packages\ee\data.py in send_with_backoff(retries)
   1150     try:
   1151       response, content = http.request(
-> 1152           url, method=opt_method, body=payload, headers=headers)
   1153       if response.status == 429:
   1154         if retries < MAX_RETRIES:

~\Anaconda3\envs\coastsat\lib\site-packages\oauth2client\transport.py in new_request(uri, method, body, headers, redirections, connection_type)
    157             _LOGGER.info('Attempting refresh to obtain '
    158                          'initial access_token')
--> 159             credentials._refresh(orig_request_method)
    160 
    161         # Clone and modify the request headers to add the appropriate

~\Anaconda3\envs\coastsat\lib\site-packages\oauth2client\client.py in _refresh(self, http)
    747         """
    748         if not self.store:
--> 749             self._do_refresh_request(http)
    750         else:
    751             self.store.acquire_lock()

~\Anaconda3\envs\coastsat\lib\site-packages\oauth2client\client.py in _do_refresh_request(self, http)
    778         resp, content = transport.request(
    779             http, self.token_uri, method='POST',
--> 780             body=body, headers=headers)
    781         content = _helpers._from_bytes(content)
    782         if resp.status == http_client.OK:

~\Anaconda3\envs\coastsat\lib\site-packages\oauth2client\transport.py in request(http, uri, method, body, headers, redirections, connection_type)
    280     return http_callable(uri, method=method, body=body, headers=headers,
    281                          redirections=redirections,
--> 282                          connection_type=connection_type)
    283 
    284 

~\Anaconda3\envs\coastsat\lib\site-packages\httplib2\__init__.py in request(self, uri, method, body, headers, redirections, connection_type)
   1989                         headers,
   1990                         redirections,
-> 1991                         cachekey,
   1992                     )
   1993         except Exception as e:

~\Anaconda3\envs\coastsat\lib\site-packages\httplib2\__init__.py in _request(self, conn, host, absolute_uri, request_uri, method, body, headers, redirections, cachekey)
   1649 
   1650         (response, content) = self._conn_request(
-> 1651             conn, request_uri, method, body, headers
   1652         )
   1653 

~\Anaconda3\envs\coastsat\lib\site-packages\httplib2\__init__.py in _conn_request(self, conn, request_uri, method, body, headers)
   1555             try:
   1556                 if conn.sock is None:
-> 1557                     conn.connect()
   1558                 conn.request(method, request_uri, body, headers)
   1559             except socket.timeout:

~\Anaconda3\envs\coastsat\lib\site-packages\httplib2\__init__.py in connect(self)
   1389             break
   1390         if not self.sock:
-> 1391             raise socket_err
   1392 
   1393 

~\Anaconda3\envs\coastsat\lib\site-packages\httplib2\__init__.py in connect(self)
   1322                 if has_timeout(self.timeout):
   1323                     sock.settimeout(self.timeout)
-> 1324                 sock.connect((self.host, self.port))
   1325 
   1326                 self.sock = self._context.wrap_socket(sock, server_hostname=self.host)

TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

**Comment by IMRAN5379** [comment]
I am getting this error in windows only but in ubuntu/Linux it is working.

**Comment by IMRAN5379** [comment]
this might be in my case that execution is not done correctly.
Executing transaction: | DEBUG menuinst_win32:__init__(199): Menu: name: 'Anaconda${PY_VER} ${PLATFORM}', prefix: 'C:\Users\IMRAN5379\Anaconda3\envs\coastsat', env_name: 'coastsat

**Comment by kvos** [comment]
is it win32? could be that GEE api is not compatible... try to activate the coastsat package and run the following commands:
-`python`
-`import ee`
-`ee.Initialize()`
let me know what error pops out
