### ISSUE TITLE
Improving resolution of satellite images

### ISSUE THREAD

**Issue by erandaperera** [kvos/CoastSat#79]
Dear Kilian: 

We are trying to improve the resolution of the satellite images obtained for Marawila region. However, it seems we are doing something wrong as the images obtained are rather blurred.

The input parameter values we used are:

cloud_thresh = 0.5
min_beach_area'= 1000
buffer_size= 100
min_length_sl=200
sand_color=dark

The KML file used is here: 
[https://drive.google.com/file/d/1CW65qN-BbG-iapZgQrFFTpj4zFTCh30H/view?usp=sharing](url)](url)

I am sharing herewith the images we obtained

![d](https://user-images.githubusercontent.com/58412110/75001671-08e91580-5488-11ea-89d5-e6337eafbbed.png)
![e](https://user-images.githubusercontent.com/58412110/75001675-0b4b6f80-5488-11ea-86d6-fd0cd69b7f9a.png)

We are certainly doing something wrong as our resolution is significantly less than the resolution that you reproduced the same region with. Please could you let us know the parameters you would change to improve this quality?
Thank you very much.

**Comment by kvos** [comment]
I think those images are 10m/pixel which is the resolution for S2. That breakwater seems to be 80m long and is about 8 pixels
