### ISSUE TITLE
cannot calculate cross distance

### ISSUE THREAD

**Issue by whitmcq81** [kvos/CoastSat#80]
When running the code everything works except for the shoreline change analysis. I can select shorelines, view all of the created shorelines, and draw transects for them, but the cross distance is given as nan and no shoreline change graph is created. 

![Annotation 2020-03-02 115744](https://user-images.githubusercontent.com/61511220/75698636-0d2de380-5c7d-11ea-9d17-1b81f93c172c.png)

My points are:
[-75.537, 35.776], [-75.52, 35.78], [-75.439, 35.591],[-75.508, 35.588],[-75.537, 35.776]

output epsg: 3358

Any ideas?

**Comment by whitmcq81** [comment]
My previous area was too large, however it is still giving me nan for those values.
 
New points:
[[[-75.537, 35.776],
            [-75.52, 35.78],
            [-75.463, 35.685],
            [-75.512, 35.675],
            [-75.537, 35.776]]]

**Comment by kvos** [comment]
hey @whitmcq81 , did you set the transects with the origin on land and the 2nd point seawards?

**Comment by whitmcq81** [comment]
Yes I did, I was wondering where my area has water on both sides could that be messing up the calculations?

**Comment by kvos** [comment]
ok I am not sure what could be causing this issue, could you please send me your example.py script so I can run it and debug it

**Comment by whitmcq81** [comment]
Here it is, I ran it this morning and got it to work. Not sure why it did this time and not the others.

#==========================================================#
# Shoreline extraction from satellite images
#==========================================================#

# Kilian Vos WRL 2018

#%% 1. Initial settings

# load modules
import os
import numpy as np
import pickle
import warnings
warnings.filterwarnings("ignore")
import matplotlib.pyplot as plt
from coastsat import SDS_download, SDS_preprocess, SDS_shoreline, SDS_tools, SDS_transects

# region of interest (longitude, latitude in WGS84)
polygon = [[[-75.537, 35.776],
            [-75.52, 35.78],
            [-75.463, 35.685],
            [-75.512, 35.675],
            [-75.537, 35.776]]]
# can also be loaded from a .kml polygon
#kml_polygon = os.path.join(os.getcwd(), 'examples', 'NARRA_polygon.kml')
#polygon = SDS_tools.polygon_from_kml(kml_polygon)
       
# date range
dates = ['2017-10-01', '2018-01-01']

# satellite missions
sat_list = ['S2']

# name of the site
sitename = 'TESTOI_11'

# filepath where data will be stored
filepath_data = os.path.join(os.getcwd(), 'data')

# put all the inputs into a dictionnary
inputs = {
    'polygon': polygon,
    'dates': dates,
    'sat_list': sat_list,
    'sitename': sitename,
    'filepath': filepath_data
        }

#%% 2. Retrieve images

# retrieve satellite images from GEE
metadata = SDS_download.retrieve_images(inputs)

# if you have already downloaded the images, just load the metadata file
metadata = SDS_download.get_metadata(inputs)

#%% 3. Batch shoreline detection
    
# settings for the shoreline extraction
settings = { 
    # general parameters:
    'cloud_thresh': 0.5,        # threshold on maximum cloud cover
    'output_epsg': 3358,       # epsg code of spatial reference system desired for the output
    # quality control:
    'check_detection': True,    # if True, shows each shoreline detection to the user for validation
    'save_figure': True,        # if True, saves a figure showing the mapped shoreline for each image
    # add the inputs defined previously
    'inputs': inputs,
    # [ONLY FOR ADVANCED USERS] shoreline detection parameters:
    'min_beach_area': 4500,     # minimum area (in metres^2) for an object to be labelled as a beach
    'buffer_size': 150,         # radius (in metres) of the buffer around sandy pixels considered in the shoreline detection
    'min_length_sl': 200,       # minimum length (in metres) of shoreline perimeter to be valid
    'cloud_mask_issue': False,  # switch this parameter to True if sand pixels are masked (in black) on many images  
    'sand_color': 'default',    # 'default', 'dark' (for grey/black sand beaches) or 'bright' (for white sand beaches)
}

# [OPTIONAL] preprocess images (cloud masking, pansharpening/down-sampling)
SDS_preprocess.save_jpg(metadata, settings)

# [OPTIONAL] create a reference shoreline (helps to identify outliers and false detections)
settings['reference_shoreline'] = SDS_preprocess.get_reference_sl(metadata, settings)
# set the max distance (in meters) allowed from the reference shoreline for a detected shoreline to be valid
settings['max_dist_ref'] = 100        

# extract shorelines from all images (also saves output.pkl and shorelines.kml)
output = SDS_shoreline.extract_shorelines(metadata, settings)

# plot the mapped shorelines
fig = plt.figure()
plt.axis('equal')
plt.xlabel('Eastings')
plt.ylabel('Northings')
plt.grid(linestyle=':', color='0.5')
for i in range(len(output['shorelines'])):
    sl = output['shorelines'][i]
    date = output['dates'][i]
    plt.plot(sl[:,0], sl[:,1], '.', label=date.strftime('%d-%m-%Y'))
plt.legend()
mng = plt.get_current_fig_manager()                                         
mng.window.showMaximized()    
fig.set_size_inches([15.76,  8.52])

#%% 4. Shoreline analysis

# if you have already mapped the shorelines, load the output.pkl file
filepath = os.path.join(inputs['filepath'], sitename)
with open(os.path.join(filepath, sitename + '_output' + '.pkl'), 'rb') as f:
    output = pickle.load(f) 

# now we have to define cross-shore transects over which to quantify the shoreline changes
# each transect is defined by two points, its origin and a second point that defines its orientation

# there are 3 options to create the transects:
# - option 1: draw the shore-normal transects along the beach
# - option 2: load the transect coordinates from a .kml file
# - option 3: create the transects manually by providing the coordinates

# option 1: draw origin of transect first and then a second point to define the orientation
transects = SDS_transects.draw_transects(output, settings)
    
# option 2: load the transects from a .geojson file
#geojson_file = os.path.join(os.getcwd(), 'examples', 'NARRA_transects.geojson')
#transects = SDS_tools.transects_from_geojson(geojson_file)

# option 3: create the transects by manually providing the coordinates of two points 
#transects = dict([])
#transects['Transect 1'] = np.array([[342836, 6269215], [343315, 6269071]])
#transects['Transect 2'] = np.array([[342482, 6268466], [342958, 6268310]])
#transects['Transect 3'] = np.array([[342185, 6267650], [342685, 6267641]])
   
# intersect the transects with the 2D shorelines to obtain time-series of cross-shore distance
settings['along_dist'] = 25
cross_distance = SDS_transects.compute_intersection(output, transects, settings) 

# plot the time-series
from matplotlib import gridspec
fig = plt.figure()
gs = gridspec.GridSpec(len(cross_distance),1)
gs.update(left=0.05, right=0.95, bottom=0.05, top=0.95, hspace=0.05)
for i,key in enumerate(cross_distance.keys()):
    if np.all(np.isnan(cross_distance[key])):
        continue
    ax = fig.add_subplot(gs[i,0])
    ax.grid(linestyle=':', color='0.5')
    ax.set_ylim([-50,50])
    ax.plot(output['dates'], cross_distance[key]- np.nanmedian(cross_distance[key]), '-^', markersize=6)
    ax.set_ylabel('distance [m]', fontsize=12)
    ax.text(0.5,0.95,'Transect ' + key, bbox=dict(boxstyle="square", ec='k',fc='w'), ha='center',
            va='top', transform=ax.transAxes, fontsize=14)
mng = plt.get_current_fig_manager()                                         
mng.window.showMaximized()    
fig.set_size_inches([15.76,  8.52])

**Comment by kvos** [comment]
ok then I don't have to test it :) I will close the issue for now, feel free to reopen if the issue arises again

**Comment by whitmcq81** [comment]
kvos, Im trying to input my own transects using option #3. Im using the correct coordinates for epsg code 3358 but I am still getting nan for my cross-section distance. I get the shorelines but no time-series chart. When I draw the shorelines, option #1, it works. Any ideas?

Here are my coordinates and transects:

<img width="436" alt="Annotation 2020-03-25 163138" src="https://user-images.githubusercontent.com/61511220/77583051-ccf60580-6eb6-11ea-9096-68bd4beb9524.png">
<img width="534" alt="Annotation 2020-03-25 163222" src="https://user-images.githubusercontent.com/61511220/77583061-d0898c80-6eb6-11ea-9736-c9c2bcf82fdc.png">

**Comment by kvos** [comment]
are those transects on the same coordinate system as the shorelines (`settings['output_epsg']`)? you can plot the transects on top of the shorelines to cross-check this

**Comment by whitmcq81** [comment]
Yes they are. When I plotted them they go from land to seaside and across the shoreline.

<img width="464" alt="Annotation 2020-03-25 194936" src="https://user-images.githubusercontent.com/61511220/77596217-c88b1600-6ed1-11ea-8850-cb8b4abd6a71.png">

**Comment by kvos** [comment]
can you plot the transects that you defined with option 3 on top of the shorelines?

**Comment by whitmcq81** [comment]
I couldn't figure out how to exactly plot them on the graph so I drew them as close as I could get them.

![Figure_1_LI](https://user-images.githubusercontent.com/61511220/77654746-d54a5100-6f47-11ea-8d61-49ccaf5c09f2.jpg)

**Comment by kvos** [comment]
ok that's not what I meant. 
After defining your transect coordinates with option 3, add these lines of code:
```
fig = plt.figure()
plt.axis('equal')
plt.xlabel('Eastings')
plt.ylabel('Northings')
plt.grid(linestyle=':', color='0.5')
for i in range(len(output['shorelines'])):
    sl = output['shorelines'][i]
    date = output['dates'][i]
    plt.plot(sl[:,0], sl[:,1], '.', label=date.strftime('%d-%m-%Y'))
plt.legend()
for key in transects.keys():
    plt.plot(transects[key][:,0], transects[key][:,1], 'k-', lw=3)
    plt.plot(transects[key][0,0], transects[key][0,1], 'ro')
mng = plt.get_current_fig_manager()                                         
mng.window.showMaximized()    
fig.set_size_inches([15.76,  8.52])
```

and see if the transects show up on top of the shorelines, if they don't it means there is a problem with the coordinates.

**Comment by whitmcq81** [comment]
Here are the plotted transects. So the coordinates seem to be fine. The time series however still does not show up.
<img width="713" alt="Annotation 2020-03-26 233710" src="https://user-images.githubusercontent.com/61511220/77719089-cc469780-6fba-11ea-8503-83f9b2194d1c.png">

**Comment by kvos** [comment]
you need to switch your origin, origin (red dot) is always the most landward point

**Comment by whitmcq81** [comment]
The origin I have is the most landward point for the shoreline.

**Comment by kvos** [comment]
ok that's weird then...can you try to swap the two points of your transects defined with option 3

**Comment by whitmcq81** [comment]
Well that seemed to do it. It gave me the time series for the shorelines. I appreciate the help.

**Comment by kvos** [comment]
cool!

**Comment by whitmcq81** [comment]
Would there be a reason that Im not getting distances for a large chunk of transects but it calculates everything else? The transects Im asking about are the ones located below the break where the slope shifts about halfway down. Above this point they calculate, below this they do not. Any ideas?

<img width="871" alt="Annotation 2020-04-06 115056" src="https://user-images.githubusercontent.com/61511220/78578134-0b67ba80-77fd-11ea-81f6-6f2d4bd806b7.png">
