### ISSUE TITLE
GEOJSON errors

### ISSUE THREAD

**Issue by ghost** [kvos/CoastSat#82]
**Describe the bug**
Unable to output .geojson file. Make some adjustments to the script (DigitalGlobe) but still unable to load within geographic spatial software (e.g. Arc).

**To Reproduce**
Steps to reproduce the behavior (you can also attach your script):
1. Go to **coastsat**
2. Open  _SDS_shoreline_
3. Scroll down to `extract shorelines`
4. details:

``` 
## save output to gdb.GeoDataFrame
gdf = SDS_tools.output_to_gdf(output)

## set projection
gdf.crs = {'init':'epsg:'+str)settings['output_epsg'])}

# # save as geojson
gdf.to_file(os.path.join(filepath,sitename + '_output.geojson'), driver = GeoJSON', encoding = 'utf-8'
```

When running `extract_shoreline`:

gdl --> 'Norway_output.geojson'

----
Paramas when importing to Arc:

```
JSON To Features
Input JSON: Norway_output.geojson
Output Feature Class: Norway_output_feat
Geometry Type: Polygon
Error when trying to load geojson in Arc:
```
> ! WARNING: Warning empty output generated.

_I opened the attribute table and it is indeed empty._

----

### Contents of gdf (var returned from `SDS_tools.output_to_gdf()`
| **geometry** | **date** | **satname** | **geoaccuracy** | **cloud_cover**|
|---------------|----------|--------------|------------------|-----------------|
LINESTRING (320.5640426308073 -10617.738442605..|2019-07-13 40:41:13|WV|12|0.00|

----

**Expected behavior**
A geojson that can be used as a layer file to visualize outputs similar to that seen in `matplotlib ` (`show_shorelines`)

**Desktop (please complete the following information):**
 - OS: Win10
 - CoastSat Version **Current**

**Additional context**
As per our earlier convos, I am working through utilizing DigitalGlobe's WorldView. The only issue I can think of (that may be causing domino affects) is the epsg. I pulled it via GDAL ('Authority') so it is auto, here is what I got for this image:

4277 

----

#### DigitalGlobe Meta
Direct Link: https://api.discover.digitalglobe.com/show?id=104001004E7F6C00
ID: 104001004E7F6C00

_You can search by ID at the landing page_ : https://discover.digitalglobe.com/

**Comment by kvos** [comment]
that sounds really cool to have compatibility with DigitalGlobe, can you attach your geojson here I will try to drag and drop it on QGIS

**Comment by phke5716** [comment]
Sure thing! It took more work thank I thought, getting the band info was
quite different from the others as well as digging through previous
research on calculating indices. -.- your research (et. al) has been my
closest read while pouring through the years of pubs haha.
