### ISSUE TITLE
spyder/coastsat

### ISSUE THREAD

**Issue by flyingsailor** [kvos/CoastSat#84]
i need help to run coastsatspyder
is there a tuto anywhere?
thank you

**Comment by kvos** [comment]
the readme is the tutorial

**Comment by flyingsailor** [comment]
hello,
i’m a french student (master in geosciences)
and i need to test coastsat, but i’m beginner in python,
i follow a mooc , but if you can give any help
you are welcome 
kind regards

Boris Fekete
