### ISSUE TITLE
Application of CoastSat to a River Flood Problem

### ISSUE THREAD

**Issue by erandaperera** [kvos/CoastSat#86]
Dear Kilian, 

Firstly, thank you very much for developing a great tool for coastline monitoring and management. There are many advantages of this software for numerical modellers.

I am currently involved in a project where we are trying to model the sediment transported due to a river flood inundation. I am looking to obtain the bed level change after a single river flood event using satellite images. I have been wondering whether it is possible to adapt CoastSat tool to do just that. 

Such a tool is especially useful to my project because there has been no field survey done on the river basin after a flood event to assess sediment transport patterns. 

I would like to get your opinion on the possibility of using CoastSat for a river problem. Additionally, I would like to know whether there are other tools available that I can employ for a given river basin to obtain bed level change. The accuracy of the tool need to be particularly high as the bed level change after a flood event may be in the order of a few centimetres.  

Thank you very much for your support.

Kind regards
Eranda

**Comment by kvos** [comment]
Hi Eranda,

Sounds like a very cool project! I know there is this software called PyRIS that was specifically developed for meandering rivers (see this article https://doi.org/10.1016/j.envsoft.2018.03.028). You can probably adapt CoastSat to look at river footprints but you will only obtain horizontal changes out of optical satellite imagery. To get vertical changes you need to use satellite altimetry, which is activate remote sensing.

All the best,
Kilian

**Comment by erandaperera** [comment]
Hi Kilian, 

Thank you very much for the info. PyRIS seem to have a potential to be used for sediment transport problem. It is also worth it to check how we can adapt CoastSat to a river. 

I will let you know how this progresses and will be in touch with you for suggestions. 

Thank you.
