### ISSUE TITLE
Struggling to install on Mac

### ISSUE THREAD

**Issue by nickrichards96** [kvos/CoastSat#89]
Hi there, please could you clarify the steps to install? Tried following the instructions but am confused.

Thanks

**Comment by kvos** [comment]
yes, in the README there is a section on how to install CoastSat, then you can run the example at Narrabeen to check if everything works fine

**Comment by Alan19922015** [comment]
Hello, which patform is most stable, Windows 10 ,Ubuntu 16.04 or Mac?  
I try to install Anaconda3 in win10 and ubuntu,but it always fialed. I want to know that is there update about coastsat.  Which branches will I download?

**Comment by kvos** [comment]
hey @Alan19922015 , I believe anaconda is stable on all three os,, you can check the documentation on how to install it, there is an executable for windows https://docs.anaconda.com/anaconda/install/windows/

Once you have anaconda installed, you open the Anaconda prompt and install the packages with 1 command `conda env create -f environment.yml -n coastsat`. Then you need to authenticate your GEE credentials and you're good to go. 

Regarding the branches, there are 2 `master`and `development`, you can check the progress of each branch here https://github.com/kvos/CoastSat/network. I recommend you clone the repo so you can pull the new updates.

**Comment by Alan19922015** [comment]
Hi, my issues is limited by VPN so I have resolved using Colab instead of based on PC. Thanks for your sharing tools.
