### ISSUE TITLE
Legend plotted coasts 

### ISSUE THREAD

**Issue by RPeet** [kvos/CoastSat#91]
Hi, 
On the added images you can see a plot that I made of the Dutch sand engine. 2 satellite images were taken on 16-03-2020, and when I want to edit them in the legend the date is only listed once. Therefore, I can only edit one of the images in the legend. I was wondering if there is a solution? 
![Schermafbeelding 2020-05-05 om 14 31 56](https://user-images.githubusercontent.com/64845036/81066874-16863700-8ede-11ea-9bac-efaf16b91d3d.png)
![Schermafbeelding 2020-05-05 om 14 32 12](https://user-images.githubusercontent.com/64845036/81066911-243bbc80-8ede-11ea-9a09-0b48b6debb9e.png)

**Comment by kvos** [comment]
hi @RPeet , the code for the plot in the example code is very basic and was just added as an example but you can modify it as you want. I think one option here would be to add to the label parameter of plot the time of acquisition as well as the data. I also have a function to remove duplicates in the `output` dictionary if you're interested.

**Comment by kvos** [comment]
for example `label=date.strftime('%d-%m-%Y %H:%M:%S')` so that your label also has time and it doesn't overwrite it

**Comment by kvos** [comment]
here is the function to remove duplicates:
```
def remove_duplicates(output):
    """
    Function to remove from the output dictionnary entries containing shorelines for the same date
    and satellite mission. This happens when there is an overlap between adjacent
    satellite images.
    
    Arguments:
    -----------
        output: dict
            contains output dict with shoreline and metadata
        
    Returns:    
    -----------
        output_no_duplicates: dict
            contains the updated dict where duplicates have been removed
        
    """
    
    # nested function
    def duplicates_dict(lst):
        "return duplicates and indices"
        def duplicates(lst, item):
                return [i for i, x in enumerate(lst) if x == item] 
        return dict((x, duplicates(lst, x)) for x in set(lst) if lst.count(x) > 1)
     
    dates = output['dates']
    # make a list with year/month/day    
    dates_str = [_.strftime('%Y%m%d') for _ in dates]
    # create a dictionnary with the duplicates
    dupl = duplicates_dict(dates_str)
    # if there are duplicates, only keep the first element
    if dupl:
        output_no_duplicates = dict([])
        idx_remove = []
        for k,v in dupl.items():  
            idx_remove.append(v[0])
        idx_remove = sorted(idx_remove)
        idx_all = np.linspace(0, len(dates_str)-1, len(dates_str))
        idx_keep = list(np.where(~np.isin(idx_all,idx_remove))[0])        
        for key in output.keys():
            output_no_duplicates[key] = [output[key][i] for i in idx_keep]
        print('%d duplicates' % len(idx_remove))
        return output_no_duplicates 
    else: 
        print('0 duplicates')
        return output
```

you can call it like this: `output = remove_duplicates(output)`
