### ISSUE TITLE
TypeError: in method 'CoordinateTransformation_TransformPoints', argument 1 of type 'OSRCoordinateTransformationShadow *'

### ISSUE THREAD

**Issue by Alan19922015** [kvos/CoastSat#92]
Hello， 
    I use many  versions of Anconda3 to install coastsat, but it always failed  after digitize the coastsat, at line 
   settings['reference_shoreline'] = SDS_preprocess.get_reference_sl(metadata, settings);

   pts_coords = SDS_tools.convert_epsg(pts_sl, image_epsg, settings['output_epsg'])

    **points_converted = np.array(coordTransform.TransformPoints(points))**  

According to isses#54, it may have broken gdal but I have unstall all the Anaconda and reinstall it.
It still appear the same errors.

**Comment by Alan19922015** [comment]
Hello, you don't need gdal 2.3.3, you need the newest gdal.  Thanks  everyone.

**Comment by kvos** [comment]
This solution is also for issue #54
