### ISSUE TITLE
Using my own reference shoreline for automatic processing of large datasets?

### ISSUE THREAD

**Issue by ronjalappe** [kvos/CoastSat#94]
Hey Kilian, 
thanks for this great contribution. 
I'm am currently working on a 30-years times series of coastlines in Central Vietnam, which requires a large amount of data and processing time. Therefore I am trying to make my workflow as automatic as possible and I've split the task in chunks. Looping through a list of ROIs and and another list of dates in order to store intermediate results. 

Now I am facing a problem with the reference shoreline (a very nice functionality, I don't want to miss), which I can't digitize manually for each task (in total 60+ times). Therefore I considered using a reference shoreline, that I digitized outside of CoastSat. But apparently "SDS_shoreline.extract_shorelines" can't use geojson linestring (pickle) as input. Do you have any ideas, how I could solve this problem?
Have you used CoastSat for large datasets and possibly any other suggestions, how to make my workflow more efficient? (Btw, the area of interest covers about 1000 km2, and processing the 1/6 of it for 30 years took me ~ 20 hours) 

Thanks for your support!
Best regards, 
Ronja

**Comment by kvos** [comment]
Hi Ronja, I have used Coastsat over large spatial scales and I did set it up in a similar way to your. I had one geojson with all the polygons, one geojson with all the reference shorelines and one with all the transects, then loop to download images, map shorelines and compute intersections. You can load your geojson file with geopandas very easily. Good luck, Kilian

**Comment by ronjalappe** [comment]
Hello Kilian, thank you for very much for this quick reply. It's interesting to know that you used a similar approach for large areas. Just regarding the reference shoreline, I still have a question: Did you map it manually within CoastSat for each of your polygons? 

Cause I wanted to try the following: I digitized a reference shoreline in QGIS, converted it to .geojson and .pkl and put it into the target folders (so that my code can run through all the tasks automatically without me having to interact). The shoreline is recognized by the "SDS_preprocess.get_reference_sl" function, but the "SDS_shoreline.extract_shorelines" function can't use it as input (see attached image). I figured that the extract_shorlines function requires some sort of converted numpy array as input, which is generated in CoastSat when the users digitizes the shorline and then stored as .pkl. Do you have any idea how I can convert my (external) .geojson reference shoreline in a way, that it is a valid input for the extract_shorelines function? 

One more question regarding large datasets: Do you apply any additional filters to your download when treating long time periods? Because downloading and processing all available Landsat 5 & 8 images even for a small roi takes me more than 20 hours and adds up to really long processing times with many polygons.... just wondering if there is a way to possibly make this more efficient? 

Thank you very much for your support, again. It's nice work that you've done!
Best, 
Ronja 


<img width="788" alt="Bildschirmfoto 2020-05-18 um 10 10 38" src="https://user-images.githubusercontent.com/44399512/82195930-50513780-98f9-11ea-94b1-b8e61062ba84.png">

**Comment by kvos** [comment]
hi ronja, the reference shoreline needs to be a numpy array with 2 columns with the coordinates in the same coordinate system as `settings['epsg_out']`. You can get the shorelines from OpenStreetMaps and then automatically extract the minimum rotated rectangle for each shoreline and that is your polygon over which to download the images. Try to keep the polygons small so you can optimise the download time (it shouldn't take 20 hours for a small polygon, like 10 kmsq if you have good bandwidth). The CoastSat toolbox available here on Github is only suitable for individual sites so you will have to make some modifications to run it over many sites (automatic quality control, outlier removal, etc...).

**Comment by ronjalappe** [comment]
Hi Kilian, thanks for your suggestions. They are good ideas for handling large datasets. Though, I still can't use my own reference shoreline. I tried the following to convert the geojson reference shoreline into a numpy array with two columns in the same coordinate system as specified in "settings". 

filepath = "/my_path_to_reference_shoreline.geojson" 
outpath = "/my_path_to_target_folder"
filename ="my_filename"
settings = {'output_epsg': 3406}

shoreline = gpd.read_file(filepath)       # load reference shoreline
shoreline.crs = {'init':'epsg:'+str(settings['output_epsg'])}       # set coordinate system
coords = list(shoreline.geometry.iloc[0][0].coords)       # extract the coordinates and store in list
sl_np = np.array(coords)       # convert list to numpy array with two columns

with open(os.path.join(outpath, filename + '.pkl'), 'wb') as f:
                    pickle.dump(sl_np, f)

but I get this error: 
<img width="790" alt="Bildschirmfoto 2020-05-20 um 11 59 20" src="https://user-images.githubusercontent.com/44399512/82435076-123c4b00-9a94-11ea-828b-398ec19cede9.png">

Could you maybe share a few lines of code, where you successfully converted an external reference shoreline?

**Comment by kvos** [comment]
what you are doing look ok, I usually load a geojson with the shorelines for all the sites and then load them like this: `settings['reference_shoreline']  = np.array(ref_shorelines.loc[site_id]['geometry'].coords)`

Watch out for a couple of things: 
- you need to use projected coordinates (no spherical coordinate systems)
- you want to have a point every 10 meters in your reference shoreline (just interpolate between the points of the linestring)

The error is that it hasn't mapped any shorelines (if it got to that stage you should still have a output.pkl file)
