### ISSUE TITLE
Digitizing reference shoreline leads to error message  "too many indices for array"

### ISSUE THREAD

**Issue by TiPaKi** [kvos/CoastSat#97]
Dear Kilian, 

from time to time it happens that I get an error message "too many indices for array" when I try to digitize a reference shoreline. This is the output which is following after I close the seperate window: 

IndexError                                Traceback (most recent call last)
<ipython-input-5-79934ce2c986> in <module>
      1 get_ipython().run_line_magic('matplotlib', 'qt')
----> 2 settings['reference_shoreline'] = SDS_preprocess.get_reference_sl(metadata, settings)
      3 settings['max_dist_ref'] = 200 # max distance (in meters) allowed from the reference shoreline

~\anaconda3\envs\coastsat\coastsat\SDS_preprocess.py in get_reference_sl(metadata, settings)
    806                     pts_pix = np.array(pts)
    807                     # convert pixel coordinates to world coordinates
--> 808                     pts_world = SDS_tools.convert_pix2world(pts_pix[:,[1,0]], georef)
    809 
    810                     # interpolate between points clicked by the user (1m resolution)

IndexError: too many indices for array

Do you know what is the reason for this error? In case the error occurs there is no reference shoreline saved. I tried to make the ROI bigger/smaller, but it most cases it didnt worked. I dont see the point which causes this error. I would be thankfull if you could help me out with that.  

Best wishes,

Tina

**Comment by kvos** [comment]
hi tina, I am not sure how can I help from this error message. It could be an issue with coordinate systems, make sure that you are using a projected (cartersian) coordinate system and not spherical coordinates (lat/lons). If you can reproduce the error somehow let me know and I will have a look.
Cheers,
Kilian

**Comment by TiPaKi** [comment]
I reproduced the error. This is the script I used: 

import os
import numpy as np
import pickle
import warnings
warnings.filterwarnings("ignore")
import matplotlib.pyplot as plt
from coastsat import SDS_download, SDS_preprocess, SDS_shoreline, SDS_tools, SDS_transects


polygon = [[[9.860899444229702, 54.51055239069431],
            [9.988615508682827, 54.48104281469951],
            [10.109465118057827, 54.63553183963733],
            [9.970762725479702, 54.63871102446804],
            [9.860899444229702, 54.51055239069431]]]



dates = ['2020-04-15', '2020-05-27']
sat_list = ['L8', 'S2']  
sitename = '7_Damp_2020_Küstenlinie'
filepath = os.path.join(os.getcwd(), 'Küstenlinie_SH_data')
inputs = {'polygon': polygon, 'dates': dates, 'sat_list': sat_list, 'sitename': sitename, 'filepath':filepath}


SDS_download.check_images_available(inputs);

metadata = SDS_download.retrieve_images(inputs)

metadata = SDS_download.get_metadata(inputs) 

settings = { 
    # general parameters:
    'cloud_thresh': 0.5,        # threshold on maximum cloud cover
    'output_epsg': 32632,       # epsg code of spatial reference system desired for the output   
    # quality control:
    'check_detection': True,    # if True, shows each shoreline detection to the user for validation
    'save_figure': True,        # if True, saves a figure showing the mapped shoreline for each image
    # add the inputs defined previously
    'inputs': inputs,
    # [ONLY FOR ADVANCED USERS] shoreline detection parameters:
    'min_beach_area': 4500,     # minimum area (in metres^2) for an object to be labelled as a beach 
    'buffer_size': 150,         # radius (in metres) of the buffer around sandy pixels considered in the shoreline detection
    'min_length_sl': 1500,       # minimum length (in metres) of shoreline perimeter to be valid 
    'cloud_mask_issue': False,  # switch this parameter to True if sand pixels are masked (in black) on many images  
    'sand_color': 'default',    # 'default', 'dark' (for grey/black sand beaches) or 'bright' (for white sand beaches)
}

%matplotlib qt
settings['reference_shoreline'] = SDS_preprocess.get_reference_sl(metadata, settings)
settings['max_dist_ref'] = 300 # max distance (in meters) allowed from the reference shoreline

The error occurs after I picked the reference shoreline. I am able to pick it, but when I want to save it (press enter and normally the window is closed and in the script it says "reference shoreline has been saved) the window stays. I have to close it manually in that case and in the notebook the following error occurs: 

IndexError                                Traceback (most recent call last)
<ipython-input-6-3a0d0f2451a6> in <module>
      1 get_ipython().run_line_magic('matplotlib', 'qt')
----> 2 settings['reference_shoreline'] = SDS_preprocess.get_reference_sl(metadata, settings)
      3 settings['max_dist_ref'] = 300 # max distance (in meters) allowed from the reference shoreline

~\anaconda3\envs\coastsat\coastsat\SDS_preprocess.py in get_reference_sl(metadata, settings)
    806                     pts_pix = np.array(pts)
    807                     # convert pixel coordinates to world coordinates
--> 808                     pts_world = SDS_tools.convert_pix2world(pts_pix[:,[1,0]], georef)
    809 
    810                     # interpolate between points clicked by the user (1m resolution)

IndexError: too many indices for array

**Comment by kvos** [comment]
hi @TiPaKi , just had a look at your code. Just want to provide you some tips.
![image](https://user-images.githubusercontent.com/7217258/84090327-cf3b1b00-aa34-11ea-89f5-33053532aa48.png)
 
First, having a polygon this large, with mostly land pixels, is not the correct approach for CoastSat. If you want to map a large region you need to create a polygon for each beach and only download the images around the beaches, here is an example of how I set it up (small polygons around each beach and run coastsat for each polygon, this will be way more efficient in terms of processing time!!!):
![image](https://user-images.githubusercontent.com/7217258/84090446-2ccf6780-aa35-11ea-940e-014de26376ef.png)

Finally, I clicked a few points (not accurately, just to test it) on that image to get a reference shoreline and it all worked ok for me. Just make sure that each shoreline is one beach, then click enter, then click add, click another shoreline etc... Also you need to start from one end of the beach and go to the other end, without jumping around. Here are a few screenshots from my shoreline that worked.

![image](https://user-images.githubusercontent.com/7217258/84090533-71f39980-aa35-11ea-8d42-a3f847cde8b6.png)

![image](https://user-images.githubusercontent.com/7217258/84090548-7c159800-aa35-11ea-9de5-207f6905b7ed.png)

I hope this helps.
