### ISSUE TITLE
Shoreline attribute field 'geoaccuracy'

### ISSUE THREAD

**Issue by sac3g15** [kvos/CoastSat#99]
Thank you for producing such an effective and easy to use piece of open-sourced code.

I am struggling to find out information on how the geoaccuracy field is calculated in the shoreline output. Are you able to give me some more information / direct me to the right source? 

Many thanks

**Comment by kvos** [comment]
hi @sac3g15 , I recommend watching this video https://www.usgs.gov/media/videos/landsat-collections-rmse for Landsat georeferencing accuracy. For Sentinel-2 is not as advanced and they only tell you whether the image passed the geometric quality control or not (pass or fail, 1 or -1) but do not quantify the errors.

**Comment by sac3g15** [comment]
Thank you for the recommendation!
